import { q } from './helper.js';

export function loadSec1() {
  q({
    id: 'ped-cardio-100-001',
    subtopic: 'Comunicação Interventricular (CIV)',
    inst: 'USP-SP',
    year: 2024,
    statement: 'Lactente de 2 meses é levado à consulta por cansaço durante as mamadas e sudorese cefálica profusa. Ao exame: taquipneico (FR: 62 irpm), acianótico, peso no percentil 3. Ausculta revela sopro holossistólico 4+/6+ rude em borda esternal esquerda baixa com frêmito palpável e sopro mesodiastólico suave em ápice. O ecocardiograma confirma CIV perimembranosa ampla. Qual é a causa do sopro mesodiastólico em ápice?',
    A: 'Hiperfluxo relativo através da valva mitral pelo aumento do retorno venoso pulmonar ao átrio esquerdo.',
    B: 'Estenose mitral congênita associada em valva em paraquedas.',
    C: 'Insuficiência tricúspide secundária ao aumento agudo da pressão sistólica ventricular direita.',
    D: 'Regurgitação da valva aórtica por prolapso da cúspide coronariana direita para a CIV.',
    ans: 'A',
    comment: 'Na CIV com grande shunt esquerda-direita, o sangue recircula pelos pulmões e retorna em grande volume para o átrio e ventrículo esquerdos. O aumento substancial do volume diastólico que atravessa o orifício valvar mitral anatomicamente normal gera estenose mitral funcional/relativa, audível como ruflar mesodiastólico no ápice.',
    expA: 'Correta. O hiperfluxo transvalvar mitral diastólico decorrente do retorno venoso pulmonar volumoso é a causa semiológica clássica do sopro mesodiastólico apical.',
    expB: 'Incorreta. A valva mitral é anatomicamente normal; a restrição é meramente funcional por hiperfluxo.',
    expC: 'Incorreta. A insuficiência tricúspide causaria sopro holossistólico em borda esternal esquerda inferior, não mesodiastólico em ápice.',
    expD: 'Incorreta. O prolapso de cúspide aórtica gera sopro protodiastólico aspirativo em foco aórtico, não ruflar mesodiastólico mitral.',
  });

  q({
    id: 'ped-cardio-100-002',
    subtopic: 'Comunicação Interventricular (CIV)',
    inst: 'UNICAMP',
    year: 2024,
    statement: 'Recém-nascido de 3 dias de vida, assintomático, apresenta ao exame auscultatório sopro holossistólico de alta frequência 2+/6+ em bordo esternal esquerdo inferior. O ecocardiograma revela CIV muscular trabecular pequena de 2 mm de diâmetro. Não há sobrecarga de câmaras. Qual é a conduta mais adequada?',
    A: 'Acompanhamento clínico ambulatorial periódico, pois a grande maioria das CIVs musculares pequenas fecha espontaneamente nos primeiros anos.',
    B: 'Indicação cirúrgica imediata com esternotomia para fechamento com retalho de pericárdio bovino.',
    C: 'Início de digitalização rápida associada a furosemida em dose plena para evitar cardiomegalia.',
    D: 'Restrição hídrica severa e cateterismo cardíaco intervencionista de urgência com prótese Amplatzer.',
    ans: 'A',
    comment: 'As CIVs musculares pequenas (doença de Roger) são lesões restritivas com gradiente elevado entre VE e VD sem sobrecarga hemodinâmica pulmonar. Cerca de 70-80% fecham espontaneamente nos primeiros anos de vida.',
    expA: 'Correta. CIVs musculares restritivas pequenas em assintomáticos possuem alta taxa de encerramento espontâneo.',
    expB: 'Incorreta. Cirurgia aberta é contraindicada em defeitos pequenos assintomáticos sem hipertensão pulmonar.',
    expC: 'Incorreta. Paciente assintomático não possui insuficiência cardíaca; diuréticos seriam iatrogênicos.',
    expD: 'Incorreta. Não há indicação de oclusão percutânea em lactente assintomático com microdefeito.',
  });

  q({
    id: 'ped-cardio-100-003',
    subtopic: 'Comunicação Interventricular (CIV)',
    inst: 'ENARE',
    year: 2024,
    statement: 'Menino de 4 anos com CIV perimembranosa subarterial (supracristal) é avaliado em consulta. Ecocardiograma revela shunt E-D moderado e discreto prolapso da cúspide aórtica coronariana direita com regurgitação aórtica leve de início recente. Qual é a conduta preconizada?',
    A: 'Indicação de correção cirúrgica do defeito para prevenir a progressão da insuficiência valvar aórtica.',
    B: 'Tratamento clínico expectante com reavaliação ecocardiográfica após os 12 anos de idade.',
    C: 'Início de vasodilatador IECA em dose alta e alta definitiva do ambulatório cirúrgico.',
    D: 'Valvoplastia aórtica percutânea por balão sem necessidade de fechar a CIV.',
    ans: 'A',
    comment: 'A CIV subarterial (supracristal) localiza-se logo abaixo das valvas semilunares. Pelo efeito Venturi da passagem de fluxo de alta velocidade, ocorre sucção e prolapso da cúspide aórtica com insuficiência aórtica progressiva (Síndrome de Laubry-Pezzi), tornando o fechamento cirúrgico mandatório.',
    expA: 'Correta. O risco de destruição valvar progressiva torna o fechamento cirúrgico da CIV infundibular mandatório ao surgir prolapso.',
    expB: 'Incorreta. A conduta expectante resultará em dano valvar grave com necessidade de prótese valvar futura.',
    expC: 'Incorreta. IECA não impede a tração mecânica hemodinâmica gerada sobre a cúspide aórtica desprovida de sustentação.',
    expD: 'Incorreta. A lesão primária é a insuficiência por prolapso, não estenose; balão pioraria a regurgitação.',
  });

  q({
    id: 'ped-cardio-100-004',
    subtopic: 'Comunicação Interventricular (CIV)',
    inst: 'UFRJ',
    year: 2023,
    statement: 'Lactente de 3 meses com CIV perimembranosa ampla evolui com taquipneia, hepatomegalia e interrupções nas mamadas. É prescrito furosemida, espironolactona e enalapril. Qual é o papel farmacológico do IECA nessa condição?',
    A: 'Reduzir a pós-carga sistêmica, favorecendo a ejeção do VE para a aorta e diminuindo a magnitude do shunt esquerda-direita.',
    B: 'Promover fechamento farmacológico anatômico das bordas fibrosas do septo interventricular.',
    C: 'Aumentar a contratilidade intrínseca do ventrículo direito via ativação beta-1 adrenérgica.',
    D: 'Diminuir a capacitância venosa pulmonar com elevação seletiva da pressão de átrio direito.',
    ans: 'A',
    comment: 'Ao promover vasodilatação arterial sistêmica e reduzir a pós-carga de VE, o IECA facilita a ejeção para a circulação sistêmica em detrimento da passagem anômala para o ventrículo direito e leito pulmonar.',
    expA: 'Correta. A diminuição da resistência sistêmica reduz o gradiente efetivo de desvio para o ventrículo direito.',
    expB: 'Incorreta. Fármacos não fecham orifícios de CIVs perimembranosas.',
    expC: 'Incorreta. IECAs são vasodilatadores, não inotrópicos positivos.',
    expD: 'Incorreta. O objetivo do IECA é desobstruir e esvaziar a vasculatura pulmonar reduzindo pressões de enchimento.',
  });

  q({
    id: 'ped-cardio-100-005',
    subtopic: 'Comunicação Interventricular (CIV)',
    inst: 'FMRP-USP',
    year: 2024,
    statement: 'Qual alteração no eletrocardiograma é mais característica de um lactente com CIV de grande magnitude antes da instalação de hipertensão pulmonar fixa irreversível?',
    A: 'Sobrecarga biventricular com complexos QRS amplos difásicos em precordiais médias (fenômeno de Katz-Wachtel).',
    B: 'Bloqueio atrioventricular de terceiro grau congênito com escape idioventricular lento.',
    C: 'Sobrecarga ventricular direita pura com onda S profunda exclusiva em V5 e V6.',
    D: 'Infradesnivelamento difuso do segmento ST com ondas T invertidas em todas as derivações.',
    ans: 'A',
    comment: 'Em lactentes com CIV grande e shunt E-D volumoso, o VD sofre sobrecarga de pressão/volume e o VE sofre sobrecarga volumétrica. O traçado clássico no ECG demonstra sobrecarga biventricular pelo sinal de Katz-Wachtel (QRS amplos difásicos em V2-V4).',
    expA: 'Correta. O fenômeno de Katz-Wachtel expressa a sobrecarga biventricular típica de grandes shunts interventriculares.',
    expB: 'Incorreta. BAVT congênito associa-se a lúpus neonatal materno (anti-Ro/SSA).',
    expC: 'Incorreta. SVD isolada surge apenas tardiamente na síndrome de Eisenmenger com atrofia relativa de VE.',
    expD: 'Incorreta. Isquemia difusa não é achado padrão de CIV isolada.',
  });

  q({
    id: 'ped-cardio-100-006',
    subtopic: 'Comunicação Interventricular (CIV)',
    inst: 'UERJ',
    year: 2023,
    statement: 'Criança de 8 meses com CIV ampla e desnutrição grave está programada para cirurgia corretiva. Durante o cateterismo para teste de vasorreatividade pulmonar, qual achado contraindica a cirurgia corretiva isolada?',
    A: 'Resistência vascular pulmonar fixa > 8 Wood units/m² não responsiva a vasodilatadores inalatórios, com shunt invertido D-E.',
    B: 'Relação de fluxo pulmonar/sistêmico (Qp/Qs) de 2,5 com pressão arterial pulmonar média responsiva a vasodilatadores.',
    C: 'Pressão de oclusão de artéria pulmonar de 12 mmHg com saturação venosa mista de 72%.',
    D: 'Gradiente transvalvar aórtico de 5 mmHg com fração de ejeção do ventrículo esquerdo de 64%.',
    ans: 'A',
    comment: 'A presença de doença vascular pulmonar obstrutiva avançada irreversível (RVP > 8 Wood units/m² fixa) caracteriza a Síndrome de Eisenmenger, contraindicando o fechamento isolado do defeito.',
    expA: 'Correta. RVP fixa alta e refratária demonstra arteriopatia plexogênica irreversível, contraindicando o fechamento do defeito.',
    expB: 'Incorreta. Qp/Qs de 2,5 com vasorreatividade preservada é excelente indicativo de indicação e sucesso cirúrgico.',
    expC: 'Incorreta. Pressão de capilar pulmonar normal e saturação adequada indicam boa reserva hemodinâmica.',
    expD: 'Incorreta. Ausência de gradiente aórtico e função de VE normal são condições favoráveis ao reparo.',
  });

  q({
    id: 'ped-cardio-100-007',
    subtopic: 'Comunicação Interventricular (CIV)',
    inst: 'SCMSP',
    year: 2024,
    statement: 'Qual é o tipo anatômico mais prevalente de Comunicação Interventricular na infância, correspondendo a cerca de 70 a 80% dos casos?',
    A: 'CIV perimembranosa.',
    B: 'CIV muscular apical.',
    C: 'CIV subarterial duplamente relacionada.',
    D: 'CIV do septo de entrada (inlet).',
    ans: 'A',
    comment: 'A CIV perimembranosa é a mais frequente, localizando-se no septo membranoso adjacente à valva tricúspide e valva aórtica, em íntimo contato com o feixe de His.',
    expA: 'Correta. A CIV perimembranosa responde pela grande maioria dos casos clínicos e cirúrgicos.',
    expB: 'Incorreta. CIVs musculares representam 10 a 20% das casuísticas.',
    expC: 'Incorreta. CIVs subarteriais perfazem cerca de 5 a 7%.',
    expD: 'Incorreta. CIVs de via de entrada são raras isoladamente e integram o defeito de septo AV.',
  });

  q({
    id: 'ped-cardio-100-008',
    subtopic: 'Comunicação Interventricular (CIV)',
    inst: 'SMS-SP',
    year: 2023,
    statement: 'No fechamento cirúrgico de uma CIV perimembranosa via atriotomia direita, qual estrutura do sistema de condução cardíaca corre maior risco de lesão iatrogênica na sutura da borda posteroinferior?',
    A: 'Feixe de His e nó atrioventricular.',
    B: 'Nó sinoatrial na crista terminal.',
    C: 'Feixe de Bachmann interatrial.',
    D: 'Ramo direito terminal na banda moderadora.',
    ans: 'A',
    comment: 'Na CIV perimembranosa, o feixe de His transita na borda posteroinferior do defeito. A sutura inadvertida nessa topografia pode gerar Bloqueio Atrioventricular Total (BAVT) pós-operatório.',
    expA: 'Correta. O feixe de condução AV corre na margem posteroinferior da CIV perimembranosa.',
    expB: 'Incorreta. O nó SA situa-se alto no átrio direito junto à veia cava superior.',
    expC: 'Incorreta. O feixe de Bachmann transita no septo interatrial superior.',
    expD: 'Incorreta. O ramo direito percorre a banda moderadora mais distalmente.',
  });

  q({
    id: 'ped-cardio-100-009',
    subtopic: 'Comunicação Interventricular (CIV)',
    inst: 'FAMERP',
    year: 2024,
    statement: 'Por que o sopro clássico de uma CIV de tamanho moderado costuma não ser audível nas primeiras 24 a 48 horas de vida do recém-nascido a termo, surgindo tipicamente entre a 2ª e a 6ª semana de vida?',
    A: 'Porque a resistência vascular pulmonar ainda está fisiologicamente elevada ao nascimento, igualando as pressões entre os ventrículos e impedindo turbilhonamento significativo.',
    B: 'Porque o forame oval patente fecha o orifício da CIV por aposição mecânica durante os primeiros dias.',
    C: 'Devido à persistência do canal arterial que gera refluxo aórtico contínuo e abafa qualquer ruído septal.',
    D: 'Pelo fechamento transitório do septo membranoso mediado por altas concentrações de prostaglandina materna.',
    ans: 'A',
    comment: 'Com o nascimento, a resistência vascular pulmonar cai gradualmente. Enquanto as pressões no VD e VE forem semelhantes, não há gradiente nem fluxo turbilhonado. Quando a RVP cai entre 2 e 6 semanas, surge o gradiente e o sopro holossistólico.',
    expA: 'Correta. A queda fisiológica progressiva da resistência vascular pulmonar pós-natal determina o surgimento do sopro.',
    expB: 'Incorreta. O forame oval comunica átrios e não tem aposição mecânica com o septo interventricular.',
    expC: 'Incorreta. A PCA não abafa o septo interventricular.',
    expD: 'Incorreta. Prostaglandinas atuam no canal arterial, sem ação oclusiva em septos musculares.',
  });

  q({
    id: 'ped-cardio-100-010',
    subtopic: 'Comunicação Interventricular (CIV)',
    inst: 'UFMG',
    year: 2023,
    statement: 'Qual manifestação clínica em lactente com CIV indica hiperfluxo pulmonar com hipertensão pulmonar hipercinética e indicação cirúrgica antes dos 6 meses de vida?',
    A: 'Taquipneia em repouso, sudorese fria às mamadas, baixo ganho ponderal e hiperfonese da 2ª bulha em foco pulmonar.',
    B: 'Cianose central isolada sem taquipneia associada a baqueteamento digital precoce.',
    C: 'Pulsos femorais impalpáveis com hipertensão arterial grave em membros superiores.',
    D: 'Episódios de dor torácica aos esforços com estalido de ejeção aórtico e sopro diastólico.',
    ans: 'A',
    comment: 'Os sinais clássicos de insuficiência cardíaca congestiva de alto fluxo em lactentes com CIV grande são taquidispneia, sudorese durante a alimentação, falha no ganho ponderal e hiperfonese de P2.',
    expA: 'Correta. Sintomas cardinais de ICC por hiperfluxo pulmonar volumoso na infância.',
    expB: 'Incorreta. Cianose precoce sem ICC aponta para cardiopatia congênita cianótica (ex: TGA, Fallot).',
    expC: 'Incorreta. Descrição clássica de Coarctação de Aorta.',
    expD: 'Incorreta. Sugestivo de estenose ou insuficiência aórtica em escolares.',
  });

  q({
    id: 'ped-cardio-100-011',
    subtopic: 'Comunicação Interventricular (CIV)',
    inst: 'PUC-PR',
    year: 2024,
    statement: 'Em um paciente portador de CIV perimembranosa pequena assintomática de 3 mm sem repercussão hemodinâmica, qual complicação infecciosa potencial requer orientação permanente de higiene oral rigorosa?',
    A: 'Endocardite Infecciosa provocada pelo fluxo de jato de alta velocidade que lesiona o endocárdio ventricular oposto.',
    B: 'Meningite meningocócica secundária à embolia séptica paradoxal interatrial.',
    C: 'Glomerulonefrite pós-estreptocócica decorrente de deposição de imunocomplexos no septo interventricular.',
    D: 'Abscesso esplênico primário por disseminação linfática retrógrada da artéria pulmonar.',
    ans: 'A',
    comment: 'Pequenos defeitos interventriculares geram jatos de alta velocidade que impactam a parede oposta do VD, desendotelizando a superfície e formando trombos plaquetários propensos à colonização bacteriana.',
    expA: 'Correta. A alta velocidade do jato em defeitos restritivos causa lesão endotelial por cisalhamento, propiciando endocardite infecciosa.',
    expB: 'Incorreta. Embolia paradoxal requer shunt direita-esquerda.',
    expC: 'Incorreta. GNPE decorre de imunocomplexos em capilares glomerulares renais.',
    expD: 'Incorreta. Disseminação de endocardite segue a via hematogênica sistêmica ou pulmonar.',
  });

  q({
    id: 'ped-cardio-100-012',
    subtopic: 'Comunicação Interventricular (CIV)',
    inst: 'IAMSPE',
    year: 2023,
    statement: 'Quando um paciente com CIV ampla atinge a adolescência com Síndrome de Eisenmenger estabelecida, o que ocorre tipicamente com o sopro holossistólico prévio da CIV?',
    A: 'O sopro holossistólico desaparece ou atenua-se expressivamente, pois o gradiente pressórico sistólico entre os ventrículos se anula.',
    B: 'O sopro torna-se contínuo em maquinária irradiando amplamente para o dorso.',
    C: 'O sopro transforma-se em um estalido protodiastólico isolado com redução drástica da segunda bulha cardíaca.',
    D: 'O sopro ganha timbre musical vibratório de alta intensidade grau 6/6 com frêmito em foco aórtico.',
    ans: 'A',
    comment: 'Na síndrome de Eisenmenger, a pressão no VD se iguala à do VE. Sem gradiente pressórico, o fluxo pelo orifício não é turbilhonado e o sopro desaparece, restando sinais de hipertensão pulmonar (hiperfonese extrema de P2).',
    expA: 'Correta. A equalização das pressões ventriculares elimina o gradiente turbilhonar.',
    expB: 'Incorreta. Sopro contínuo em maquinária é exclusivo da persistência do canal arterial.',
    expC: 'Incorreta. A segunda bulha torna-se intensamente hiperfonética e palpável.',
    expD: 'Incorreta. Sopro vibratório benigno é o sopro de Still.',
  });
}
