import { q } from './helper.js';

export function loadSec2() {
  q({
    id: 'ped-cardio-100-013',
    subtopic: 'Tetralogia de Fallot',
    inst: 'USP-RP',
    year: 2024,
    statement: 'Quais são os quatro componentes anatômicos clássicos que compõem a Tetralogia de Fallot?',
    A: 'Estenose pulmonar infundibular, Comunicação Interventricular (CIV), Dextroposição/cavalgamento da aorta e Hipertrofia do ventrículo direito.',
    B: 'Comunicação Interatrial (CIA), CIV, Valva AV única comum e Hipoplasia do arco aórtico.',
    C: 'Transposição das grandes artérias, Estenose aórtica subvalvar, CIV e Persistência do canal arterial.',
    D: 'Coarctação da aorta, Atresia tricúspide, Dextrocardia e Drenagem anômala de veias pulmonares.',
    ans: 'A',
    comment: 'A tétrade descrita por Étienne-Louis Fallot decorre do desvio anterior e cefálico do septo infundibular, resultando em estenose pulmonar, CIV ampla, dextroposição da aorta e hipertrofia de VD.',
    expA: 'Correta. Define com exatidão os 4 defeitos anatômicos clássicos da Tetralogia de Fallot.',
    expB: 'Incorreta. Essa composição caracteriza o Defeito do Septo Atrioventricular (DSAV).',
    expC: 'Incorreta. Trata-se de TGA com lesões associadas.',
    expD: 'Incorreta. Mistura elementos de cardiopatias univentriculares e obstrutivas esquerdas.',
  });

  q({
    id: 'ped-cardio-100-014',
    subtopic: 'Tetralogia de Fallot',
    inst: 'UNICAMP',
    year: 2024,
    statement: 'Lactente de 7 meses portador de Tetralogia de Fallot apresenta episódio súbito de irritabilidade, choro intenso, taquipneia profunda e cianose labial acentuada. O sopro sistólico prévio encontra-se quase inaudível. Qual é a conduta imediata prioritária?',
    A: 'Colocar a criança em posição genupeitoral (joelho-tórax), ofertar oxigênio e administrar morfina intramuscular ou subcutânea.',
    B: 'Administrar infusão rápida de bicarbonato de sódio a 8,4% e digoxina intravenosa imediata.',
    C: 'Realizar intubação orotraqueal imediata com hiperventilação mecânica agressiva.',
    D: 'Administrar furosemida intravenosa em alta dose associada a nitroprussiato de sódio.',
    ans: 'A',
    comment: 'Na crise hipercianótica do Fallot, o espasmo infundibular reduz criticamente o fluxo pulmonar e desvia sangue desoxigenado para a aorta. A posição genupeitoral aumenta a resistência vascular sistêmica e a morfina acalma o lactente, quebrando o ciclo adrenérgico.',
    expA: 'Correta. Posição genupeitoral, oxigênio e morfina constituem o tripé inicial de resgate na crise de hipóxia do Fallot.',
    expB: 'Incorreta. Bicarbonato é reservado para acidose metabólica grave; digoxina não relaxa o infundíbulo.',
    expC: 'Incorreta. Intubação intempestiva pode piorar a descarga adrenérgica antes da sedação adequada.',
    expD: 'Incorreta. Vasodilatadores reduzem a resistência sistêmica, piorando o shunt direita-esquerda.',
  });

  q({
    id: 'ped-cardio-100-015',
    subtopic: 'Tetralogia de Fallot',
    inst: 'ENARE',
    year: 2024,
    statement: 'Durante uma crise de cianose em um paciente com Tetralogia de Fallot, por que a intensidade do sopro sistólico diminui ou desaparece?',
    A: 'Porque o sopro audível no Fallot decorre da estenose pulmonar; durante o espasmo infundibular quase não passa fluxo através da via de saída do VD.',
    B: 'Porque a CIV se fecha reflexamente durante a taquicardia extrema da crise hipoxêmica.',
    C: 'Devido à hipotensão arterial sistêmica súbita que anula a pressão na aorta ascendente.',
    D: 'Pelo fechamento espontâneo do canal arterial que sustentava a pressão intracardíaca.',
    ans: 'A',
    comment: 'O sopro do Fallot é exclusivamente o sopro ejetivo da estenose pulmonar. No espasmo infundibular, o orifício para o pulmão fica quase totalmente ocluído, diminuindo expressivamente o fluxo e abafando o sopro.',
    expA: 'Correta. O sopro reflete a passagem pela via de saída de VD; a redução crítica do fluxo pulmonar no espasmo atenua o ruído.',
    expB: 'Incorreta. A CIV é ampla, não contrátil e não fecha na crise.',
    expC: 'Incorreta. A pressão da aorta não define o sopro estenótico pulmonar.',
    expD: 'Incorreta. O canal arterial geralmente já está fechado no lactente de vários meses com Fallot.',
  });

  q({
    id: 'ped-cardio-100-016',
    subtopic: 'Tetralogia de Fallot',
    inst: 'USP-SP',
    year: 2023,
    statement: 'Qual é o aspecto radiológico característico da silhueta cardíaca na radiografia de tórax de um paciente com Tetralogia de Fallot clássica?',
    A: 'Coração em formato de bota ou tamanco holandês (coeur en sabot) com ponta cardíaca levantada e hipofluxo pulmonar (campos pleuro-pulmonares escuros).',
    B: 'Coração em formato de ovo deitado (egg-on-a-string) com mediastino superior estreito.',
    C: 'Cardiomegalia maciça ocupando todo o hemitórax com aspecto em garrafa ou moringa.',
    D: 'Aspecto de boneco de neve ou formato em 8 com circulação pulmonar hipercongestiva difusa.',
    ans: 'A',
    comment: 'A hipertrofia concêntrica de VD eleva o ápice cardíaco acima do diafragma, associada à escavação da artéria pulmonar hipoplásica, configurando o coração em tamanco holandês (coeur en sabot) com campos oligêmicos.',
    expA: 'Correta. Coeur en sabot com escavação do tronco pulmonar e hipofluxo periférico é a descrição clássica do Fallot.',
    expB: 'Incorreta. Ovo deitado com pedículo estreito é característico da Transposição das Grandes Artérias (TGA).',
    expC: 'Incorreta. Coração em moringa/garrafa é típico de Anomalia de Ebstein ou derrame pericárdico volumoso.',
    expD: 'Incorreta. Sinal do boneco de neve é patognomônico da DATVP supracardíaca.',
  });

  q({
    id: 'ped-cardio-100-017',
    subtopic: 'Tetralogia de Fallot',
    inst: 'SCMSP',
    year: 2024,
    statement: 'Menino de 3 anos com Tetralogia de Fallot não operada é observado correndo no parque e, ao sentir cansaço, agacha-se espontaneamente no chão (posição de cócoras / squatting). Qual é o benefício fisiológico dessa manobra?',
    A: 'Aumentar a resistência vascular sistêmica pela flexão das artérias femorais, reduzindo o shunt direita-esquerda e aumentando o fluxo de sangue aos pulmões.',
    B: 'Promover relaxamento imediato do diafragma facilitando a expansão da base pulmonar esquerda.',
    C: 'Diminuir o retorno venoso de sangue desoxigenado para o átrio direito, aliviando a sobrecarga de volume do VD.',
    D: 'Bloquear os barorreceptores carotídeos induzindo bradicardia reflexa e redução da fração de ejeção.',
    ans: 'A',
    comment: 'O agachamento (squatting) comprime as artérias femorais e ilíacas, elevando a resistência vascular sistêmica. Com a RVS mais alta, o shunt D-E diminui e mais sangue atravessa a via pulmonar, melhorando a saturação.',
    expA: 'Correta. O squatting eleva a RVS, forçando maior proporção do débito cardíaco a ultrapassar a estenose pulmonar.',
    expB: 'Incorreta. O benefício é predominantemente hemodinâmico vascular, não ventilatório diafragmático.',
    expC: 'Incorreta. A posição de cócoras eleva o retorno venoso dos membros inferiores.',
    expD: 'Incorreta. A manobra não visa bradicardia, mas reversão do shunt intracardíaco.',
  });

  q({
    id: 'ped-cardio-100-018',
    subtopic: 'Tetralogia de Fallot',
    inst: 'UERJ',
    year: 2024,
    statement: 'Qual é o fármaco de escolha para a profilaxia farmacológica crônica de novas crises de hipóxia em lactentes com Fallot enquanto aguardam a cirurgia definitiva?',
    A: 'Propranolol por via oral.',
    B: 'Enalapril por via oral.',
    C: 'Furosemida em dose contínua.',
    D: 'Amiodarona em dose de impregnação.',
    ans: 'A',
    comment: 'O betabloqueador (propranolol) atua relaxando a musculatura infundibular hipertrofiada da via de saída do VD, reduzindo a hiper-reatividade adrenérgica ao estresse e prevenindo o espasmo infundibular.',
    expA: 'Correta. O propranolol oral é a droga de escolha para prevenção de crises de cianose no pré-operatório do Fallot.',
    expB: 'Incorreta. IECA reduz a pós-carga sistêmica, piorando o shunt D-E.',
    expC: 'Incorreta. Diuréticos diminuem a pré-carga de VD, favorecendo o colapso e espasmo infundibular.',
    expD: 'Incorreta. Amiodarona é antiarrítmico com múltiplos efeitos adversos, sem indicação profilática no Fallot.',
  });

  q({
    id: 'ped-cardio-100-019',
    subtopic: 'Tetralogia de Fallot',
    inst: 'UFRJ',
    year: 2023,
    statement: 'Em um recém-nascido com Tetralogia de Fallot com estenose pulmonar crítica e hipoxemia refratária grave nas primeiras semanas de vida, qual cirurgia paliativa é classicamente realizada para garantir fluxo pulmonar?',
    A: 'Anastomose sistêmico-pulmonar de Blalock-Taussig modificada (tubo de PTFE entre artéria subclávia e artéria pulmonar).',
    B: 'Bandeamento da artéria pulmonar para redução de hiperfluxo.',
    C: 'Cirurgia de Jatene com transposição dos grandes vasos.',
    D: 'Cirurgia de Glenn bidirecional término-lateral isolada.',
    ans: 'A',
    comment: 'O shunt de Blalock-Taussig modificado cria uma fístula sistêmico-pulmonar usando um enxerto de Gore-Tex entre a artéria subclávia e a artéria pulmonar ipsilateral, garantindo fluxo pulmonar até a correção total.',
    expA: 'Correta. O Blalock-Taussig modificado é o procedimento paliativo clássico para garantir suprimento sanguíneo pulmonar.',
    expB: 'Incorreta. O bandeamento é feito em cardiopatias de hiperfluxo (CIV ampla, DSAV), e o Fallot tem hipofluxo.',
    expC: 'Incorreta. Jatene é o tratamento cirúrgico definitivo da TGA.',
    expD: 'Incorreta. O Glenn é o segundo estágio de cirurgias univentriculares.',
  });

  q({
    id: 'ped-cardio-100-020',
    subtopic: 'Tetralogia de Fallot',
    inst: 'IAMSPE',
    year: 2024,
    statement: 'Qual microdeleção cromossômica está fortemente associada à Tetralogia de Fallot e outros defeitos conotrunciais, associando-se a hipocalcemia neonatal, dismorfismos faciais e imunodeficiência celular?',
    A: 'Deleção do cromossomo 22q11.2 (Síndrome de DiGeorge / velocardiofacial).',
    B: 'Trissomia do cromossomo 18 (Síndrome de Edwards).',
    C: 'Monossomia do cromossomo X (45,X0 / Síndrome de Turner).',
    D: 'Deleção do braço curto do cromossomo 5 (5p- / Síndrome de Cri-du-Chat).',
    ans: 'A',
    comment: 'A microdeleção 22q11.2 (Síndrome de DiGeorge) responde por cerca de 15% dos casos de Tetralogia de Fallot e decorre de falha no desenvolvimento do 3º e 4º arcos faríngeos, cursando com cardiopatia conotruncal, aplasia/hipoplasia de timo e paratireoides.',
    expA: 'Correta. A deleção 22q11.2 é a anomalia genética mais prevalente em cardiopatias de via de saída (conotrunciais).',
    expB: 'Incorreta. Edwards associa-se a sobreposição de dedos e pés em mata-borrão.',
    expC: 'Incorreta. Turner (45,X0) associa-se a Coarctação de Aorta e valva aórtica bicúspide.',
    expD: 'Incorreta. Cri-du-chat cursa com choro miado de gato e microcefalia, sem associação predominante com Fallot.',
  });

  q({
    id: 'ped-cardio-100-021',
    subtopic: 'Tetralogia de Fallot',
    inst: 'FMRP-USP',
    year: 2024,
    statement: 'No pós-operatório tardio da correção cirúrgica completa da Tetralogia de Fallot em adultos jovens, qual é a sequela hemodinâmica mais frequente que comumente exige reintervenção valvar pulmonar?',
    A: 'Insuficiência valvar pulmonar livre crônica com dilatação progressiva e disfunção do ventrículo direito.',
    B: 'Estenose mitral grave decorrente de calcificação fibroelástica distrófica.',
    C: 'Hipertensão arterial pulmonar pré-capilar suprassistêmica irreversível.',
    D: 'Regurgitação aórtica maciça decorrente de rotura do anel aórtico reconstruído.',
    ans: 'A',
    comment: 'A ampliação da via de saída do VD durante a correção do Fallot envolve frequentemente a colocação de retalho transanular, resultando em insuficiência pulmonar livre crônica, dilatação do VD e arritmias ventriculares tardias.',
    expA: 'Correta. A insuficiência pulmonar crônica é a principal lesão residual tardia pós-correção de Fallot.',
    expB: 'Incorreta. A valva mitral não é abordada na cirurgia de Fallot.',
    expC: 'Incorreta. O Fallot tem hipofluxo pulmonar prévio; não desenvolve hipertensão pulmonar primária.',
    expD: 'Incorreta. Regurgitação aórtica maciça é incomum comparada à pulmonar.',
  });

  q({
    id: 'ped-cardio-100-022',
    subtopic: 'Tetralogia de Fallot',
    inst: 'FAMERP',
    year: 2023,
    statement: 'Qual é o achado clássico da ausculta da segunda bulha cardíaca (B2) em um paciente com Tetralogia de Fallot típica?',
    A: 'Segunda bulha única e hiperfonética em foco pulmonar, correspondente exclusivamente ao componente aórtico audível (A2).',
    B: 'Desdobramento amplo e fixo de B2 sem variação respiratória.',
    C: 'Desdobramento paradoxal de B2 com fechamento aórtico atrasado após o pulmonar.',
    D: 'Bulha hipofonética em quatro tempos com galope protodiastólico atrial.',
    ans: 'A',
    comment: 'O componente pulmonar de B2 (P2) é inaudível devido à estenose pulmonar acentuada e baixa pressão arterial pulmonar. Assim, ausculta-se uma segunda bulha única, constituída puramente pelo componente aórtico (A2).',
    expA: 'Correta. A segunda bulha é única porque P2 é inaudível devido à estenose pulmonar acentuada.',
    expB: 'Incorreta. Desdobramento fixo de B2 é a marca semiológica da CIA.',
    expC: 'Incorreta. Desdobramento paradoxal ocorre no BRE grave ou estenose aórtica importante.',
    expD: 'Incorreta. Galope em 4 tempos ocorre na Anomalia de Ebstein.',
  });

  q({
    id: 'ped-cardio-100-023',
    subtopic: 'Tetralogia de Fallot',
    inst: 'SMS-SP',
    year: 2024,
    statement: 'Criança de 4 anos com Tetralogia de Fallot não operada apresenta hematócrito de 68% e hemoglobina de 22 g/dL. Apresenta cefaleia, letargia e hemiparesia motora focal súbita à direita. Qual complicação deve ser prontamente suspeitada?',
    A: 'Abscesso cerebral piogênico ou acidente vascular cerebral isquêmico decorrente de hiperviscosidade e shunt D-E.',
    B: 'Mielite transversa aguda pós-vacinal com bloqueio de condução espinhal.',
    C: 'Encefalopatia hipertensiva maligna por estenose de artéria renal associada.',
    D: 'Edema cerebral vasogênico decorrente de intoxicação digitálica crônica.',
    ans: 'A',
    comment: 'A hipóxia crônica estimula eritropoiese extrema (hematócrito > 65%), aumentando a viscosidade sanguínea e predispondo a microtrombose venosa cerebral. Além disso, o shunt D-E permite que êmbolos sépticos ultrapassem a barreira capilar pulmonar, alcançando o cérebro e formando abscessos.',
    expA: 'Correta. Abscesso cerebral e AVC isquêmico por hiperviscosidade e shunt D-E são complicações clássicas da cianose crônica.',
    expB: 'Incorreta. Não há quadro espinhal sensitivo-motor compatível com mielite.',
    expC: 'Incorreta. O paciente não tem hipertensão arterial maligna sistêmica de base.',
    expD: 'Incorreta. O quadro focal com policitemia não decorre de intoxicação digitálica.',
  });

  q({
    id: 'ped-cardio-100-024',
    subtopic: 'Tetralogia de Fallot',
    inst: 'PUC-Campinas',
    year: 2024,
    statement: 'Em que faixa etária é atualmente recomendada a correção cirúrgica total eletiva da Tetralogia de Fallot na maioria dos centros cardiopediátricos?',
    A: 'Entre 3 e 6 meses de vida.',
    B: 'Imediatamente nas primeiras 24 horas de vida de rotina para todos os casos.',
    C: 'Somente após os 10 anos de idade, aguardando o crescimento do anel pulmonar.',
    D: 'Aos 18 anos de idade, após o término da maturação óssea esquelética.',
    ans: 'A',
    comment: 'O reparo cirúrgico primário eletivo precoce entre 3 e 6 meses previne a hipertrofia ventricular excessiva, reduz a incidência de crises hipercianóticas e protege o desenvolvimento neurocognitivo.',
    expA: 'Correta. O reparo cirúrgico completo eletivo é realizado idealmente entre 3 e 6 meses de vida.',
    expB: 'Incorreta. Nas primeiras 24h é reservado apenas para formas extremas com atresia pulmonar crítica.',
    expC: 'Incorreta. Postergar para os 10 anos causaria danos cerebrais e fibrose miocárdica grave.',
    expD: 'Incorreta. Não se posterga cirurgia de cardiopatia congênita cianótica até a idade adulta.',
  });
}
