import { q } from './helper.js';

export function loadSec3() {
  q({
    id: 'ped-cardio-100-025',
    subtopic: 'Coarctação de Aorta',
    inst: 'USP-SP',
    year: 2024,
    statement: 'Lactente de 40 dias é levado à consulta ambulatorial. A mãe queixa-se de irritabilidade ocasional. Ao exame físico: corado, eupneico. Aferição pressórica revela PA em membro superior direito de 130/80 mmHg e em membros inferiores de 75/45 mmHg. Pulsos radiais são amplos, enquanto os pulsos femorais são filiformes, com nítido atraso de pulso femoro-radial. Ausculta revela sopro sistólico suave em região interescapular dorsal esquerda. Qual é o diagnóstico?',
    A: 'Coarctação de Aorta.',
    B: 'Persistência do Canal Arterial.',
    C: 'Defeito do Septo Atrioventricular total.',
    D: 'Estenose valvar aórtica congênita crítica.',
    ans: 'A',
    comment: 'A disparidade de pulsos e de pressão arterial entre membros superiores (hipertensão) e inferiores (hipotensão e pulsos diminuídos/atrasados), associada a sopro interescapular dorsal, é o quadro patognomônico da Coarctação da Aorta.',
    expA: 'Correta. Discrepância pressórica com gradiente MMSS > MMII e retardo femoro-radial define Coarctação de Aorta.',
    expB: 'Incorreta. A PCA cursa com pulsos amplos em quatro membros e sopro contínuo infraclavicular.',
    expC: 'Incorreta. DSAV cursa com insuficiência cardíaca e pulsos simétricos.',
    expD: 'Incorreta. Estenose aórtica reduz os pulsos de forma difusa (parvus et tardus em 4 membros).',
  });

  q({
    id: 'ped-cardio-100-026',
    subtopic: 'Coarctação de Aorta',
    inst: 'UNICAMP',
    year: 2024,
    statement: 'Qual anomalia valvar congênita está mais frequentemente associada à Coarctação de Aorta, ocorrendo em cerca de 50 a 80% dos pacientes acometidos?',
    A: 'Valva aórtica bicúspide.',
    B: 'Valva tricúspide com delaminação incompleta.',
    C: 'Valva mitral em paraquedas com orifício único.',
    D: 'Valva pulmonar quadricúspide estenótica.',
    ans: 'A',
    comment: 'A valva aórtica bicúspide é a malformação congênita associada mais prevalente na Coarctação de Aorta (50-80% dos casos), exigindo rastreio ecocardiográfico e vigilância a longo prazo para estenose, regurgitação e endocardite.',
    expA: 'Correta. A valva aórtica bicúspide é encontrada na grande maioria dos pacientes com Coarctação de Aorta.',
    expB: 'Incorreta. Alteração característica da Anomalia de Ebstein.',
    expC: 'Incorreta. Faz parte do complexo de Shone.',
    expD: 'Incorreta. Valva pulmonar quadricúspide é uma anomalia extremamente rara.',
  });

  q({
    id: 'ped-cardio-100-027',
    subtopic: 'Coarctação de Aorta',
    inst: 'ENARE',
    year: 2024,
    statement: 'Neonato de 10 dias de vida evolui subitamente com choque cardiogênico grave, letargia, palidez acinzentada, anúria e acidose láctica profunda logo após o fechamento do canal arterial. A palpação revela ausência completa de pulsos femorais. Qual medida farmacológica inicial é mandatória?',
    A: 'Infusão contínua imediata de Prostaglandina E1 (Alprostadil).',
    B: 'Indometacina intravenosa em bólus rápido para constrição ductal.',
    C: 'Furosemida em dose dobrada associada a carvedilol oral.',
    D: 'Bicarbonato de sódio contínuo sem drogas vasoativas.',
    ans: 'A',
    comment: 'Na coarctação crítica neonatal justa-ductal, o fechamento espontâneo do canal arterial interrompe o fluxo para a aorta descendente, gerando choque obstrutivo e anúria. A infusão de Prostaglandina E1 (Alprostadil) reabre o canal e restabelece a perfusão sistêmica.',
    expA: 'Correta. Prostaglandina E1 reabre o canal arterial, mantendo o fluxo distal até a cirurgia.',
    expB: 'Incorreta. Indometacina fecha o canal, o que levaria o recém-nascido ao óbito.',
    expC: 'Incorreta. Betabloqueadores e diuréticos em choque descompensado são deletérios.',
    expD: 'Incorreta. Bicarbonato não desobstrui a circulação sistêmica interrompida.',
  });

  q({
    id: 'ped-cardio-100-028',
    subtopic: 'Coarctação de Aorta',
    inst: 'USP-RP',
    year: 2023,
    statement: 'Qual síndrome genética em meninas com baixa estatura, pescoço alado, tórax em escudo e amenorreia primária tem forte associação com Coarctação de Aorta (cerca de 15 a 20% dos casos)?',
    A: 'Síndrome de Turner (cariótipo 45,X0).',
    B: 'Síndrome de Down (Trissomia 21).',
    C: 'Síndrome de Williams-Beuren (microdeleção 7q11.23).',
    D: 'Síndrome de Marfan (mutação no gene FBN1).',
    ans: 'A',
    comment: 'A Síndrome de Turner (45,X0) possui íntima correlação com Coarctação de Aorta e valva aórtica bicúspide. Todas as pacientes com Turner devem realizar ecocardiograma ou angio-RNM de aorta ao diagnóstico.',
    expA: 'Correta. A Coarctação de Aorta é a cardiopatia congênita típica da Síndrome de Turner.',
    expB: 'Incorreta. Down associa-se a defeito do septo atrioventricular (DSAV) e CIV.',
    expC: 'Incorreta. Williams associa-se à estenose aórtica supravalvar e estenose de ramos pulmonares.',
    expD: 'Incorreta. Marfan associa-se à ectasia da raiz aórtica e prolapso mitral.',
  });

  q({
    id: 'ped-cardio-100-029',
    subtopic: 'Coarctação de Aorta',
    inst: 'SCMSP',
    year: 2024,
    statement: 'Na radiografia de tórax de um adolescente com Coarctação de Aorta de longa data, quais são os dois sinais clássicos visualizados na aorta e nos arcos costais?',
    A: 'Sinal do 3 na aorta e erosões/entalhes nas bordas inferiores dos arcos costais posteriores (sinal de Roesler).',
    B: 'Sinal do boneco de neve e hiperinsuflação pulmonar com retificação de cúpulas.',
    C: 'Sinal do duplo contorno atrial e escavação profunda do tronco da pulmonar.',
    D: 'Sinal da cimitarra e desvio do mediastino para a direita.',
    ans: 'A',
    comment: 'O sinal do 3 na aorta corresponde à constrição da coarctação com dilatação pré e pós-estenótica. O sinal de Roesler são entalhes/erosões no bordo inferior da 3ª à 8ª costelas produzidos pela pulsação hipertrófica das artérias intercostais colaterais.',
    expA: 'Correta. Sinal do 3 e erosões costais de Roesler são patognomônicos da Coarctação aórtica.',
    expB: 'Incorreta. Sinal do boneco de neve ocorre na DATVP.',
    expC: 'Incorreta. Duplo contorno indica aumento de átrio esquerdo.',
    expD: 'Incorreta. Sinal da cimitarra caracteriza a drenagem anômala parcial de veias pulmonares direitas.',
  });

  q({
    id: 'ped-cardio-100-030',
    subtopic: 'Coarctação de Aorta',
    inst: 'UERJ',
    year: 2023,
    statement: 'Em um escolar de 8 anos com Coarctação de Aorta isolada nativa circunscrita com gradiente sistólico transcoarctação de 40 mmHg, qual é o tratamento intervencionista percutâneo de primeira linha amplamente aceito?',
    A: 'Angioplastia aórtica com implante de stent (endoprótese vascular).',
    B: 'Atriosseptostomia com balão de Rashkind.',
    C: 'Fechamento percutâneo por dispositivo Amplatzer.',
    D: 'Trombectomia mecânica rotacional por aspiração.',
    ans: 'A',
    comment: 'Em crianças maiores (> 25-30 kg) e adolescentes com coarctação aórtica nativa, o implante de stent vascular expansível é a terapia de escolha, pois reduz as taxas de recoarctação e aneurismas pós-procedimento comparado à dilatação isolada por balão.',
  expA: 'Correta. O implante de stent aórtico é a conduta padrão em crianças maiores e adolescentes.',
  expB: 'Incorreta. Rashkind é manobra de mistura atrial para neonatos com TGA.',
  expC: 'Incorreta. Amplatzer serve para ocluir comunicações (CIA, PCA), não para dilatar estenoses.',
  expD: 'Incorreta. A coarctação é uma malformação congênita obstrutiva parietal, não um trombo intraluminal agudo.',
  });

  q({
    id: 'ped-cardio-100-031',
    subtopic: 'Coarctação de Aorta',
    inst: 'UFRJ',
    year: 2024,
    statement: 'Qual complicação cerebrovascular potencialmente fatal tem incidência aumentada em pacientes jovens com Coarctação de Aorta devido à associação congênita e à hipertensão crônica na circulação cefálica?',
    A: 'Ruptura de aneurisma sacular intracraniano no Polígono de Willis (hemorragia subaracnóidea).',
    B: 'Trombose de seio sagital superior por hipercoagulabilidade congênita.',
    C: 'Arterite de Takayasu oclusiva do tronco braquiocefálico.',
    D: 'Malformação arteriovenosa da veia de Galeno com dilatação aneurismática.',
    ans: 'A',
    comment: 'Pacientes com Coarctação de Aorta apresentam risco aumentado (cerca de 5 a 10 vezes maior) de possuírem aneurismas saculares ("berry aneurysms") no Polígono de Willis, cujo risco de ruptura e hemorragia subaracnóidea é amplificado pela hipertensão arterial em território pré-coarctação.',
    expA: 'Correta. Aneurismas saculares no polígono de Willis associam-se à Coarctação e podem romper causando HSA.',
    expB: 'Incorreta. A Coarctação não induz trombofilia venosa primária.',
    expC: 'Incorreta. Takayasu é vasculite inflamatória adquirida de grandes vasos.',
    expD: 'Incorreta. Aneurisma de veia de Galeno é malformação vascular congênita neonatal específica.',
  });

  q({
    id: 'ped-cardio-100-032',
    subtopic: 'Coarctação de Aorta',
    inst: 'IAMSPE',
    year: 2024,
    statement: 'O que define a Coarctação de Aorta do tipo justaductal (a apresentação anatômica mais frequente)?',
    A: 'O estreitamento aórtico localiza-se na transição entre o arco aórtico e a aorta descendente, imediatamente oposto à inserção do ligamento/canal arterial.',
    B: 'A obstrução ocorre na aorta abdominal abaixo do nascimento das artérias renais.',
    C: 'A estenose situa-se na aorta ascendente proximal, entre os óstios coronarianos.',
    D: 'Ocorre estenose concêntrica exclusiva do tronco celíaco e artéria mesentérica superior.',
    ans: 'A',
    comment: 'A vasta maioria das coarctações é do tipo justaductal: estreitamento do istmo aórtico localizado no nível do ducto/ligamento arterioso, logo abaixo da emergência da artéria subclávia esquerda.',
    expA: 'Correta. O estreitamento justaductal no istmo aórtico é a localização anatômica clássica da coarctação.',
    expB: 'Incorreta. Coarctação abdominal é rara (associada a neurofibromatose ou arterite).',
    expC: 'Incorreta. Estenose de aorta ascendente caracteriza estenose supravalvar aórtica (Síndrome de Williams).',
    expD: 'Incorreta. Não define coarctação da aorta torácica.',
  });

  q({
    id: 'ped-cardio-100-033',
    subtopic: 'Coarctação de Aorta',
    inst: 'FMRP-USP',
    year: 2023,
    statement: 'No pós-operatório imediato da correção cirúrgica da Coarctação de Aorta, qual fenômeno vascular hipertensivo reflexo pode ocorrer nas primeiras 24 a 72 horas exigindo controle agressivo com vasodilatadores (ex: nitroprussiato de sódio ou esmolol)?',
    A: 'Hipertensão arterial rebote paradoxal associada à síndrome pós-coarctectomia (arterite mesentérica reativa).',
    B: 'Hipotensão profunda refratária com falência autonômica central.',
    C: 'Bloqueio sinoatrial agudo com síndrome bradi-taqui.',
    D: 'Trombocitopenia imune induzida por consumo plaquetário no leito aórtico.',
    ans: 'A',
    comment: 'A correção da coarctação restaura subitamente pressões pulsáteis elevadas aos leitos vasculares cronicamente subperfundidos abaixo da estenose. Ocorre estimulação de barorreceptores e do sistema renina-angiotensina com hipertensão paradoxal e risco de arterite mesentérica dolorosa (dor abdominal pós-coarctectomia).',
    expA: 'Correta. A hipertensão paradoxal pós-operatória e arterite mesentérica reativa exigem controle pressórico rigoroso.',
    expB: 'Incorreta. Ocorre hipertensão aguda de rebote, não hipotensão.',
    expC: 'Incorreta. A inervação do nó sinoatrial não é lesada na abordagem do istmo aórtico torácico.',
    expD: 'Incorreta. Não há trombocitopenia imune descrita como complicação padrão da coarctectomia.',
  });

  q({
    id: 'ped-cardio-100-034',
    subtopic: 'Coarctação de Aorta',
    inst: 'FAMERP',
    year: 2024,
    statement: 'Durante o exame físico de uma criança de 6 anos com sopro sistólico dorsal e suspeita de Coarctação de Aorta, qual gradiente de pressão arterial sistólica entre membro superior e membro inferior estabelece diagnóstico de relevância clínica?',
    A: 'Diferença de pressão arterial sistólica maior que 20 mmHg a favor dos membros superiores.',
    B: 'Diferença de pressão menor que 5 mmHg com pulsos idênticos.',
    C: 'Pressão diastólica em membros inferiores superior em 40 mmHg à dos membros superiores.',
    D: 'Pressão sistólica igual a zero em ambos os membros superiores.',
    ans: 'A',
    comment: 'Em condições normais, a pressão arterial sistólica nos membros inferiores é igual ou ligeiramente maior (5 a 10 mmHg) que nos membros superiores. Uma PAS em MMSS superior à de MMII em mais de 20 mmHg é altamente diagnóstica de Coarctação aórtica significativa.',
    expA: 'Correta. Gradiente sistólico MMSS > MMII superior a 20 mmHg confirma obstrução aórtica significativa.',
    expB: 'Incorreta. Gradiente < 5 mmHg é normal.',
    expC: 'Incorreta. Na coarctação a pressão em MMII é menor, não maior.',
    expD: 'Incorreta. A pressão em MMSS é elevada na coarctação típica.',
  });

  q({
    id: 'ped-cardio-100-035',
    subtopic: 'Coarctação de Aorta',
    inst: 'SMS-SP',
    year: 2023,
    statement: 'Qual é a técnica cirúrgica clássica de escolha para a correção definitiva da Coarctação de Aorta em recém-nascidos e lactentes pequenos?',
    A: 'Ressecção do segmento coarctado com anastomose término-terminal estendida.',
    B: 'Implante de prótese mecânica tubular com troca da aorta torácica inteira.',
    C: 'Enxerto com retalho de Dacron sem ressecção da área estenosada.',
    D: 'Cerclagem externa com anel de silicone restritivo no arco aórtico.',
    ans: 'A',
    comment: 'A cirurgia padrão-ouro no lactente é a ressecção de todo o tecido ductal e segmento estenosado da aorta, seguida de anastomose término-terminal estendida (end-to-end), preservando o crescimento do vaso e minimizando o risco de recoarctação.',
    expA: 'Correta. Ressecção com anastomose término-terminal estendida é a técnica consagrada em neonatos e lactentes.',
    expB: 'Incorreta. Tubos rígidos não acompanham o crescimento da criança e são contraindicados em lactentes.',
    expC: 'Incorreta. Retalhos protéticos simples têm maior taxa de formação tardia de aneurismas na parede oposta.',
    expD: 'Incorreta. Cerclagem aumentaria a estenose em vez de tratá-la.',
  });
}
