import { q } from './helper.js';

export function loadSec4() {
  q({
    id: 'ped-cardio-100-036',
    subtopic: 'Persistência do Canal Arterial (PCA)',
    inst: 'USP-SP',
    year: 2024,
    statement: 'Recém-nascido pré-termo de 27 semanas e 950 g, no 5º dia de vida, apresenta piora ventilatória, precórdio hiperdinâmico, pulsos periféricos amplos e em martelo d\'água e sopro contínuo em região infraclavicular esquerda. O ecocardiograma confirma PCA hemodinamicamente significativa com diâmetro de 2,8 mm. Qual é o mecanismo de ação dos fármacos de primeira linha (Ibuprofeno e Indometacina) no tratamento dessa condição?',
    A: 'Inibição da enzima ciclo-oxigenase (COX), bloqueando a síntese de prostaglandinas vasodilatadoras (especialmente PGE2) e promovendo a constrição do canal.',
    B: 'Bloqueio seletivo dos canais de cálcio do tipo L nas células musculares lisas ductais.',
    C: 'Estímulo direto dos receptores de óxido nítrico endotelial com vasoconstrição paradoxal.',
    D: 'Aumento da degradação hepática da bradicinina plasmática e do peptídeo natriurético.',
    ans: 'A',
    comment: 'O canal arterial é mantido pérvio na vida fetal por baixas tensões de oxigênio e altas concentrações de prostaglandinas (principalmente PGE2 sintetizada localmente e pela placenta). Os inibidores da COX (Ibuprofeno ou Indometacina) diminuem os níveis circulantes de PGE2, estimulando a contração muscular da túnica média e o fechamento do canal.',
    expA: 'Correta. A inibição da síntese de prostaglandinas via bloqueio da COX é o mecanismo terapêutico clássico para fechar o canal no prematuro.',
    expB: 'Incorreta. Bloqueadores de cálcio relaxam a musculatura vascular e manteriam o canal aberto.',
    expC: 'Incorreta. Óxido nítrico é um potente vasodilatador pulmonar e ductal.',
    expD: 'Incorreta. A via de fechamento ductal é mediada por prostaglandinas e oxigênio, não por degradação de bradicinina.',
  });

  q({
    id: 'ped-cardio-100-037',
    subtopic: 'Persistência do Canal Arterial (PCA)',
    inst: 'UNICAMP',
    year: 2024,
    statement: 'Em um prematuro extremo com PCA hemodinamicamente significativa, qual das seguintes condições clínicas constitui contraindicação formal ao uso de anti-inflamatórios inibidores da COX (Ibuprofeno ou Indometacina)?',
    A: 'Enterocolite necrosante ativa ou sangramento gastrintestinal clinicamente evidente.',
    B: 'Dependência de oxigênio com necessidade de ventilação mecânica não invasiva (CPAP).',
    C: 'Glicemia sérica de 85 mg/dL com fração de ejeção do VE de 65%.',
    D: 'Presença de sopro contínuo audível na ausculta cardíaca.',
    ans: 'A',
    comment: 'Inibidores da COX reduzem o fluxo sanguíneo esplâncnico e renal e inibem a agregação plaquetária. Suas contraindicações formais são: sangramento ativo significativo, trombocitopenia grave (< 50.000/mm³), enterocolite necrosante (ECN) suspeita ou confirmada, perfuração intestinal e insuficiência renal grave (anúria ou creatinina muito elevada).',
    expA: 'Correta. Enterocolite necrosante e sangramento ativo são contraindicações absolutas aos AINEs.',
    expB: 'Incorreta. Desconforto respiratório é indicação clássica para tratar a PCA.',
    expC: 'Incorreta. Glicemia e fração de ejeção normais não contraindicam o tratamento.',
    expD: 'Incorreta. O sopro é manifestação física da PCA, indicando a necessidade de avaliação e tratamento.',
  });

  q({
    id: 'ped-cardio-100-038',
    subtopic: 'Persistência do Canal Arterial (PCA)',
    inst: 'ENARE',
    year: 2024,
    statement: 'Qual é o nome semiológico clássico atribuído ao sopro contínuo que ocupa toda a sístole e diástole com reforço telessistólico, melhor audível no 1º e 2º espaços intercostais esquerdos infraclaviculares na Persistência do Canal Arterial?',
    A: 'Sopro de Gibson (sopro em maquinária).',
    B: 'Sopro de Austin Flint.',
    C: 'Sopro de Carey Coombs.',
    D: 'Sopro de Graham-Steell.',
    ans: 'A',
    comment: 'O sopro de Gibson é o clássico sopro contínuo em maquinária (ou em locomotiva). Ocorre porque a pressão na aorta é superior à pressão na artéria pulmonar tanto na sístole quanto na diástole, gerando fluxo contínuo e turbilhonado ao longo de todo o ciclo cardíaco.',
    expA: 'Correta. O sopro em maquinária de Gibson é o sinal semiológico clássico da PCA.',
    expB: 'Incorreta. Austin Flint é sopro mesodiastólico apical por regurgitação aórtica grave sobre o folheto mitral.',
    expC: 'Incorreta. Carey Coombs é sopro mesodiastólico na cardite reumática ativa.',
    expD: 'Incorreta. Graham-Steell é sopro diastólico de insuficiência pulmonar por hipertensão pulmonar grave.',
  });

  q({
    id: 'ped-cardio-100-039',
    subtopic: 'Persistência do Canal Arterial (PCA)',
    inst: 'FAMERP',
    year: 2023,
    statement: 'Em recém-nascidos prematuros com PCA hemodinamicamente significativa que apresentam contraindicação formal ao uso de ibuprofeno e indometacina (como plaquetopenia grave ou sangramento ativo), qual fármaco intravenoso tem demonstrado eficácia comparável para o fechamento ductal com menor toxicidade gastrointestinal e renal?',
    A: 'Paracetamol (Acetaminofeno) intravenoso.',
    B: 'Alprostadil (Prostaglandina E1).',
    C: 'Sildenafil intravenoso.',
    D: 'Captopril sublingual.',
    ans: 'A',
    comment: 'O Paracetamol intravenoso atua inibindo a peroxidase na enzima prostaglandina H2 sintase (sítio diferente da COX inibida pelos AINEs clássicos). Vários ensaios clínicos demonstraram taxas de fechamento ductal similares às do ibuprofeno, com a grande vantagem de não inibir plaquetas nem causar vasoconstrição renal ou mesentérica, sendo excelente alternativa segura quando há contraindicação a AINEs.',
    expA: 'Correta. O paracetamol IV é alternativa consagrada quando há contraindicação a inibidores da COX.',
    expB: 'Incorreta. O Alprostadil mantém o canal aberto, o que agravaria o quadro.',
    expC: 'Incorreta. O sildenafil é vasodilatador pulmonar e não fecha o canal.',
    expD: 'Incorreta. Captopril não fecha o canal arterial.',
  });

  q({
    id: 'ped-cardio-100-040',
    subtopic: 'Persistência do Canal Arterial (PCA)',
    inst: 'UFRJ',
    year: 2024,
    statement: 'Qual é o fenômeno hemodinâmico sistêmico gerado por uma PCA calibrosa no prematuro que predispõe ao desenvolvimento de enterocolite necrosante, insuficiência renal e hemorragia peri-intraventricular?',
    A: 'Roubo de fluxo diastólico sistêmico ("diastolic steal") decorrente do desvio maciço de sangue da aorta para a artéria pulmonar durante a diástole.',
    B: 'Hipertensão arterial sistólica fulminante com vasoespasmo coronariano reflexo.',
    C: 'Congestão venosa hepática com estase portal retrógrada pura.',
    D: 'Trombocitopenia dilucional extrema por sequestro esplênico maciço.',
    ans: 'A',
    comment: 'Como a resistência vascular pulmonar é baixa, ocorre um escoamento contínuo de sangue da aorta para o leito pulmonar, inclusive durante a diástole ("roubo diastólico"). Isso gera fluxo reverso na aorta descendente com hipoperfusão diastólica crítica nos órgãos abdominais (isquemia mesentérica -> ECN; isquemia renal) e flutuações no fluxo cerebral (predispondo a hemorragia intracraniana).',
    expA: 'Correta. O roubo de fluxo diastólico da aorta para o pulmão hipoperfunde os leitos mesentérico, renal e cerebral.',
    expB: 'Incorreta. A PCA não gera hipertensão sistólica fulminante, mas sim pressão de pulso ampla por queda da diastólica.',
    expC: 'Incorreta. A fisiopatologia primária das lesões isquêmicas é o baixo débito diastólico sistêmico, não estase retrógrada isolada.',
    expD: 'Incorreta. Não decorre de hiperesplenismo.',
  });

  q({
    id: 'ped-cardio-100-041',
    subtopic: 'Persistência do Canal Arterial (PCA)',
    inst: 'UERJ',
    year: 2023,
    statement: 'Em um lactente de 9 meses, hígido, no qual se ausculta sopro contínuo infraclavicular esquerdo e o ecocardiograma confirma PCA de 3 mm com dilatação de átrio e ventrículo esquerdos, qual é o método terapêutico definitivo de escolha?',
    A: 'Fechamento percutâneo por cateterismo intervencionista com implante de mola (coil) ou prótese oclusora (plug/Amplatzer).',
    B: 'Ciclo de Indometacina intravenosa por 3 doses consecutivas.',
    C: 'Tratamento clínico com furosemida até a puberdade sem intervenção mecânica.',
    D: 'Transplante cardíaco pediátrico ortotópico precoce.',
    ans: 'A',
    comment: 'Fora do período neonatal imediato, o canal arterial perde a capacidade de resposta farmacológica aos inibidores da COX (pois o tecido ductal já não responde a prostaglandinas). O tratamento definitivo de escolha para lactentes e crianças é o fechamento percutâneo via cateterismo cardíaco com coils ou dispositivos oclusores dedicados (baixo risco e rápida recuperação).',
    expA: 'Correta. O fechamento percutâneo por cateterismo é o método padrão-ouro e curativo em lactentes maiores.',
    expB: 'Incorreta. Anti-inflamatórios são eficazes apenas no período neonatal imediato (especialmente em prematuros).',
    expC: 'Incorreta. A PCA com sobrecarga de câmaras esquerdas requer oclusão mecânica para evitar dilatação e arritmias.',
    expD: 'Incorreta. O transplante não tem qualquer cabimento em uma anomalia extracardíaca simples e perfeitamente corrigível.',
  });

  q({
    id: 'ped-cardio-100-042',
    subtopic: 'Persistência do Canal Arterial (PCA)',
    inst: 'FMRP-USP',
    year: 2024,
    statement: 'Qual é o estímulo fisiológico mais potente responsável pelo desencadeamento do fechamento funcional do canal arterial nas primeiras horas de vida de um recém-nascido a termo?',
    A: 'Elevação expressiva da pressão parcial de oxigênio arterial (PaO2) com a primeira ventilação pulmonar, associada à queda dos níveis de PGE2 após a remoção da placenta.',
    B: 'Aumento abrupto dos níveis circulantes de adenosina e óxido nítrico fetal.',
    C: 'Hipotermia fisiológica transitória pós-parto imediato.',
    D: 'Acidose metabólica decorrente do clampeamento do cordão umbilical.',
    ans: 'A',
    comment: 'Ao nascer, a expansão pulmonar eleva a PaO2 arterial de ~25-30 mmHg no feto para > 70-90 mmHg. O oxigênio atua diretamente sobre canais de potássio nas células musculares lisas ductais, promovendo influxo de cálcio e vasoconstrição. Concomitantemente, a eliminação da placenta e o clearance pulmonar reduzem abruptamente os níveis circulantes de PGE2, levando ao fechamento funcional.',
    expA: 'Correta. A hiperóxia pós-natal e a queda das prostaglandinas materno-placentárias promovem o fechamento ductal.',
    expB: 'Incorreta. Adenosina e óxido nítrico são vasodilatadores que mantêm o canal aberto.',
    expC: 'Incorreta. A hipotermia neonatal na verdade retarda o fechamento ductal.',
    expD: 'Incorreta. A acidose relaxa a musculatura ductal, impedindo a constrição eficaz.',
  });

  q({
    id: 'ped-cardio-100-043',
    subtopic: 'Persistência do Canal Arterial (PCA)',
    inst: 'IAMSPE',
    year: 2023,
    statement: 'Por que o canal arterial é anatomicamente essencial para a sobrevivência intrauterina do feto humano normal?',
    A: 'Desvia cerca de 90% do débito do ventrículo direito diretamente para a aorta descendente, contornando a vasculatura pulmonar fetal colapsada de alta resistência.',
    B: 'Garante o fluxo exclusivo de sangue oxigenado para as artérias coronárias a partir da veia umbilical.',
    C: 'Impede que o sangue do ventrículo esquerdo chegue ao cérebro fetal antes do terceiro trimestre.',
    D: 'Promove a oxigenação do sangue venoso fetal diretamente na luz da artéria pulmonar.',
    ans: 'A',
    comment: 'No feto, os pulmões não realizam trocas gasosas e a resistência vascular pulmonar é muito elevada. O canal arterial conecta a artéria pulmonar principal à aorta descendente, permitindo que a maior parte do sangue ejetado pelo VD contorne os pulmões e siga em direção à placenta para oxigenação.',
    expA: 'Correta. O canal desvia o débito do VD diretamente para a aorta descendente e placenta na circulação fetal.',
    expB: 'Incorreta. O sangue oxigenado da veia umbilical vai preferencialmente ao átrio esquerdo via forame oval e irriga coronárias e cérebro.',
    expC: 'Incorreta. O VE irriga cérebro e membros superiores via aorta ascendente.',
    expD: 'Incorreta. A oxigenação fetal ocorre exclusivamente na placenta.',
  });

  q({
    id: 'ped-cardio-100-044',
    subtopic: 'Persistência do Canal Arterial (PCA)',
    inst: 'FAMERP',
    year: 2024,
    statement: 'Qual achado no pulso arterial periférico é clássico da Persistência do Canal Arterial com repercussão hemodinâmica?',
    A: 'Pulsos amplos, céleres e hiperdinâmicos (pulsos em martelo d\'água ou de Corrigan), com pressão arterial diastólica baixa e diferencial de pulso alargado.',
    B: 'Pulsos parvus et tardus (pequena amplitude e ascensão lenta) em quatro membros.',
    C: 'Assimetria isolada entre o membro superior direito e o esquerdo.',
    D: 'Pulso alternante associado a pulso paradoxal respiratório com colapso inspiratório.',
    ans: 'A',
    comment: 'O desvio maciço de sangue da aorta para o leito pulmonar durante a diástole faz a pressão arterial diastólica despencar. Como o volume sistólico do VE é elevado pelo hiperfluxo, a pressão sistólica se mantém ou eleva, resultando em pressão de pulso ampliada (diferencial aumentado) e pulsos amplos e hiperdinâmicos (martelo d\'água).',
    expA: 'Correta. Pulsos amplos em martelo d\'água com pressão diastólica baixa são a marca semiológica periférica da PCA calibrosa.',
    expB: 'Incorreta. Parvus et tardus é característico de estenose aórtica grave.',
    expC: 'Incorreta. Assimetria de pulsos em MMSS aponta para anomalia de artéria subclávia ou arterite de Takayasu.',
    expD: 'Incorreta. Pulso alternante ocorre na disfunção miocárdica terminal e pulso paradoxal no tamponamento cardíaco.',
  });

  q({
    id: 'ped-cardio-100-045',
    subtopic: 'Persistência do Canal Arterial (PCA)',
    inst: 'SMS-SP',
    year: 2023,
    statement: 'Qual síndrome congênita materna infecciosa tem na Persistência do Canal Arterial (PCA) e na Estenose de Ramos da Artéria Pulmonar as suas manifestações cardiovasculares mais clássicas?',
    A: 'Síndrome da Rubéola Congênita (Tétrada de Gregg).',
    B: 'Síndrome da Toxoplasmose Congênita (Tétrada de Sabin).',
    C: 'Citomegalovirose congênita primária.',
    D: 'Sífilis congênita precoce.',
    ans: 'A',
    comment: 'A Síndrome da Rubéola Congênita é historicamente marcada pela clássica Tétrade de Gregg: catarata congênita, surdez neurossensorial, microcefalia e cardiopatia congênita (especialmente PCA e estenose periférica de artérias pulmonares).',
    expA: 'Correta. A Rubéola Congênita é o agente teratogênico infeccioso classicamente associado à PCA.',
    expB: 'Incorreta. Toxoplasmose cursa com coriorretinite, hidrocefalia e calcificações cerebrais difusas (Tétrada de Sabin).',
    expC: 'Incorreta. CMV cursa com calcificações periventriculares e microcefalia, sem associação direta com PCA.',
    expD: 'Incorreta. Sífilis cursa com rinite serossanguinolenta, lesões palmo-plantares e osteocondrite.',
  });

  q({
    id: 'ped-cardio-100-046',
    subtopic: 'Persistência do Canal Arterial (PCA)',
    inst: 'PUC-PR',
    year: 2024,
    statement: 'Na evolução tardia de uma grande PCA não tratada que desenvolveu Síndrome de Eisenmenger, qual é a alteração peculiar e patognomônica da distribuição da cianose no exame físico (cianose diferencial)?',
    A: 'Cianose presente exclusivamente nos membros inferiores e pés, enquanto os membros superiores e cabeça mantêm-se corados e com saturação de oxigênio normal.',
    B: 'Cianose intensa restrita ao hemicorpo direito com palidez no hemicorpo esquerdo.',
    C: 'Cianose exclusiva nos lábios e língua com pés normais e rosados.',
    D: 'Cianose alternante que muda de membro a cada batimento cardíaco.',
    ans: 'A',
    comment: 'Na Síndrome de Eisenmenger decorrente de PCA, o shunt inverte da artéria pulmonar para a aorta descendente (direita-esquerda). Como o canal arterial desemboca na aorta distalmente à emergência dos vasos braquiocefálicos (subclávia esquerda, carótida e tronco braquiocefálico), o sangue desoxigenado irriga apenas a porção inferior do corpo, gerando a clássica cianose diferencial (membros superiores normais e membros inferiores cianóticos com baqueteamento digital nos pododáctilos).',
    expA: 'Correta. A cianose diferencial (MMII cianóticos com MMSS rosados) é patognomônica da PCA com Eisenmenger.',
    expB: 'Incorreta. A distribuição não respeita simetria lateral, mas sim proximal versus distal ao canal.',
    expC: 'Incorreta. A cabeça recebe sangue oxigenado pré-ductal e permanece corada.',
    expD: 'Incorreta. A cianose é fixa e anatômica, não alternante.',
  });
}
