import { q } from './helper.js';

export function loadSec5() {
  q({
    id: 'ped-cardio-100-047',
    subtopic: 'Transposição das Grandes Artérias (TGA)',
    inst: 'USP-SP',
    year: 2024,
    statement: 'Qual é a alteração anatômica que define a Transposição das Grandes Artérias (TGA completa ou D-TGA)?',
    A: 'Discordância ventriculoarterial: a aorta emerge do ventrículo direito (com sangue desoxigenado) e o tronco da artéria pulmonar emerge do ventrículo esquerdo (com sangue oxigenado).',
    B: 'Discordância atrioventricular pura com posicionamento invertido das valvas semilunares.',
    C: 'Conexão anômala da veia cava superior no átrio esquerdo associada a tronco arterioso único.',
    D: 'Atresia da valva aórtica com hipoplasia acentuada das artérias coronárias esquerdas.',
    ans: 'A',
    comment: 'Na D-TGA clássica, as conexões atrioventriculares são concordantes (AD->VD e AE->VE), mas as conexões ventriculoarteriais são discordantes: a aorta nasce do VD e a artéria pulmonar nasce do VE, criando dois circuitos vasculares independentes e paralelos.',
    expA: 'Correta. A discordância ventriculoarterial com dois circuitos fechados e paralelos é a definição da D-TGA.',
    expB: 'Incorreta. Discordância AV combinada com discordância VA define a L-TGA (transposição corrigida).',
    expC: 'Incorreta. Conexão venosa sistêmica anômala é outra entidade embriológica.',
    expD: 'Incorreta. Atresia aórtica caracteriza a Síndrome do Coração Esquerdo Hipoplásico.',
  });

  q({
    id: 'ped-cardio-100-048',
    subtopic: 'Transposição das Grandes Artérias (TGA)',
    inst: 'UNICAMP',
    year: 2024,
    statement: 'Recém-nascido a termo, masculino, peso 3.500 g, apresenta cianose central importante refratária com 4 horas de vida. O teste de hiperóxia (FiO2 a 100% por 10 minutos) mantém PaO2 de 38 mmHg e SatO2 de 64%. O ecocardiograma confirma TGA com septo interventricular íntegro e forame oval restritivo de 1,5 mm. Qual procedimento intervencionista de urgência está indicado?',
    A: 'Atriosseptostomia por cateter-balão (procedimento de Rashkind).',
    B: 'Valvoplastia aórtica percutânea por balão retrógrado.',
    C: 'Cerclagem bilateral dos ramos das artérias pulmonares.',
    D: 'Fechamento imediato do canal arterial com indometacina.',
    ans: 'A',
    comment: 'Na TGA com septo intacto, a sobrevivência depende de mistura sanguínea eficaz entre os dois circuitos paralelos. Se o forame oval for restritivo, o sangue oxigenado do AE não consegue alcançar o AD e o VD. A atriosseptostomia com balão de Rashkind rompe a lâmina do septo interatrial na beira do leito (guiada por ecocardiograma), criando uma ampla CIA que permite a mistura vital de sangue até a cirurgia definitiva.',
    expA: 'Correta. O procedimento de Rashkind cria comunicação interatrial para garantir mistura sanguínea e sobrevida imediata.',
    expB: 'Incorreta. A valva aórtica não é primariamente estenótica na TGA.',
    expC: 'Incorreta. Cerclagem de ramos pulmonares não resolve a falta de mistura intracardíaca.',
    expD: 'Incorreta. Fechar o canal arterial provocaria colapso e óbito imediato do neonato.',
  });

  q({
    id: 'ped-cardio-100-049',
    subtopic: 'Transposição das Grandes Artérias (TGA)',
    inst: 'ENARE',
    year: 2024,
    statement: 'Qual é o tratamento cirúrgico definitivo anatômico de escolha para a Transposição das Grandes Artérias com septo interventricular íntegro e em que período ideal ele deve ser realizado?',
    A: 'Operação de Jatene (troca anatômica das artérias aorta e pulmonar com reimplante dos óstios coronarianos), idealmente nas primeiras 2 a 3 semanas de vida.',
    B: 'Cirurgia de Senning ou Mustard (inversão do fluxo no nível atrial com retalhos pericárdicos), realizada após os 2 anos de idade.',
    C: 'Operação de Glenn bidirecional isolada na primeira semana.',
    D: 'Operação de Fontan terminoterminal estagiada no primeiro mês.',
    ans: 'A',
    comment: 'A cirurgia de Jatene (arterial switch) é o padrão-ouro anatômico: a aorta é transposta para o VE (neoaorta), o tronco pulmonar para o VD (neopulmonar) e os botões coronarianos são reimplantados na neoaorta. Deve ser feita nas primeiras 2 a 3 semanas de vida, antes que o ventrículo esquerdo (exposto a pressões pulmonares baixas) perca sua massa muscular e não consiga mais suportar a circulação sistêmica.',
    expA: 'Correta. A cirurgia de Jatene é o tratamento corretivo anatômico ideal nas primeiras 2-3 semanas de vida.',
    expB: 'Incorreta. Senning/Mustard são cirurgias fisiológicas antigas com alta incidência de disfunção ventricular direita tardia.',
    expC: 'Incorreta. Glenn é paliativo para circulação univentricular.',
    expD: 'Incorreta. Fontan é a etapa final de fisiologia univentricular.',
  });

  q({
    id: 'ped-cardio-100-050',
    subtopic: 'Transposição das Grandes Artérias (TGA)',
    inst: 'USP-RP',
    year: 2023,
    statement: 'Qual é o aspecto radiológico característico da silhueta cardíaca e do mediastino superior na radiografia de tórax de um neonato com TGA?',
    A: 'Aspecto de coração em ovo deitado na horizontal sobre o diafragma, com pedículo vascular mediastinal superior estreito ("egg-on-a-string").',
    B: 'Coração em formato de bota holandesa com hipofluxo pulmonar periférico.',
    C: 'Cardiomegalia globular em moringa com área cardíaca ocupando 95% do tórax.',
    D: 'Aspecto de coração em boneco de neve com abaulamento acentuado do mediastino superior.',
    ans: 'A',
    comment: 'Na TGA, a aorta situa-se anteriormente e paralela ao tronco pulmonar (em vez de cruzar em espiral), o que estreita a silhueta vascular mediastinal no RX anteroposterior. Associado à hipertrofia e dilatação do coração, gera a imagem clássica do "ovo deitado apoiado sobre um barbante" (egg on a string).',
    expA: 'Correta. Egg-on-a-string (ovo deitado com pedículo estreito) e hiperfluxo pulmonar definem a radiologia da TGA.',
    expB: 'Incorreta. Bota holandesa (coeur en sabot) é típica da Tetralogia de Fallot.',
    expC: 'Incorreta. Coração em moringa caracteriza a Anomalia de Ebstein.',
    expD: 'Incorreta. Boneco de neve é característico da DATVP supracardíaca.',
  });

  q({
    id: 'ped-cardio-100-051',
    subtopic: 'Transposição das Grandes Artérias (TGA)',
    inst: 'SCMSP',
    year: 2024,
    statement: 'Qual é o papel obrigatório da infusão contínua de Prostaglandina E1 (Alprostadil) na fase inicial de estabilização de um neonato com diagnóstico suspeito ou confirmado de TGA?',
    A: 'Manter a perviedade do canal arterial, permitindo um shunt bidirecional fundamental para a mistura de sangue oxigenado e desoxigenado entre os circuitos sistêmico e pulmonar.',
    B: 'Promover a dilatação coronariana seletiva impedindo a isquemia miocárdica induzida por bradicardia.',
    C: 'Fechar rapidamente a comunicação interatrial para evitar congestão venosa no átrio direito.',
    D: 'Estimular a hipertrofia rápida da parede livre do ventrículo esquerdo.',
    ans: 'A',
    comment: 'A Prostaglandina E1 mantém o canal arterial amplamente aberto. Na TGA, o canal arterial funciona como uma das principais portas de mistura entre a aorta (circulação sistêmica) e a artéria pulmonar (circulação pulmonar), evitando anóxia tecidual fatal até a abordagem cirúrgica.',
    expA: 'Correta. A PGE1 garante o canal arterial aberto para viabilizar a mistura de sangue entre os dois circuitos paralelos.',
    expB: 'Incorreta. O objetivo central é manter o canal arterial pérvio, não dilatação coronariana isolada.',
    expC: 'Incorreta. A CIA deve ser mantida aberta ou ampliada, nunca fechada na TGA neonatal.',
    expD: 'Incorreta. Prostaglandinas não têm ação indutora de hipertrofia miocárdica de VE.',
  });

  q({
    id: 'ped-cardio-100-052',
    subtopic: 'Transposição das Grandes Artérias (TGA)',
    inst: 'UERJ',
    year: 2023,
    statement: 'Por que o teste de hiperóxia (oferta de FiO2 a 100% por máscara por 10 minutos) é considerado negativo (ou seja, aponta fortemente para cardiopatia congênita cianótica com shunt intracardíaco fixo como na TGA) quando a PaO2 arterial não ultrapassa qual valor de corte?',
    A: 'PaO2 permanece inferior a 150 mmHg (geralmente mantendo-se entre 30 e 60 mmHg).',
    B: 'PaO2 ultrapassa obrigatoriamente 450 mmHg.',
    C: 'PaO2 atinge exatamente 600 mmHg em ar ambiente.',
    D: 'PaO2 diminui para zero imediatamente.',
    ans: 'A',
    comment: 'Em patologias pulmonares puras (SDR, aspiração meconial, taquipneia transitória), a oferta de O2 a 100% eleva a PaO2 para valores > 150-250 mmHg. Em cardiopatias cianóticas com circulação em paralelo (TGA) ou shunt D-E fixo, o sangue venoso desvia diretamente para a aorta sem passar pelos alvéolos oxigenados, mantendo a PaO2 teimosamente baixa (< 100-150 mmHg).',
    expA: 'Correta. PaO2 < 150 mmHg sob FiO2 a 100% confirma teste de hiperóxia negativo (sugestivo de cardiopatia congênita cianótica).',
    expB: 'Incorreta. PaO2 > 450 mmHg descarta shunt intracardíaco fixo significativo.',
    expC: 'Incorreta. Em ar ambiente a PaO2 máxima ao nível do mar é ~100 mmHg.',
    expD: 'Incorreta. A PaO2 nunca atinge zero fisiologicamente.',
  });

  q({
    id: 'ped-cardio-100-053',
    subtopic: 'Transposição das Grandes Artérias (TGA)',
    inst: 'UFRJ',
    year: 2024,
    statement: 'Qual é o perfil epidemiológico e físico clássico do recém-nascido com Transposição das Grandes Artérias simples ao nascimento?',
    A: 'Recém-nascido a termo, com peso adequado para a idade gestacional ou macrossômico (frequentemente filho de mãe com diabetes gestacional), do sexo masculino, que se apresenta cianótico porém inicialmente vigoroso e sem desconforto respiratório importante.',
    B: 'Prematuro extremo com peso < 1.000 g com graves malformações craniofaciais e membros ausentes.',
    C: 'Neonato hipotérmico, microcefálico com calcificações cerebrais periventriculares extensas.',
    D: 'Neonato feminino pós-termo anencefálico com tórax escavado.',
    ans: 'A',
    comment: 'O bebê com TGA simples é classicamente um RN a termo ou macrossômico (muitas vezes filho de mãe diabética), do sexo masculino (proporção 2-3:1), com peso excelente e bom escore de Apgar, que se apresenta cianótico "confortável" nas primeiras horas de vida (cianose sem taquipneia ou tiragens no início).',
    expA: 'Correta. RN a termo, sexo masculino, peso normal/elevado, cianótico porém inicialmente sem desconforto evidente.',
    expB: 'Incorreta. A TGA raramente se associa a anomalias extracardíacas sindrômicas em prematuros extremos.',
    expC: 'Incorreta. Descrição clássica de infecção congênita por citomegalovírus.',
    expD: 'Incorreta. Não há correlação com anencefalia.',
  });

  q({
    id: 'ped-cardio-100-054',
    subtopic: 'Transposição das Grandes Artérias (TGA)',
    inst: 'IAMSPE',
    year: 2023,
    statement: 'Em um lactente de 2 meses com TGA simples que não foi diagnosticado no período neonatal e apresenta-se agora para avaliação cirúrgica tardia, por que a cirurgia de Jatene pode não ser mais factível em tempo único?',
    A: 'Porque a pressão e a resistência vascular pulmonar caíram após o nascimento, fazendo com que o ventrículo esquerdo (que ejeta para o pulmão na TGA) atrofie e descondicione, tornando-se incapaz de assumir a pressão sistêmica da aorta.',
    B: 'Porque as artérias coronárias obliteram-se fisiologicamente após a 4ª semana de vida.',
    C: 'Pelo fechamento congênito irreversível da valva tricúspide com fibroelastose.',
    D: 'Devido à ossificação precoce da raiz da artéria pulmonar principal.',
    ans: 'A',
    comment: 'Na TGA simples, o VE está conectado à artéria pulmonar. Conforme a RVP cai nas primeiras semanas, o VE passa a ejetar contra pressões muito baixas (~20-25 mmHg), ocorrendo remodelamento com afilamento da parede livre (descondicionamento de VE). Se o VE for conectado subitamente à circulação sistêmica de alta pressão (Jatene tardio), ele entra em falência aguda.',
    expA: 'Correta. O descondicionamento do ventrículo esquerdo pela queda da RVP impede que ele assuma o regime pressórico sistêmico sem preparo prévio.',
    expB: 'Incorreta. As artérias coronárias permanecem pérvias ao longo de toda a vida.',
    expC: 'Incorreta. A valva tricúspide conecta-se ao VD e não sofre atresia secundária.',
    expD: 'Incorreta. Não ocorre ossificação da artéria pulmonar.',
  });

  q({
    id: 'ped-cardio-100-055',
    subtopic: 'Transposição das Grandes Artérias (TGA)',
    inst: 'FMRP-USP',
    year: 2024,
    statement: 'Como é chamado o procedimento cirúrgico estagiado de preparação do ventrículo esquerdo ("retreinamento do VE") em lactentes com TGA descondicionado, preparando-o para posterior cirurgia de Jatene?',
    A: 'Bandeamento da artéria pulmonar associado a um shunt sistêmico-pulmonar (Blalock-Taussig).',
    B: 'Cirurgia de Fontan extracardíaca com conduto fenestrado.',
    C: 'Operação de Ross com autoenxerto valvar pulmonar.',
    D: 'Valvoplastia mitral com anel protético percutâneo.',
    ans: 'A',
    comment: 'Para retreinar o VE atrófico na TGA tardia, o cirurgião realiza o bandeamento da artéria pulmonar (constrição mecânica com fita para forçar o VE a trabalhar contra alta pós-carga e hipertrofiar em 1 a 2 semanas), frequentemente associado a um shunt de Blalock-Taussig para garantir oxigenação durante o processo.',
    expA: 'Correta. O bandeamento da artéria pulmonar eleva a pós-carga de VE, induzindo hipertrofia muscular para posterior Jatene.',
    expB: 'Incorreta. Fontan é para circulação univentricular.',
    expC: 'Incorreta. Cirurgia de Ross substitui a valva aórtica doente pela pulmonar autóloga.',
    expD: 'Incorreta. A valva mitral é anatomicamente normal.',
  });

  q({
    id: 'ped-cardio-100-056',
    subtopic: 'Transposição das Grandes Artérias (TGA)',
    inst: 'FAMERP',
    year: 2023,
    statement: 'Na cirurgia anatômica de Jatene para TGA, qual etapa técnica é a mais delicada e crucial para o sucesso da sobrevida do paciente e prevenção de isquemia miocárdica fatal?',
    A: 'Mobilização cuidadosa e reimplante dos botões das artérias coronárias da aorta nativa para a neoaorta.',
    B: 'Fechamento da veia ázigos retropleural com clipe de titânio.',
    C: 'Secção transversa da traqueia torácica para descompressão de vias aéreas.',
    D: 'Implante de marcapasso epicárdico definitivo de rotina em todos os casos.',
    ans: 'A',
    comment: 'O reimplante coronariano é o tempo cirúrgico mais complexo da operação de Jatene. As coronárias emergem do vaso que originalmente era a aorta (conectada ao VD) e precisam ser transferidas em pequenos botões parietais para a raiz da neoaorta sem torção, estenose ou acotovelamento (kinking), sob pena de infarto agudo e colapso miocárdico imediato.',
    expA: 'Correta. A transferência meticulosa das artérias coronárias para a neoaorta é o passo determinante do prognóstico cirúrgico.',
    expB: 'Incorreta. A veia ázigos não faz parte das grandes artérias transpostas.',
    expC: 'Incorreta. A traqueia não é seccionada na cirurgia cardiovascular.',
    expD: 'Incorreta. Marcapasso definitivo é reservado apenas para casos de bloqueio AV irreversível pós-operatório raro.',
  });

  q({
    id: 'ped-cardio-100-057',
    subtopic: 'Transposição das Grandes Artérias (TGA)',
    inst: 'SMS-SP',
    year: 2024,
    statement: 'Qual é a alteração auscultatória e semiológica comumente encontrada no recém-nascido com TGA simples (sem CIV ou estenose pulmonar associada)?',
    A: 'Ausculta com bulhas rítmicas e normofonéticas ou segunda bulha única hiperfonética, frequentemente sem sopros patológicos significativos nas primeiras horas de vida.',
    B: 'Sopro holossistólico 5+/6+ com frêmito em toda a borda esternal esquerda.',
    C: 'Sopro contínuo em maquinária audível até o dorso com pulsos em martelo d\'água.',
    D: 'Sopro diastólico aspirativo 4+/6+ com clique de abertura mitral.',
    ans: 'A',
    comment: 'Um aspecto traiçoeiro da TGA simples com septo íntegro é a ausência de sopros cardíacos audíveis nas primeiras horas de vida. O neonato apresenta cianose grave progressiva, mas a ausculta cardíaca pode soar enganosamente normal (ou com B2 única proeminente porque a aorta anteriorizada fecha mais perto da parede torácica), o que atrasa o diagnóstico se o examinador depender de sopros.',
    expA: 'Correta. A ausência de sopros é comum na TGA com septo íntegro, reforçando a importância da oximetria de pulso e ecocardiograma precoce.',
    expB: 'Incorreta. Sopro holossistólico exuberante ocorreria se houvesse CIV ampla associada.',
    expC: 'Incorreta. Sopro em maquinária requer grande PCA com gradiente.',
    expD: 'Incorreta. Sopro diastólico aspirativo indica regurgitação aórtica, incomum no neonato com TGA nativa.',
  });
}
