import { q } from './helper.js';

export function loadSec6() {
  q({
    id: 'ped-cardio-100-058',
    subtopic: 'Doença de Kawasaki',
    inst: 'USP-SP',
    year: 2024,
    statement: 'Lactente de 2 anos é trazido ao pronto-atendimento com febre alta diária (39-40 °C) há 6 dias, refratária a antitérmicos comuns. Ao exame: hiperemia conjuntival bulbar bilateral não exsudativa que poupa o limbo, lábios intensamente eritematosos e com fissuras sangrantes, língua em framboesa, exantema polimorfo maculopapular em tronco e linfonodomegalia cervical unilateral de 2,0 cm no trígono anterior. Qual é o diagnóstico e qual é o exame complementar complementar mandatório para estratificação de risco imediata?',
    A: 'Doença de Kawasaki; Ecocardiograma transtorácico com avaliação de artérias coronárias.',
    B: 'Escarlatina estreptocócica; Cultura de orofaringe em ágar sangue.',
    C: 'Mononucleose infecciosa por vírus Epstein-Barr; Sorologia anti-VCA IgM.',
    D: 'Adenovirose aguda sistêmica; PCR viral em secreção nasofaríngea.',
    ans: 'A',
    comment: 'O paciente preenche todos os critérios diagnósticos clássicos da Doença de Kawasaki: febre persistente por ≥ 5 dias associada a 4 critérios cardinais (conjuntivite não purulenta com halo límbico poupado, alterações orais típicas, exantema polimorfo e adenomegalia cervical aguda unilateral > 1,5 cm). O ecocardiograma transtorácico é o exame de eleição para avaliar a presença de ectasia ou aneurismas nas artérias coronárias.',
    expA: 'Correta. Critérios clássicos completos de Doença de Kawasaki com indicação imediata de ecocardiograma.',
    expB: 'Incorreta. A escarlatina não cursa com conjuntivite bilateral e responde rapidamente à penicilina.',
    expC: 'Incorreta. Mononucleose cursa com esplenomegalia volumosa e linfadenopatia generalizada, não com acometimento coronariano.',
    expD: 'Incorreta. Adenovírus causa conjuntivite exsudativa folicular, e não conjuntivite seca que poupa o limbo.',
  });

  q({
    id: 'ped-cardio-100-059',
    subtopic: 'Doença de Kawasaki',
    inst: 'UNICAMP',
    year: 2024,
    statement: 'Qual é a complicação mais grave e temida da Doença de Kawasaki, responsável pela principal causa de morbimortalidade cardiovascular adquirida na infância em países desenvolvidos?',
    A: 'Aneurismas e ectasias de artérias coronárias com risco de trombose, infarto agudo do miocárdio e morte súbita.',
    B: 'Glomerulonefrite proliferativa difusa com insuficiência renal crônica dialítica.',
    C: 'Hipertensão arterial pulmonar primária irreversível por vasculite plexiforme.',
    D: 'Cirrose hepática biliar secundária a colangite esclerosante autoimune.',
    ans: 'A',
    comment: 'A Doença de Kawasaki é uma vasculite necrosante sistêmica de médios vasos com predileção pelas artérias coronárias. Sem o tratamento adequado na fase aguda, cerca de 20 a 25% dos pacientes não tratados desenvolvem aneurismas coronarianos, predispondo à trombose intraluminal, estenose coronária tardia, infarto agudo do miocárdio e ruptura de aneurismas gigantes.',
    expA: 'Correta. O acometimento coronariano com formação de aneurismas é a complicação mais grave da doença.',
    expB: 'Incorreta. Pode ocorrer piúria estéril transitória por uretrite, mas não glomerulonefrite crônica dialítica.',
    expC: 'Incorreta. A circulação pulmonar não desenvolve hipertensão arterial plexogênica típica.',
    expD: 'Incorreta. Pode haver hidropsia de vesícula biliar transitória, mas não cirrose biliar.',
  });

  q({
    id: 'ped-cardio-100-060',
    subtopic: 'Doença de Kawasaki',
    inst: 'ENARE',
    year: 2024,
    statement: 'Qual é o esquema terapêutico padrão-ouro de primeira linha preconizado para o tratamento da Doença de Kawasaki na fase aguda com objetivo de reduzir drasticamente o risco de aneurismas coronarianos?',
    A: 'Imunoglobulina Humana Intravenosa (IVIG) 2 g/kg em infusão única contínua associada a Ácido Acetilsalicílico (AAS).',
    B: 'Prednisona oral isolada em dose imunossupressora por 6 meses sem imunoglobulina.',
    C: 'Penicilina G Benzatina intramuscular em dose única associada a metotrexato semanal.',
    D: 'Ciclofosfamida em pulsoterapia intravenosa mensal associada a varfarina oral.',
    ans: 'A',
    comment: 'O tratamento padrão-ouro consiste na infusão de Imunoglobulina Humana Intravenosa (IVIG) na dose de 2 g/kg em infusão única (ao longo de 10 a 12 horas) associada ao Ácido Acetilsalicílico (AAS) em dose anti-inflamatória (30 a 50 mg/kg/dia) até 48 a 72 horas afebril, seguido de dose antiplaquetária (3 a 5 mg/kg/dia). Essa conduta reduz a incidência de aneurismas de 25% para menos de 4 a 5%.',
    expA: 'Correta. A associação de IVIG 2 g/kg em dose única com AAS é o padrão-ouro consagrado mundialmente.',
    expB: 'Incorreta. Corticosteroide isolado não substitui a IVIG e no passado foi associado a maior fragilidade aneurismática quando usado isoladamente.',
    expC: 'Incorreta. Penicilina é para infecção bacteriana/febre reumática; Kawasaki é vasculite autoimune.',
    expD: 'Incorreta. Ciclofosfamida é reservada para vasculites ANCA-associadas graves refratárias.',
  });

  q({
    id: 'ped-cardio-100-061',
    subtopic: 'Doença de Kawasaki',
    inst: 'UFRJ',
    year: 2023,
    statement: 'Em que período ideal de tempo, contado a partir do primeiro dia do surgimento da febre, deve ser iniciada a Imunoglobulina Humana Intravenosa para alcançar a máxima eficácia na prevenção de aneurismas de coronária na Doença de Kawasaki?',
    A: 'Até o 10º dia do início dos sintomas (idealmente entre o 5º e o 10º dia).',
    B: 'Exclusivamente nas primeiras 24 horas de febre.',
    C: 'Apenas após o 21º dia, quando surgem as alterações de descamação periungueal.',
    D: 'Entre o 30º e o 45º dia, durante a fase de convalescença da doença.',
    ans: 'A',
    comment: 'A janela de ouro para administração da IVIG situa-se nos primeiros 10 dias da doença (idealmente entre o 5º e o 10º dia), período de vasculite ativa em que a neutralização da cascata de citocinas endoteliais é mais eficaz. Após o 10º dia, a IVIG ainda está indicada se houver persistência de febre sem outra causa explicável ou evidência de aneurismas coronários com provas inflamatórias elevadas.',
    expA: 'Correta. Administrar a IVIG até o 10º dia de febre previne de maneira máxima o dano vascular coronariano.',
    expB: 'Incorreta. Antes do 5º dia raramente os critérios clínicos diagnósticos estão consolidados.',
    expC: 'Incorreta. Após a 3ª semana a fase aguda inflamatória cedeu e os danos parietais já se estabeleceram.',
    expD: 'Incorreta. Na fase de convalescença não há mais indicação de infusão de IVIG rotineira.',
  });

  q({
    id: 'ped-cardio-100-062',
    subtopic: 'Doença de Kawasaki',
    inst: 'FMRP-USP',
    year: 2024,
    statement: 'Menino de 11 meses de vida com diagnóstico de Doença de Kawasaki recebeu infusão de IVIG (2 g/kg) e AAS no 7º dia de doença. Decorridas 40 horas do término da infusão da IVIG, o paciente volta a apresentar febre de 38,8 °C com irritabilidade e PCR persistentemente elevado. Qual é a conduta preconizada para este quadro de Doença de Kawasaki Resistente (refratária)?',
    A: 'Administrar uma segunda dose de Imunoglobulina Intravenosa (2 g/kg) ou pulsoterapia com metilprednisolona intravenosa.',
    B: 'Suspender todo o tratamento medicamentoso e manter observação expectante domiciliar.',
    C: 'Iniciar antibioticoterapia tripla de amplo espectro com vancomicina, meropenem e amicacina.',
    D: 'Realizar esternotomia de urgência para revascularização miocárdica cirúrgica com artéria torácica interna.',
    ans: 'A',
    comment: 'Define-se Doença de Kawasaki resistente (ou refratária) como a persistência ou recorrência da febre pelo menos 36 horas após o término da infusão da dose inicial de IVIG (ocorre em 10-20% dos pacientes). A conduta recomendada pelas diretrizes internacionais (AHA e SBP) é a administração de uma segunda infusão de IVIG (2 g/kg) ou pulsoterapia com corticosteroides (metilprednisolona 30 mg/kg/dia por 3 dias), podendo-se considerar antagonistas de TNF-alfa (infliximabe).',
    expA: 'Correta. A segunda dose de IVIG (2 g/kg) ou pulsoterapia com corticoide é a conduta para casos refratários.',
    expB: 'Incorreta. A conduta expectante eleva muito o risco de aneurismas gigantes de coronária.',
    expC: 'Incorreta. Não se trata de infecção bacteriana secundária, mas sim de vasculite persistente mediada por citocinas.',
    expD: 'Incorreta. Cirurgia de revascularização é restrita a infarto miocárdico estabelecido crônico por estenose obstrutiva.',
  });

  q({
    id: 'ped-cardio-100-063',
    subtopic: 'Doença de Kawasaki',
    inst: 'SCMSP',
    year: 2024,
    statement: 'Lactente de 5 meses apresenta febre persistente há 6 dias associada apenas a irritabilidade e eritema em área de fralda. Diante da suspeita de Doença de Kawasaki Incompleta (atípica), muito comum em menores de 6 meses de vida, quais alterações laboratoriais dão suporte ao diagnóstico?',
    A: 'PCR ≥ 3,0 mg/dL e/ou VHS ≥ 40 mm/h, associados a anemia para a idade, plaquetose > 450.000/mm³ após o 7º dia, hipoalbuminemia, elevação de ALT e piúria estéril.',
    B: 'Plaquetopenia grave < 20.000/mm³ associada a tempo de protrombina alargado e fibrinogênio indetectável.',
    C: 'Leucopenia intensa com linfocitose absoluta e redução drástica da ferritina sérica.',
    D: 'Hipercalcemia grave associada a hipofosfatemia e supressão total do paratormônio.',
    ans: 'A',
    comment: 'Lactentes menores de 6 meses têm alto risco de Kawasaki Incompleto (apresentam febre e menos de 4 critérios cardinais, com altíssimo risco de aneurismas coronários por atraso diagnóstico). Segundo o algoritmo da AHA, a presença de febre ≥ 5 dias com PCR ≥ 3 mg/dL ou VHS ≥ 40 mm/h associada a ≥ 3 achados laboratoriais adicionais (anemia, plaquetas > 450.000 após o 7º dia, albumina ≤ 3,0 g/dL, transaminases elevadas, leucócitos ≥ 15.000/mm³ ou piúria estéril ≥ 10 leucócitos/campo) autoriza o tratamento imediato com IVIG e AAS.',
    expA: 'Correta. Conjunto de alterações laboratoriais preconizado pelo algoritmo de Kawasaki incompleto da AHA.',
    expB: 'Incorreta. Plaquetose (aumento de plaquetas) é a regra na fase subaguda, não CIVD com plaquetopenia.',
    expC: 'Incorreta. Ocorre leucocitose com desvio à esquerda e ferritina elevada por processo inflamatório sistêmico.',
    expD: 'Incorreta. Distúrbios de cálcio não integram os critérios laboratoriais do algoritmo.',
  });

  q({
    id: 'ped-cardio-100-064',
    subtopic: 'Doença de Kawasaki',
    inst: 'UERJ',
    year: 2023,
    statement: 'Qual é a manifestação cutânea característica da fase subaguda da Doença de Kawasaki, que tipicamente surge entre a 2ª e a 3ª semana de doença, coincidindo com a resolução da febre e pico de plaquetose?',
    A: 'Descamação periungueal laminar nos dedos das mãos e dos pés, com progressão para palmas e plantas.',
    B: 'Erupção máculo-papular purpúrica palpável exclusiva em nádegas e membros inferiores.',
    C: 'Vesículas e bolhas flácidas com sinal de Nikolsky positivo por clivagem intraepidérmica.',
    D: 'Alopecia areata cicatricial irreversível no couro cabeludo occipital.',
    ans: 'A',
    comment: 'Na fase subaguda da Doença de Kawasaki (10 a 25 dias do início), a febre cessa e surge a clássica descamação periungueal laminar em escamas ou em "dedo de luva", que se inicia na borda das unhas dos dedos das mãos e pés e pode estender-se para as palmas e plantas.',
    expA: 'Correta. A descamação periungueal laminar é o marco clínico característico da fase subaguda.',
    expB: 'Incorreta. Púrpura palpável em nádegas e MMII caracteriza a Vasculite por IgA (Púrpura de Henoch-Schönlein).',
    expC: 'Incorreta. Bolhas com Nikolsky positivo sugerem Síndrome da Pele Escaldada Estafilocócica ou NET.',
    expD: 'Incorreta. Alopecia cicatricial não faz parte da evolução da Doença de Kawasaki.',
  });

  q({
    id: 'ped-cardio-100-065',
    subtopic: 'Doença de Kawasaki',
    inst: 'SMS-SP',
    year: 2024,
    statement: 'Um lactente de 1 ano recebeu Imunoglobulina Humana Intravenosa (2 g/kg) para tratamento de Doença de Kawasaki. A mãe solicita orientações sobre o calendário vacinal do Programa Nacional de Imunizações (PNI). Qual é a recomendação correta quanto à administração das vacinas de vírus vivos atenuados (ex: Tríplice Viral e Varicela)?',
    A: 'Adiar a administração de vacinas de vírus vivos atenuados por um período de 11 meses após a infusão da IVIG em alta dose.',
    B: 'Aplicar as vacinas de vírus vivos normalmente no dia seguinte à alta hospitalar.',
    C: 'Contraindicar permanentemente qualquer tipo de vacina de vírus vivos atenuados por toda a vida.',
    D: 'Aguardar apenas 14 dias para aplicação de qualquer vacina do calendário oficial.',
    ans: 'A',
    comment: 'A Imunoglobulina Humana Intravenosa em altas doses contém grande quantidade de anticorpos circulantes adquiridos de milhares de doadores. Esses anticorpos específicos neutralizam os vírus vacinais atenuados (como os do sarampo, caxumba, rubéola e varicela), impedindo a replicação viral necessária para gerar imunidade ativa protetora. Por isso, as diretrizes orientam postergar essas vacinas por 11 meses.',
    expA: 'Correta. O intervalo de 11 meses é obrigatório após a dose de 2 g/kg de IVIG para garantir eficácia sorológica vacinal.',
    expB: 'Incorreta. Os anticorpos passivos neutralizariam a vacina, resultando em ausência de proteção imunológica.',
    expC: 'Incorreta. A contraindicação é temporária (11 meses), não permanente por toda a vida.',
    expD: 'Incorreta. 14 dias é intervalo insuficiente; a meia-vida dos anticorpos transfundidos dura muitos meses.',
  });

  q({
    id: 'ped-cardio-100-066',
    subtopic: 'Doença de Kawasaki',
    inst: 'IAMSPE',
    year: 2024,
    statement: 'Ao ecocardiograma de controle realizado na 6ª semana de evolução de um pré-escolar com Doença de Kawasaki, identifica-se um aneurisma coronariano classificado como "aneurisma gigante" na artéria coronária descendente anterior. Segundo os critérios da AHA, qual diâmetro luminal interno ou Z-score define um aneurisma gigante?',
    A: 'Diâmetro interno luminal ≥ 8 mm ou escore Z (Z-score) ≥ 10.',
    B: 'Diâmetro interno entre 3 e 4 mm com Z-score entre 2 e 2,5.',
    C: 'Diâmetro de 1,5 mm com Z-score menor que 1,0.',
    D: 'Apenas aneurismas que acometem a bifurcação da carótida interna com espessura > 12 mm.',
    ans: 'A',
    comment: 'Pela classificação da American Heart Association (AHA), as lesões coronarianas na Doença de Kawasaki são estratificadas pelo Z-score (ajustado para a superfície corpórea): sem envolvimento (Z < 2), dilatação/ectasia isolada (Z 2 a < 2,5), aneurisma pequeno (Z 2,5 a < 5), aneurisma médio (Z 5 a < 10 e diâmetro < 8 mm) e aneurisma gigante (diâmetro luminal interno ≥ 8 mm ou Z-score ≥ 10).',
    expA: 'Correta. O aneurisma gigante é definido por diâmetro ≥ 8 mm ou Z-score ≥ 10.',
    expB: 'Incorreta. Representa dilatação leve/ectasia.',
    expC: 'Incorreta. Valores dentro da normalidade para a superfície corporal da infância.',
    expD: 'Incorreta. A classificação coronariana da Kawasaki não utiliza medições de artéria carótida.',
  });

  q({
    id: 'ped-cardio-100-067',
    subtopic: 'Doença de Kawasaki',
    inst: 'PUC-Campinas',
    year: 2024,
    statement: 'Qual é o esquema antitrombótico de manutenção preconizado para uma criança com Doença de Kawasaki que evoluiu com aneurisma coronariano gigante persistente (≥ 8 mm ou Z ≥ 10) para prevenção secundária de oclusão trombótica?',
    A: 'Terapia combinada de antiagregação plaquetária (AAS em dose baixa) associada à anticoagulação oral plena com Varfarina (alvo de INR 2,0-3,0) ou Heparina de Baixo Peso Molecular.',
    B: 'Monoterapia exclusiva com paracetamol em gotas sob demanda.',
    C: 'Aspirina em dose anti-inflamatória plena contínua (100 mg/kg/dia) sem anticoagulantes pelo risco de sangramento.',
    D: 'Suspensão de qualquer medicamento após 8 semanas do início dos sintomas.',
    ans: 'A',
    comment: 'Em aneurismas coronários gigantes (≥ 8 mm), a lentificação do fluxo sanguíneo intraluminal, a lesão endotelial e o turbilhonamento criam altíssimo risco de trombose oclusiva aguda e infarto maciço. As diretrizes recomendam a associação de anticoagulação sistêmica (varfarina com RNI alvo entre 2,0 e 3,0 ou heparina de baixo peso molecular com anti-Xa 0,5 a 1,0 U/mL) com um antiagregante plaquetário em dose baixa (AAS 3 a 5 mg/kg/dia).',
    expA: 'Correta. Anticoagulação plena associada a antiagregante é o esquema padrão para aneurismas gigantes.',
    expB: 'Incorreta. Paracetamol não possui atividade antiagregante nem anticoagulante.',
    expC: 'Incorreta. AAS em alta dose por tempo prolongado causa toxicidade gástrica/renal e não oferece anticoagulação eficaz.',
    expD: 'Incorreta. Aneurismas gigantes requerem terapia antitrombótica crônica mantida indefinidamente.',
  });

  q({
    id: 'ped-cardio-100-068',
    subtopic: 'Doença de Kawasaki',
    inst: 'FAMERP',
    year: 2023,
    statement: 'Qual das seguintes manifestações clínicas permite diferenciar confiavelmente a Doença de Kawasaki da Escarlatina clássica no atendimento pediátrico?',
    A: 'A presença de hiperemia conjuntival bilateral não purulenta que poupa a região periquerática (halo límbico), característica da Kawasaki e ausente na escarlatina.',
    B: 'A presença de febre alta, que é exclusiva da Doença de Kawasaki.',
    C: 'A presença de exantema no tronco, que ocorre apenas na escarlatina estreptocócica.',
    D: 'O achado de língua em framboesa, exclusivo de infecções fúngicas orais.',
    ans: 'A',
    comment: 'A conjuntivite bulbar bilateral não exsudativa com preservação do limbo esclero-corneano é um sinal cardeal da Doença de Kawasaki (presente em > 90% dos casos) e não faz parte do quadro clínico da escarlatina. A escarlatina apresenta faringite exsudativa, palidez perioral (sinal de Filatow) e reforço nas dobras (linhas de Pastia), além de responder em 24-48 horas à antibioticoterapia com penicilina.',
    expA: 'Correta. A conjuntivite bilateral seca poupando o limbo é altamente distintiva da Doença de Kawasaki.',
    expB: 'Incorreta. Ambas as condições cursam com febre alta.',
    expC: 'Incorreta. Ambas apresentam exantema eritematoso difuso.',
    expD: 'Incorreta. A língua em framboesa pode estar presente tanto na Doença de Kawasaki quanto na escarlatina.',
  });
}
