import { q } from './helper.js';

export function loadSec7() {
  q({
    id: 'ped-cardio-100-069',
    subtopic: 'Febre Reumática',
    inst: 'USP-SP',
    year: 2024,
    statement: 'Qual é o agente bacteriano causador da infecção primária que desencadeia a Febre Reumática aguda através de mimetismo molecular e qual sítio anatômico de infecção inicial tem capacidade exclusiva de deflagrá-la?',
    A: 'Streptococcus pyogenes (Streptococcus beta-hemolítico do grupo A de Lancefield); exclusivamente após faringoamigdalite aguda.',
    B: 'Streptococcus agalactiae (grupo B); exclusivamente após infecção urinária neonatal.',
    C: 'Staphylococcus aureus; após piodermite cutânea extensa ou impetigo bolhoso.',
    D: 'Streptococcus pneumoniae; após pneumonia lobar consolidativa com derrame pleural.',
    ans: 'A',
    comment: 'A Febre Reumática aguda é uma sequela tardia autoimune decorrente de mimetismo molecular (anticorpos contra a proteína M da parede celular estreptocócica sofrem reação cruzada com antígenos miocárdicos, valvares, sinoviais e dos núcleos da base). Ela ocorre EXCLUSIVAMENTE após infecção estreptocócica de vias aéreas superiores (faringoamigdalite purulenta por Streptococcus pyogenes). Infecções cutâneas estreptocócicas (impetigo/piodermite) podem deflagrar Glomerulonefrite Difusa Aguda (GNPE), mas NUNCA Febre Reumática.',
    expA: 'Correta. O S. pyogenes causando faringoamigdalite é o único agente e sítio que desencadeia a febre reumática.',
    expB: 'Incorreta. O grupo B causa sepse e meningite neonatal, não febre reumática.',
    expC: 'Incorreta. Estafilococos não causam febre reumática e infecções de pele não a deflagram.',
    expD: 'Incorreta. O pneumococo causa pneumonia e otite, sem relação causal com febre reumática.',
  });

  q({
    id: 'ped-cardio-100-070',
    subtopic: 'Febre Reumática',
    inst: 'UNICAMP',
    year: 2024,
    statement: 'Segundo a revisão de 2015 dos Critérios de Jones adotada pela American Heart Association e Sociedade Brasileira de Pediatria, quais são os critérios maiores estabelecidos para populações de risco moderado a alto (como o Brasil)?',
    A: 'Cardite (clínica ou subclínica pelo ecocardiograma), Artrite (monoartrite, poliartrite ou poliartralgia), Coreia de Sydenham, Eritema Marginado e Nódulos Subcutâneos.',
    B: 'Febre alta persistente, Plaquetose > 1.000.000/mm³, Conjuntivite purulenta e Esplenomegalia.',
    C: 'Insuficiência renal oligoanúrica, Hipocalcemia, Edema bipalpebral e Hematuria dismórfica.',
    D: 'Poliartrite simétrica deformante crônica de pequenas articulações com fator reumatoide positivo.',
    ans: 'A',
    comment: 'A revisão dos critérios de Jones (2015) estratificou as populações pelo risco endêmico. Em populações de moderado a alto risco (como no Brasil), o critério articular maior foi ampliado: aceita-se monoartrite, poliartrite ou mesmo poliartralgia como critério maior! Os cinco critérios maiores clássicos permanecem: Cardite (incluindo cardite subclínica ao eco), Artrite, Coreia de Sydenham, Eritema Marginado e Nódulos Subcutâneos.',
    expA: 'Correta. Enumera os critérios maiores adaptados para populações de alto risco epidemiológico.',
    expB: 'Incorreta. Critérios que lembram vasculites/Kawasaki ou sepse, não Jones.',
    expC: 'Incorreta. Quadro clássico de síndrome nefrítica pós-estreptocócica (GNPE).',
    expD: 'Incorreta. Caracteriza a Artrite Reumatoide Juvenil / Idiopática, e não a febre reumática que tem artrite migratória não deformante.',
  });

  q({
    id: 'ped-cardio-100-071',
    subtopic: 'Febre Reumática',
    inst: 'ENARE',
    year: 2024,
    statement: 'Em qual das seguintes manifestações clínicas da Febre Reumática NÃO é obrigatória a comprovação laboratorial de infecção estreptocócica prévia (cultura positiva, teste antigênico ou elevação de ASLO) para confirmar o diagnóstico da doença?',
    A: 'Coreia de Sydenham isolada ou Cardite reumática insidiosa de início arrastado.',
    B: 'Poliartrite migratória típica com febre alta.',
    C: 'Eritema marginado com intervalo PR alargado no ECG.',
    D: 'Nódulos subcutâneos associados a PCR e VHS elevados.',
    ans: 'A',
    comment: 'Como a Coreia de Sydenham e a Cardite insidiosa de evolução arrastada surgem tardiamente (frequentemente 2 a 6 meses após a faringite primária), os títulos de anticorpos estreptocócicos (como a ASLO) e as provas de atividade inflamatória podem já ter se normalizado completamente. Por essa razão, os Critérios de Jones estabelecem que a Coreia de Sydenham (após exclusão de outras causas como lúpus) e a Cardite insidiosa autorizam o diagnóstico de febre reumática SEM a necessidade de documentação de infecção estreptocócica prévia.',
    expA: 'Correta. A Coreia de Sydenham e a Cardite insidiosa dispensam a comprovação laboratorial de ASLO elevada.',
    expB: 'Incorreta. Quadros com artrite ocorrem precocemente (2-3 semanas) e exigem comprovação de ASLO/cultura.',
    expC: 'Incorreta. Eritema marginado requer evidência laboratorial de estreptococo.',
    expD: 'Incorreta. Nódulos subcutâneos ocorrem em surtos agudos associados a cardite, necessitando de confirmação estreptocócica.',
  });

  q({
    id: 'ped-cardio-100-072',
    subtopic: 'Febre Reumática',
    inst: 'FMRP-USP',
    year: 2024,
    statement: 'Qual é a valvopatia aguda mais frequentemente identificada na cardite reumática e qual achado auscultatório clássico pode acompanhar o sopro sistólico apical quando há regurgitação volumosa na fase ativa?',
    A: 'Insuficiência (regurgitação) mitral; acompanhada pelo sopro mesodiastólico apical de Carey Coombs.',
    B: 'Estenose mitral pura com abertura em estalido e ruflar diastólico persistente.',
    C: 'Estenose aórtica calcificada congênita com frêmito em fúrcula esternal.',
    D: 'Insuficiência pulmonar isolada associada ao sopro contínuo de Gibson.',
    ans: 'A',
    comment: 'Na cardite reumática aguda (fase inflamatória ativa), a lesão valvar mais comum é a Insuficiência Mitral (sopro holossistólico regurgitativo de alta frequência no ápice que irradia para a axila). Em casos de refluxo mitral volumoso, o grande volume de sangue que regurgita para o AE retorna através da valva mitral na diástole seguinte gerando um hiperfluxo relativo, audível como um sopro mesodiastólico suave no ápice, denominado sopro de Carey Coombs.',
    expA: 'Correta. A insuficiência mitral e o sopro de Carey Coombs são as marcas semiológicas da cardite aguda.',
    expB: 'Incorreta. A estenose mitral é uma lesão cicatricial crônica que leva anos a décadas para se desenvolver.',
    expC: 'Incorreta. Estenose aórtica calcificada é doença degenerativa ou congênita bicúspide.',
    expD: 'Incorreta. Insuficiência pulmonar não é a lesão primária e sopro de Gibson é da PCA.',
  });

  q({
    id: 'ped-cardio-100-073',
    subtopic: 'Febre Reumática',
    inst: 'UFRJ',
    year: 2023,
    statement: 'Menina de 10 anos é levada ao neurologista por alterações comportamentais, choro imotivado, fraqueza muscular, piora do rendimento escolar e movimentos rápidos, involuntários, involuntários e incoordenados em mãos e face, que cessam durante o sono. Ao exame: hipotonia generalizada, preensão manual intermitente (sinal da ordenha) e reflexos pendulares. Qual é a hipótese diagnóstica e qual é a conduta farmacológica sintomática?',
    A: 'Coreia de Sydenham (manifestação neurológica da Febre Reumática); Haloperidol ou Ácido Valproico associados a repouso e profilaxia com Penicilina Benzatina.',
    B: 'Síndrome de Tourette; Estimulantes adrenérgicos do SNC (metilfenidato).',
    C: 'Doença de Huntington infantil; Terapia gênica com oligonucleotídeos antisense.',
    D: 'Epilepsia mioclônica juvenil; Lamotrigina isolada sem antibióticos.',
    ans: 'A',
    comment: 'A Coreia de Sydenham ("dança de São Vito") é a manifestação neurológica exclusiva da Febre Reumática, decorrente de vasculite autoimune nos núcleos da base (núcleo caudado e putâmen). Caracteriza-se por movimentos coreiformes involuntários que desaparecem no sono, fraqueza muscular e labilidade emocional. Tem curso autolimitado (2 a 6 meses) e cura SEM sequelas neurológicas. O tratamento sintomático das crises incapacitantes é feito com bloqueadores dopaminérgicos (haloperidol) ou anticonvulsivantes (ácido valproico, carbamazepina), sendo imperativo iniciar profilaxia com Penicilina Benzatina.',
    expA: 'Correta. Reconhece os sinais semiológicos da Coreia de Sydenham, o tratamento sintomático e a profilaxia secundária.',
    expB: 'Incorreta. Tourette cursa com tiques motores e vocais estereotipados crônicos, e estimulantes pioram os tiques.',
    expC: 'Incorreta. Huntington tem padrão autossômico dominante progressivo e demência.',
    expD: 'Incorreta. A coreia não tem correlação com crises eletroencefalográficas de epilepsia mioclônica.',
  });

  q({
    id: 'ped-cardio-100-074',
    subtopic: 'Febre Reumática',
    inst: 'SCMSP',
    year: 2024,
    statement: 'Qual é o tratamento anti-inflamatório de primeira escolha para a artrite pura (sem cardite moderada a grave associada) na fase aguda da Febre Reumática?',
    A: 'Ácido Acetilsalicílico (AAS) em dose anti-inflamatória alta (80 a 100 mg/kg/dia dividida em 4 doses).',
    B: 'Prednisona em altas doses (2 mg/kg/dia) associada a metilprednisolona venosa.',
    C: 'Infliximabe intravenoso associado a metotrexato subcutâneo semanal.',
    D: 'Paracetamol oral em baixas doses como monoterapia analgésica.',
    ans: 'A',
    comment: 'A artrite da febre reumática tem uma resposta extremamente rápida, dramática e quase patognomônica ao Ácido Acetilsalicílico (AAS) em dose de 80 a 100 mg/kg/dia (máx 4-6 g/dia): a dor, febre e sinais inflamatórios articulares costumam regredir por completo em 24 a 48 horas. Se o paciente persistir com queixas articulares após 72 horas de AAS em dose plena, o diagnóstico de febre reumática deve ser fortemente questionado. Corticosteroides são reservados para os casos com cardite moderada a grave.',
    expA: 'Correta. O AAS em dose de 80-100 mg/kg/dia é o tratamento de eleição na artrite isolada.',
    expB: 'Incorreta. Corticosteroides são reservados para cardite com insuficiência cardíaca ou cardiomegalia.',
    expC: 'Incorreta. Biológicos anti-TNF são para artrite idiopática juvenil, não para o surto agudo de febre reumática.',
    expD: 'Incorreta. Paracetamol tem fraca ação anti-inflamatória periférica.',
  });

  q({
    id: 'ped-cardio-100-075',
    subtopic: 'Febre Reumática',
    inst: 'UERJ',
    year: 2023,
    statement: 'Escolar de 8 anos apresenta cardite reumática com sopro holossistólico mitral moderado, cardiomegalia leve no RX de tórax e sinais incipientes de insuficiência cardíaca com dispneia aos esforços. Qual fármaco anti-inflamatório é o mais indicado para o controle da fase ativa da cardite?',
    A: 'Prednisona por via oral na dose de 1 a 2 mg/kg/dia por 2 a 4 semanas, seguida de desmame gradual.',
    B: 'AAS em dose baixa (3 mg/kg/dia) como antiagregante isolado.',
    C: 'Ibuprofeno em dose antipirética por 3 dias.',
    D: 'Colquicina associada a hidroxicloroquina oral.',
    ans: 'A',
    comment: 'Na cardite reumática moderada a grave (evidenciada por cardiomegalia, disfunção ventricular ou insuficiência cardíaca clínica), os corticosteroides são a droga de escolha (Prednisona 1 a 2 mg/kg/dia por 2 a 4 semanas, com posterior desmame gradual). Eles diminuem o edema inflamatório miocárdico e o risco de insuficiência cardíaca refratária.',
    expA: 'Correta. A corticoterapia com prednisona oral é o tratamento padrão na cardite com repercussão.',
    expB: 'Incorreta. Dose antiplaquetária não possui qualquer efeito anti-inflamatório sobre a cardite ativa.',
    expC: 'Incorreta. Ibuprofeno por 3 dias é subdose e tempo insuficiente para controlar a pancardite.',
    expD: 'Incorreta. Colquicina e cloroquina não fazem parte do arsenal terapêutico da cardite reumática aguda.',
  });

  q({
    id: 'ped-cardio-100-076',
    subtopic: 'Febre Reumática',
    inst: 'SMS-SP',
    year: 2024,
    statement: 'Qual é o antibiótico de escolha e o intervalo preconizado para a profilaxia secundária da Febre Reumática na prevenção de novos surtos bacterianos?',
    A: 'Penicilina G Benzatina por via intramuscular profunda aplicada a cada 21 dias.',
    B: 'Amoxicilina oral administrada 1 vez ao dia continuamente por 3 meses.',
    C: 'Ciprofloxacino oral a cada 12 horas por 1 ano.',
    D: 'Azitromicina intramuscular aplicada mensalmente.',
    ans: 'A',
    comment: 'A profilaxia secundária contínua é o pilar mais importante do tratamento da Febre Reumática para prevenir novas infecções pelo Streptococcus pyogenes e novos surtos com agravamento do dano valvar. A droga padrão-ouro é a Penicilina G Benzatina na dose de 600.000 UI (< 27 kg) ou 1.200.000 UI (≥ 27 kg) aplicada a cada 21 dias (intervalo de 21 dias é o recomendado no Brasil devido à perda de níveis séricos protetores na 4ª semana em áreas de alto risco).',
    expA: 'Correta. Penicilina Benzatina intramuscular a cada 21 dias é o esquema de profilaxia secundária no Brasil.',
    expB: 'Incorreta. A amoxicilina não é utilizada para profilaxia secundária contínua de longa duração.',
    expC: 'Incorreta. Quinolonas não são indicadas para profilaxia estreptocócica.',
    expD: 'Incorreta. Não existe formulação intramuscular de azitromicina para profilaxia mensal.',
  });

  q({
    id: 'ped-cardio-100-077',
    subtopic: 'Febre Reumática',
    inst: 'IAMSPE',
    year: 2024,
    statement: 'Jovem de 19 anos teve diagnóstico de Febre Reumática aos 12 anos cursando com artrite e coreia de Sydenham, SEM qualquer evidência de cardite clínica ou ecocardiográfica em todo o seguimento. Por quanto tempo a profilaxia secundária com Penicilina Benzatina deve ser mantida?',
    A: 'Até completar 21 anos de idade ou por 5 anos após o último surto (o que for mais longo).',
    B: 'Por apenas 6 meses após o término dos movimentos coreiformes.',
    C: 'Indefinidamente por toda a vida.',
    D: 'Até completar 40 anos de idade obrigatoriamente.',
    ans: 'A',
    comment: 'As diretrizes do Ministério da Saúde e SBP/AHA estabelecem os períodos de duração da profilaxia secundária com Penicilina Benzatina: 1) Febre reumática SEM cardite: até os 21 anos de idade ou por 5 anos após o último surto (o que durar mais tempo); 2) Febre reumática COM cardite prévia curada sem sequela valvar residual: até os 25 anos de idade ou por 10 anos após o último surto; 3) Febre reumática com sequela valvar crônica persistente ou prótese valvar: até os 40 anos de idade ou por toda a vida.',
    expA: 'Correta. Paciente sem cardite: profilaxia até os 21 anos ou 5 anos do último surto.',
    expB: 'Incorreta. 6 meses é tempo insuficiente; a taxa de recorrência após surto recente é altíssima.',
    expC: 'Incorreta. Profilaxia vitalícia é reservada para sequela valvar grave ou exposição ocupacional extrema.',
    expD: 'Incorreta. 40 anos é a meta para quem tem lesão valvar estrutural crônica.',
  });

  q({
    id: 'ped-cardio-100-078',
    subtopic: 'Febre Reumática',
    inst: 'PUC-PR',
    year: 2024,
    statement: 'Paciente de 24 anos com histórico de múltiplos surtos de Febre Reumática na infância apresenta sequela valvar crônica com insuficiência mitral moderada a grave e estenose mitral leve no ecocardiograma. Segundo as diretrizes vigentes, qual é a duração recomendada da profilaxia secundária com Penicilina Benzatina?',
    A: 'Até os 40 anos de idade ou por toda a vida (especialmente se houver alta exposição ao estreptococo).',
    B: 'Pode ser suspensa imediatamente pois o paciente já completou 21 anos.',
    C: 'Apenas até os 25 anos de idade.',
    D: 'Por mais 1 ano a contar do último exame ecocardiográfico.',
    ans: 'A',
    comment: 'Em pacientes que desenvolveram lesão valvar residual permanente (cardiopatia reumática crônica) ou que foram submetidos a cirurgia de troca valvar / plastia, a profilaxia secundária deve ser estendida até os 40 anos de idade ou mantida por toda a vida, particularmente em indivíduos com risco contínuo de contato com crianças em idade escolar ou profissionais de saúde.',
    expA: 'Correta. Em presença de sequela valvar crônica, o tempo de profilaxia se estende até os 40 anos ou por toda a vida.',
    expB: 'Incorreta. Suspender aos 21 anos em paciente com sequela valvar causará novo surto com destruição valvar fatal.',
    expC: 'Incorreta. Até 25 anos é a regra para cardite curada sem sequela residual.',
    expD: 'Incorreta. O tempo mínimo é muito mais longo.',
  });

  q({
    id: 'ped-cardio-100-079',
    subtopic: 'Febre Reumática',
    inst: 'FAMERP',
    year: 2023,
    statement: 'Qual das seguintes manifestações dermatológicas é considerada critério maior de Jones para o diagnóstico de Febre Reumática aguda, caracterizando-se por lesões maculares eritematosas, com bordas serpiginosas salientes e centro claro, não pruriginosas, de localização preferencial no tronco e membros proximais?',
    A: 'Eritema marginado de Leiner.',
    B: 'Eritema multiforme maior com lesões em alvo centrípetas.',
    C: 'Eritema nodoso em regiões pré-tibiais anteriores dolorosas.',
    D: 'Lúpus discoide com atrofia cicatricial e rolhões foliculares.',
    ans: 'A',
    comment: 'O Eritema Marginado de Leiner é uma lesão cutânea típica da febre reumática (critério maior). É uma erupção macular eritematosa evanescente, não pruriginosa, que se expande centrifugamente deixando bordas avermelhadas serpiginosas com clareamento central. Localiza-se predominantemente no tronco e raiz de membros (poupa a face) e tem forte associação com a presença de cardite.',
    expA: 'Correta. O eritema marginado é o critério maior dermatológico clássico da Febre Reumática.',
    expB: 'Incorreta. Eritema multiforme cursa com lesões em alvo típicas e acometimento mucoso.',
    expC: 'Incorreta. O eritema nodoso apresenta nódulos dolorosos em membros inferiores (comum em sarcoidose, tuberculose, DII).',
    expD: 'Incorreta. Lúpus discoide é manifestação cutânea do LED.',
  });

  q({
    id: 'ped-cardio-100-080',
    subtopic: 'Febre Reumática',
    inst: 'SMS-SP',
    year: 2024,
    statement: 'Para um paciente com diagnóstico confirmado de Febre Reumática aguda com histórico comprovado e inequívoco de reação anafilática prévia à Penicilina (choque anafilático e broncoespasmo), qual é o esquema alternativo de escolha para a profilaxia secundária contínua?',
    A: 'Sulfadiazina por via oral (500 mg/dia para peso ≤ 27 kg ou 1.000 mg/dia para > 27 kg) ou Eritromicina oral.',
    B: 'Cefalotina intravenosa a cada 21 dias.',
    C: 'Amoxicilina associada a clavulanato semanal.',
    D: 'Nenhum medicamento, orientando apenas evitar aglomerações urbanas.',
    ans: 'A',
    comment: 'Para pacientes com alergia comprovada e grave à penicilina (reação anafilática mediada por IgE), a Sulfadiazina oral diária é a primeira escolha para profilaxia secundária (500 mg/dia para ≤ 27 kg e 1 g/dia para > 27 kg). Caso o paciente também seja alérgico a sulfas ou apresente intolerância gástrica, a alternativa é a Eritromicina oral (250 mg 2 vezes ao dia). Cefalosporinas são contraindicadas se houve anafilaxia a penicilinas devido ao risco de reatividade cruzada.',
    expA: 'Correta. A sulfadiazina oral diária (ou eritromicina) é a opção de eleição no paciente com anafilaxia à penicilina.',
    expB: 'Incorreta. Cefalosporinas têm risco de reação cruzada anafilática em indivíduos com hipersensibilidade IgE à penicilina.',
    expC: 'Incorreta. Amoxicilina é uma aminopenicilina, contraindicada pelo risco de anafilaxia.',
    expD: 'Incorreta. Não prescrever profilaxia condena o cardiopata a novos surtos e morte por falência valvar.',
  });
}
