import { q } from './helper.js';

export function loadSec8() {
  q({
    id: 'ped-cardio-100-081',
    subtopic: 'Taquicardia Supraventricular (TSV)',
    inst: 'USP-SP',
    year: 2024,
    statement: 'Lactente de 2 meses de vida é trazido à emergência por recusa alimentar, palidez e irritabilidade há 12 horas. Ao exame: reativo, afebril, FR de 60 irpm, tempo de enchimento capilar de 2 segundos, pulsos palpáveis e PA normal para a idade. O monitor cardíaco exibe ritmo taquicárdico estritamente regular com frequência cardíaca mantida e invariável em 250 bpm. O ECG revela QRS estreito (< 0,08 s) sem ondas P sinusais visíveis. Diante da estabilidade hemodinâmica, qual é a primeira conduta terapêutica recomendada?',
    A: 'Aplicação de manobra vagal com bolsa de gelo sobre a face (reflexo do mergulho) por 10 a 15 segundos.',
    B: 'Cardioversão elétrica sincronizada com 2 J/kg sob sedação profunda.',
    C: 'Massagem compressiva bilateral dos globos oculares.',
    D: 'Infusão venosa lenta de verapamil na dose de 0,5 mg/kg.',
    ans: 'A',
    comment: 'No paciente pediátrico com Taquicardia Supraventricular (TSV) hemodinamicamente estável, o primeiro passo é a realização de manobras vagais. Em lactentes e crianças pequenas, a técnica mais eficaz e segura é a aplicação de uma bolsa com água e gelo sobre a fronte e ponte nasal por 10 a 15 segundos (reflexo do mergulho ou "diving reflex"), sem ocluir a boca ou as narinas. A massagem ocular e carotídea são proscritas em crianças pelo risco de descolamento de retina e asfixia.',
    expA: 'Correta. A aplicação de gelo na face é a manobra vagal de escolha e segura em lactentes estáveis.',
    expB: 'Incorreta. Cardioversão elétrica é reservada para pacientes instáveis (com sinais de choque, má perfusão ou hipotensão).',
    expC: 'Incorreta. A compressão ocular é perigosa e formalmente contraindicada em pediatria.',
    expD: 'Incorreta. O verapamil é formalmente contraindicado em menores de 1 ano pelo risco de colapso cardiovascular fatal.',
  });

  q({
    id: 'ped-cardio-100-082',
    subtopic: 'Taquicardia Supraventricular (TSV)',
    inst: 'UNICAMP',
    year: 2024,
    statement: 'Como diferenciar clínica e eletrocardiograficamente uma Taquicardia Sinusal de uma Taquicardia Supraventricular (TSV) paroxística em um lactente de 3 meses febril e desidratado?',
    A: 'A taquicardia sinusal raramente ultrapassa 220 bpm no lactente, varia sua frequência com o choro/repouso e exibe onda P sinusal precedente normal; a TSV apresenta FC fixa e invariável (geralmente > 220 bpm), início/término súbitos e ondas P ausentes ou anômalas.',
    B: 'A taquicardia sinusal apresenta QRS alargado acima de 0,16 segundos, enquanto a TSV sempre tem QRS com onda delta.',
    C: 'A taquicardia sinusal não se altera com a infusão de volume venoso, ao passo que a TSV reverte espontaneamente com soro oral.',
    D: 'A presença de febre exclui totalmente o diagnóstico de Taquicardia Supraventricular.',
    ans: 'A',
    comment: 'A diferenciação é essencial: a Taquicardia Sinusal é uma resposta fisiológica a gatilhos (febre, dor, hipovolemia, anemia); sua FC costuma ser < 220 bpm no lactente (< 180 na criança maior), varia a cada minuto dependendo do estresse/choro e possui onda P sinusal idêntica antes de cada QRS. Já a TSV paroxística é uma arritmia por reentrada: sua FC é fixa, extremamente rápida (> 220 bpm no lactente), sem qualquer variabilidade fisiológica respiratória ou comportamental, e as ondas P estão ocultas no QRS ou são retrógradas.',
    expA: 'Correta. Detalha os critérios de frequência, variabilidade e morfologia de onda P que distinguem as duas entidades.',
    expB: 'Incorreta. Ambas são arritmias com QRS estreito em condições habituais de condução.',
    expC: 'Incorreta. A taquicardia sinusal desacelera com a reposição volêmica; a TSV decorre de circuito elétrico e independe de hidratação.',
    expD: 'Incorreta. Crianças com TSV podem ter febre concomitante ou desencadeada por viroses.',
  });

  q({
    id: 'ped-cardio-100-083',
    subtopic: 'Taquicardia Supraventricular (TSV)',
    inst: 'ENARE',
    year: 2024,
    statement: 'Lactente com TSV sustentada de 240 bpm permaneceu em taquiarritmia após manobra vagal correta com gelo na face. O paciente permanece hemodinamicamente estável e já possui acesso venoso calibroso em fossa antecubital. Qual é o fármaco de escolha e a técnica de administração recomendada?',
    A: 'Adenosina na dose inicial de 0,1 mg/kg em bólus intravenoso ultrarrápido seguido imediatamente de flush de soro fisiológico em torneirinha de 3 vias.',
    B: 'Digoxina intravenosa em infusão lenta contínua por 48 horas.',
    C: 'Amiodarona em bólus rápido intravenoso sem diluição.',
    D: 'Atropina intravenosa associada a adrenalina diluída.',
    ans: 'A',
    comment: 'A Adenosina é a droga de primeira escolha na TSV por reentrada estável. A dose inicial é de 0,1 mg/kg (máximo de 6 mg na 1ª dose). Como sua meia-vida é ultracurta (< 10 segundos), ela deve ser administrada em bólus IV rápido em veia calibrosa o mais próximo possível do coração, utilizando a técnica de duas seringas com torneirinha de 3 vias (three-way stopcock): injeta-se a adenosina rapidamente e, no mesmo segundo, faz-se o flush vigoroso com 5 a 10 mL de soro fisiológico, elevando-se o membro do paciente.',
    expA: 'Correta. Descreve a droga de escolha (adenosina), a dose pediátrica inicial (0,1 mg/kg) e a técnica do flush rápido com torneirinha.',
    expB: 'Incorreta. A digoxina tem ação lenta e não é utilizada na reversão aguda emergencial da TSV.',
    expC: 'Incorreta. A amiodarona em bólus rápido causa colapso cardiovascular grave e hipotensão severa.',
    expD: 'Incorreta. Atropina e adrenalina são cronotrópicas positivas e agravariam drasticamente a taquicardia.',
  });

  q({
    id: 'ped-cardio-100-084',
    subtopic: 'Taquicardia Supraventricular (TSV)',
    inst: 'FMRP-USP',
    year: 2024,
    statement: 'Criança de 1 ano com TSV sustentada há mais de 36 horas evolui para a sala de emergência com palidez cutânea acinzentada, sonolência, pulsos periféricos filiformes, tempo de enchimento capilar de 5 segundos e pressão arterial inaudível. Diante do quadro de INSTABILIDADE HEMODINÂMICA grave (choque descompensado), qual é a conduta prioritária imediata?',
    A: 'Cardioversão elétrica sincronizada imediata com carga de 0,5 a 1 J/kg (aumentando para 2 J/kg se refratária).',
    B: 'Manobras vagais repetidas por 15 minutos até haver melhora da perfusão.',
    C: 'Tentativa seriada de até 3 doses de adenosina antes de qualquer choque elétrico.',
    D: 'Infusão venosa de 20 mL/kg de solução glicosada a 5% sem monitorização.',
    ans: 'A',
    comment: 'Na presença de sinais de instabilidade hemodinâmica (hipotensão arterial, alteração do nível de consciência, choque cardiogênico ou má perfusão periférica grave), não se deve retardar o tratamento com manobras vagais ou esperar preparo de medicações: a conduta mandatória imediata pelas diretrizes do PALS (Pediatric Advanced Life Support) é a Cardioversão Elétrica Sincronizada com carga inicial de 0,5 a 1 J/kg, podendo ser aumentada para 2 J/kg se não houver reversão.',
    expA: 'Correta. A cardioversão elétrica sincronizada imediata é a prioridade absoluta no paciente com TSV e choque/instabilidade.',
    expB: 'Incorreta. Manobras vagais são contraindicadas como conduta isolada no choque com hipotensão pelo risco de parada cardiorrespiratória.',
    expC: 'Incorreta. No paciente instável com choque descompensado, não se perde tempo aguardando doses seriadas de fármacos se o desfibrilador estiver pronto.',
    expD: 'Incorreta. Não corrige o mecanismo da arritmia e pode gerar hiponatremia e edema cerebral.',
  });

  q({
    id: 'ped-cardio-100-085',
    subtopic: 'Taquicardia Supraventricular (TSV)',
    inst: 'UERJ',
    year: 2023,
    statement: 'Qual fármaco antiarrítmico é expressamente contraindicado para o tratamento de Taquicardia Supraventricular em lactentes menores de 1 ano de idade devido ao elevado risco de precipitar colapso hemodinâmico irreversível, hipotensão refratária e parada cardiorrespiratória em atividade elétrica sem pulso?',
    A: 'Verapamil intravenoso.',
    B: 'Adenosina intravenosa.',
    C: 'Amiodarona oral em dose ajustada.',
    D: 'Propranolol oral em manutenção.',
    ans: 'A',
    comment: 'O Verapamil (bloqueador dos canais de cálcio não-di-hidropiridínico) é estritamente contraindicado por via intravenosa em crianças com menos de 1 ano de idade. O miocárdio do lactente é altamente dependente do influxo de cálcio transsarcolêmico para manter o tônus inotrópico e a contratilidade basal (pois o retículo sarcoplasmático ainda é imaturo). A administração de verapamil IV bloqueia a entrada de cálcio, desencadeando choque cardiogênico fatal e assistolia refratária a ressuscitação.',
    expA: 'Correta. O verapamil IV é contraindicado em < 1 ano pelo risco documentado de colapso cardiovascular e óbito.',
    expB: 'Incorreta. A adenosina é o fármaco de escolha e seguro em lactentes.',
    expC: 'Incorreta. Amiodarona pode ser utilizada em situações de refratariedade com cuidados de infusão.',
    expD: 'Incorreta. O propranolol é amplamente utilizado na profilaxia crônica de manutenção.',
  });

  q({
    id: 'ped-cardio-100-086',
    subtopic: 'Taquicardia Supraventricular (TSV)',
    inst: 'SCMSP',
    year: 2024,
    statement: 'Após a reversão da TSV para ritmo sinusal em um menino de 7 anos, o eletrocardiograma de 12 derivações basal revela: intervalo PR curto (< 0,10 s), onda de pré-excitação com empastamento inicial no início do complexo QRS (onda delta) e complexo QRS com duração alargada. Qual é o diagnóstico correspondente a esse padrão eletrocardiográfico?',
    A: 'Síndrome de Wolff-Parkinson-White (WPW).',
    B: 'Bloqueio de ramo esquerdo completo congênito isolado.',
    C: 'Síndrome de Brugada tipo 1.',
    D: 'Taquicardia nodal reentrante atípica crônica.',
    ans: 'A',
    comment: 'A tríade eletrocardiográfica clássica da Síndrome de Wolff-Parkinson-White (WPW) é: 1) Intervalo PR curto (< 0,12 s em adultos e crianças maiores, ou < 0,08-0,10 s em lactentes); 2) Onda delta (empastamento ascendente do início do QRS decorrente da despolarização precoce ventricular pela via acessória); 3) Alargamento da duração total do complexo QRS. Ela decorre da persistência de uma via anômala de condução direta entre átrios e ventrículos (feixe de Kent).',
    expA: 'Correta. A descrição reúne os três critérios cardinais patognomônicos do padrão eletrocardiográfico de Wolff-Parkinson-White.',
    expB: 'Incorreta. O BRE isolado não cursa com intervalo PR encurtado.',
    expC: 'Incorreta. Brugada cursa com supradesnivelamento côncavo de ST em "sela de cavaleiro" em V1-V2.',
    expD: 'Incorreta. Na TRNAV o ECG em ritmo sinusal é rigorosamente normal (não há via acessória extranodal visível).',
  });

  q({
    id: 'ped-cardio-100-087',
    subtopic: 'Taquicardia Supraventricular (TSV)',
    inst: 'SMS-SP',
    year: 2024,
    statement: 'Um adolescente de 14 anos com diagnóstico de Síndrome de Wolff-Parkinson-White procura a emergência com palpitações intensas e dispneia. O ECG revela uma taquiarritmia irregular com complexos QRS bizarros e de larguras variáveis, com frequências ventriculares que atingem 260 bpm, compatível com Fibrilação Atrial pré-excitada com condução anterógrada pela via acessória. Por que o uso de fármacos bloqueadores do nó atrioventricular (como verapamil, diltiazem ou digoxina) é estritamente PROIBIDO nessa situação?',
    A: 'Porque o bloqueio do nó AV desvia toda a condução dos múltiplos estímulos atriais desorganizados exclusivamente para a via acessória (feixe de Kent), precipitando taquicardia ventricular polimórfica ou fibrilação ventricular fatal.',
    B: 'Porque essas drogas provocam broncoespasmo grave mediado por histamina.',
    C: 'Porque aumentam o período refratário da via acessória, impedindo o retorno ao ritmo sinusal.',
    D: 'Porque degradam quimicamente as moléculas de heparina endógena aumentando o risco de AVC.',
    ans: 'A',
    comment: 'Na FA pré-excitada em pacientes com WPW, centenas de impulsos elétricos caóticos originados nos átrios chegam aos ventrículos tanto pelo nó AV quanto pela via acessória. O nó AV funciona como um "filtro fisiológico" que bloqueia a maioria dos impulsos. Se forem administradas drogas bloqueadoras do nó AV (verapamil, digoxina, adenosina ou diltiazem), o nó AV é desligado e todos os impulsos atriais de alta frequência trafegam livremente pela via acessória (que tem período refratário curto), levando à degeneração imediata em Fibrilação Ventricular e parada cardíaca.',
    expA: 'Correta. O bloqueio nodal favorece a condução anterógrada acelerada pela via acessória, podendo degenerar em fibrilação ventricular.',
    expB: 'Incorreta. O risco principal não é broncoespasmo, mas arritmia ventricular fatal.',
    expC: 'Incorreta. Elas não prolongam a refratariedade da via acessória, e sim bloqueiam o nó AV.',
    expD: 'Incorreta. Não há qualquer interação farmacológica com heparina.',
  });

  q({
    id: 'ped-cardio-100-088',
    subtopic: 'Taquicardia Supraventricular (TSV)',
    inst: 'IAMSPE',
    year: 2024,
    statement: 'Qual é o procedimento de escolha para a cura definitiva da Taquicardia Supraventricular por reentrada atrioventricular ou nodal em crianças e adolescentes sintomáticos refratários ou que praticam esportes competitivos?',
    A: 'Estudo eletrofisiológico intracardíaco com ablação por cateter da via anômala (por radiofrequência ou crioablação).',
    B: 'Denervação simpática renal bilateral por via arterial percutânea.',
    C: 'Implante de marcapasso definitivo dupla-câmara epicárdico.',
    D: 'Simpatectomia torácica endoscópica esquerda isolada.',
    ans: 'A',
    comment: 'A ablação por cateter (utilizando energia de radiofrequência ou crioablação) é o tratamento de escolha para a cura definitiva das taquicardias supraventriculares por reentrada (WPW ou reentrada nodal). Apresenta taxas de sucesso superiores a 95% e baixo índice de complicações. É recomendada em crianças com episódios frequentes refratários ao tratamento farmacológico, naquelas que praticam esportes de alta performance ou com vias acessórias de alto risco de condução rápida.',
    expA: 'Correta. A ablação por radiofrequência ou crioablação é a terapia curativa padrão-ouro.',
    expB: 'Incorreta. Denervação renal é experimental para hipertensão arterial resistente no adulto.',
    expC: 'Incorreta. Marcapasso trata bradiarritmias, não ablação de via rápida.',
    expD: 'Incorreta. Simpatectomia é usada em canalopatias graves (Síndrome do QT Longo refratária), não na TSV comum.',
  });

  q({
    id: 'ped-cardio-100-089',
    subtopic: 'Taquicardia Supraventricular (TSV)',
    inst: 'PUC-Campinas',
    year: 2024,
    statement: 'Em escolares e adolescentes cooperativos com TSV hemodinamicamente estáveis, qual variante de manobra física vagal tem demonstrado maior taxa de reversão para o ritmo sinusal quando comparada à manobra de Valsalva convencional?',
    A: 'Manobra de Valsalva Modificada (expiração contra resistência de 40 mmHg em seringa por 15 segundos, seguida imediatamente por decúbito dorsal e elevação passiva dos membros inferiores a 45° por 15 segundos).',
    B: 'Manobra de compressão bimanual das artérias carótidas por 1 minuto.',
    C: 'Manobra de hiperflexão cervical forçada com apneia inspiratória profunda.',
    D: 'Manobra de descompressão gástrica com sonda nasogástrica calibrosa.',
    ans: 'A',
    comment: 'O ensaio clínico REVERT comprovou a superioridade da Manobra de Valsalva Modificada em comparação à tradicional (taxa de reversão de 43% vs 17%). Consiste em: o paciente sentado sopra o êmbolo de uma seringa de 10-20 mL gerando pressão de 40 mmHg por 15 segundos; em seguida, o paciente é colocado imediatamente em decúbito dorsal e seus membros inferiores são elevados passivamente a 45° por mais 15 segundos. Isso otimiza o retorno venoso e o estímulo barorreceptor vagal sobre o nó AV.',
    expA: 'Correta. A manobra de Valsalva modificada é o método físico mais eficaz e validado para reversão de TSV em adolescentes.',
    expB: 'Incorreta. Massagem carotídea bilateral é formalmente contraindicada.',
    expC: 'Incorreta. Flexão cervical não gera estímulo autonômico barorreflexo adequado.',
    expD: 'Incorreta. Sondagem gástrica gera desconforto e estímulo adrenérgico deletério.',
  });

  q({
    id: 'ped-cardio-100-090',
    subtopic: 'Taquicardia Supraventricular (TSV)',
    inst: 'FAMERP',
    year: 2023,
    statement: 'Qual é o fármaco betabloqueador oral de primeira escolha comumente utilizado para a profilaxia a longo prazo de recidivas de TSV em lactentes durante o primeiro ano de vida?',
    A: 'Propranolol por via oral.',
    B: 'Sotalol em dose de sobrecarga venosa rápida.',
    C: 'Atenolol em inalação contínua.',
    D: 'Carvedilol apenas se houver fração de ejeção supranormal (> 75%).',
    ans: 'A',
    comment: 'O Propranolol oral é o fármaco de primeira escolha clássico e mais amplamente prescrito para a profilaxia de episódios recorrentes de TSV em lactentes ao longo do primeiro ano de vida. Possui amplo perfil de segurança, atua reduzindo o tônus adrenérgico e retardando a condução no nó atrioventricular e no circuito reentrante.',
    expA: 'Correta. O propranolol oral é a medicação padrão de manutenção na prevenção de novas crises de TSV no primeiro ano.',
    expB: 'Incorreta. Sotalol requer vigilância estrita de intervalo QT em ambiente hospitalar, sendo droga de segunda linha.',
    expC: 'Incorreta. Atenolol é administrado por via oral, não por inalação.',
    expD: 'Incorreta. Carvedilol é usado no manejo da insuficiência cardíaca crônica com fração de ejeção reduzida.',
  });

  q({
    id: 'ped-cardio-100-091',
    subtopic: 'Taquicardia Supraventricular (TSV)',
    inst: 'SCMSP',
    year: 2024,
    statement: 'Durante a infusão intravenosa em bólus rápido de adenosina para reversão de TSV em uma criança monitorizada, qual traçado eletrocardiográfico transitório com duração de 2 a 5 segundos é comum e esperado logo antes do retorno ao ritmo sinusal normal, devendo ser antecipado à equipe para evitar alarmes indevidos?',
    A: 'Pausa sinusal breve ou assistolia transitória transitória com posterior surgimento de onda P sinusal e ritmo regular.',
    B: 'Fibrilação ventricular persistente que exige desfibrilação com 4 J/kg.',
    C: 'Torsades de pointes refratária com necessidade de sulfato de magnésio.',
    D: 'Bloqueio de ramo bilateral irreversível com necessidade de marcapasso definitivo.',
    ans: 'A',
    comment: 'A adenosina liga-se aos receptores A1 no nó atrioventricular e no nó sinusal, ativando canais de potássio acoplados à proteína G e causando hiperpolarização celular imediata. O efeito é uma parada abrupta e transitória da condução elétrica nodal (assistolia ou pausa ventricular curta de 2 a 5 segundos) no monitor, seguida de recuperação espontânea do ritmo sinusal fisiológico.',
    expA: 'Correta. A pausa transitória/assistolia de poucos segundos é o efeito fisiopatológico esperado da adenosina antes da reversão ao ritmo sinusal.',
    expB: 'Incorreta. Degeneração para fibrilação ventricular é excepcional em crianças com corações normais.',
    expC: 'Incorreta. A adenosina não prolonga o intervalo QT a ponto de induzir torsades de rotina.',
    expD: 'Incorreta. O efeito bloqueador é ultracurto e desaparece em segundos pela rápida recaptação pelas hemácias e endotélio.',
  });
}
