import { q } from './helper.js';

export function loadSec9() {
  q({
    id: 'ped-cardio-100-092',
    subtopic: 'Teste do Coraçãozinho',
    inst: 'USP-SP',
    year: 2024,
    statement: 'Qual é o período cronológico de vida preconizado pelo Ministério da Saúde e pela Sociedade Brasileira de Pediatria para a realização da oximetria de pulso para triagem neonatal de cardiopatias congênitas críticas (Teste do Coraçãozinho) em recém-nascidos assintomáticos com idade gestacional ≥ 35 semanas?',
    A: 'Entre 24 e 48 horas de vida, sempre antes da alta hospitalar da maternidade.',
    B: 'Exclusivamente nos primeiros 10 minutos após o clampeamento do cordão umbilical.',
    C: 'Apenas entre o 7º e o 10º dia de vida na primeira consulta na Unidade Básica de Saúde.',
    D: 'No 28º dia de vida, coincidindo com o término do período neonatal.',
    ans: 'A',
    comment: 'O Teste do Coraçãozinho deve ser realizado de rotina em todos os recém-nascidos aparentemente saudáveis com idade gestacional > 35 semanas entre 24 e 48 horas de vida (antes da alta da maternidade). Fazer antes de 24 horas eleva o número de resultados falso-positivos devido à instabilidade hemodinâmica transicional e shunt fisiológico pelo canal arterial; postergar para além de 48 horas aumenta o risco de o canal arterial se fechar no domicílio, levando a choque ou óbito por cardiopatia canal-dependente não diagnosticada.',
    expA: 'Correta. A janela entre 24 e 48 horas de vida (antes da alta) é o período padrão recomendado pelas diretrizes.',
    expB: 'Incorreta. Nos primeiros minutos de vida a saturação normal ainda é baixa e o shunt transicional gera falsos positivos.',
    expC: 'Incorreta. Postergar para a UBS após o 7º dia expõe o recém-nascido a choque e morte domiciliar.',
    expD: 'Incorreta. 28 dias é tardio demais para o rastreio neonatal de cardiopatias críticas.',
  });

  q({
    id: 'ped-cardio-100-093',
    subtopic: 'Teste do Coraçãozinho',
    inst: 'UNICAMP',
    year: 2024,
    statement: 'Quais são os locais anatômicos exatos preconizados para a colocação do sensor de oximetria de pulso na realização do Teste do Coraçãozinho e qual é a justificativa anatômica para a escolha específica do membro superior direito?',
    A: 'Membro Superior Direito (pré-ductal) e em um dos Membros Inferiores (pós-ductal); o membro superior direito recebe sangue do tronco braquiocefálico que emerge da aorta antes do canal arterial.',
    B: 'Membro Superior Esquerdo e Membro Superior Direito simultaneamente; ambos recebem circulação exclusivamente pré-ductal.',
    C: 'Ambos os Membros Inferiores apenas; os membros inferiores concentram a maior pressão arterial sistólica do organismo.',
    D: 'Hálux esquerdo e lobo da orelha direita; ambos representam o território capilar cutâneo periférico terminal.',
    ans: 'A',
    comment: 'A aferição deve ser feita no Membro Superior Direito (MSD) e em um dos Membros Inferiores (MID ou MIE). O MSD é obrigatoriamente a referência pré-ductal porque o tronco braquiocefálico é o primeiro ramo do arco aórtico, originando-se proximalmente à inserção do canal arterial (ductus arteriosus). Já o membro superior esquerdo recebe a artéria subclávia esquerda, que pode ter origem próxima ou imediatamente pós-ductal.',
    expA: 'Correta. MSD (pré-ductal) e um dos membros inferiores (pós-ductal) com justificativa anatômica precisa.',
    expB: 'Incorreta. O membro superior esquerdo pode sofrer influência pós-ductal e não avalia o gradiente inferior.',
    expC: 'Incorreta. Não permite a comparação entre território pré-ductal e pós-ductal.',
    expD: 'Incorreta. O lobo da orelha não é sítio preconizado para o teste neonatal.',
  });

  q({
    id: 'ped-cardio-100-094',
    subtopic: 'Teste do Coraçãozinho',
    inst: 'ENARE',
    year: 2024,
    statement: 'De acordo com a Sociedade Brasileira de Pediatria e o Ministério da Saúde, quais são os critérios que definem um resultado NORMAL (teste negativo) no Teste do Coraçãozinho?',
    A: 'Saturação periférica de oxigênio (SpO2) maior ou igual a 95% em ambos os membros (MSD e MI) E diferença entre as duas medidas menor ou igual a 3% (diferença ≤ 3%).',
    B: 'SpO2 maior que 85% em membros inferiores e maior que 90% em membros superiores, independentemente da diferença.',
    C: 'SpO2 de 100% no MSD e qualquer valor acima de 80% nos membros inferiores.',
    D: 'Diferença entre MSD e MI de exatamente 10% com SpO2 superior a 92% em ambos.',
    ans: 'A',
    comment: 'O Teste do Coraçãozinho é considerado NORMAL (negativo) quando: 1) A saturação de oxigênio for ≥ 95% tanto no MSD (pré-ductal) quanto no membro inferior (pós-ductal); E 2) A diferença percentual entre a medida do MSD e a do membro inferior for menor ou igual a 3% (diferença ≤ 3%). Cumpridos esses dois critérios, o recém-nascido é liberado para a alta hospitalar habitual da maternidade.',
    expA: 'Correta. SpO2 ≥ 95% em ambos os sítios e diferença absoluta ≤ 3% definem o teste normal.',
    expB: 'Incorreta. Saturações abaixo de 95% são alteradas e exigem investigação.',
    expC: 'Incorreta. Qualquer valor abaixo de 95% ou diferença > 3% torna o teste alterado.',
    expD: 'Incorreta. Diferença de 10% é francamente patológica.',
  });

  q({
    id: 'ped-cardio-100-095',
    subtopic: 'Teste do Coraçãozinho',
    inst: 'FMRP-USP',
    year: 2024,
    statement: 'Recém-nascido a termo com 30 horas de vida, clinicamente assintomático, realiza o Teste do Coraçãozinho com o seguinte resultado: SpO2 em MSD = 96% e SpO2 em MID = 91% (diferença de 5 pontos percentuais). Qual é a conduta IMEDIATA recomendada pelas diretrizes oficiais?',
    A: 'Considerar o teste alterado preliminar, NÃO conceder alta hospitalar e repetir a aferição após 1 hora.',
    B: 'Conceder alta hospitalar imediata com encaminhamento para ecocardiograma ambulatorial em 30 dias.',
    C: 'Iniciar imediatamente infusão contínua de Prostaglandina E1 e intubação orotraqueal.',
    D: 'Encaminhar o paciente imediatamente para cateterismo cardíaco intervencionista de urgência.',
    ans: 'A',
    comment: 'Como a SpO2 no MID foi < 95% e a diferença entre pré e pós-ductal foi de 5% (≥ 4%), o teste é classificado como ALTERADO PRELIMINAR (ou duvidoso). A conduta mandatória nesse primeiro momento é manter o neonato na maternidade e REPETIR a oximetria de pulso após 1 hora (podendo ser repetida mais uma vez se persistir alterada). Apenas se persistir alterada na reavaliação o teste torna-se positivo e indica ecocardiograma.',
    expA: 'Correta. A conduta padrão para o primeiro teste alterado é repetir o exame após 1 hora sem liberar a alta.',
    expB: 'Incorreta. É formalmente proibido conceder alta hospitalar com teste de triagem alterado.',
    expC: 'Incorreta. Prostaglandina imediata sem eco ou sinais clínicos de choque é conduta precipitada na primeira medida alterada.',
    expD: 'Incorreta. Não há diagnóstico anatômico confirmado para indicar cateterismo.',
  });

  q({
    id: 'ped-cardio-100-096',
    subtopic: 'Teste do Coraçãozinho',
    inst: 'UERJ',
    year: 2023,
    statement: 'Um recém-nascido com resultado preliminar alterado no Teste do Coraçãozinho é reavaliado após 1 hora, apresentando SpO2 em MSD = 93% e em MID = 89%. Como esse resultado é classificado e qual é a conduta mandatória?',
    A: 'Teste POSITIVO; o recém-nascido não deve receber alta hospitalar, deve permanecer monitorizado e realizar Ecocardiograma confirmatório antes da alta (em até 24 horas).',
    B: 'Teste falso-positivo; o recém-nascido pode receber alta com puericultura de rotina.',
    C: 'Teste duvidoso permanente; repetir diariamente por 14 dias antes de solicitar exames de imagem.',
    D: 'Resultado normal para o período de transição neonatal; alta imediata.',
    ans: 'A',
    comment: 'Se após 1 hora da primeira aferição a SpO2 permanecer < 95% em qualquer um dos membros ou a diferença entre eles persistir ≥ 4% (ou > 3%), o Teste do Coraçãozinho é classificado definitivamente como POSITIVO. O recém-nascido NÃO PODE receber alta da maternidade e deve ser submetido obrigatoriamente a um Ecocardiograma transtorácico em até 24 horas para confirmação diagnóstica antes de qualquer liberação.',
    expA: 'Correta. Teste positivo confirmado na repetição exige ecocardiograma antes da alta e monitorização rigorosa.',
    expB: 'Incorreta. A persistência de hipoxemia não pode ser desprezada como falso-positivo.',
    expC: 'Incorreta. Aguardar 14 dias causaria colapso cardiovascular por fechamento do canal arterial.',
    expD: 'Incorreta. Valores abaixo de 95% em RN a termo com > 24h não são normais.',
  });

  q({
    id: 'ped-cardio-100-097',
    subtopic: 'Teste do Coraçãozinho',
    inst: 'SCMSP',
    year: 2024,
    statement: 'Qual é o principal objetivo do Teste do Coraçãozinho na triagem neonatal de maternidade?',
    A: 'Detectar precocemente Cardiopatias Congênitas Críticas canal-dependentes (de fluxo pulmonar ou sistêmico) antes que o fechamento fisiológico do canal arterial provoque choque cardiogênico, hipóxia grave ou morte súbita.',
    B: 'Diagnosticar precocemente arritmias ventriculares genéticas hereditárias como a Síndrome de Brugada.',
    C: 'Identificar trombose venosa profunda congênita de membros inferiores.',
    D: 'Rastrear insuficiência renal pré-renal funcional neonatal transitória.',
    ans: 'A',
    comment: 'O teste foi desenhado para detectar cardiopatias congênitas críticas canal-dependentes de fluxo sistêmico (ex: Síndrome do Coração Esquerdo Hipoplásico, Coarctação de Aorta grave, Interrupção do arco aórtico) ou de fluxo pulmonar (ex: Atresia pulmonar, Tetralogia de Fallot crítica), além da Transposição das Grandes Artérias. Nestas patologias, o recém-nascido parece inicialmente saudável enquanto o canal arterial está aberto, mas evolui para colapso fatal súbito ao receber alta.',
    expA: 'Correta. Identificar cardiopatias congênitas críticas canal-dependentes antes do colapso pós-fechamento ductal.',
    expB: 'Incorreta. A oximetria de pulso não é método para detecção de canalopatias arrítmicas.',
    expC: 'Incorreta. Oximetria avalia saturação de hemoglobina arterial, não trombose venosa profunda.',
    expD: 'Incorreta. Função renal é avaliada por débito urinário e creatinina sérica.',
  });

  q({
    id: 'ped-cardio-100-098',
    subtopic: 'Teste do Coraçãozinho',
    inst: 'SMS-SP',
    year: 2024,
    statement: 'Qual das seguintes cardiopatias congênitas é uma limitação reconhecida do Teste do Coraçãozinho, podendo facilmente passar despercebida com oximetria de pulso normal (resultado falso-negativo do teste)?',
    A: 'Comunicação Interventricular (CIV) pequena ou moderada restritiva sem repercussão hemodinâmica precoce.',
    B: 'Síndrome da Hipoplasia do Ventrículo Esquerdo com canal arterial fechando.',
    C: 'Transposição das Grandes Artérias simples com septo íntegro.',
    D: 'Atresia Pulmonar com septo interventricular íntegro.',
    ans: 'A',
    comment: 'O Teste do Coraçãozinho tem excelente sensibilidade para cardiopatias com hipoxemia e shunts dependentes do canal arterial, mas NÃO detecta lesões acianóticas sem shunt direita-esquerda pelo canal arterial, tais como: CIVs pequenas/médias, CIAs tipo ostium secundum, estenose pulmonar leve ou coarctação de aorta leve. Essas lesões não geram hipoxemia pré ou pós-ductal nas primeiras 48 horas de vida.',
    expA: 'Correta. A CIV restritiva pequena tem saturação de oxigênio normal em todos os membros, sendo falso-negativo na oximetria.',
    expB: 'Incorreta. A hipoplasia de VE gera má perfusão sistêmica e dessaturação evidente no teste.',
    expC: 'Incorreta. A TGA cursa com cianose acentuada detectada prontamente pelo teste.',
    expD: 'Incorreta. Atresia pulmonar causa hipoxemia grave detectada pelo teste.',
  });

  q({
    id: 'ped-cardio-100-099',
    subtopic: 'Teste do Coraçãozinho',
    inst: 'IAMSPE',
    year: 2024,
    statement: 'Ao realizar a oximetria de triagem neonatal, o pediatra encontra SpO2 no membro superior direito de 86% e SpO2 no membro inferior direito de 95% (oxigenação pós-ductal significativamente superior à pré-ductal). Qual cardiopatia congênita crítica associada a hipertensão pulmonar persistente neonatal explica esse fenômeno fisiopatológico de "cianose diferencial reversa"?',
    A: 'Transposição das Grandes Artérias (TGA) associada a persistência de hipertensão pulmonar ou coarctação de aorta.',
    B: 'Persistência isolada do canal arterial com shunt esquerda-direita maciço puro.',
    C: 'Tetralogia de Fallot com estenose subpulmonar leve e arco aórtico normal.',
    D: 'Comunicação interatrial ampla tipo ostium primum sem valvopatia associada.',
    ans: 'A',
    comment: 'O achado de SpO2 pós-ductal (membros inferiores) superior à SpO2 pré-ductal (membro superior direito) é denominado "cianose diferencial reversa". Na TGA, o ventrículo esquerdo ejeta sangue oxigenado na artéria pulmonar. Se houver hipertensão pulmonar ou coarctação de aorta, esse sangue oxigenado da artéria pulmonar é desviado pelo canal arterial para a aorta descendente, oxigenando os membros inferiores mais do que a aorta ascendente (que recebe sangue venoso desoxigenado do VD para o MSD).',
    expA: 'Correta. A TGA associada à hipertensão pulmonar é a causa clássica da cianose diferencial reversa.',
    expB: 'Incorreta. Na PCA simples, o sangue oxigenado vem da aorta e satura igualmente ou reduz o MI se houver shunt reverso.',
    expC: 'Incorreta. No Fallot a saturação no MSD e MI é similar e reduzida.',
    expD: 'Incorreta. A CIA não gera shunt pós-ductal preferencial em membros inferiores.',
  });

  q({
    id: 'ped-cardio-100-100',
    subtopic: 'Teste do Coraçãozinho',
    inst: 'FAMERP',
    year: 2023,
    statement: 'Em um recém-nascido prematuro limítrofe (35 semanas de gestação), qual das seguintes causas NÃO cardíacas é a causa mais comum de um Teste do Coraçãozinho alterado preliminar nas primeiras 24 a 48 horas de vida na maternidade?',
    A: 'Doenças respiratórias neonatais (como Taquipneia Transitória do Recém-Nascido ou Síndrome do Desconforto Respiratório) e Hipertensão Pulmonar Persistente do Neonato.',
    B: 'Hipercalcemia hipofisária congênita.',
    C: 'Estenose congênita do piloro hipertrófica.',
    D: 'Displasia do desenvolvimento do quadril bilateral.',
    ans: 'A',
    comment: 'Embora o teste seja voltado para cardiopatias congênitas críticas, causas pulmonares e transicionais são os principais fatores de teste alterado na maternidade: a Taquipneia Transitória do RN (TTRN), o desconforto respiratório do prematuro tardio, pneumonias congênitas e a Hipertensão Pulmonar Persistente do Neonato (HPPN) causam hipoxemia e shunts intrapulmonares e intercâmaras que alteram a oximetria de pulso, exigindo diagnóstico diferencial imediato.',
    expA: 'Correta. Patologias respiratórias e HPPN são as principais causas extracardíacas de oximetria alterada na triagem neonatal.',
    expB: 'Incorreta. Distúrbios eletrolíticos não geram hipoxemia arterial primária imediata sem colapso.',
    expC: 'Incorreta. Estenose de piloro manifesta-se entre a 3ª e 6ª semana com vômitos em jato, não hipoxemia neonatal.',
    expD: 'Incorreta. Afecção ortopédica que não interfere na saturação periférica de oxigênio.',
  });
}
