import { q } from './helper_itu.js';

export function loadSec10() {
  q({
    id: 'ped-itu-076',
    subtopic: 'Válvula de Uretra Posterior (VUP)',
    inst: 'USP-SP',
    year: 2024,
    statement: 'Qual é a anomalia congênita obstrutiva infravesical mais frequente do trato urinário inferior em pacientes do sexo masculino, representando uma das principais causas de doença renal crônica terminal na infância?',
    A: 'Válvula de Uretra Posterior (VUP).',
    B: 'Estenose congênita do meato uretral anterior isolada.',
    C: 'Duplicação uretral completa em Y.',
    D: 'Divertículo congênito da uretra pendular.',
    ans: 'A',
    comment: 'A Válvula de Uretra Posterior (VUP) é a causa mais comum de obstrução infravesical grave no recém-nascido e lactente do sexo masculino (incidência aproximada de 1 para cada 4.000 a 8.000 nascidos vivos masculinos). Consiste em pregas mucosas anômalas membranosas no nível do verumontanum na uretra prostática que agem como válvulas unidirecionais, impedindo a saída da urina da bexiga.',
    expA: 'Correta. A Válvula de Uretra Posterior é a principal causa de obstrução infravesical congênita no sexo masculino.',
    expB: 'Incorreta. Estenose de meato é mais comumente adquirida pós-postectomia ou trauma e causa obstrução distal menos grave.',
    expC: 'Incorreta. Duplicação uretral é anomalia anatômica rara.',
    expD: 'Incorreta. Divertículo uretral anterior é muito menos frequente do que a VUP.',
  });

  q({
    id: 'ped-itu-077',
    subtopic: 'Válvula de Uretra Posterior (VUP)',
    inst: 'UNICAMP',
    year: 2024,
    statement: 'Gestante no 3º trimestre realiza ultrassonografia obstétrica morfológica que revela feto masculino com: bexiga fetal intensamente distendida com parede muscular espessada e trabeculada, uretra posterior dilatada gerando o clássico "sinal do buraco de fechadura" (keyhole sign), ureterohidronefrose bilateral e oligoâmnio acentuado. Qual diagnóstico fetal esses achados definem?',
    A: 'Válvula de Uretra Posterior (VUP) com obstrução do trato urinário inferior (LUTO).',
    B: 'Cisto de colédoco intra-abdominal congênito.',
    C: 'Agenesia renal bilateral com feto viável.',
    D: 'Teratoma sacrococcígeo tipo 1.',
    ans: 'A',
    comment: 'A imagem ultrassonográfica da bexiga distendida com colo aberto e uretra prostática dilatada projeta o clássico aspecto do "buraco de fechadura" (keyhole sign), que associado a espessamento parietal da bexiga, hidronefrose bilateral e oligoidrâmnio em feto do sexo masculino é virtualmente patognomônico de Válvula de Uretra Posterior com Obstrução do Trato Urinário Inferior (LUTO - Lower Urinary Tract Obstruction).',
    expA: 'Correta. Bexiga espessada, keyhole sign e hidronefrose bilateral no feto masculino definem VUP.',
    expB: 'Incorreta. Cisto de colédoco situa-se no hipocôndrio direito na via biliar.',
    expC: 'Incorreta. Na agenesia renal bilateral a bexiga não se enche (ausência de urina).',
    expD: 'Incorreta. Teratoma sacrococcígeo é massa tumoral pélvica perineal extrínseca.',
  });

  q({
    id: 'ped-itu-078',
    subtopic: 'Válvula de Uretra Posterior (VUP)',
    inst: 'ENARE',
    year: 2024,
    statement: 'Qual é a complicação extra-renal mais grave e potencialmente letal associada à presença de Válvula de Uretra Posterior grave com oligoidrâmnio acentuado e precoce durante a gestação?',
    A: 'Hipoplasia Pulmonar grave com insuficiência respiratória neonatal imediata refratária (Sequência de Potter).',
    B: 'Cardiopatia congênita cianótica com transposição dos grandes vasos.',
    C: 'Atresia congênita de esôfago sem fístula traqueal.',
    D: 'Fechamento intrauterino precoce do ducto arterioso.',
    ans: 'A',
    comment: 'O líquido amniótico no segundo e terceiro trimestres é composto quase que exclusivamente por urina fetal. A obstrução uretral grave impede o esvaziamento da urina para a cavidade amniótica, gerando anidrâmnio/oligoâmnio severo. Como o líquido amniótico é fundamental para a expansão mecânica e desenvolvimento dos alvéolos e vias aéreas fetais, o oligoâmnio leva à Hipoplasia Pulmonar grave e deformidades esqueléticas/faciais (Sequência de Potter), sendo a hipoplasia pulmonar a principal causa de óbito neonatal na primeira hora de vida.',
    expA: 'Correta. Oligoidrâmnio severo gera hipoplasia pulmonar grave na Sequência de Potter, causa de óbito neonatal.',
    expB: 'Incorreta. VUP não altera a septação conotruncal cardiovascular primária.',
    expC: 'Incorreta. Atresia de esôfago causa polidrâmnio, não oligoâmnio.',
    expD: 'Incorreta. O canal arterial permanece aberto fisiologicamente sob estímulo de PGE2 placentária.',
  });

  q({
    id: 'ped-itu-079',
    subtopic: 'Válvula de Uretra Posterior (VUP)',
    inst: 'FMRP-USP',
    year: 2024,
    statement: 'Recém-nascido a termo do sexo masculino com 48 horas de vida apresenta recusa de mamadas, palidez e hipotermia. Ao exame físico: abdome distendido com bexiga palpável e tensa até a cicatriz umbilical (globo vesical firme permanente). Durante a micção espontânea, observa-se ausência de jato miccional contínuo vigoroso, apresentando apenas gotejamento intermitente e fraco ("jato em gota a gota"). Qual é a principal hipótese diagnóstica?',
    A: 'Válvula de Uretra Posterior (VUP).',
    B: 'Doença da membrana hialina pulmonar pura.',
    C: 'Encefalopatia hipóxico-isquêmica isolada.',
    D: 'Estenose hipertrófica congênita de piloro.',
    ans: 'A',
    comment: 'A tríade clássica do recém-nascido masculino com VUP ao nascimento consiste em: 1) Jato urinário anormal (fraco, fino, intermitente ou gotejamento em gotas); 2) Bexiga palpável, globosa e tensa que não esvazia após a micção (bexigoma permanente); 3) Sinais de uremia, acidose metabólica e sepse urinária secundária. Essa apresentação clínica exige intervenção descompressiva imediata.',
    expA: 'Correta. Menino neonato com bexigoma tenso e jato urinário fraco em gotas define quadro clássico de VUP.',
    expB: 'Incorreta. Membrana hialina decorre de prematuridade e déficit de surfactante em pulmões.',
    expC: 'Incorreta. Não justifica o globo vesical e a obstrução do fluxo urinário.',
    expD: 'Incorreta. Estenose de piloro cursa com vômitos em jato não biliosos após as primeiras semanas de vida.',
  });

  q({
    id: 'ped-itu-080',
    subtopic: 'Válvula de Uretra Posterior (VUP)',
    inst: 'SCMSP',
    year: 2024,
    statement: 'Qual é a conduta prioritária e emergencial imediata que deve ser tomada logo após o nascimento de um recém-nascido com forte suspeita ou diagnóstico confirmado de Válvula de Uretra Posterior com bexiga distendida e oligúria?',
    A: 'Descompressão vesical imediata por meio de cateterismo uretral de fino calibre (sonda de alívio ou Foley 6 a 8 Fr) associada à estabilização hidroeletrolítica e correção de acidose.',
    B: 'Furosemida intravenosa em alta dose em bólus rápido para forçar diurese.',
    C: 'Observação expectante domiciliar por 30 dias para avaliar o fechamento espontâneo da válvula.',
    D: 'Paracentese abdominal evacuadora de grande volume.',
    ans: 'A',
    comment: 'A prioridade absoluta e salvadora no neonato com suspeita de VUP é a DESCOMPRESSÃO VESICAL IMEDIATA. A passagem de uma sonda vesical de fino calibre (cateter uretral 6 ou 8 Fr) ultrapassa as válvulas membranosas e drena o reservatório vesical, aliviando a contrapressão retrógrada sobre os rins e ureteres, permitindo a recuperação da função renal, monitorização do débito urinário e prevenção de urossepse fulminante.',
    expA: 'Correta. Descompressão vesical imediata com passagem de cateter uretral fino e estabilização metabólica.',
    expB: 'Incorreta. Diuréticos em sistema obstrutivo não funcionam e provocam rotura de via urinária ou piora da hidronefrose.',
    expC: 'Incorreta. A VUP é uma membrana anatômica que nunca involui espontaneamente; atraso gera óbito por insuficiência renal.',
    expD: 'Incorreta. A distensão é vesical e não ascite livre volumosa.',
  });

  q({
    id: 'ped-itu-081',
    subtopic: 'Válvula de Uretra Posterior (VUP)',
    inst: 'UERJ',
    year: 2023,
    statement: 'Qual achado radiológico patognomônico é visualizado na fase miccional da Uretrocistografia Miccional (UCM) em um menino com Válvula de Uretra Posterior?',
    A: 'Uretra posterior (prostática) marcadamente dilatada e elongada, com afilamento abrupto ou interrupção do fluxo de contraste na transição para a uretra bulbar/membranosa anterior afilada.',
    B: 'Ausência total de contraste no interior da bexiga por agenesia vesical completa.',
    C: 'Refluxo retrógrado exclusivo para as artérias umbilicais.',
    D: 'Dilatação aneurismática isolada da glande peniana.',
    ans: 'A',
    comment: 'O exame de escolha definitivo para o diagnóstico de VUP é a UCM. Na fase miccional com o paciente urinando, o contraste preenche a bexiga trabeculada e a uretra posterior: como as válvulas se opõem à saída do fluxo, a uretra prostática sofre dilatação e balonamento extremos, contrastando abruptamente com a uretra bulbar e anterior que permanece colapsada ou filamentosa distalmente às válvulas.',
    expA: 'Correta. Uretra prostática amplamente dilatada com transição e afilamento abrupto na transição membranosa.',
    expB: 'Incorreta. A bexiga enche-se normalmente e costuma estar espessada.',
    expC: 'Incorreta. O contraste vesical não penetra no sistema arterial umbilical obliterado.',
    expD: 'Incorreta. A anomalia é na uretra posterior profunda, não na glande.',
  });

  q({
    id: 'ped-itu-082',
    subtopic: 'Válvula de Uretra Posterior (VUP)',
    inst: 'IAMSPE',
    year: 2024,
    statement: 'Qual é o tratamento cirúrgico definitivo padrão-ouro de primeira escolha para desobstrução da Válvula de Uretra Posterior em recém-nascidos e lactentes estáveis após descompressão inicial e uretra de calibre adequado?',
    A: 'Ablação (ou Fulguração) Endoscópica primária das válvulas por via transuretral sob visão direta com cistoscópio pediátrico.',
    B: 'Cistectomia radical com derivação urinária continente em bolsa ileal.',
    C: 'Ureterostomia cutânea alta definitiva em todos os casos.',
    D: 'Prostatectomia suprapúbica aberta com reconstrução do colo.',
    ans: 'A',
    comment: 'O tratamento de escolha e curativo definitivo da VUP é a Ablação Endoscópica Transuretral das válvulas. Utilizando um cistoscópio pediátrico de fino calibre sob visão direta, as lâminas mucosas anômalas da uretra posterior são incisadas/fulguradas (habitualmente nas posições de 5, 7 e 12 horas do mostrador do relógio) com gancho eletrocirúrgico, eletrodo ou laser, restaurando o calibre normal do lúmen uretral.',
    expA: 'Correta. A ablação/fulguração endoscópica transuretral das válvulas é a cirurgia padrão-ouro curativa.',
    expB: 'Incorreta. Cistectomia radical é cirurgia oncológica de mutilação vesical.',
    expC: 'Incorreta. Derivações altas (vesicostomia/ureterostomia) são exceções reservadas para prematuros extremos ou falência endoscópica.',
    expD: 'Incorreta. A próstata do neonato não deve ser ressecada cirurgicamente.',
  });

  q({
    id: 'ped-itu-083',
    subtopic: 'Válvula de Uretra Posterior (VUP)',
    inst: 'SMS-SP',
    year: 2024,
    statement: 'Mesmo após a ablação cirúrgica bem sucedida da válvula com desobstrução uretral anatômica completa, muitos meninos com histórico de VUP persistem com disfunção miccional crônica, perda involuntária de urina e dilatação progressiva do trato superior ("Síndrome da Bexiga da VUP" / Valve Bladder Syndrome). Qual é a fisiopatologia dessa disfunção vesical residual?',
    A: 'Espessamento miogênico hipertrófico da parede vesical com depósito de colágeno, resultando em bexiga de baixa complacência, hiperatividade do detrusor e pressões intravesicais patologicamente elevadas com resíduo urinário permanente.',
    B: 'Denervação somática congênita do plexo celíaco gástrico.',
    C: 'Infecção crônica por citomegalovírus nos podócitos renais.',
    D: 'Fechamento congênito irreversível da junção ureteropélvica contralateral.',
    ans: 'A',
    comment: 'Durante toda a vida fetal, a bexiga contraiu-se contra uma obstrução fixa de alta resistência, gerando hipertrofia maciça do detrusor com proliferação de tecido conjuntivo e fibrose entre os feixes musculares. Essa bexiga desestruturada perde a complacência e exibe contrações não inibidas sob altíssima pressão (Valve Bladder Syndrome). Mesmo desobstruída a uretra, as pressões intravesicais permanecem altas, exigindo tratamento com anticolinérgicos (oxibutinina) ou cateterismo intermitente limpo.',
    expA: 'Correta. Hipertrofia do detrusor com perda de complacência e hiperatividade pressórica caracteriza a bexiga da VUP.',
    expB: 'Incorreta. O plexo celíaco inerva o trato digestivo superior, não a bexiga urinária.',
    expC: 'Incorreta. Não se relaciona a citomegalovirose.',
    expD: 'Incorreta. Não decorre de estenose de JUP contralateral.',
  });

  q({
    id: 'ped-itu-084',
    subtopic: 'Válvula de Uretra Posterior (VUP)',
    inst: 'PUC-Campinas',
    year: 2024,
    statement: 'Qual é o principal determinante prognóstico para a função renal a longo prazo em um paciente tratado de Válvula de Uretra Posterior?',
    A: 'O grau de Displasia Renal Congênita associada desenvolvida durante a embriogênese sob alta pressão urinária e a dosagem do nadir da creatinina sérica no primeiro ano de vida (especialmente nadir < 0,8-1,0 mg/dL).',
    B: 'A quantidade de dentes erupcionados no primeiro ano de vida.',
    C: 'A presença de icterícia fisiológica neonatal na primeira semana.',
    D: 'A presença de sopro cardíaco inocente de Still na primeira infância.',
    ans: 'A',
    comment: 'Cerca de um terço dos meninos com VUP evoluem para Doença Renal Crônica terminal na adolescência ou idade adulta jovem, mesmo com desobstrução uretral perfeita. Isso ocorre porque a obstrução precoce na vida embrionária induz Displasia Renal Obstrutiva (desorganização dos túbulos e glomérulos com perda congênita de néfrons). O melhor preditor prognóstico da reserva renal funcional é o menor valor de creatinina sérica atingido no primeiro ano de vida (o nadir da creatinina): se o nadir for < 0,8-1,0 mg/dL, o prognóstico renal é excelente.',
    expA: 'Correta. O grau de displasia renal congênita e o nadir da creatinina no 1º ano são os grandes preditores de sobrevida renal.',
    expB: 'Incorreta. Erupção dentária não interfere na função renal.',
    expC: 'Incorreta. Icterícia fisiológica não tem correlação nefrológica.',
    expD: 'Incorreta. Sopro inocente é variante normal cardiovascular.',
  });
}
