import { q } from './helper_itu.js';

export function loadSec12() {
  q({
    id: 'ped-itu-093',
    subtopic: 'Disfunção do Trato Urinário Inferior e Constipação',
    inst: 'USP-SP',
    year: 2024,
    statement: 'Qual é o conceito e a relevância clínica da Síndrome de Eliminação Disfuncional (ou Disfunção Vesical e Intestinal - BBD / Bladder and Bowel Dysfunction) em meninas com episódios repetidos de infecção do trato urinário?',
    A: 'A associação fisiopatológica e funcional entre constipação intestinal crônica e disfunção do trato urinário inferior (incontinência, urgência ou retenção), sendo a causa tratável mais comum de infecções urinárias recorrentes na infância.',
    B: 'Uma doença genética mitocondrial incurável transmitida exclusivamente pelo cromossomo Y.',
    C: 'Uma anomalia anatômica congênita que exige amputação cirúrgica do esfíncter anal.',
    D: 'A presença concomitante de ascite volumosa e insuficiência pancreática exócrina.',
    ans: 'A',
    comment: 'A Disfunção Vesical e Intestinal (BBD ou Síndrome de Eliminação Disfuncional) descreve a coocorrência de constipação crônica e distúrbios miccionais (como hiperatividade detrusora, micção postergada ou incoordenação esfincteriana). Devido à proximidade anatômica e inervação parassimpática compartilhada (S2-S4), a disfunção de um órgão desestabiliza o outro, sendo o principal fator de risco não anatômico para ITUs de repetição em crianças com controle esfincteriano.',
    expA: 'Correta. BBD é a associação fisiopatológica entre constipação e disfunção miccional, grande vilã de ITUs de repetição.',
    expB: 'Incorreta. BBD é uma disfunção funcional adquirida e tratável, muito mais prevalente em meninas.',
    expC: 'Incorreta. O esfíncter anal é anatômica e neurologicamente íntegro; não há indicação cirúrgica.',
    expD: 'Incorreta. Não envolve ascite ou insuficiência pancreática.',
  });

  q({
    id: 'ped-itu-094',
    subtopic: 'Disfunção do Trato Urinário Inferior e Constipação',
    inst: 'UNICAMP',
    year: 2024,
    statement: 'Como a constipação intestinal crônica (retenção fecal na ampola retal) atua diretamente como fator causal mecânico e funcional para o desenvolvimento de infecção do trato urinário de repetição?',
    A: 'O fecaloma ou fezes volumosas retidas na ampola retal comprimem a parede posterior da bexiga e o colo vesical, desencadeando contrações involuntárias do detrusor, obstrução funcional à saída da urina com esvaziamento incompleto (resíduo pós-miccional elevado) e proliferação bacteriana maciça no introito perineal.',
    B: 'As fezes acumuladas no cólon secretam endotoxinas que entram nos glomérulos renais por transporte ativo.',
    C: 'A constipação impede a síntese hepática de imunoglobulinas protetoras.',
    D: 'A ausência de evacuações eleva a concentração de cálcio na urina dissolvendo a mucosa vesical.',
    ans: 'A',
    comment: 'A ampola retal dilatada por fezes ressecadas projeta-se anteriormente contra a base da bexiga e colo vesical. Isso causa compressão mecânica do fluxo urinário e instabilidade do detrusor, resultando em estase urinária e resíduo pós-miccional aumentado (meio de cultura ideal para bactérias). Paralelamente, o ressecamento fecal e a higiene perineal prejudicada aumentam a carga e aderência de E. coli no vestíbulo vulvar.',
    expA: 'Correta. Compressão mecânica vesical, resíduo pós-miccional aumentado e contaminação perineal explicam o mecanismo.',
    expB: 'Incorreta. Não há transporte ativo glomerular de endotoxinas fecais.',
    expC: 'Incorreta. A síntese de imunoglobulinas plasmáticas não é dependente da evacuação diária.',
    expD: 'Incorreta. Não ocorre dissolução tecidual por hipercalcemia.',
  });

  q({
    id: 'ped-itu-095',
    subtopic: 'Disfunção do Trato Urinário Inferior e Constipação',
    inst: 'ENARE',
    year: 2024,
    statement: 'Menina de 6 anos com ITUs de repetição é observada pela mãe realizando frequentemente uma postura corporal característica ao sentir vontade de urinar: agacha-se subitamente pressionando o calcanhar contra o períneo ou cruza as pernas com força e contrai as nádegas ("Manobra de Vincent"). Qual é o significado semiológico dessa manobra de contenção?',
    A: 'Reflete uma tentativa comportamental involuntária de conter a perda urinária causada por contrações não inibidas e súbitas do músculo detrusor (hiperatividade detrusora com urgência miccional).',
    B: 'Sinal patognomônico de fratura de bacia pediátrica por estresse.',
    C: 'Movimento coreiforme involuntário secundário a febre reumática neurológica.',
    D: 'Manobra para aliviar a cólica biliar associada a colelitíase congênita.',
    ans: 'A',
    comment: 'A "Manobra de Vincent" (Vincent curtsey) é uma postura de contenção clássica adotada por crianças com hiperatividade detrusora / bexiga hiperativa. Quando a bexiga contrai involuntariamente gerando urgência miccional abrupta, a criança cruza as pernas, contrai o assoalho pélvico ou senta-se sobre o calcanhar para ocluir mecanicamente a uretra e impedir o escape involuntário de urina na roupa.',
    expA: 'Correta. A manobra de Vincent é uma postura clássica de contenção para evitar perda por hiperatividade detrusora.',
    expB: 'Incorreta. Não se relaciona a traumatismo esquelético da pelve.',
    expC: 'Incorreta. A coreia cursa com movimentos descoordenados em membros superiores e face, não posturas de contenção.',
    expD: 'Incorreta. Não tem correlação com afecções biliares.',
  });

  q({
    id: 'ped-itu-096',
    subtopic: 'Disfunção do Trato Urinário Inferior e Constipação',
    inst: 'FMRP-USP',
    year: 2024,
    statement: 'Segundo os Critérios de Roma IV para Constipação Funcional em crianças com idade de desenvolvimento de pelo menos 4 anos, a presença de pelo menos dois critérios ocorrendo pelo menos uma vez por semana durante o último mês firma o diagnóstico. Quais achados clínicos integram esses critérios?',
    A: '≤ 2 evacuações semanais; pelo menos 1 episódio de incontinência fecal por semana; histórico de postura retentiva excessiva; histórico de dor à evacuação ou fezes ressecadas/endurecidas; presença de grande massa fecal no reto; e histórico de fezes de grande calibre que entopem o vaso sanitário.',
    B: 'Presença de diarreia líquida profusa com sangue visível e esteatorreia diária.',
    C: 'Evacuação diária de fezes pastosas sem dor após cada mamada.',
    D: 'Apenas a constatação radiológica de pneumoperitônio maciço sob o diafragma.',
    ans: 'A',
    comment: 'Os Critérios de Roma IV para constipação intestinal funcional acima de 4 anos exigem pelo menos 2 dos seguintes itens: 1) ≤ 2 evacuações por semana no vaso sanitário; 2) Pelo menos um episódio de incontinência fecal (escape/soiling) por semana; 3) Postura de retenção excessiva deliberada; 4) Evacuações dolorosas ou fezes endurecidas; 5) Grande massa fecal no reto (fecaloma ao exame); 6) Fezes de diâmetro volumoso que chegam a entupir o vaso sanitário.',
    expA: 'Correta. Enumera com rigor os critérios clínicos formais de Roma IV para constipação funcional na infância.',
    expB: 'Incorreta. Diarreia sanguinolenta aponta para doença inflamatória intestinal ou colite infecciosa.',
    expC: 'Incorreta. Padrão evacuatório perfeitamente normal e saudável.',
    expD: 'Incorreta. Pneumoperitônio é sinal de perfuração de víscera oca, emergência cirúrgica.',
  });

  q({
    id: 'ped-itu-097',
    subtopic: 'Disfunção do Trato Urinário Inferior e Constipação',
    inst: 'SCMSP',
    year: 2024,
    statement: 'Qual é o pilar não farmacológico fundamental de primeira linha no manejo da Disfunção do Trato Urinário Inferior (DTUI) em crianças com controle esfincteriano e ITUs recorrentes, denominado "Uroterapia Padrão"?',
    A: 'Micções programadas com horário fixo a cada 2 a 3 horas pelo relógio (evitando retenção prolongada), ingesta hídrica hídrica adequada fracionada e postura miccional correta no vaso sanitário com apoio firme para os pés e relaxamento do assoalho pélvico.',
    B: 'Restrição hídrica absoluta a menos de 200 mL de água por dia para manter a bexiga colapsada.',
    C: 'Orientar a segurar a urina por pelo menos 12 horas consecutivas para treinar a elasticidade vesical.',
    D: 'Cateterismo vesical permanente com sonda de três vias por 6 meses.',
    ans: 'A',
    comment: 'A Uroterapia Padrão é a terapia comportamental inicial indispensável para reeducar o trato urinário inferior. Consiste em: 1) Micções com horário programado (a cada 2 a 3 horas, sem esperar a bexiga encher ao extremo); 2) Ingesta hídrica regular ao longo do dia; 3) Postura adequada no vaso sanitário (uso de redutor de assento e apoio para os pés, permitindo que os joelhos fiquem a 90° e a musculatura do assoalho pélvico relaxe completamente durante a micção).',
    expA: 'Correta. Micções programadas a cada 2-3h, hidratação regular e apoio nos pés com postura adequada.',
    expB: 'Incorreta. A restrição hídrica torna a urina excessivamente concentrada e irritativa para o detrusor.',
    expC: 'Incorreta. Reter a urina por 12 horas causa estase maciça e proliferação bacteriana exuberante.',
    expD: 'Incorreta. Sondagem de demora é deletéria e contraindicada em crianças funcionais.',
  });

  q({
    id: 'ped-itu-098',
    subtopic: 'Disfunção do Trato Urinário Inferior e Constipação',
    inst: 'UERJ',
    year: 2023,
    statement: 'No tratamento medicamentoso da constipação intestinal crônica associada à Síndrome de Eliminação Disfuncional na infância, qual fármaco laxativo osmótico é o padrão-ouro de primeira escolha para desimpactação fecal e terapia de manutenção?',
    A: 'Polietilenoglicol sem eletrólitos (PEG 4000 / Macrogol).',
    B: 'Óleo mineral administrado por via inalatória.',
    C: 'Bisacodil em altas doses diárias contínuas por 5 anos.',
    D: 'Carvão vegetal ativado em suspensão concentrada.',
    ans: 'A',
    comment: 'O Polietilenoglicol 4000 sem eletrólitos (PEG 4000 / Macrogol) é o laxativo osmótico de primeira linha consagrado pelas diretrizes internacionais (ESPGHAN e NASPGHAN). É insípido, inodoro, não absorvível, não fermentado por bactérias colônicas (não gera cólicas nem gases) e retém água na luz intestinal, amolecendo as fezes. Utiliza-se 1 a 1,5 g/kg/dia para desimpactação e 0,5 a 0,8 g/kg/dia na manutenção por vários meses.',
    expA: 'Correta. O PEG 4000 é o laxativo de escolha de primeira linha com excelente eficácia e tolerabilidade.',
    expB: 'Incorreta. Óleo mineral tem risco de pneumonia lipoídica se aspirado e é contraindicado em lactentes e crianças pequenas.',
    expC: 'Incorreta. Laxativos estimulantes em uso contínuo crônico provocam dependência e atonia colônica.',
    expD: 'Incorreta. O carvão ativado prende o intestino e inativa medicamentos.',
  });

  q({
    id: 'ped-itu-099',
    subtopic: 'Disfunção do Trato Urinário Inferior e Constipação',
    inst: 'IAMSPE',
    year: 2024,
    statement: 'Menina de 7 anos mantém urgência miccional, incontinência urinária diurna e manobras de contenção evidentes mesmo após 3 meses de uroterapia comportamental bem conduzida e resolução completa da constipação intestinal. O estudo urodinâmico confirma Hiperatividade Detrusora com contrações involuntárias não inibidas. Qual classe farmacológica e fármaco de escolha estão indicados?',
    A: 'Anticolinérgico / Antimuscarínico (Cloridrato de Oxibutinina por via oral).',
    B: 'Agonista colinérgico muscarínico (Betanecol em alta dose).',
    C: 'Diurético de alça (Furosemida intravenosa contínua).',
    D: 'Antipsicótico típico de alta potência (Haloperidol intramuscular).',
    ans: 'A',
    comment: 'A Oxibutinina é um potente agente anticolinérgico/antimuscarínico que bloqueia os receptores muscarínicos M2 e M3 no músculo detrusor da bexiga, inibindo as contrações involuntárias não inibidas e aumentando a capacidade vesical funcional e a complacência. É o tratamento farmacológico de escolha na bexiga hiperativa pediátrica refratária à uroterapia comportamental, devendo ser introduzido apenas após o tratamento efetivo da constipação (para evitar agravamento do quadro intestinal).',
    expA: 'Correta. A oxibutinina (antimuscarínico) é a droga de escolha para hiperatividade detrusora infantil.',
    expB: 'Incorreta. Betanecol estimula a contração do detrusor, o que agravaria dramaticamente a urgência e perdas.',
    expC: 'Incorreta. Furosemida aumentaria a produção de urina, piorando os episódios de incontinência.',
    expD: 'Incorreta. Antipsicóticos não têm indicação no manejo da bexiga hiperativa comum.',
  });

  q({
    id: 'ped-itu-100',
    subtopic: 'Disfunção do Trato Urinário Inferior e Constipação',
    inst: 'SMS-SP',
    year: 2024,
    statement: 'Criança de 8 anos com ITUs de repetição apresenta diagnóstico de "Micção Disfuncional" (incoordenação vésico-esfincteriana), caracterizada pela contração paradoxal involuntária da musculatura estriada do esfíncter uretral externo durante a fase de esvaziamento (micção interrompida com curvas urofluxométricas em platô/estaccato). Qual modalidade terapêutica não invasiva de reabilitação neuromuscular pélvica tem alto índice de sucesso para ensinar a criança a relaxar o assoalho pélvico durante a micção?',
    A: 'Biofeedback associado à Fisioterapia Pélvica / Treinamento dos Músculos do Assoalho Pélvico.',
    B: 'Fio de sutura permanente no meato uretral externo.',
    C: 'Eletroconvulsoterapia sob anestesia geral.',
    D: 'Denervação cirúrgica completa de todos os ramos da cauda equina.',
    ans: 'A',
    comment: 'O Biofeedback guiado por eletromiografia de superfície perineal é a modalidade de reabilitação neuromuscular padrão-ouro para a micção disfuncional na infância. Através de jogos interativos em telas de computador estimulados pelos sensores de eletromiografia, a criança aprende de forma lúdica a reconhecer os músculos do assoalho pélvico e relaxar ativamente o esfíncter durante o ato miccional, restaurando o fluxo laminar e reduzindo a zero o resíduo pós-miccional e as recidivas de ITU.',
    expA: 'Correta. O biofeedback com fisioterapia pélvica ensina o relaxamento esfincteriano ativo durante a micção.',
    expB: 'Incorreta. Sutura no meato provocaria retenção urinária obstrutiva grave.',
    expC: 'Incorreta. ECT não tem indicação em distúrbios miccionais funcionais periféricos.',
    expD: 'Incorreta. Lesão da cauda equina causaria paralisia flácida e bexiga neurogênica arrefléxica permanente.',
  });
}
