import { q } from './helper_itu.js';

export function loadSec1() {
  q({
    id: 'ped-itu-001',
    subtopic: 'Métodos de coleta de urina',
    inst: 'USP-SP',
    year: 2024,
    statement: 'Lactente feminina de 7 meses é trazida à UPA com febre de 38,8 °C há 48 horas, sem sintomas respiratórios ou gastrointestinais. Ao exame físico: irritada ao manuseio, hidratada, ausculta cardiopulmonar e otoscopia normais. A médica assistente solicita EAS e urocultura. A mãe questiona se não poderia usar o saco coletor adesivo. Qual é a orientação correta sobre o valor clínico e as limitações do saco coletor adesivo?',
    A: 'A punção suprapúbica ou cateterismo vesical é mandatório para urocultura confirmatória, pois o saco coletor apresenta taxa de contaminação de até 50-70% (baixo VPP), sendo útil apenas quando a urina tipo 1 é totalmente normal para afastar ITU (alto VPN).',
    B: 'O saco coletor é o método padrão-ouro para urocultura em lactentes, desde que trocado a cada 6 horas.',
    C: 'Se a cultura do saco coletor isolar mais de 10.000 UFC/mL de qualquer bactéria, o diagnóstico de pielonefrite está confirmado e dispensa novo exame.',
    D: 'O saco coletor adesivo possui alta especificidade e alto valor preditivo positivo, sendo contraindicado apenas em recém-nascidos prematuros.',
    ans: 'A',
    comment: 'O saco coletor plástico estéril tem uma taxa inaceitavelmente alta de contaminação por flora perineal e fecal (falso-positivo em 50 a 70% dos casos). No entanto, um sedimento urinário (EAS) completamente normal colhido por saco coletor (sem leucocitúria, sem bacteriúria e com nitrito negativo) tem excelente Valor Preditivo Negativo (VPN > 95%), permitindo afastar ITU. Qualquer urocultura positiva em saco coletor requer confirmação por método estéril (cateterismo vesical ou punção suprapúbica).',
    expA: 'Correta. O saco coletor tem excelente valor preditivo negativo quando a urina é normal, mas não serve para firmar diagnóstico de ITU devido à altíssima taxa de contaminação.',
    expB: 'Incorreta. O padrão-ouro de coleta estéril em não continentes é o cateterismo vesical ou a punção suprapúbica.',
    expC: 'Incorreta. Urocultura em saco coletor não confirma diagnóstico de ITU em lactentes; necessita de amostra estéril.',
    expD: 'Incorreta. O saco coletor possui baixo valor preditivo positivo e baixa especificidade para infecção verdadeira.',
  });

  q({
    id: 'ped-itu-002',
    subtopic: 'Métodos de coleta de urina',
    inst: 'UNICAMP',
    year: 2024,
    statement: 'Menino de 4 meses com febre de 39 °C sem foco evidente é admitido para investigação. O médico decide realizar cateterismo vesical para coleta estéril de urina. Ao passar a sonda de alívio uretral com técnica asséptica rigorosa, são obtidos 4 mL de urina límpida. Qual é a principal vantagem do cateterismo vesical em comparação com a punção suprapúbica em lactentes menores de 6 meses?',
    A: 'Menor dependência de repleção vesical prévia volumosa no momento do procedimento e maior taxa de sucesso na primeira tentativa.',
    B: 'Ausência total de risco de contaminação bacteriana pela flora uretral distal.',
    C: 'Possibilidade de confirmação imediata da função de filtração glomerular renal.',
    D: 'Substituição definitiva da necessidade de urocultura quantitativa.',
    ans: 'A',
    comment: 'O cateterismo vesical de alívio é o método estéril mais amplamente utilizado em emergências pediátricas para lactentes que não controlam esfíncteres. Apresenta taxa de sucesso superior a 95% na primeira tentativa (mesmo com volumes vesicais pequenos), enquanto a punção suprapúbica sem guia ultrassonográfico tem taxa de sucesso inferior a 50% se a bexiga não estiver palpável ou com volume inferior a 10 mL.',
    expA: 'Correta. O cateterismo vesical tem alta taxa de sucesso prático e exige menor volume vesical acumulado em comparação à punção suprapúbica às cegas.',
    expB: 'Incorreta. Pode haver carreamento mínimo transitório de bactérias do meato uretral distal se a antissepsia for inadequada.',
    expC: 'Incorreta. A coleta não afere diretamente a taxa de filtração glomerular.',
    expD: 'Incorreta. A urocultura quantitativa continua sendo mandatória.',
  });

  q({
    id: 'ped-itu-003',
    subtopic: 'Métodos de coleta de urina',
    inst: 'ENARE',
    year: 2024,
    statement: 'Lactente masculino de 2 meses de vida, com suspeita de pielonefrite aguda febril, apresenta fimose fisiológica acentuada com meato uretral puntiforme, impossibilitando a cateterização vesical. A bexiga encontra-se palpável a 2 cm acima da sínfise púbica. O pediatra opta por realizar punção suprapúbica (PSP). Qual marco anatômico e técnica de antissepsia são recomendados para a execução segura da PSP?',
    A: 'Punção realizada cerca de 1 a 2 cm acima da sínfise púbica na linha média, com agulha perpendicular de calibre fino (22 a 25G) aspirando continuamente.',
    B: 'Punção realizada 5 cm acima da cicatriz umbilical direcionada obliquamente para a fossa ilíaca direita.',
    C: 'Punção transretal profunda guiada por toque bimanual digital sob anestesia geral.',
    D: 'Incisão suprapúbica cirúrgica aberta de 3 cm sob anestesia inalatória obrigatória.',
    ans: 'A',
    comment: 'A punção suprapúbica (PSP) é o método estéril definitivo (padrão-ouro) em lactentes, pois a bexiga no lactente é um órgão intra-abdominal e não intrapélvico. Quando a bexiga está cheia (palpável ou confirmada por USG), punciona-se na linha média, 1 a 2 cm acima da sínfise púbica, com agulha 22G a 25G em ângulo de 90° (ou ligeiramente cefálico-caudal de 10-20°), aspirando até a saída de urina.',
    expA: 'Correta. 1 a 2 cm acima da sínfise púbica na linha média em ângulo perpendicular aspirando urina.',
    expB: 'Incorreta. Acima da cicatriz umbilical puncionaria alças intestinais ou vasos mesentéricos.',
    expC: 'Incorreta. A via transretal é contaminada e provocaria peritonite bacteriana maciça.',
    expD: 'Incorreta. A PSP é uma punção percutânea com agulha fina, não uma cirurgia aberta.',
  });

  q({
    id: 'ped-itu-004',
    subtopic: 'Métodos de coleta de urina',
    inst: 'FMRP-USP',
    year: 2024,
    statement: 'Menina de 5 anos, previamente hígida e com controle esfincteriano completo há 2 anos, queixa-se de disúria intensa, polaciúria e dor suprapúbica há 24 horas. Está afebril. Qual é o método de coleta de urina de primeira escolha e quais orientações de higiene devem ser fornecidas à mãe?',
    A: 'Jato médio espontâneo com higienização prévia da genitália externa com água e sabonete, afastamento dos grandes lábios e descarte da primeira porção da micção.',
    B: 'Punção suprapúbica obrigatória para evitar contaminação vulvar.',
    C: 'Cateterismo vesical com sonda de Folley de demora por 24 horas.',
    D: 'Coleta com saco coletor adesivo após banho de imersão de 30 minutos.',
    ans: 'A',
    comment: 'Em crianças com continência urinária adquirida (controle esfincteriano), o método de escolha é o Jato Médio espontâneo. Recomenda-se higiene perineal cuidadosa com água e sabão neutro (ou gaze úmida), separação dos grandes lábios, descarte do primeiro jato urinário (que lava a uretra distal) e coleta do jato intermediário em frasco estéril.',
    expA: 'Correta. Jato médio espontâneo com higiene adequada e separação dos lábios é o padrão para crianças continentes.',
    expB: 'Incorreta. Punção suprapúbica é procedimento invasivo desnecessário em crianças com controle esfincteriano.',
    expC: 'Incorreta. Cateterismo de demora gera trauma e risco de infecção associada a dispositivo.',
    expD: 'Incorreta. Saco coletor é proscrito para crianças com controle esfincteriano.',
  });

  q({
    id: 'ped-itu-005',
    subtopic: 'Métodos de coleta de urina',
    inst: 'SCMSP',
    year: 2024,
    statement: 'Lactente masculino de 8 meses sem controle esfincteriano chega com febre sem sinais localizatórios. A equipe de enfermagem colocou saco coletor adesivo às 08h da manhã. Às 11h30 (3 horas e meia depois), a mãe avisa que a criança finalmente urinou no saco. O médico deve orientar qual conduta em relação a essa amostra?',
    A: 'Descartar a amostra e não enviar para urocultura, pois sacos coletores mantidos por mais de 30 a 60 minutos apresentam proliferação bacteriana exuberante da pele e fezes, invalidando qualquer resultado microbiológico.',
    B: 'Enviar a amostra imediatamente, pois o tempo de permanência do saco plástico não interfere na flora bacteriana.',
    C: 'Adicionar álcool a 70% na bolsa plástica antes de enviar ao laboratório para matar os contaminantes de pele.',
    D: 'Iniciar antibioticoterapia profilática e enviar o saco para teste de biologia molecular.',
    ans: 'A',
    comment: 'Se a criança não urinar em 30 a 60 minutos após a aposição do saco coletor adesivo, este deve ser retirado, nova antissepsia realizada e outro saco afixado. Bolsas mantidas por mais de 1 hora funcionam como estufas de cultura para bactérias comensais da pele e flora fecal perineal, tornando a urocultura 100% contaminada e clinicamente inútil.',
    expA: 'Correta. Bolsas adesivas mantidas por mais de 30 a 60 minutos proliferam bactérias da pele e devem ser descartadas.',
    expB: 'Incorreta. O calor corporal e o tempo prolongado causam multiplicação maciça de contaminantes cutâneos.',
    expC: 'Incorreta. O álcool esterilizaria a urina e destruiria qualquer patógeno verdadeiro, gerando falso-negativo.',
    expD: 'Incorreta. Não se inicia antibiótico nem se valida amostra comprovadamente inadequada.',
  });

  q({
    id: 'ped-itu-006',
    subtopic: 'Métodos de coleta de urina',
    inst: 'UERJ',
    year: 2023,
    statement: 'Recém-nascido a termo com 14 dias de vida apresenta febre de 38,5 °C, hipoatividade e sucção débil ao seio materno. Qual é o método de coleta de urina para EAS e urocultura preconizado pelas diretrizes da Sociedade Brasileira de Pediatria e Academia Americana de Pediatria no período neonatal?',
    A: 'Cateterismo vesical estéril ou Punção suprapúbica; o saco coletor adesivo é expressamente contraindicado para diagnóstico de ITU no neonato.',
    B: 'Saco coletor adesivo trocado a cada 12 horas com dosagem de proteína C reativa.',
    C: 'Espremedura direta de fralda descartável com seringa estéril.',
    D: 'Coleta em comadre hospitalar desinfetada com hipoclorito.',
    ans: 'A',
    comment: 'No período neonatal (< 28 dias), qualquer ITU deve ser tratada como sepse bacteriana neonatal tardia e potencial pielonefrite com risco de bacteriemia. Por isso, a coleta de urina exige método asséptico seguro: Cateterismo vesical ou Punção suprapúbica. O saco coletor é proscrito no neonato, pois além de atrasar o diagnóstico com falsos positivos, a infecção verdadeira exige isolamento preciso para guiar terapia parenteral.',
    expA: 'Correta. No neonato, apenas métodos estéreis diretos (cateterismo ou PSP) são aceitos para definir conduta.',
    expB: 'Incorreta. O saco coletor é contraindicado no neonato febril.',
    expC: 'Incorreta. Espremer fraldas é uma prática errônea com 100% de contaminação e perda de elementos figurados.',
    expD: 'Incorreta. Comadres não são recipientes estéreis adequados para urocultura.',
  });

  q({
    id: 'ped-itu-007',
    subtopic: 'Métodos de coleta de urina',
    inst: 'IAMSPE',
    year: 2024,
    statement: 'Em um lactente de 5 meses no qual foi realizada punção suprapúbica com saída de 10 mL de urina límpida, qual o valor de corte de unidades formadoras de colônias por mililitro (UFC/mL) na urocultura que define bacteriúria significativa e confirma o diagnóstico de ITU?',
    A: 'Qualquer crescimento bacteriano de um único uropatógeno Gram-negativo (ex: ≥ 1 UFC/mL ou > 1.000 UFC/mL em algumas diretrizes).',
    B: 'Apenas se houver mais de 100.000 UFC/mL associado a nitrito fortemente positivo.',
    C: 'Exclusivamente se isoladas três bactérias diferentes com contagem superior a 50.000 UFC/mL cada.',
    D: 'Apenas se houver contagem maior que 1.000.000 UFC/mL e glicose urinária elevada.',
    ans: 'A',
    comment: 'Como a urina no interior da bexiga é fisiologicamente estéril e a agulha da punção suprapúbica não passa pela uretra nem tem contato com a flora da pele genital, o achado de QUALQUER número de colônias (≥ 1 UFC/mL de bacilo Gram-negativo ou > 1.000 UFC/mL para cocos Gram-positivos) em amostra monomicrobiana é diagnóstico definitivo de infecção do trato urinário.',
    expA: 'Correta. Na punção suprapúbica, qualquer crescimento bacteriano de patógeno típico confirma ITU.',
    expB: 'Incorreta. O corte de 100.000 UFC/mL é para jato médio ou saco coletor histórico.',
    expC: 'Incorreta. Crescimento polimicrobiano indica contaminação acidental por punção de alça intestinal.',
    expD: 'Incorreta. Contagem de 1 milhão é desnecessariamente restritiva e geraria subdiagnóstico grave.',
  });

  q({
    id: 'ped-itu-008',
    subtopic: 'Métodos de coleta de urina',
    inst: 'UFRJ',
    year: 2023,
    statement: 'Menino de 9 anos, sem comorbidades prévias, comparece ao ambulatório com queixa de disúria e urina turva há 2 dias. É realizada coleta de urina por jato médio. A mãe pergunta se a criança pode urinar a qualquer hora do dia ou se é obrigatória a primeira urina da manhã. Qual é a recomendação correta?',
    A: 'A urina com retenção vesical prévia de pelo menos 2 a 4 horas (ou a primeira da manhã) é preferível porque permite tempo adequado para as bactérias desdobrarem os nitratos em nitritos e acumularem leucócitos.',
    B: 'Deve-se forçar a ingesta imediata de 2 litros de água para que a criança urine nos próximos 5 minutos.',
    C: 'A urina deve ser colhida somente após cateterismo uretral de urgência.',
    D: 'A amostra da tarde é inválida porque o hormônio antidiurético inibe o crescimento de E. coli.',
    ans: 'A',
    comment: 'Para a pesquisa de nitrito e análise citológica fidedigna no EAS/urina tipo 1, a urina deve ter permanecido retida na bexiga por pelo menos 2 a 4 horas (ou a primeira urina da manhã). O teste do nitrito baseia-se na enzima nitrato-redutase bacteriana, que requer tempo de incubação na bexiga para converter o nitrato alimentar em nitrito. Forçar ingesta hídrica excessiva dilui a urina e causa falsos-negativos para leucocitúria e bacteriúria.',
    expA: 'Correta. Retenção vesical de 2 a 4 horas otimiza a conversão de nitrito e concentração celular.',
    expB: 'Incorreta. Hiper-hidratação forçada dilui excessivamente a urina, mascarando leucocitúria e contagem de colônias.',
    expC: 'Incorreta. Criança de 9 anos continente coleta perfeitamente por jato médio espontâneo.',
    expD: 'Incorreta. O ADH não exerce efeito antimicrobiano sobre enterobactérias.',
  });

  q({
    id: 'ped-itu-009',
    subtopic: 'Métodos de coleta de urina',
    inst: 'SMS-SP',
    year: 2024,
    statement: 'Lactente de 11 meses feminina é submetida a sondagem vesical de alívio por febre persistente. A urocultura revela crescimento de 2.000 UFC/mL de Lactobacillus sp. e Corynebacterium sp. com EAS revelando 2 leucócitos por campo e nitrito negativo. Como esse resultado microbiológico deve ser interpretado?',
    A: 'Contaminação da amostra por flora comensal periuretral e perineal; não indica ITU e não requer tratamento antibiótico.',
    B: 'Pielonefrite atípica com indicação imediata de ceftriaxona venosa por 14 dias.',
    C: 'Infecção fúngica invasiva com necessidade urgente de anfotericina B.',
    D: 'Tuberculose urogenital congênita com indicação de esquema RIPE.',
    ans: 'A',
    comment: 'Lactobacillus e Corynebacterium são componentes normais da microbiota da pele e genitália externa. O crescimento polimicrobiano de bactérias não uropatogênicas em contagens baixas, associado a EAS estritamente normal (sem piúria), representa contaminação durante a passagem da sonda pelo vestíbulo vaginal. Não é ITU e não deve ser tratada com antibióticos.',
    expA: 'Correta. Bactérias comensais polimicrobianas sem leucocitúria representam contaminação de amostra.',
    expB: 'Incorreta. Não há qualquer evidência de pielonefrite; tratar geraria indução de resistência bacteriana.',
    expC: 'Incorreta. Não foram isolados fungos.',
    expD: 'Incorreta. O bacilo de Koch não cresce em cultura bacteriana comum de 24 horas.',
  });
}
