import { q } from './helper_itu.js';

export function loadSec11() {
  q({
    id: 'ped-itu-085',
    subtopic: 'Quimioprofilaxia de ITU',
    inst: 'USP-SP',
    year: 2024,
    statement: 'Qual é o princípio posológico e o melhor horário de administração da quimioprofilaxia antimicrobiana contínua em crianças com indicação formal de prevenção de ITU de repetição?',
    A: 'Utilização de aproximadamente 1/4 a 1/3 da dose terapêutica diária habitual, administrada em dose ÚNICA diária preferencialmente à NOITE (ao deitar), período em que o intervalo miccional é mais prolongado e o antibiótico permanece concentrado na bexiga por várias horas.',
    B: 'Dose máxima terapêutica dobrada administrada a cada 4 horas ininterruptamente por 2 anos.',
    C: 'Infusão intravenosa semanal contínua sob regime de internação domiciliar.',
    D: 'Administração exclusiva pela manhã em jejum associada a laxante diário.',
    ans: 'A',
    comment: 'A quimioprofilaxia antimicrobiana visa manter níveis bactericidas mínimos na urina vesical sem provocar toxicidade sistêmica nem suprimir a flora bacteriana intestinal normal. Utiliza-se 1/3 a 1/4 da dose diária de tratamento em tomada única à noite. O horário noturno ao deitar é estratégico porque a bexiga permanece cheia por 8 a 10 horas de sono, permitindo que o fármaco atue exatamente durante a estase fisiológica noturna.',
    expA: 'Correta. 1/4 a 1/3 da dose terapêutica em dose única noturna ao deitar é o regime padrão.',
    expB: 'Incorreta. Dose dobrada causaria toxicidade grave e rápida indução de resistência bacteriana.',
    expC: 'Incorreta. A profilaxia é oral ambulatorial, não intravenosa invasiva de internação.',
    expD: 'Incorreta. A tomada noturna é muito mais eficaz que a matinal devido ao tempo de estase vesical no sono.',
  });

  q({
    id: 'ped-itu-086',
    subtopic: 'Quimioprofilaxia de ITU',
    inst: 'UNICAMP',
    year: 2024,
    statement: 'Lactente de 25 dias de vida com diagnóstico pré-natal de hidronefrose bilateral importante aguarda investigação anatômica com UCM. Diante da necessidade de iniciar quimioprofilaxia antimicrobiana nessa faixa etária (< 2 meses de vida), qual é o antimicrobiano oral de escolha?',
    A: 'Cefalexina por via oral (10 a 25 mg/kg/dia em dose única noturna) ou Amoxicilina.',
    B: 'Nitrofurantoína em suspensão oral contínua.',
    C: 'Sulfametoxazol-Trimetoprima em dose cheia.',
    D: 'Ciprofloxacino oral associado a doxiciclina.',
    ans: 'A',
    comment: 'Em recém-nascidos e lactentes com MENOS de 2 meses de vida, as opções profiláticas padrão são a Cefalexina (cefalosporina de 1ª geração em dose profilática de 10 a 25 mg/kg/dia à noite) ou a Amoxicilina. A Nitrofurantoína e o Sulfametoxazol-Trimetoprima são formalmente contraindicados abaixo dos 2 meses de idade devido ao risco de reações adversas metabólicas e hematológicas potencialmente fatais.',
    expA: 'Correta. Cefalexina (ou amoxicilina) é a droga de escolha para quimioprofilaxia em menores de 2 meses.',
    expB: 'Incorreta. Nitrofurantoína é contraindicada em menores de 1-2 meses pelo risco de anemia hemolítica.',
    expC: 'Incorreta. SMX-TMP é contraindicado em menores de 2 meses pelo risco de kernicterus.',
    expD: 'Incorreta. Quinolonas e tetraciclinas são contraindicadas na rotina profilática neonatal.',
  });

  q({
    id: 'ped-itu-087',
    subtopic: 'Quimioprofilaxia de ITU',
    inst: 'ENARE',
    year: 2024,
    statement: 'Por qual razão farmacológica a NITROFURANTOÍNA é expressamente contraindicada para profilaxia ou tratamento de infecções urinárias em lactentes menores de 1 a 2 meses de vida?',
    A: 'Devido à imaturidade dos sistemas enzimáticos eritrocitários do neonato (em especial o sistema da glutationa e G6PD), o que predispõe à ocorrência de Anemia Hemolítica aguda grave induzida por estresse oxidativo.',
    B: 'Risco de necrose fulminante do timo mediastinal com imunodeficiência combinada.',
    C: 'Indução imediata de fechamento das suturas cranianas gerando cranioestenose universal.',
    D: 'Capacidade de causar esclerodermia sistêmica congênita irreversível.',
    ans: 'A',
    comment: 'Nos primeiros meses de vida, as hemácias dos neonatos apresentam instabilidade da glutationa e níveis imaturos de enzimas antioxidantes. A nitrofurantoína gera metabólitos reativos e estresse oxidativo que precipitam hemólise intravascular e meta-hemoglobinemia (anemia hemolítica grave), contraindicando seu uso estrito em menores de 1 a 2 meses de idade.',
    expA: 'Correta. Imaturidade dos sistemas eritrocitários antioxidantes com risco de anemia hemolítica grave.',
    expB: 'Incorreta. Não induz necrose tímica.',
    expC: 'Incorreta. Não interfere na ossificação das suturas cranianas.',
    expD: 'Incorreta. Não tem correlação com esclerodermia.',
  });

  q({
    id: 'ped-itu-088',
    subtopic: 'Quimioprofilaxia de ITU',
    inst: 'FMRP-USP',
    year: 2024,
    statement: 'Por que o SULFAMETOXAZOL-TRIMETOPRIMA (SMX-TMP) é contraindicado no período neonatal e nos primeiros 2 meses de vida para quimioprofilaxia de ITU?',
    A: 'Porque as sulfas competem com a bilirrubina não conjugada pelos sítios de ligação na albumina sérica, deslocando a fração livre de bilirrubina e aumentando o risco de Encefalopatia Bilirrubínica (Kernicterus), além da imaturidade hepática de glucuronidação neonatal.',
    B: 'Porque a droga bloqueia irreversivelmente a absorção intestinal de oxigênio gasoso.',
    C: 'Devido ao risco de alopecia total permanente em 100% dos recém-nascidos expostos.',
    D: 'Porque o trimetoprima provoca fibrose pulmonar cística congênita.',
    ans: 'A',
    comment: 'O Sulfametoxazol desloca competitivamente a bilirrubina indireta dos sítios de ligação com a albumina plasmática. No neonato, cuja barreira hematoencefálica ainda é muito permeável, a elevação da bilirrubina livre circulante facilita sua impregnação nos núcleos da base do cérebro, desencadeando Kernicterus. Por essa razão, sulfas são rigorosamente contraindicadas em menores de 6 a 8 semanas (2 meses).',
    expA: 'Correta. O deslocamento da bilirrubina da albumina eleva a bilirrubina livre e o risco de kernicterus.',
    expB: 'Incorreta. A absorção de oxigênio é pulmonar e não intestinal.',
    expC: 'Incorreta. Não causa alopecia universal congênita.',
    expD: 'Incorreta. Trimetoprima atua na di-hidrofolato redutase bacteriana, sem relação com fibrose cística.',
  });

  q({
    id: 'ped-itu-089',
    subtopic: 'Quimioprofilaxia de ITU',
    inst: 'SCMSP',
    year: 2024,
    statement: 'Lactente de 7 meses, feminina, com diagnóstico confirmado de Refluxo Vesicoureteral bilateral Grau IV, necessita de quimioprofilaxia antimicrobiana contínua. Quais são as duas opções de primeira linha preconizadas pelas diretrizes internacionais e nacionais para crianças maiores de 2 meses?',
    A: 'Nitrofurantoína (1 a 2 mg/kg/dia em dose única noturna) OU Sulfametoxazol-Trimetoprima (2 mg/kg/dia de TMP em dose única noturna).',
    B: 'Ciprofloxacino intravenoso semanal OU Vancomicina oral contínua.',
    C: 'Penicilina G Benzatina a cada 15 dias OU Amicacina oral diária.',
    D: 'Metronidazol oral associado a aciclovir profilático por 1 ano.',
    ans: 'A',
    comment: 'Para crianças acima de 2 meses de vida com indicação formal de quimioprofilaxia (como RVU dilatante de alto grau), as drogas padrão-ouro de primeira linha são a Nitrofurantoína (1 a 2 mg/kg/dia em dose única noturna) ou o Sulfametoxazol-Trimetoprima (2 mg/kg/dia com base no componente trimetoprima em dose noturna). A nitrofurantoína é particularmente vantajosa por não alterar a microbiota bacteriana fecal.',
    expA: 'Correta. Nitrofurantoína (1-2 mg/kg/dia) ou SMX-TMP (2 mg/kg/dia de TMP) em dose única noturna.',
    expB: 'Incorreta. Ciprofloxacino e vancomicina não são drogas de primeira linha para profilaxia ambulatorial.',
    expC: 'Incorreta. Penicilina Benzatina é para febre reumática e amicacina não é absorvida por via oral.',
    expD: 'Incorreta. Metronidazol e aciclovir não cobrem uropatógenos entéricos Gram-negativos.',
  });

  q({
    id: 'ped-itu-090',
    subtopic: 'Quimioprofilaxia de ITU',
    inst: 'UERJ',
    year: 2023,
    statement: 'Qual das seguintes crianças apresenta indicação FORMAL estabelecida para o início de quimioprofilaxia antimicrobiana contínua segundo os consensos da Sociedade Brasileira de Pediatria e da Academia Americana de Pediatria?',
    A: 'Lactente de 4 meses com diagnóstico comprovado de Refluxo Vesicoureteral Grau IV à UCM enquanto aguarda avaliação cirúrgica especializada.',
    B: 'Menina de 6 anos que apresentou um único episódio de cistite afebril resolvida com 3 dias de nitrofurantoína.',
    C: 'Lactente de 1 ano com bacteriúria assintomática comprovada em urina de jato médio sem qualquer cicatriz.',
    D: 'Recém-nascido a termo com ultrassonografia pré e pós-natal rigorosamente normais.',
    ans: 'A',
    comment: 'As indicações formais aceitas para quimioprofilaxia incluem: 1) Refluxo Vesicoureteral de alto grau (graus III, IV e V), especialmente em menores de 1 ano; 2) Crianças com episódios frequentes de ITU febril de repetição (≥ 2 a 3 episódios em 6 a 12 meses); 3) Presença de uropatias obstrutivas em programação de cirurgia; 4) Período pós-operatório imediato de reconstruções urológicas ou cistoscopia com manipulação. Não está indicada após episódio único de cistite nem em bacteriúria assintomática.',
    expA: 'Correta. RVU de alto grau (grau IV) em lactente é indicação formal de quimioprofilaxia contínua.',
    expB: 'Incorreta. Primeiro episódio de cistite baixa em escolar não tem qualquer indicação de profilaxia.',
    expC: 'Incorreta. Bacteriúria assintomática não deve receber profilaxia.',
    expD: 'Incorreta. Neonato saudável com exames normais não requer quimioprofilaxia.',
  });

  q({
    id: 'ped-itu-091',
    subtopic: 'Quimioprofilaxia de ITU',
    inst: 'IAMSPE',
    year: 2024,
    statement: 'Por que os grandes ensaios clínicos randomizados multicêntricos (como o estudo RIVUR e PRIVENT) e as diretrizes recentes da AAP NÃO recomendam mais a quimioprofilaxia antimicrobiana de rotina para crianças após o primeiro episódio de ITU febril quando não há Refluxo Vesicoureteral ou quando há apenas RVU de baixo grau (graus I e II)?',
    A: 'Porque a profilaxia contínua nesses casos não demonstrou redução significativa na incidência de cicatrizes renais permanentes e eleva substancialmente o risco de infecções futuras por cepas de Escherichia coli multirresistentes.',
    B: 'Porque os antibióticos orais causam fechamento precoce das cartilagens de crescimento.',
    C: 'Porque o primeiro episódio de ITU imuniza a criança contra qualquer uropatógeno bacteriano.',
    D: 'Porque a profilaxia causa atrofia congênita da bexiga em mais de 70% das crianças.',
    ans: 'A',
    comment: 'Evidências robustas demonstraram que o uso indiscriminado de antibióticos profiláticos contínuos em crianças sem refluxo ou com refluxo leve não reduz a formação de novas cicatrizes renais e seleciona bactérias multirresistentes da microbiota fecal. Quando essas crianças desenvolvem uma nova infecção, ela é causada por bactérias resistentes a cefalosporinas e ampicilinas, com maior morbidade.',
    expA: 'Correta. Ausência de benefício na prevenção de cicatrizes e indução de resistência bacteriana fecal.',
    expB: 'Incorreta. Antibióticos usuais de ITU não fecham cartilagens de crescimento.',
    expC: 'Incorreta. Não existe imunidade protetora esterilizante duradoura contra uropatógenos.',
    expD: 'Incorreta. A profilaxia não causa atrofia muscular vesical.',
  });

  q({
    id: 'ped-itu-092',
    subtopic: 'Quimioprofilaxia de ITU',
    inst: 'PUC-Campinas',
    year: 2024,
    statement: 'Menino de 4 anos em uso de quimioprofilaxia prolongada com Nitrofurantoína há 10 meses devido a RVU grau IV desenvolve tosse seca persistente, taquipneia aos esforços e febrícula vespertina. A ausculta pulmonar revela crepitações tele-inspiratórias bilaterais e o RX de tórax exibe infiltrado intersticial bibasilar difuso. Qual efeito adverso pulmonar raro da nitrofurantoína deve ser suspeitado e qual é a conduta imediata?',
    A: 'Pneumonite Intersticial induzida por Nitrofurantoína (toxicidade pulmonar por hipersensibilidade crônica); suspensão imediata da medicação e troca da profilaxia.',
    B: 'Asma brônquica alérgica induzida por esforço físico; aumentar a dose da nitrofurantoína para controlar a inflamação.',
    C: 'Metástase pulmonar difusa de rabdomiossarcoma de bexiga.',
    D: 'Tuberculose miliar primária adquirida por transmissão hídrica.',
    ans: 'A',
    comment: 'A Nitrofurantoína em uso prolongado (meses a anos) pode causar reações adversas pulmonares raras, que variam de reações agudas de hipersensibilidade (febre, tosse, dispneia e eosinofilia) a pneumonite intersticial crônica com fibrose pulmonar insidiosa. A suspeita clínica impõe a SUSPENSÃO IMEDIATA da droga, que geralmente leva à reversão completa dos sintomas.',
    expA: 'Correta. Pneumonite intersticial por nitrofurantoína exige suspensão imediata da droga e substituição.',
    expB: 'Incorreta. Aumentar a nitrofurantoína agravaria a lesão pulmonar com risco de fibrose permanente.',
    expC: 'Incorreta. O quadro clínico e radiológico é compatível com toxicidade medicamentosa pulmonar reversível.',
    expD: 'Incorreta. Não há história de contato com TB e o quadro coincide com uso prolongado de nitrofurantoína.',
  });
}
