import { q } from './helper_itu.js';

export function loadSec2() {
  q({
    id: 'ped-itu-010',
    subtopic: 'Critérios diagnósticos de ITU',
    inst: 'USP-SP',
    year: 2024,
    statement: 'Lactente feminina de 9 meses com febre de 39,2 °C há 3 dias é submetida a cateterismo vesical para investigação. O EAS revela leucocitúria de 85.000/mL (18 leucócitos/campo) e nitrito positivo. De acordo com as diretrizes da Academia Americana de Pediatria (AAP) e da Sociedade Brasileira de Pediatria (SBP), qual contagem de colônias de um único uropatógeno na urocultura colhida por cateterismo vesical confirma o diagnóstico de ITU em lactentes febris?',
    A: '≥ 50.000 UFC/mL (ou ≥ 10.000 UFC/mL associada a EAS francamente alterado com piúria).',
    B: 'Exatamente 1.000.000 UFC/mL sem necessidade de piúria no sedimento urinário.',
    C: 'Apenas contagens superiores a 500.000 UFC/mL com presença de leveduras.',
    D: '≥ 100 UFC/mL exclusivamente se o paciente estiver afecioso e afebril.',
    ans: 'A',
    comment: 'Pelo consenso da AAP (American Academy of Pediatrics) e diretrizes da SBP, em amostras obtidas por cateterismo vesical de alívio, a presença de ≥ 50.000 UFC/mL de um único patógeno bacteriano confirma a ITU. Diretrizes europeias e da SBP admitem ainda que contagens entre 10.000 e 50.000 UFC/mL são diagnósticas quando acompanhadas de manifestações clínicas e piúria inequívoca no EAS.',
    expA: 'Correta. ≥ 50.000 UFC/mL (ou ≥ 10.000 UFC/mL com piúria evidente) no cateterismo vesical define ITU confirmada.',
    expB: 'Incorreta. O corte de 1.000.000 UFC/mL é excessivamente alto e atrasaria o tratamento de lactentes.',
    expC: 'Incorreta. Leveduras não são uropatógenos bacterianos típicos em lactentes hígidos comunitários.',
    expD: 'Incorreta. 100 UFC/mL em cateterismo é insuficiente para afastar contaminação incidental.',
  });

  q({
    id: 'ped-itu-011',
    subtopic: 'Critérios diagnósticos de ITU',
    inst: 'UNICAMP',
    year: 2024,
    statement: 'Menina de 6 anos com disúria, polaciúria e urgência miccional colheu urina por jato médio após higienização cuidadosa. O EAS revelou 60 leucócitos por campo, hemácias 10/campo e nitrito positivo. A urocultura isolou Escherichia coli. Qual ponto de corte clássico de unidades formadoras de colônias por mililitro (UFC/mL) colhidas por jato médio define bacteriúria significativa segundo os critérios de Kass?',
    A: '≥ 100.000 UFC/mL.',
    B: '≥ 10.000 UFC/mL em amostra mista polimicrobiana.',
    C: 'Qualquer contagem acima de 500 UFC/mL independentemente de sintomas.',
    D: 'Apenas contagens superiores a 1.000.000 UFC/mL.',
    ans: 'A',
    comment: 'O critério clássico de Kass estabelece que, na coleta de urina espontânea por jato médio em crianças continentes com sintomas urinários baixos, o isolamento de ≥ 100.000 UFC/mL (10^5 UFC/mL) de um único uropatógeno bacteriano define bacteriúria significativa e confirma o diagnóstico de ITU com 95% de probabilidade de infecção verdadeira.',
    expA: 'Correta. O corte clássico para jato médio é de ≥ 100.000 UFC/mL de um único uropatógeno.',
    expB: 'Incorreta. Amostras polimicrobianas em jato médio indicam contaminação pela flora vulvovaginal.',
    expC: 'Incorreta. 500 UFC/mL em jato médio não é considerado bacteriúria significativa.',
    expD: 'Incorreta. 1 milhão de colônias não é o valor de corte habitual.',
  });

  q({
    id: 'ped-itu-012',
    subtopic: 'Critérios diagnósticos de ITU',
    inst: 'ENARE',
    year: 2024,
    statement: 'Na análise da fita reagente (dipstick urinário) durante a triagem de um lactente febril no pronto-socorro, observa-se teste da esterase leucocitária positivo e teste do nitrito negativo. Qual das seguintes justificativas explica CORRETAMENTE por que o teste do nitrito pode ser falso-negativo na presença de infecção urinária ativa na infância?',
    A: 'Infecção causada por uropatógenos que não produzem a enzima nitrato-redutase (como Enterococcus faecalis e Staphylococcus saprophyticus) ou esvaziamento vesical frequente do lactente sem tempo hábil (mínimo de 4 horas) para a conversão de nitrato em nitrito.',
    B: 'Presença excessiva de vitamina D na urina que inibe a reação enzimática cromogênica.',
    C: 'Uso concomitante de paracetamol que oxida o nitrito em gás nitrogênio livre.',
    D: 'O teste do nitrito só é ativado na presença de glicosúria maciça.',
    ans: 'A',
    comment: 'O teste do nitrito tem altíssima especificidade (> 98%), mas sensibilidade moderada (50-60%). As principais causas de falso-negativo são: 1) Lactentes esvaziam a bexiga com frequência (a cada 30-60 minutos), impedindo que as bactérias permaneçam tempo suficiente (mínimo de 4 horas) para metabolizar o nitrato da dieta em nitrito; 2) Bactérias Gram-positivas (Enterococcus, Staphylococcus) e Pseudomonas aeruginosa NÃO produzem nitrato-redutase; 3) Dieta com baixo teor de nitratos vegetais.',
    expA: 'Correta. Esvaziamento vesical precoce e patógenos não produtores de nitrato-redutase geram nitrito falso-negativo.',
    expB: 'Incorreta. Vitamina C (ácido ascórbico) pode interferir, mas não a vitamina D.',
    expC: 'Incorreta. Paracetamol não metaboliza nitritos urinários em gás nitrogênio.',
    expD: 'Incorreta. A reação do nitrito independe de glicose urinária.',
  });

  q({
    id: 'ped-itu-013',
    subtopic: 'Critérios diagnósticos de ITU',
    inst: 'FMRP-USP',
    year: 2024,
    statement: 'Menina de 8 anos realiza exames admissionais para atividade física escolar. O EAS de rotina mostra densidade 1.020, pH 6,0, ausência de leucócitos (leucócitos 2/campo) e nitrito negativo. A urocultura de jato médio solicitada inadvertidamente acusa crescimento de 100.000 UFC/mL de Escherichia coli com perfil multissensível. A paciente está absolutamente assintomática, com bom ganho ponderal e sem queixas urinárias. Qual é a conduta preconizada para este achado de Bacteriúria Assintomática?',
    A: 'Não prescrever antibioticoterapia e tranquilizar os familiares, pois o tratamento de bacteriúria assintomática na infância não previne pielonefrite e elimina cepas colonizadoras de baixa virulência, predispondo à recolonização por cepas mais agressivas.',
    B: 'Internar imediatamente para ceftriaxona intravenosa por 14 dias para erradicar o foco.',
    C: 'Prescrever ciprofloxacino oral em dose dobrada por 21 dias associado a sulfametoxazol.',
    D: 'Indicar nefrectomia parcial profilática para evitar hipertensão arterial.',
    ans: 'A',
    comment: 'Bacteriúria Assintomática (BA) é a colonização da urina por bactérias sem resposta inflamatória tecidual (sem piúria) e sem sintomas sistêmicos ou locais. Em crianças sem alterações urológicas graves, as evidências científicas comprovam que a BA é inofensiva e seu tratamento com antibióticos NÃO é recomendado, pois destrói cepas comensais de baixa virulência que competem contra cepas uropatogênicas virulentas, além de induzir resistência bacteriana.',
    expA: 'Correta. Não tratar bacteriúria assintomática em crianças saudáveis é a recomendação universal.',
    expB: 'Incorreta. Internação e ceftriaxona seriam conduta iatrogênica e prejudicial.',
    expC: 'Incorreta. Ciprofloxacino é desnecessário e contraindicado sem indicação formal estrita.',
    expD: 'Incorreta. Cirurgia mutiladora completamente descabida.',
  });

  q({
    id: 'ped-itu-014',
    subtopic: 'Critérios diagnósticos de ITU',
    inst: 'SCMSP',
    year: 2024,
    statement: 'Menino de 3 anos com febre alta há 4 dias e hiperemia conjuntival bilateral sem secreção apresenta EAS com piúria maciça (> 100 leucócitos/campo) e nitrito negativo. A urocultura colhida por cateterismo vesical antes de qualquer antibiótico resulta ESTÉRIL (sem crescimento bacteriano após 72 horas). Dentre os seguintes diagnósticos pediátricos, qual patologia inflamatória sistêmica cursa classicamente com piúria estéril por uretrite estéril?',
    A: 'Doença de Kawasaki.',
    B: 'Insuficiência adrenal primária por hiperplasia congênita.',
    C: 'Deficiência congênita de lactase intestinal.',
    D: 'Anemia ferropriva refratária.',
    ans: 'A',
    comment: 'A piúria estéril (leucocitúria importante com urocultura negativa em paciente que não usou antibióticos prévios) é uma manifestação clássica da Doença de Kawasaki, decorrente de uretrite descamativa estéril por vasculite. Outras causas de piúria estéril incluem: infecções virais (adenovírus), tuberculose urinária, apendicite aguda ou peritonite contígua à bexiga, nefropatias tubulointersticiais e uso prévio recente de antimicrobianos.',
    expA: 'Correta. A Doença de Kawasaki cursa com piúria estéril típica por uretrite inflamatória.',
    expB: 'Incorreta. Hiperplasia adrenal cursa com desidratação perdedora de sal e ambiguidade genital, não piúria estéril.',
    expC: 'Incorreta. Deficiência de lactase cursa com diarreia osmótica ácida.',
    expD: 'Incorreta. Anemia por privação de ferro não induz infiltrado leucocitário na urina.',
  });

  q({
    id: 'ped-itu-015',
    subtopic: 'Critérios diagnósticos de ITU',
    inst: 'UERJ',
    year: 2023,
    statement: 'Um lactente de 6 meses é avaliado por ITU febril. A urocultura de cateterismo vesical isola Proteus mirabilis com contagem de 80.000 UFC/mL. O EAS revela pH urinário persistentemente alcalino (pH 8,0) e presença de cristais de fosfato triplo (estruvita). Qual propriedade enzimática característica do Proteus mirabilis é responsável por essa alteração do pH e predispõe à litíase urinária na infância?',
    A: 'Produção da enzima Urease, que hidrolisa a ureia em amônia e dióxido de carbono, alcalinizando a urina e precipitando cálculos de estruvita (cálculos coraliformes).',
    B: 'Secreção de betalactamase de espectro ampliado que degrada citrato urinário em oxalato.',
    C: 'Síntese de lipase ácida que saponifica as gorduras dos túbulos coletores renais.',
    D: 'Liberação de toxina eritrogênica que destrói a camada de glicosaminoglicanos da bexiga.',
    ans: 'A',
    comment: 'O Proteus mirabilis (e outras bactérias como Klebsiella e Morganella) produz Urease, uma enzima que cliva a ureia gerando amônia (NH3) e elevando o pH urinário (> 7,5 a 8,0). Em meio alcalino e rico em amônia, ocorre a precipitação de fosfato amônio-magnesiano e carbonato-apatita, formando cálculos de estruvita (que podem assumir configuração coraliforme ocupando a pelve renal).',
    expA: 'Correta. A produção de urease eleva o pH urinário e precipita cristais de estruvita, predispondo a cálculos coraliformes.',
    expB: 'Incorreta. ESBL é mecanismo de resistência a betalactâmicos, sem efeito no citrato.',
    expC: 'Incorreta. Proteus não secreta lipases calcificantes tubulares.',
    expD: 'Incorreta. Toxina eritrogênica é produzida pelo Streptococcus pyogenes.',
  });

  q({
    id: 'ped-itu-016',
    subtopic: 'Critérios diagnósticos de ITU',
    inst: 'IAMSPE',
    year: 2024,
    statement: 'Qual é o microrganismo etiológico responsável por mais de 80 a 90% dos casos de infecção do trato urinário comunitária na infância tanto em lactentes quanto em crianças maiores?',
    A: 'Escherichia coli uropatogênica (UPEC).',
    B: 'Pseudomonas aeruginosa.',
    C: 'Streptococcus agalactiae (Streptococcus do grupo B).',
    D: 'Candida albicans.',
    ans: 'A',
    comment: 'A Escherichia coli uropatogênica (UPEC) é de longe o agente mais frequente em ITU comunitária pediátrica (responsável por 80 a 90% dos episódios). Possui fatores de virulência específicos como as fímbrias P (que se ligam aos receptores de digalactosídeo no epitélio uroepitelial renal promovendo ascensão) e fímbrias tipo 1 (aderência à bexiga). Outros agentes menos comuns incluem Klebsiella, Proteus, Enterobacter e Enterococcus.',
    expA: 'Correta. E. coli é o agente causador de 80-90% de todas as ITUs comunitárias pediátricas.',
    expB: 'Incorreta. Pseudomonas é patógeno nosocomial ou relacionado a manipulação cirúrgica/cateteres crônicos.',
    expC: 'Incorreta. EGB causa sepse/meningite neonatal precoce, raramente ITU comunitária isolada.',
    expD: 'Incorreta. Candida causa ITU hospitalar em imunossuprimidos ou uso prolongado de antibióticos de amplo espectro.',
  });

  q({
    id: 'ped-itu-017',
    subtopic: 'Critérios diagnósticos de ITU',
    inst: 'PUC-PR',
    year: 2024,
    statement: 'De acordo com a diretriz da Academia Americana de Pediatria (AAP), para o diagnóstico confiável de infecção do trato urinário em lactentes entre 2 e 24 meses de vida, exige-se a presença OBRIGATÓRIA de quais dois componentes diagnósticos simultâneos?',
    A: 'Evidência de piúria no sedimento urinário (leucocitúria > 5-10 leucócitos/campo ou teste positivo para esterase leucocitária/nitrito) E urocultura positiva com crescimento de ≥ 50.000 UFC/mL de um único patógeno colhida por cateterismo vesical ou punção suprapúbica.',
    B: 'Apenas urocultura positiva isolada com qualquer contagem, mesmo com EAS completamente normal e ausência de leucócitos.',
    C: 'Apenas febre alta isolada associada a PCR sérico acima de 100 mg/L sem necessidade de urocultura.',
    D: 'Visualização de cilindros granulosos na ausência de crescimento bacteriano.',
    ans: 'A',
    comment: 'A diretriz da AAP de 2011/2016 estipula categoricamente que, para evitar sobrediagnóstico e tratamento desnecessário de bacteriúria assintomática com contaminação, o diagnóstico de ITU em lactentes exige AMBOS: 1) Resposta inflamatória urinária documentada (piúria no EAS ≥ 10 leucócitos/mm³ ou esterase/nitrito positivos); E 2) Urocultura quantitativa positiva com ≥ 50.000 UFC/mL de um único uropatógeno em urina colhida adequadamente por cateter ou PSP.',
    expA: 'Correta. A exigência simultânea de piúria (inflamação) e urocultura ≥ 50.000 UFC/mL em método estéril é a definição formal da AAP.',
    expB: 'Incorreta. Urocultura positiva com EAS normal representa colonização/bacteriúria assintomática ou contaminação.',
    expC: 'Incorreta. PCR não substitui a confirmação microbiológica urinária.',
    expD: 'Incorreta. Cilindros granulosos são inespecíficos de lesão tubular e não fecham diagnóstico bacteriano.',
  });
}
