import { q } from './helper_itu.js';

export function loadSec3() {
  q({
    id: 'ped-itu-018',
    subtopic: 'Cistite vs Pielonefrite',
    inst: 'USP-SP',
    year: 2024,
    statement: 'Como se manifesta clinicamente a Infecção do Trato Urinário em lactentes menores de 1 a 2 anos em comparação com crianças em idade escolar?',
    A: 'No lactente, predomina a apresentação inespecífica e sistêmica (febre alta sem foco, irritabilidade, vômitos, recusa alimentar e baixo ganho ponderal); na criança maior, os sintomas são localizatórios do trato urinário inferior (disúria, polaciúria, urgência e dor suprapúbica).',
    B: 'No lactente, o sinal patognomônico é a queixa espontânea de disúria intensa e hematúria macroscópica em 100% dos casos.',
    C: 'A criança maior nunca apresenta febre, mesmo em casos de abscesso perirrenal grave.',
    D: 'O lactente sempre apresenta bexigoma doloroso e retenção urinária aguda com anúria total.',
    ans: 'A',
    comment: 'Quanto mais jovem a criança, mais inespecíficos e enganosos são os sintomas de ITU. Lactentes não expressam disúria verbalmente e costumam abrir o quadro com febre sem foco aparente, irritabilidade, perda ponderal, recusa alimentar e vômitos (sinais de ITU alta/pielonefrite). Já pré-escolares e escolares queixam-se de sintomas clássicos do trato urinário baixo (disúria, polaciúria, queimação miccional, enurese secundária e dor suprapúbica).',
    expA: 'Correta. Lactentes manifestam febre sem foco e sintomas sistêmicos inespecíficos, enquanto escolares expressam sintomas miccionais localizatórios.',
    expB: 'Incorreta. Lactentes não relatam disúria e hematúria franca é incomum.',
    expC: 'Incorreta. Pielonefrite e abscesso na criança maior causam febre alta com calafrios.',
    expD: 'Incorreta. A retenção aguda com anúria não é a regra na ITU simples do lactente.',
  });

  q({
    id: 'ped-itu-019',
    subtopic: 'Cistite vs Pielonefrite',
    inst: 'UNICAMP',
    year: 2024,
    statement: 'Qual achado microscópico específico no sedimento urinário (EAS/urina tipo 1) é patognomônico de acometimento inflamatório/infeccioso do parênquima renal (pielonefrite aguda), permitindo diferenciá-la categoricamente de uma cistite baixa isolada?',
    A: 'Cilindros leucocitários.',
    B: 'Cristais de oxalato de cálcio bi-hidratados.',
    C: 'Células epiteliais pavimentosas em abundância.',
    D: 'Hemácias isomórficas íntegras em pequena quantidade.',
    ans: 'A',
    comment: 'Os cilindros são estruturas formadas exclusivamente na luz dos túbulos contorcidos distais e ductos coletores renais, a partir da precipitação da mucoproteína de Tamm-Horsfall. A presença de Cilindros Leucocitários demonstra que os leucócitos infiltraram o parênquima renal tubular e foram moldados na luz tubular, sendo patognomônicos de nefropatia tubulointersticial/pielonefrite aguda e ausentes na cistite não complicada.',
    expA: 'Correta. Cilindros leucocitários comprovam origem parenquimatosa renal da infecção (pielonefrite).',
    expB: 'Incorreta. Cristais de oxalato refletem supersaturação de solutos na urina, comuns na desidratação.',
    expC: 'Incorreta. Células pavimentosas indicam descamação do meato e contaminação por secreção genital externa.',
    expD: 'Incorreta. Hemácias isomórficas podem surgir tanto na cistite hemorrágica quanto em litíase.',
  });

  q({
    id: 'ped-itu-020',
    subtopic: 'Cistite vs Pielonefrite',
    inst: 'ENARE',
    year: 2024,
    statement: 'Menino de 5 anos com febre de 39,5 °C com calafrios, vômitos e dor em flanco direito. Exames laboratoriais mostram Leucócitos de 22.000/mm³ com 12% de bastões, Proteína C Reativa (PCR) de 140 mg/L (VR < 5) e Procalcitonina de 3,8 ng/mL (VR < 0,5). EAS com piúria maciça e nitrito positivo. Em contrapartida, sua irmã de 7 anos apresenta apenas disúria e polaciúria sem febre, com PCR de 3 mg/L e hemograma normal. Como esses marcadores laboratoriais auxiliam na distinção clínica entre ITU alta e baixa?',
    A: 'A elevação acentuada de provas de fase aguda (PCR e procalcitonina) e leucocitose com desvio refletem invasão do parênquima renal com resposta inflamatória sistêmica na pielonefrite, enquanto a cistite restringe-se à mucosa vesical superficial sem ativação inflamatória sistêmica.',
    B: 'A procalcitonina eleva-se exclusivamente na cistite fúngica, mantendo-se normal na pielonefrite bacteriana.',
    C: 'A cistite não complicada cursa com leucocitose superior a 30.000/mm³ em virtude da alta vascularização do trígono vesical.',
    D: 'A PCR é sintetizada pelos podócitos glomerulares e excretada apenas na cistite aguda.',
    ans: 'A',
    comment: 'A pielonefrite aguda é uma infecção invasiva do parênquima renal rica em citocinas inflamatórias (IL-1, IL-6, TNF-alfa), gerando resposta de fase aguda sistêmica: leucocitose com neutrofilia e desvio à esquerda, além de elevação expressiva de PCR e Procalcitonina. Já a cistite aguda afeta apenas a camada urotelial da bexiga, sem gerar febre, leucocitose ou elevação significativa de PCR sérico.',
    expA: 'Correta. PCR e procalcitonina marcam infecção sistêmica/invasão tecidual parenquimatosa na pielonefrite.',
    expB: 'Incorreta. A procalcitonina é um marcador específico de infecções bacterianas invasivas.',
    expC: 'Incorreta. A cistite não causa leucocitose sistêmica exuberante.',
    expD: 'Incorreta. A PCR é sintetizada pelo fígado sob estímulo de IL-6, não pelos podócitos.',
  });

  q({
    id: 'ped-itu-021',
    subtopic: 'Cistite vs Pielonefrite',
    inst: 'FMRP-USP',
    year: 2024,
    statement: 'Qual é o nome da manobra semiológica propedêutica caracterizada pelo desencadeamento de dor aguda quando o examinador realiza a percussão com a borda ulnar da mão fechada sobre a loja renal posterior (ângulo costovertebral), típica de pielonefrite em crianças escolares e adolescentes?',
    A: 'Sinal de Giordano (punhopercussão lombar dolorosa).',
    B: 'Sinal de Blumberg (descompressão brusca dolorosa).',
    C: 'Sinal de Murphy (interrupção inspiratória súbita).',
    D: 'Sinal de Rovsing (dor na FID à palpação da FIE).',
    ans: 'A',
    comment: 'O Sinal de Giordano (ou punhopercussão lombar) é a manobra em que a percussão delicada com o punho fechado sobre o ângulo costovertebral desencadeia dor intensa, sinalizando distensão da cápsula renal secundária a processo inflamatório/infeccioso agudo do parênquima renal (pielonefrite aguda) ou litíase obstrutiva. O sinal de Blumberg aponta para peritonite, Murphy para colecistite e Rovsing para apendicite.',
    expA: 'Correta. O sinal de Giordano é a punhopercussão lombar positiva, marco da pielonefrite aguda.',
    expB: 'Incorreta. Blumberg é sinal de irritação peritoneal.',
    expC: 'Incorreta. Murphy indica colecistite aguda calculosa.',
    expD: 'Incorreta. Rovsing é sinal de apendicite aguda.',
  });

  q({
    id: 'ped-itu-022',
    subtopic: 'Cistite vs Pielonefrite',
    inst: 'SCMSP',
    year: 2024,
    statement: 'Por que a diferenciação entre Pielonefrite Aguda e Cistite é de crucial relevância prognóstica na infância a longo prazo?',
    A: 'Porque episódios repetidos de pielonefrite podem causar destruição focal do parênquima renal com formação de cicatrizes renais permanentes, predispondo a hipertensão arterial crônica, proteinúria e doença renal do estágio terminal.',
    B: 'Porque a cistite não tratada evolui invariavelmente para estenose de artéria renal congênita.',
    C: 'Porque a pielonefrite aguda é uma alteração autolimitada que nunca deixa qualquer lesão anatômica permanente.',
    D: 'Porque a cistite é a principal causa de raquitismo dependente de vitamina D tipo 1.',
    ans: 'A',
    comment: 'A grande preocupação com a ITU alta (pielonefrite) na infância reside no fato de que a reação inflamatória intersticial purulenta leva a isquemia e fibrose com perda de néfrons, gerando as temidas Cicatrizes Renais (nefropatia de refluxo). Crianças com cicatrizes renais bilaterais extensas têm risco elevado de desenvolver hipertensão arterial secundária, pré-eclâmpsia no futuro e insuficiência renal crônica. A cistite isolada não afeta o parênquima e não causa cicatrizes renais.',
    expA: 'Correta. Cicatrizes renais, hipertensão e doença renal crônica são sequelas diretas de pielonefrites.',
    expB: 'Incorreta. A cistite não causa estenose de artéria renal (que decorre de displasia fibromuscular ou Takayasu).',
    expC: 'Incorreta. Pielonefrite pode deixar cicatrizes anatômicas graves e irreversíveis.',
    expD: 'Incorreta. Cistite não altera o metabolismo mineral de vitamina D.',
  });

  q({
    id: 'ped-itu-023',
    subtopic: 'Cistite vs Pielonefrite',
    inst: 'UERJ',
    year: 2023,
    statement: 'Por qual razão farmacocinética fundamental o antimicrobiano NITROFURANTOÍNA é formalmente CONTRAINDICADO para o tratamento da Pielonefrite Aguda febril na infância, mesmo quando a urocultura acusa sensibilidade in vitro a essa droga?',
    A: 'Porque a nitrofurantoína atinge excelentes concentrações na luz da bexiga, mas apresenta níveis séricos e teciduais desprezíveis ou indetectáveis no parênquima renal.',
    B: 'Porque a droga induz necrose tubular aguda fulminante em mais de 90% dos pacientes com pielonefrite.',
    C: 'Porque a nitrofurantoína alcaliniza a urina, estimulando a multiplicação de Escherichia coli.',
    D: 'Porque ela só tem ação farmacológica contra vírus RNA envelopados.',
    ans: 'A',
    comment: 'A Nitrofurantoína é rapidamente absorvida no trato gastrointestinal e quase totalmente eliminada por filtração glomerular e secreção tubular diretamente na urina, alcançando níveis terapêuticos elevados na bexiga (ideal para CISTITE). No entanto, seus níveis séricos e penetração no tecido parenquimatoso renal são praticamente nulos. Tratar pielonefrite com nitrofurantoína equivale a não tratar a infecção renal, levando à persistência bacteriana, bacteriemia, sepse e formação de cicatrizes renais.',
    expA: 'Correta. Ausência de concentração tecidual e sérica no parênquima renal contraindica a nitrofurantoína na pielonefrite.',
    expB: 'Incorreta. Não induz necrose tubular em 90%; o problema é a falta de concentração tecidual renal.',
    expC: 'Incorreta. Ela não alcaliniza a urina.',
    expD: 'Incorreta. É um antibacteriano sintético com ação contra bactérias Gram-negativas e algumas Gram-positivas.',
  });

  q({
    id: 'ped-itu-024',
    subtopic: 'Cistite vs Pielonefrite',
    inst: 'IAMSPE',
    year: 2024,
    statement: 'Lactente de 10 meses é internado com diagnóstico de pielonefrite aguda. Durante a internação, a densidade urinária no EAS mantém-se persistentemente baixa (1.002 a 1.005), apesar de sinais de desidratação leve com sede ávida. Qual alteração fisiopatológica tubular transitória explica essa incapacidade de concentrar a urina durante a pielonefrite aguda?',
    A: 'Perda transitória da hipertonicidade da medula renal por inflamação dos túbulos coletores e alça de Henle, gerando defeito transitório de concentração urinária.',
    B: 'Supressão total irreversível da síntese hipotalâmica de vasopressina (ADH).',
    C: 'Destruição congênita completa de todas as arteríolas aferentes glomerulares.',
    D: 'Excreção massiva de insulina ativa na luz da bexiga com diurese osmótica pura.',
    ans: 'A',
    comment: 'Na pielonefrite aguda, a infiltração inflamatória e o edema local na medula renal e túbulos coletores prejudicam o mecanismo contracorrente da alça de Henle e a resposta à vasopressina. Como resultado, ocorre um defeito transitório na capacidade de concentrar a urina (isostenúria/hipostenúria com densidade < 1.010), que se recupera semanas após o tratamento eficaz da infecção.',
    expA: 'Correta. O edema e infiltrado inflamatório medular causam defeito transitório na capacidade de concentração urinária.',
    expB: 'Incorreta. A síntese de ADH no eixo hipotálamo-hipofisário está preservada.',
    expC: 'Incorreta. Não há destruição congênita de arteríolas aferentes.',
    expD: 'Incorreta. A glicemia e a insulina não estão desreguladas dessa forma.',
  });

  q({
    id: 'ped-itu-025',
    subtopic: 'Cistite vs Pielonefrite',
    inst: 'PUC-Campinas',
    year: 2024,
    statement: 'Menina de 7 anos apresenta disúria, polaciúria e urgência miccional sem febre (temperatura axilar de 36,6 °C) e sem dor lombar. O abdome é indolor e flácido. O sedimento urinário revela 45 leucócitos/campo e nitrito positivo. Como esse quadro clínico deve ser classificado e qual é a duração habitual do tratamento antimicrobiano oral recomendado?',
    A: 'Cistite aguda (infecção do trato urinário baixo); tratada com antimicrobiano oral por 3 a 5 dias.',
    B: 'Pielonefrite aguda grave; tratada com internação e ceftriaxona venosa por 21 dias.',
    C: 'Síndrome nefrítica aguda; tratada com pulsoterapia com metilprednisolona por 5 dias.',
    D: 'Bacteriúria assintomática crônica; não deve receber qualquer tipo de acompanhamento.',
    ans: 'A',
    comment: 'A presença de sintomas estritamente vesicais (disúria, polaciúria, urgência) sem febre e sem manifestações sistêmicas define Cistite Aguda (ITU baixa). Em meninas previamente saudáveis e continentes, cursos curtos de antimicrobianos orais (3 a 5 dias) com Nitrofurantoína, Cefalexina ou Cefuroxima são altamente eficazes para erradicar a infecção vesical e minimizar efeitos adversos e seleção de resistência.',
    expA: 'Correta. Cistite aguda tratada por 3 a 5 dias com antibiótico oral ambulatorial.',
    expB: 'Incorreta. Na ausência de febre e toxemia, não se classifica como pielonefrite nem se interna para antibioticoterapia venosa prolongada.',
    expC: 'Incorreta. Não há hipertensão, edema nem hematúria dismórfica da síndrome nefrítica.',
    expD: 'Incorreta. A paciente é francamente sintomática (disúria e polaciúria), o que afasta o conceito de bacteriúria assintomática.',
  });
}
