import { q } from './helper_itu.js';

export function loadSec4() {
  q({
    id: 'ped-itu-026',
    subtopic: 'Tratamento antimicrobiano',
    inst: 'USP-SP',
    year: 2024,
    statement: 'Menina de 6 anos, sem antecedentes mórbidos, apresenta disúria e polaciúria há 2 dias, afebril e em excelente estado geral. O EAS confirma piúria e nitrito positivo. Não há vômitos e a criança aceita líquidos normalmente. Qual é o antimicrobiano oral de primeira escolha e a duração recomendada para o tratamento dessa cistite não complicada?',
    A: 'Nitrofurantoína por via oral (5 a 7 mg/kg/dia dividida em 4 doses) por 3 a 5 dias.',
    B: 'Ceftriaxona intravenosa (100 mg/kg/dia) em regime hospitalar por 14 dias.',
    C: 'Vancomicina oral associada a metronidazol por 21 dias consecutivos.',
    D: 'Ciprofloxacino intravenoso contínuo por 1 mês para profilaxia de bacteriemia.',
    ans: 'A',
    comment: 'Para a cistite aguda não complicada em crianças em idade escolar, a Nitrofurantoína por via oral (5 a 7 mg/kg/dia em 4 tomadas, durante 3 a 5 dias) é uma excelente escolha de primeira linha. Possui baixíssimas taxas de resistência entre cepas de E. coli, mínima perturbação da microbiota intestinal normal e excelente concentração na urina da bexiga.',
    expA: 'Correta. A nitrofurantoína por 3 a 5 dias é opção de primeira linha ideal para cistite não complicada.',
    expB: 'Incorreta. Ceftriaxona venosa internada é reservada para pielonefrite grave ou com toxemia, não para cistite simples.',
    expC: 'Incorreta. Vancomicina oral trata colite por C. difficile, não age em ITU por enterobactérias.',
    expD: 'Incorreta. Quinolonas são desnecessárias, caras e com risco de toxicidade musculoesquelética na infância.',
  });

  q({
    id: 'ped-itu-027',
    subtopic: 'Tratamento antimicrobiano',
    inst: 'UNICAMP',
    year: 2024,
    statement: 'Lactente de 11 meses feminina apresenta febre de 38,7 °C há 24 horas. Está em bom estado geral, corada, hidratada, ativa e aceitando bem o aleitamento materno e a dieta complementar, sem vômitos. O EAS de cateterismo vesical mostra leucocitúria acentuada e nitrito positivo. A mãe é orientada e possui fácil acesso ao serviço de saúde. Qual conduta terapêutica antimicrobiana é recomendada segundo a Academia Americana de Pediatria (AAP)?',
    A: 'Tratamento ambulatorial por via oral com Cefalosporina (como Cefuroxima axetil, Cefixima ou Cefalexina) ou Amoxicilina-Clavulanato por 7 a 10 dias, com reavaliação clínica obrigatória em 48 a 72 horas.',
    B: 'Internação obrigatória em UTI Pediátrica para infusão de Meropenem por 28 dias.',
    C: 'Prescrição de Nitrofurantoína oral por 3 dias em dose única diária.',
    D: 'Conduta expectante sem antibióticos até a liberação do resultado da urocultura em 5 dias.',
    ans: 'A',
    comment: 'Ensaios clínicos randomizados demonstraram que o tratamento oral ambulatorial da pielonefrite em lactentes maiores de 2 a 3 meses em bom estado geral, bem hidratados e sem vômitos é tão eficaz quanto a terapia parenteral inicial na prevenção de cicatrizes renais e cura clínica. As opções de primeira linha incluem cefalosporinas de 2ª ou 3ª geração oral (Cefuroxima, Cefixima), Cefalexina ou Amoxicilina-clavulanato por 7 a 10 dias, com reavaliação clínica cuidadosa em 48-72h.',
    expA: 'Correta. Crianças sem toxemia e que toleram via oral podem ser tratadas com antibióticos orais ambulatoriais.',
    expB: 'Incorreta. Meropenem em UTI é tratamento desproporcional para lactente hígido estável.',
    expC: 'Incorreta. Nitrofurantoína não atinge níveis teciduais no parênquima renal e é contraindicada na pielonefrite.',
    expD: 'Incorreta. Retardar o tratamento da pielonefrite aumenta o risco de dano renal permanente e cicatrizes.',
  });

  q({
    id: 'ped-itu-028',
    subtopic: 'Tratamento antimicrobiano',
    inst: 'ENARE',
    year: 2024,
    statement: 'Por qual razão a Ampicilina ou a Amoxicilina isoladas (sem inibidor de betalactamase) NÃO são recomendadas como opções de primeira linha para o tratamento empírico de ITU comunitária na infância?',
    A: 'Devido às elevadíssimas taxas de resistência bacteriana da Escherichia coli comunitária (frequentemente superiores a 40-50%) decorrentes da produção de betalactamases clássicas plasmidiais.',
    B: 'Porque a amoxicilina não é absorvida pelo trato digestivo de crianças menores de 5 anos.',
    C: 'Porque a droga sofre inativação pela urina ácida em todos os indivíduos saudáveis.',
    D: 'Devido ao risco de precipitação de cristais intratubulares irreversíveis nos rins.',
    ans: 'A',
    comment: 'Mais de 40 a 50% das cepas de E. coli comunitárias no Brasil e no mundo são resistentes à ampicilina e à amoxicilina devido à ampla disseminação de betalactamases de espectro estreito (como TEM-1 e SHV-1). O uso dessas drogas em monoterapia empírica resulta em alta taxa de falha terapêutica, progressão de lesão renal e choque séptico.',
    expA: 'Correta. A alta taxa de resistência comunitária da E. coli contra aminopenicilinas isoladas desaconselha seu uso empírico.',
    expB: 'Incorreta. A amoxicilina tem excelente absorção oral em qualquer faixa etária.',
    expC: 'Incorreta. A amoxicilina permanece ativa e estável em pH urinário fisiológico.',
    expD: 'Incorreta. Aminopenicilinas não precipitam cristais intratubulares obstrutivos nas doses usuais.',
  });

  q({
    id: 'ped-itu-029',
    subtopic: 'Tratamento antimicrobiano',
    inst: 'FMRP-USP',
    year: 2024,
    statement: 'De acordo com as diretrizes internacionais da IDSA e SBP, qual é o limite máximo tolerável de resistência bacteriana local da Escherichia coli comunitária contra o Sulfametoxazol-Trimetoprima (SMX-TMP) para que essa combinação ainda possa ser utilizada de forma empírica segura no tratamento de ITU?',
    A: 'Taxa de resistência local inferior a 20%.',
    B: 'Taxa de resistência local de até 85%.',
    C: 'Apenas se a taxa de resistência for rigorosamente de 0%.',
    D: 'A resistência bacteriana não interfere na eficácia clínica do SMX-TMP.',
    ans: 'A',
    comment: 'Pelas diretrizes de infectologia pediátrica, o Sulfametoxazol-Trimetoprima só deve ser prescrito empiricamente se os dados epidemiológicos da comunidade local demonstrarem taxas de resistência da E. coli inferiores a 20%. Quando a taxa de resistência local ultrapassa 20% (como ocorre na maioria das cidades brasileiras, onde atinge 30-40%), o SMX-TMP não deve ser empregado empiricamente para tratar ITU aguda.',
    expA: 'Correta. Taxa de resistência local abaixo de 20% é o limite preconizado pelas diretrizes.',
    expB: 'Incorreta. Resistência de 85% levaria a falha terapêutica na grande maioria dos pacientes.',
    expC: 'Incorreta. Não se exige 0%; 20% é a margem de segurança epidemiológica.',
    expD: 'Incorreta. A resistência in vitro correlaciona-se diretamente com falha clínica e bacteriológica.',
  });

  q({
    id: 'ped-itu-030',
    subtopic: 'Tratamento antimicrobiano',
    inst: 'SCMSP',
    year: 2024,
    statement: 'Lactente de 3 meses é admitido no pronto-socorro com pielonefrite aguda febril e vômitos persistentes. A equipe decide iniciar Ceftriaxona por via intravenosa. Qual é a posologia diária habitual recomendada da Ceftriaxona para o tratamento de pielonefrite aguda na infância e sua principal vantagem posológica?',
    A: '50 a 100 mg/kg/dia administrada em dose única diária (a cada 24 horas), facilitando a comodidade de administração e transição para hospital-dia.',
    B: '10 mg/kg/dia fracionada em infusão contínua por bomba a cada 2 horas.',
    C: '500 mg/kg/dia administrada exclusivamente a cada 4 horas.',
    D: '1 mg/kg/dia por via subcutânea quinzenal.',
    ans: 'A',
    comment: 'A Ceftriaxona é uma cefalosporina de 3ª geração de amplo espectro com excelente atividade contra enterobactérias uropatogênicas. Sua longa meia-vida plasmática permite a administração em dose única diária (50 a 100 mg/kg/dia uma vez ao dia, EV ou IM), tornando-a a droga parenteral de eleição em serviços de emergência pediátrica.',
    expA: 'Correta. 50 a 100 mg/kg/dia uma vez ao dia (dose única) é a posologia padrão e prática da ceftriaxona.',
    expB: 'Incorreta. Fracionamento a cada 2 horas é desnecessário e inviável.',
    expC: 'Incorreta. 500 mg/kg/dia é dose tóxica extrema.',
    expD: 'Incorreta. Dose subótima e via incorreta para infecção aguda.',
  });

  q({
    id: 'ped-itu-031',
    subtopic: 'Tratamento antimicrobiano',
    inst: 'UERJ',
    year: 2023,
    statement: 'Durante a internação de uma criança de 2 anos com pielonefrite por bacilo Gram-negativo multirresistente, prescreve-se Amicacina intravenosa em regime de dose única diária (15 mg/kg/dia uma vez ao dia). Quais são as duas principais toxicidades farmacológicas dos aminoglicosídeos que exigem monitorização atenta da função renal e da audição?',
    A: 'Nefrotoxicidade (por acúmulo nas células tubulares proximais) e Ototoxicidade (coclear e vestibular).',
    B: 'Cardiomiopatia dilatada aguda e insuficiência hepática fulminante.',
    C: 'Hipertensão intracraniana idiopática e cegueira cortical.',
    D: 'Anemia hemolítica autoimune e cetoacidose euglicêmica.',
    ans: 'A',
    comment: 'Os aminoglicosídeos (gentamicina, amicacina) são potentes bactericidas com efeito pós-antibiótico dependente da concentração de pico. As duas toxicidades clássicas e limitantes são: 1) Nefrotoxicidade (lesão tubular renal aguda, geralmente não oligúrica e reversível); 2) Ototoxicidade (lesão das células ciliadas da cóclea e do labirinto vestibular, frequentemente irreversível). O regime de dose única diária maximiza a eficácia bactericida e minimiza a toxicidade.',
    expA: 'Correta. Nefrotoxicidade e ototoxicidade são os efeitos adversos clássicos dos aminoglicosídeos.',
    expB: 'Incorreta. Aminoglicosídeos não causam cardiomiopatia dilatada nem falência hepática típica.',
    expC: 'Incorreta. Não provocam hipertensão intracraniana idiopática.',
    expD: 'Incorreta. Não induzem cetoacidose nem hemólise imune.',
  });

  q({
    id: 'ped-itu-032',
    subtopic: 'Tratamento antimicrobiano',
    inst: 'IAMSPE',
    year: 2024,
    statement: 'Qual é o tempo total de tratamento antimicrobiano preconizado pelas diretrizes da AAP e Sociedade Brasileira de Pediatria para um episódio típico de Pielonefrite Aguda na infância que apresentou excelente e rápida resposta clínica (defervescência em 48 horas)?',
    A: '7 a 10 dias (podendo estender-se até 14 dias em casos graves ou resposta mais lenta).',
    B: 'Exatamente 3 dias em dose única.',
    C: 'Mínimo obrigatório de 60 dias de antibioticoterapia contínua parenteral.',
    D: 'Apenas 24 horas após a primeira dose.',
    ans: 'A',
    comment: 'A duração recomendada do tratamento para Pielonefrite Aguda na infância é de 7 a 10 dias (podendo chegar a 14 dias em crianças com resposta inicial lenta, uropatias obstrutivas complexas ou neonatos). Cursos inferiores a 7 dias associam-se a taxas inaceitáveis de recidiva precoce da infecção renal, enquanto cursos acima de 14 dias não agregam benefício clínico e ampliam a seleção de resistência.',
    expA: 'Correta. 7 a 10 dias é o tempo padrão preconizado para tratamento de pielonefrite com boa resposta.',
    expB: 'Incorreta. 3 dias é esquema para cistite baixa em crianças maiores, insuficiente para infecção do parênquima renal.',
    expC: 'Incorreta. 60 dias é tempo excessivo e causaria indução de superbactérias.',
    expD: 'Incorreta. 24 horas não erradica o foco parenquimatoso renal.',
  });

  q({
    id: 'ped-itu-033',
    subtopic: 'Tratamento antimicrobiano',
    inst: 'SMS-SP',
    year: 2024,
    statement: 'Lactente de 8 meses com pielonefrite aguda foi internado e iniciado Ceftriaxona venosa empírica. No 3º dia de internação, a criança está afebril há 36 horas, ativa, mamando normalmente. O resultado definitivo da urocultura revela Escherichia coli (> 100.000 UFC/mL) sensível a ampicilina, cefalexina, cefuroxima, ciprofloxacino e ceftriaxona. Qual é a conduta farmacológica mais adequada (desescalonamento / terapia sequencial oral)?',
    A: 'Transicionar para antibioticoterapia por via oral com Cefalexina ou Cefuroxima para completar o tempo total de 7 a 10 dias de tratamento, permitindo a alta hospitalar precoce.',
    B: 'Manter a Ceftriaxona intravenosa internado até o 21º dia para garantir esterilização tecidual.',
    C: 'Trocar imediatamente para Meropenem venoso por 14 dias pelo risco de resistência tardia.',
    D: 'Suspender todo o tratamento antibiótico imediatamente pois a criança já está afebril.',
    ans: 'A',
    comment: 'A terapia sequencial (troca de antibiótico venoso para via oral quando o paciente atinge estabilidade clínica, afebril por > 24-48 horas e com boa tolerância oral) é uma prática segura e padrão em pediatria ("step-down therapy"). Com o antibiograma disponível, faz-se o desescalonamento para uma cefalosporina oral de menor espectro (como Cefalexina ou Cefuroxima), completando 7 a 10 dias totais em casa.',
    expA: 'Correta. Desescalonamento para via oral com cefalexina/cefuroxima para alta hospitalar e completar 7-10 dias.',
    expB: 'Incorreta. Manter Ceftriaxona venosa desnecessariamente expõe a criança a infecções hospitalares e custos.',
    expC: 'Incorreta. Escalonamento para carbapenêmico em bactéria sensível viola as regras de stewardship antimicrobiano.',
    expD: 'Incorreta. Suspender precocemente no 3º dia causará recidiva da pielonefrite e formação de cicatrizes.',
  });

  q({
    id: 'ped-itu-034',
    subtopic: 'Tratamento antimicrobiano',
    inst: 'PUC-PR',
    year: 2024,
    statement: 'Lactente de 1 ano com pielonefrite aguda confirmada por E. coli recebe Ceftriaxona intravenosa há 72 horas em dose correta, porém persiste com picos febris diários de 39,5 °C, irritabilidade e toxemia. Qual é a conduta prioritária imediata para esclarecer a causa dessa falha terapêutica?',
    A: 'Realizar Ultrassonografia de Rins e Vias Urinárias com urgência para investigar complicações supurativas (abscesso renal ou perirrenal, nefrite lobar aguda) ou uropatia obstrutiva congênita associada.',
    B: 'Adicionar paracetamol em dose dobrada e aguardar mais 5 dias sem novos exames.',
    C: 'Suspender a hidratação venosa e iniciar furosemida em altas doses.',
    D: 'Encaminhar para biópsia renal percutânea imediata sob anestesia geral.',
    ans: 'A',
    comment: 'A resposta clínica ao tratamento adequado da pielonefrite geralmente ocorre em 24 a 48 horas (queda da febre e melhora do estado geral). A persistência de febre alta após 48 a 72 horas de antibioticoterapia venosa adequada define falha terapêutica e exige investigação IMEDIATA com Ultrassonografia de urgência para afastar abscesso renal/perirrenal, nefrite focal aguda (lobar) ou uropatia obstrutiva (que exija drenagem urológica de emergência).',
    expA: 'Correta. USG urgente é mandatória após 48-72h de febre refratária para pesquisar abscesso ou obstrução.',
    expB: 'Incorreta. Ignorar a febre persistente atrasa o diagnóstico de complicações que podem necessitar de drenagem.',
    expC: 'Incorreta. Diuréticos podem causar hipovolemia sem resolver a causa infecciosa.',
    expD: 'Incorreta. Biópsia renal não tem indicação na pielonefrite aguda bacteriana.',
  });
}
