import { q } from './helper_itu.js';

export function loadSec5() {
  q({
    id: 'ped-itu-035',
    subtopic: 'Indicações de internação hospitalar',
    inst: 'USP-SP',
    year: 2024,
    statement: 'Recém-nascido com 18 dias de vida, a termo, apresenta febre de 38,4 °C, letargia, recusa alimentar e icterícia zona 3 de Kramer. O cateterismo vesical revela urina turva com 80 leucócitos/campo e bacteriúria. Diante da idade neonatal e risco iminente de urossepse, qual conduta e esquema antimicrobiano empírico inicial são os mais indicados?',
    A: 'Internação hospitalar obrigatória com rastreio de sepse neonatal tardia (incluindo hemoculturas e punção lombar) e início imediato de Ampicilina associada a Gentamicina (ou amicacina) por via intravenosa.',
    B: 'Tratamento ambulatorial com nitrofurantoína em suspensão oral por 7 dias.',
    C: 'Prescrição de ciprofloxacino oral domiciliar com retorno em 1 semana.',
    D: 'Apenas banho morno e observação domiciliar até o resultado da urocultura.',
    ans: 'A',
    comment: 'No período neonatal (< 28-30 dias), a barreira hematológica e a imunidade celular são imaturas, e a ITU é frequentemente uma manifestação de bacteriemia sistêmica (urossepse) com risco de meningite concomitante. A internação hospitalar é mandatória em 100% dos recém-nascidos. O esquema clássico de primeira linha no período neonatal é Ampicilina associada a um Aminoglicosídeo (Gentamicina ou Amicacina), cobrindo Enterococcus faecalis, Listeria monocytogenes, Streptococcus agalactiae e bacilos Gram-negativos entéricos.',
    expA: 'Correta. Internação mandatória com investigação completa de sepse tardia e Ampicilina + Gentamicina EV.',
    expB: 'Incorreta. Nitrofurantoína é contraindicada em neonatos pelo risco de anemia hemolítica e não trata pielonefrite/sepse.',
    expC: 'Incorreta. Tratamento ambulatorial é contraindicado no período neonatal febril.',
    expD: 'Incorreta. Conduta omissiva que levaria a choque séptico neonatal fatal.',
  });

  q({
    id: 'ped-itu-036',
    subtopic: 'Indicações de internação hospitalar',
    inst: 'UNICAMP',
    year: 2024,
    statement: 'Lactente de 7 meses é trazido à sala de emergência com história de febre alta há 48 horas. Ao exame físico: prostrado, gemente, tempo de enchimento capilar de 4 segundos, pulsos periféricos filiformes, taquicárdico (FC: 195 bpm) e PA no percentil 5. O sedimento urinário colhido por cateterismo revela piúria maciça e nitrito positivo. Qual é a conduta prioritária imediata?',
    A: 'Classificar como Choque Séptico de foco urinário (Urossepse), proceder à ressuscitação volêmica imediata com cristaloides isotônicos (20 mL/kg) em bólus e administrar Ceftriaxona intravenosa na primeira hora (hora de ouro).',
    B: 'Prescrever amoxicilina oral e aguardar melhora do enchimento capilar na sala de espera.',
    C: 'Realizar lavagem gástrica descompressiva com carvão ativado.',
    D: 'Encaminhar ambulatorialmente para ecografia urológica antes de qualquer medicamento.',
    ans: 'A',
    comment: 'O paciente apresenta sinais clínicos evidentes de choque séptico descompensado/frio (tempo de enchimento capilar > 3 segundos, pulsos filiformes, taquicardia extrema e hipotensão limítrofe) secundário a pielonefrite aguda invasiva (urossepse). O manejo na "hora de ouro" exige: estabilização da via aérea e oxigênio, expansão volêmica vigorosa com solução cristaloide isotônica a 20 mL/kg e antibioticoterapia parenteral de amplo espectro (Ceftriaxona EV) iniciada na primeira hora.',
    expA: 'Correta. Reconhece choque séptico de foco urinário e prioriza ressuscitação volêmica rápida e ceftriaxona na 1ª hora.',
    expB: 'Incorreta. Conduta inaceitável que levaria a parada cardiorrespiratória por choque distributivo/hipovolêmico.',
    expC: 'Incorreta. Não se trata de intoxicação exógena.',
    expD: 'Incorreta. Não se retarda a ressuscitação e antibióticos para exames de imagem.',
  });

  q({
    id: 'ped-itu-037',
    subtopic: 'Indicações de internação hospitalar',
    inst: 'ENARE',
    year: 2024,
    statement: 'Lactente de 5 meses é diagnosticada com pielonefrite aguda. A mãe relata que a criança apresentou 8 episódios de vômitos nas últimas 6 horas, não consegue reter nenhum líquido e vomitou imediatamente a primeira dose do antibiótico oral prescrito no posto. Ao exame: mucosas secas, olhos encovados, turgor diminuído da pele e perda ponderal de 7%. Qual é a indicação inequívoca de internação hospitalar neste caso?',
    A: 'Desidratação clínica moderada associada a intolerância à via oral por vômitos incoercíveis, impedindo a absorção segura de antimicrobianos orais.',
    B: 'Presença isolada de turgor pastoso sem qualquer relevância volêmica.',
    C: 'Apenas a constatação de febre axilar superior a 37,8 °C.',
    D: 'Necessidade de realizar tomografia computadorizada contrastada de corpo inteiro.',
    ans: 'A',
    comment: 'A intolerância à via oral decorrente de vômitos incoercíveis e a presença de desidratação clínica são critérios absolutos para internação hospitalar em crianças com ITU. Nessas condições, a absorção de antibióticos por via oral é errática ou impossível, e o risco de choque hipovolêmico sobreposto à infecção bacteriana exige hidratação venosa contínua e antimicrobianos parenterais.',
    expA: 'Correta. Vômitos incoercíveis e desidratação impedem terapia oral e exigem internação e via parenteral.',
    expB: 'Incorreta. A desidratação é clinicamente significativa (perda de 7% do peso corporal).',
    expC: 'Incorreta. Febre isolada sem desidratação ou vômitos não obriga internação se a criança tolerar medicação oral.',
    expD: 'Incorreta. TC de corpo inteiro não tem indicação na pielonefrite não complicada.',
  });

  q({
    id: 'ped-itu-038',
    subtopic: 'Indicações de internação hospitalar',
    inst: 'FMRP-USP',
    year: 2024,
    statement: 'Menino de 4 anos com diagnóstico prévio de Rim Único funcionante congênito (agenesia renal unilateral esquerda) apresenta febre de 39,2 °C, dor lombar direita intensa e urina turva com EAS evidenciando piúria e nitrito positivo. Creatinina sérica basal era 0,4 mg/dL e encontra-se agora em 1,3 mg/dL. Qual é a justificativa para a internação hospitalar imediata desta criança?',
    A: 'Paciente portador de Rim Único que desenvolveu Injúria Renal Aguda associada à pielonefrite, com alto risco de perda irreversível da massa nefronal funcionante remanescente.',
    B: 'Indicação exclusiva de hemodiálise de urgência imediata sem uso de antibióticos.',
    C: 'Apenas para realização de cistoscopia diagnóstica sob sedação contínua.',
    D: 'Risco de contaminação cruzada para os familiares no domicílio.',
    ans: 'A',
    comment: 'Crianças com anomalias estruturais complexas, nefropatias prévias, transplante renal ou rim único funcionante constituem um grupo de altíssimo risco na vigência de pielonefrite aguda. A elevação aguda da escória nitrogenada (creatinina de 0,4 para 1,3 mg/dL) confirma Injúria Renal Aguda (IRA) sobreposta. A internação hospitalar com antibioticoterapia parenteral rápida e monitorização estrita do débito urinário e da volemia é indispensável para proteger a função renal do rim solitário.',
    expA: 'Correta. Rim único funcionante com perda aguda de função renal exige internação e terapia parenteral protetora.',
    expB: 'Incorreta. Não há indicação de diálise imediata antes da ressuscitação e tratamento clínico da infecção.',
    expC: 'Incorreta. Cistoscopia na fase aguda inflamatória não está indicada.',
    expD: 'Incorreta. ITU por E. coli não é infecção de transmissão interpessoal respiratória.',
  });

  q({
    id: 'ped-itu-039',
    subtopic: 'Indicações de internação hospitalar',
    inst: 'SCMSP',
    year: 2024,
    statement: 'Em um lactente de 6 meses com ITU febril, qual das seguintes situações socioambientais constitui indicação formal de internação hospitalar mesmo na ausência de critérios clínicos de toxemia grave?',
    A: 'Vulnerabilidade social extrema com cuidadores que não demonstram compreensão do tratamento, ausência de recursos para aquisição de medicamentos e impossibilidade de retorno garantido para reavaliação em 48 horas.',
    B: 'Mãe primípara com nível superior completo e residência a 500 metros do hospital.',
    C: 'Criança que frequenta creche em período integral.',
    D: 'Família que possui convênio médico privado de cobertura nacional.',
    ans: 'A',
    comment: 'A avaliação pediátrica deve sempre incluir a esfera psicossocial. Mesmo que o lactente esteja clinicamente estável, a incapacidade dos cuidadores de administrar as doses corretas do antibiótico, a falta de acesso à medicação ou a impossibilidade de comparecer à reavaliação clínica obrigatória em 48 a 72 horas configuram "internação social". A negligência involuntária ou falha na administração domiciliar levaria à progressão para pielonefrite grave e bacteriemia.',
    expA: 'Correta. Insegurança social e risco de não adesão ou perda de seguimento justificam internação protetora.',
    expB: 'Incorreta. Família estruturada e próxima ao hospital favorece o tratamento ambulatorial seguro.',
    expC: 'Incorreta. Frequentar creche não é critério de internação hospitalar.',
    expD: 'Incorreta. Posse de plano de saúde não dita necessidade de admissão hospitalar.',
  });

  q({
    id: 'ped-itu-040',
    subtopic: 'Indicações de internação hospitalar',
    inst: 'UERJ',
    year: 2023,
    statement: 'Lactente de 10 meses foi iniciado em Cefuroxima oral ambulatorial após diagnóstico de ITU febril. Retorna ao serviço após 60 horas de tratamento com piora do estado geral, sonolência intercalada com irritabilidade e persistência de febre de 39,8 °C. Qual é a conduta indicada diante desta falha do tratamento ambulatorial?',
    A: 'Internação hospitalar imediata, coleta de exames laboratoriais (hemograma, PCR, função renal, hemocultura), troca da antibioticoterapia para via intravenosa (ex: Ceftriaxona ou amicacina) e realização de ultrassonografia do trato urinário.',
    B: 'Aumentar a dose da cefuroxima oral e liberar para casa por mais 5 dias.',
    C: 'Orientar que a febre pode durar até 14 dias sem necessidade de qualquer alteração.',
    D: 'Prescrever apenas antitérmicos alternados a cada 2 horas sem exames adicionais.',
    ans: 'A',
    comment: 'A persistência de febre e a piora clínica após 48 a 72 horas de tratamento oral indicam falha terapêutica (por má adesão, vômitos, resistência bacteriana in vitro ou complicação supurativa como abscesso). A conduta obrigatória é a internação hospitalar imediata para transição para antibiótico parenteral de amplo espectro (Ceftriaxona), recoleta de culturas e ultrassonografia das vias urinárias.',
    expA: 'Correta. Falha terapêutica após 48-72h exige internação, investigação laboratorial, USG e antibiótico parenteral.',
    expB: 'Incorreta. Manter o mesmo antibiótico oral que falhou clinicamente agrava a infecção tecidual renal.',
    expC: 'Incorreta. A febre da pielonefrite deve ceder em 48 a 72 horas com o tratamento correto.',
    expD: 'Incorreta. Mascarar a infecção com antitérmicos não resolve a sepse subjacente.',
  });

  q({
    id: 'ped-itu-041',
    subtopic: 'Indicações de internação hospitalar',
    inst: 'IAMSPE',
    year: 2024,
    statement: 'Menina de 3 anos portadora de Leucemia Linfoide Aguda (LLA) em fase de indução quimioterápica apresenta febre de 38,8 °C e disúria. O hemograma revela contagem absoluta de neutrófilos de 280/mm³ (neutropenia febril grave). O EAS revela bacteriúria e leucocitúria. Qual é a conduta mandatória para esta paciente?',
    A: 'Internação hospitalar imediata em isolamento protetor com início urgente de antibioticoterapia intravenosa de amplo espectro antipseudomonas (como Cefepima ou Meropenem).',
    B: 'Tratamento ambulatorial com nitrofurantoína por via oral por 3 dias.',
    C: 'Apenas suspensão temporária da quimioterapia sem antibióticos.',
    D: 'Coleta de urocultura e alta domiciliar com agendamento de retorno em 7 dias.',
    ans: 'A',
    comment: 'A presença de ITU em paciente pediátrico oncológico com neutropenia febril grave (neutrófilos < 500/mm³) constitui emergência médica máxima. A ausência de neutrófilos impede a contenção local do foco infeccioso, com risco de invasão vascular rápida e choque séptico fatal por Pseudomonas aeruginosa ou enterobactérias produtoras de ESBL. A internação imediata com betalactâmico antipseudomonas EV (Cefepima ou Piperacilina-Tazobactam) na primeira hora é obrigatória.',
    expA: 'Correta. Neutropenia febril com foco urinário exige internação e cobertura antipseudomonas imediata.',
    expB: 'Incorreta. A nitrofurantoína é totalmente inadequada para paciente neutropênico de alto risco.',
    expC: 'Incorreta. Suspender antibiótico no neutropênico infectado culmina em óbito em poucas horas.',
    expD: 'Incorreta. Liberar paciente neutropênico febril para casa é erro gravíssimo.',
  });

  q({
    id: 'ped-itu-042',
    subtopic: 'Indicações de internação hospitalar',
    inst: 'PUC-Campinas',
    year: 2024,
    statement: 'Por qual motivo farmacológico clássico a CEFTRIAXONA deve ser evitada no período neonatal precoce (< 28 dias), especialmente em recém-nascidos com hiperbilirrubinemia indireta ou em uso de infusões contendo cálcio?',
    A: 'Risco de deslocamento da bilirrubina indireta de seus sítios de ligação à albumina sérica (aumentando o risco de kernicterus / encefalopatia bilirrubínica) e risco de precipitação de cristais insolúveis de ceftriaxona cálcica nos pulmões e rins.',
    B: 'Risco de hipotireoidismo congênito transitório por bloqueio da peroxidase tiroidiana.',
    C: 'Capacidade de induzir fechamento intrauterino tardio do forame oval com cianose maciça.',
    D: 'Efeito teratogênico sobre o desenvolvimento dos folículos pilosos cutâneos.',
    ans: 'A',
    comment: 'No período neonatal imediato, a Ceftriaxona tem duas contraindicações formais: 1) Liga-se fortemente à albumina sérica, deslocando a bilirrubina não conjugada (indireta) e elevando a fração livre que atravessa a barreira hematoencefálica, predispondo ao Kernicterus; 2) Forma precipitados insolúveis de ceftriaxona-cálcio quando administrada concomitantemente com soluções venosas contendo cálcio (como gluconato de cálcio ou nutrição parenteral), podendo provocar embolia e lesão fatal em pulmões e rins. Por isso, prefere-se Cefotaxima ou Ampicilina + Gentamicina em neonatos.',
    expA: 'Correta. Risco de kernicterus por deslocamento da bilirrubina e precipitação de sais de cálcio insolúveis.',
    expB: 'Incorreta. Ceftriaxona não inibe a síntese de hormônios tireoidianos.',
    expC: 'Incorreta. O forame oval não sofre fechamento por cefalosporinas.',
    expD: 'Incorreta. Efeito teratogênico refere-se a exposição embriofetal, não uso pós-natal em folículos.',
  });
}
