import { q } from './helper_itu.js';

export function loadSec6() {
  q({
    id: 'ped-itu-043',
    subtopic: 'Ultrassonografia de Rins e Vias Urinárias',
    inst: 'USP-SP',
    year: 2024,
    statement: 'Lactente feminina de 5 meses apresenta seu primeiro episódio de ITU febril com urocultura confirmando E. coli > 100.000 UFC/mL. Respondeu rapidamente ao antibiótico oral, encontrando-se afebril e assintomática no 4º dia. Segundo as diretrizes da Sociedade Brasileira de Pediatria (SBP) e da Academia Americana de Pediatria (AAP), qual é o exame de imagem inicial mandatório indicado para todas as crianças entre 2 e 24 meses após o primeiro episódio de ITU febril?',
    A: 'Ultrassonografia de Rins e Vias Urinárias (USG).',
    B: 'Ressonância Magnética de abdome total com contraste paramagnético.',
    C: 'Uretrocistografia Miccional invasiva imediata na sala de emergência.',
    D: 'Arteriografia renal bilateral seletiva por punção femoral.',
    ans: 'A',
    comment: 'A Ultrassonografia de Rins e Vias Urinárias (USG) é o método de imagem de primeira linha indicado para TODOS os lactentes e crianças de 2 a 24 meses após o primeiro episódio documentado de ITU febril. É um exame não invasivo, sem radiação ionizante e de baixo custo, cujo objetivo principal é identificar ou descartar anomalias anatômicas estruturais congênitas maiores (como hidronefrose, estenose de JUP, duplicidade pielocalicial, hipoplasia/agenesia renal e dilatações vesicais).',
    expA: 'Correta. A USG de rins e vias urinárias é o exame de imagem inicial padrão para todas as crianças após a 1ª ITU febril.',
    expB: 'Incorreta. Ressonância magnética exige anestesia geral e não é exame de triagem de primeira linha.',
    expC: 'Incorreta. UCM é exame invasivo com indicações selecionadas, não o método inicial para todos de rotina imediata.',
    expD: 'Incorreta. Arteriografia é exame invasivo vascular sem indicação em infecção comum.',
  });

  q({
    id: 'ped-itu-044',
    subtopic: 'Ultrassonografia de Rins e Vias Urinárias',
    inst: 'UNICAMP',
    year: 2024,
    statement: 'Em um lactente de 8 meses com primeiro episódio de pielonefrite aguda que apresentou excelente resposta clínica, tornando-se afebril em 24 horas e mantendo bom estado geral, qual é o momento ideal para a realização da Ultrassonografia de Rins e Vias Urinárias?',
    A: 'Realização ambulatorial eletiva após o término ou nas semanas seguintes à resolução do quadro agudo, evitando alterações transitórias de calibre pielocalicial induzidas pela infecção aguda.',
    B: 'Na sala de emergência nas primeiras 2 horas antes de iniciar o antibiótico.',
    C: 'Exclusivamente durante a vigência de febre máxima para sensibilizar o Doppler vascular.',
    D: 'Apenas após a puberdade aos 14 anos de idade.',
    ans: 'A',
    comment: 'Quando a criança evolui favoravelmente com pronta defervescência e sem sinais de gravidade, a USG não precisa ser feita na urgência. Recomenda-se realizá-la de forma eletiva ambulatorial após a resolução da fase aguda infecciosa (ou nos dias que antecedem a alta hospitalar). Isso evita falsos positivos de ectasia pielocalicial leve transitória decorrente do relaxamento muscular ureteral induzido por endotoxinas bacterianas na vigência da infecção ativa.',
    expA: 'Correta. Em pacientes com boa resposta, a USG pode ser feita eletivamente após a fase aguda.',
    expB: 'Incorreta. Não há necessidade de atrasar o tratamento ou sobrecarregar a emergência se a criança evolui bem.',
    expC: 'Incorreta. Fazer no pico febril não traz benefícios e causa estresse desnecessário.',
    expD: 'Incorreta. Postergar para a puberdade causaria perda irreparável da janela de detecção de malformações congênitas.',
  });

  q({
    id: 'ped-itu-045',
    subtopic: 'Ultrassonografia de Rins e Vias Urinárias',
    inst: 'ENARE',
    year: 2024,
    statement: 'Em qual das seguintes situações clínicas em um lactente com ITU febril a realização da Ultrassonografia de Rins e Vias Urinárias deve ser realizada de forma URGENTE (nas primeiras 24 a 48 horas de admissão)?',
    A: 'Presença de toxemia grave/choque séptico, elevação abrupta de escórias nitrogenadas com anúria, massa abdominal palpável ou ausência de defervescência clínica após 48 a 72 horas de antibiótico intravenoso adequado.',
    B: 'Lactente em excelente estado geral que defervesceu após a primeira dose de antitérmico.',
    C: 'Criança de 7 anos com cistite afebril que respondeu à nitrofurantoína em 24 horas.',
    D: 'Menina continente com urocultura isolando E. coli multissensível em uso de cefalexina há 2 dias sem queixas.',
    ans: 'A',
    comment: 'A USG deve ser realizada em caráter de emergência/urgência (nas primeiras 24-48h) se houver: 1) Choque séptico ou toxemia grave; 2) Massa abdominal ou globo vesical palpável; 3) Insuficiência renal aguda / anúria; 4) Infecção por agente atípico não-E. coli; ou 5) Falha na resposta clínica com febre persistente após 48-72h de antibioticoterapia correta (para excluir abscesso renal, pionefrose ou uropatia obstrutiva aguda que exijam nefrostomia ou drenagem).',
    expA: 'Correta. Toxemia, massa palpável, insuficiência renal e febre refratária são indicações de USG de urgência.',
    expB: 'Incorreta. Paciente estável com boa resposta realiza USG ambulatorial eletiva.',
    expC: 'Incorreta. Cistite em escolar não exige USG de urgência.',
    expD: 'Incorreta. Evolução favorável dispensa exames de urgência.',
  });

  q({
    id: 'ped-itu-046',
    subtopic: 'Ultrassonografia de Rins e Vias Urinárias',
    inst: 'FMRP-USP',
    year: 2024,
    statement: 'Apesar de ser o exame inicial de escolha, qual é a principal limitação diagnóstica da Ultrassonografia de Rins e Vias Urinárias na avaliação de crianças com infecção urinária?',
    A: 'Baixa sensibilidade para diagnosticar Refluxo Vesicoureteral (RVU) de graus leve a moderado (graus I a III) e baixa capacidade de detectar cicatrizes renais corticais focais iniciais.',
    B: 'Exposição excessiva da criança a altas doses de radiação ionizante gonadal.',
    C: 'Necessidade obrigatória de injeção intravenosa de contraste iodado nefrotóxico.',
    D: 'Incapacidade total de mensurar as dimensões dos rins em centímetros.',
    ans: 'A',
    comment: 'A USG é excelente para avaliar anatomia grosseira, diâmetro renal e hidronefrose acentuada. No entanto, uma USG completamente normal NÃO exclui Refluxo Vesicoureteral (RVU): ela falha em detectar até 70-80% dos RVU de graus I a III (pois o refluxo intermitente sem dilatação persistente não altera a ecogenicidade ou calibre ureteral). Além disso, a USG não possui sensibilidade para pequenas cicatrizes renais corticais, cuja detecção requer cintilografia com DMSA.',
    expA: 'Correta. A USG normal não afasta RVU leve/moderado e não detecta com sensibilidade cicatrizes renais pequenas.',
    expB: 'Incorreta. A ultrassonografia utiliza ondas sonoras mecânicas; não emite radiação ionizante.',
    expC: 'Incorreta. A USG de rotina não utiliza contrastes iodados venosos.',
    expD: 'Incorreta. A USG mede com altíssima precisão o comprimento e volume renal.',
  });

  q({
    id: 'ped-itu-047',
    subtopic: 'Ultrassonografia de Rins e Vias Urinárias',
    inst: 'SCMSP',
    year: 2024,
    statement: 'Durante a realização de USG em um lactente internado com pielonefrite febril no 2º dia de internação, o radiologista relata: "Rim direito aumentado de volume em relação ao contralateral, com parênquima edemaciado e perda da diferenciação corticomedular habitual, sem dilatação de cálices". Qual é o significado clínico desse achado ecográfico?',
    A: 'Achado ecográfico compatível com processo inflamatório/infeccioso agudo do parênquima renal (pielonefrite aguda edematosa), sem evidência de abscesso organizado ou hidronefrose obstrutiva.',
    B: 'Diagnóstico definitivo de tumor de Wilms congênito bilateral com invasão de veia cava.',
    C: 'Doença renal policística autossômica recessiva terminal em estágio dialítico.',
    D: 'Trombose de artéria renal com infarto isquêmico irreversível de 100% do órgão.',
    ans: 'A',
    comment: 'Na pielonefrite aguda, a infiltração leucocitária maciça e o edema celular provocam nefromegalia (aumento das dimensões renais) e obscurecimento da transição entre o córtex e a medula (perda da diferenciação corticomedular). Esse achado confirma o envolvimento parenquimatoso renal e descarta complicações obstrutivas ou coleções purulentas organizadas.',
    expA: 'Correta. Nefromegalia com perda de diferenciação corticomedular traduz edema inflamatório agudo da pielonefrite.',
    expB: 'Incorreta. Tumor de Wilms apresenta massa sólida heterogênea expansiva bem delimitada.',
    expC: 'Incorreta. Rins policísticos exibem múltiplos cistos bilaterais e perda arquitetural difusa crônica.',
    expD: 'Incorreta. Trombose arterial causa rim excluído sem fluxo ao Doppler colorido.',
  });

  q({
    id: 'ped-itu-048',
    subtopic: 'Ultrassonografia de Rins e Vias Urinárias',
    inst: 'UERJ',
    year: 2023,
    statement: 'Lactente de 1 ano com ITU febril refratária após 72 horas de antibiótico venoso realiza ultrassonografia renal que evidencia uma área focal nodular hipoecoica, arredondada, mal definida, sem vascularização central ao Doppler, localizada no polo superior do rim esquerdo, medindo 1,5 cm. Qual é a hipótese diagnóstica e a conduta terapêutica?',
    A: 'Nefrite Bacteriana Focal Aguda (nefronia lobar aguda) ou Abscesso Renal inicial; manter antibioticoterapia parenteral por tempo prolongado (2 a 3 semanas) com vigilância ecográfica.',
    B: 'Angiomiolipoma benigno; alta hospitalar imediata com alta ingesta hídrica.',
    C: 'Cisto renal simples congênito; não necessita de acompanhamento.',
    D: 'Carcinoma de células renais papilífero; nefrectomia radical de urgência.',
    ans: 'A',
    comment: 'A Nefrite Bacteriana Focal Aguda (ou nefronia lobar) e o microabscesso renal representam estágios intermediários e avançados de infecção parenquimatosa supurativa não tratada ou refratária. Na USG, apresenta-se como massa focal hipoecoica ou com áreas centrais de liquefação sem fluxo ao Doppler. A conduta em coleções pequenas (< 3 cm) é a manutenção de antibioticoterapia parenteral prolongada (2 a 3 semanas), reservando drenagem percutânea para abscessos volumosos (> 3-5 cm) ou refratários.',
    expA: 'Correta. Nefrite bacteriana focal/abscesso requer antibioticoterapia parenteral prolongada e seguimento.',
    expB: 'Incorreta. Angiomiolipoma é hiperecoico e não decorre de infecção febril aguda refratária.',
    expC: 'Incorreta. Cistos simples são anecoicos com reforço acústico posterior puro e sem febre.',
    expD: 'Incorreta. Cirurgia radical mutiladora estaria totalmente errada para complicação infecciosa tratável.',
  });

  q({
    id: 'ped-itu-049',
    subtopic: 'Ultrassonografia de Rins e Vias Urinárias',
    inst: 'IAMSPE',
    year: 2024,
    statement: 'Em uma menina de 7 anos com cistite aguda sintomática, a avaliação ultrassonográfica da bexiga em repleção revela espessamento difuso e irregular da parede vesical (> 3-4 mm) e presença de conteúdo ecogênico móvel em suspensão na urina (debris). O que esses achados indicam?',
    A: 'Sinais ultrassonográficos inflamatórios compatíveis com cistite aguda (espessamento da mucosa vesical por edema e debris celulares inflamatórios na luz da bexiga).',
    B: 'Achado patognomônico de bexiga neurogênica espástica descompensada.',
    C: 'Presença inequívoca de papilomatose vesical maligna disseminada.',
    D: 'Fibrose congênita do detrusor por esquistossomose urinária em fase terminal.',
    ans: 'A',
    comment: 'Na cistite aguda, o processo inflamatório na mucosa urotelial gera hiperemia e edema difuso da parede da bexiga, visível na USG como espessamento parietal (> 3 mm com bexiga repleta). Os debris móveis em suspensão refletem o acúmulo de leucócitos (piúria), muco e descamação de células uroteliais na luz vesical.',
    expA: 'Correta. Espessamento da parede vesical e debris intraluminais são os achados clássicos de cistite aguda na USG.',
    expB: 'Incorreta. Bexiga neurogênica cursa com bexiga de esforço trabeculada com pseudodivertículos crônicos.',
    expC: 'Incorreta. Papilomas vesicais são lesões sólidas vegetantes fixas raras na infância.',
    expD: 'Incorreta. Esquistossomose causa calcificações lineares na parede vesical, endêmica em áreas específicas.',
  });

  q({
    id: 'ped-itu-050',
    subtopic: 'Ultrassonografia de Rins e Vias Urinárias',
    inst: 'SMS-SP',
    year: 2024,
    statement: 'Lactente de 3 meses feminina com ITU de repetição realiza USG que identifica duplicação completa do sistema coletor à direita, com ureterohidronefrose acentuada do polo superior e presença de uma formação cística de parede fina no interior da bexiga na topografia do meato ureteral direito. Qual malformação congênita do trato urinário associada à duplicidade pielocalicial foi diagnosticada?',
    A: 'Ureterocele ectópica obstrutiva do polo superior.',
    B: 'Megabexiga congênita idiopática.',
    C: 'Fístula vesicovaginal adquirida.',
    D: 'Persistência de cloaca comum.',
    ans: 'A',
    comment: 'A Ureterocele é a dilatação cística congênita da porção submucosa terminal intravesical do ureter. Associa-se classicamente à duplicidade pielocalicial completa, na qual o ureter que drena o polo renal superior desemboca de forma ectópica e estenótica na bexiga (regra de Weigert-Meyer), gerando ureterocele com hidronefrose obstrutiva e estase urinária que predispõem a ITUs graves de repetição.',
    expA: 'Correta. Ureterocele do polo superior associada a sistema duplo é a anomalia clássica descrita.',
    expB: 'Incorreta. Megabexiga é dilatação vesical global difusa, não lesão cística intravesical localizada.',
    expC: 'Incorreta. Fístula causa perda urinária contínua pela vagina.',
    expD: 'Incorreta. Persistência de cloaca é anomalia anorretal complexa associada a canal comum.',
  });
}
