import { q } from './helper_itu.js';

export function loadSec7() {
  q({
    id: 'ped-itu-051',
    subtopic: 'Uretrocistografia Miccional e Refluxo Vesicoureteral',
    inst: 'USP-SP',
    year: 2024,
    statement: 'Qual é o exame de imagem considerado padrão-ouro indiscutível para o diagnóstico definitivo, graduação anatômica e visualização direta do Refluxo Vesicoureteral (RVU) e da anatomia uretral na infância?',
    A: 'Uretrocistografia Miccional (UCM).',
    B: 'Cintilografia renal dinâmica com DTPA.',
    C: 'Ultrassonografia renal com contraste microbolha isolada.',
    D: 'Urografia excretora intravenosa clássica.',
    ans: 'A',
    comment: 'A Uretrocistografia Miccional (UCM) convencional com contraste radiológico instilado por sonda vesical retrógrada é o padrão-ouro anatômico para demonstrar o Refluxo Vesicoureteral (RVU). Ela permite visualizar o contraste refluindo da bexiga em direção aos ureteres e rins durante o enchimento e a micção, classificar a gravidade do RVU de grau I a V e avaliar com detalhes a uretra posterior masculina.',
    expA: 'Correta. A Uretrocistografia Miccional (UCM) é o método padrão-ouro para o diagnóstico e estadiamento do RVU.',
    expB: 'Incorreta. DTPA avalia função de excreção e filtração glomerular, não anatomia do refluxo em graus.',
    expC: 'Incorreta. A ultrassonografia com contraste é modalidade alternativa especializada, mas o padrão radiológico ouro formal é a UCM.',
    expD: 'Incorreta. A urografia excretora foi abandonada pela alta carga de radiação e baixa sensibilidade para refluxo.',
  });

  q({
    id: 'ped-itu-052',
    subtopic: 'Uretrocistografia Miccional e Refluxo Vesicoureteral',
    inst: 'UNICAMP',
    year: 2024,
    statement: 'Lactente masculino de 9 meses apresentou o primeiro episódio de ITU febril. A ultrassonografia de vias urinárias realizada ambulatorialmente revelou: "Rins de dimensões normais, sem hidronefrose, sem dilatações e bexiga com paredes finas". A criança está assintomática em seguimento. Segundo as diretrizes da Academia Americana de Pediatria (AAP), qual é a conduta quanto à realização de Uretrocistografia Miccional (UCM) neste momento?',
    A: 'Não realizar a UCM rotineiramente no momento; manter acompanhamento clínico ambulatorial e indicar a UCM apenas se houver novo episódio de ITU febril (recidiva) ou se a USG inicial tivesse revelado hidronefrose ou outras anomalias estruturais.',
    B: 'Realizar a UCM imediatamente em todos os lactentes do sexo masculino, independentemente da USG.',
    C: 'Indicar cirurgia antirrefluxo preventiva sem necessidade de exames adicionais.',
    D: 'Prescrever quimioprofilaxia com ciprofloxacino por 5 anos contínuos.',
    ans: 'A',
    comment: 'A diretriz da AAP de 2011/2016 (adotada amplamente) estabelece que a Uretrocistografia Miccional (UCM) NÃO deve ser realizada de rotina após o primeiro episódio de ITU febril se a USG renal for completamente normal e a criança tiver respondido rapidamente ao antibiótico. A UCM fica indicada se: 1) A USG evidenciar hidronefrose, cicatrizes ou sinais de refluxo de alto grau; 2) Ocorrer um SEGUNDO episódio de ITU febril (recidiva); ou 3) O episódio agudo tiver sido atípico/grave (sepse, germe não-E. coli).',
    expA: 'Correta. A UCM não é mandatória na 1ª ITU com USG normal; fica reservada para recidiva ou alterações no USG.',
    expB: 'Incorreta. A conduta clássica de indicar UCM para todos na 1ª ITU foi superada pelas diretrizes atuais.',
    expC: 'Incorreta. Cirurgia antirrefluxo requer documentação de refluxo de alto grau sintomático refratário.',
    expD: 'Incorreta. Quimioprofilaxia empírica indiscriminada com ciprofloxacino é formalmente contraindicada.',
  });

  q({
    id: 'ped-itu-053',
    subtopic: 'Uretrocistografia Miccional e Refluxo Vesicoureteral',
    inst: 'ENARE',
    year: 2024,
    statement: 'De acordo com a Classificação Internacional do Refluxo Vesicoureteral (Comitê Internacional de Estudo do Refluxo), como é classificado o Refluxo Vesicoureteral Grau I observado à UCM?',
    A: 'Refluxo retrógrado de contraste que atinge apenas o ureter, sem alcançar a pelve renal e sem provocar qualquer dilatação ureteral.',
    B: 'Refluxo que alcança a pelve renal e todos os cálices renais com dilatação ureteral maciça em sifão.',
    C: 'Refluxo acompanhado de destruição completa das papilas renais com hidronefrose gigante.',
    D: 'Estenose congênita do meato ureteral sem passagem de urina retrógrada.',
    ans: 'A',
    comment: 'Pela Classificação Internacional do RVU: Grau I: o contraste reflui apenas para o interior do ureter, sem chegar até a pelve renal e sem provocar dilatação da luz ureteral. É a forma mais leve de refluxo e apresenta altíssima taxa de resolução espontânea (> 80-90% nos primeiros anos de vida).',
    expA: 'Correta. Grau I: refluxo restrito ao ureter, sem atingir a pelve renal e sem dilatação.',
    expB: 'Incorreta. Refluxo com dilatação maciça corresponde aos graus IV e V.',
    expC: 'Incorreta. Destruição papilar com grande dilatação caracteriza o grau V.',
    expD: 'Incorreta. Descreve estenose anatômica, não a definição do refluxo retrógrado grau I.',
  });

  q({
    id: 'ped-itu-054',
    subtopic: 'Uretrocistografia Miccional e Refluxo Vesicoureteral',
    inst: 'FMRP-USP',
    year: 2024,
    statement: 'Lactente de 14 meses realiza UCM após segundo episódio de pielonefrite. O laudo radiológico descreve: "Refluxo vesicoureteral bilateral que ascende por todo o ureter, preenchendo a pelve renal e todos os cálices renais, porém com calibres ureterais estritamente normais e preservação integral dos fórnices caliciais pontiagudos normais, sem qualquer dilatação". Qual é o grau do Refluxo Vesicoureteral de acordo com o Comitê Internacional?',
    A: 'Refluxo Vesicoureteral Grau II.',
    B: 'Refluxo Vesicoureteral Grau I.',
    C: 'Refluxo Vesicoureteral Grau IV.',
    D: 'Refluxo Vesicoureteral Grau V.',
    ans: 'A',
    comment: 'O Grau II da Classificação Internacional do RVU define-se pelo refluxo de contraste que atinge todo o trato urinário superior (ureter, pelve renal e cálices renais), porém SEM provocar qualquer dilatação (calibres normais de ureter e pelve) e com os fórnices caliciais mantendo sua angulação nítida e pontiaguda normal. Assim como o grau I, tem excelente taxa de resolução espontânea com o crescimento.',
    expA: 'Correta. Grau II: refluxo atinge pelve e cálices, mas SEM dilatação e com fórnices preservados.',
    expB: 'Incorreta. Grau I não atinge a pelve renal.',
    expC: 'Incorreta. Grau IV apresenta dilatação acentuada e tortuosidade ureteral evidente.',
    expD: 'Incorreta. Grau V apresenta dilatação extrema e perda completa das impressões papilares.',
  });

  q({
    id: 'ped-itu-055',
    subtopic: 'Uretrocistografia Miccional e Refluxo Vesicoureteral',
    inst: 'SCMSP',
    year: 2024,
    statement: 'Qual achado radiológico na UCM define o Refluxo Vesicoureteral Grau III?',
    A: 'Refluxo para o ureter, pelve e cálices com dilatação leve a moderada do ureter e da pelve renal, com fórnices caliciais ligeiramente rombos ou arredondados, sem tortuosidade significativa do ureter.',
    B: 'Refluxo com inversão completa da bexiga para a cavidade peritoneal.',
    C: 'Refluxo restrito à uretra bulbar sem ascensão ao trígono vesical.',
    D: 'Tortuosidade extrema com ureter em sifão e ausência de qualquer impressão papilar.',
    ans: 'A',
    comment: 'No Grau III do RVU, o refluxo atinge ureter, pelve e cálices, acompanhando-se de dilatação leve a moderada do ureter (com mínima ou nenhuma tortuosidade) e discreto aplanamento/arredondamento dos fórnices caliciais (fórnices caliciais ligeiramente rombos), mantendo a maior parte das impressões papilares identificáveis.',
    expA: 'Correta. Grau III: dilatação leve a moderada de ureter e pelve com fórnices caliciais discretamente rombos.',
    expB: 'Incorreta. Não existe inversão peritoneal na classificação de RVU.',
    expC: 'Incorreta. Refluxo uretrobulbar é fenômeno uretral, não refluxo vesicoureteral.',
    expD: 'Incorreta. Tortuosidade extrema com perda papilar define o grau V.',
  });

  q({
    id: 'ped-itu-056',
    subtopic: 'Uretrocistografia Miccional e Refluxo Vesicoureteral',
    inst: 'UERJ',
    year: 2023,
    statement: 'Menino de 2 anos com episódios repetidos de pielonefrite realiza Uretrocistografia Miccional. O exame exibe: dilatação moderada a acentuada do ureter com tortuosidade moderada, pelve renal francamente dilatada e perda quase completa do aspecto pontiagudo dos cálices, com a maioria das impressões papilares achatadas ou apagadas. Qual é a graduação desse refluxo?',
    A: 'Refluxo Vesicoureteral Grau IV.',
    B: 'Refluxo Vesicoureteral Grau II.',
    C: 'Refluxo Vesicoureteral Grau I.',
    D: 'Refluxo Vesicoureteral Grau III.',
    ans: 'A',
    comment: 'O Grau IV é caracterizado por dilatação moderada a importante do ureter com tortuosidade ureteral nítida, dilatação expressiva da pelve renal e apagamento evidente da morfologia papilar na maioria dos cálices renais. É classificado como refluxo de alto grau e tem baixa probabilidade de resolução espontânea rápida, com alto risco de cicatrizes renais.',
    expA: 'Correta. Grau IV: dilatação acentuada, tortuosidade moderada e apagamento evidente das impressões papilares.',
    expB: 'Incorreta. Grau II não tem dilatação nem tortuosidade.',
    expC: 'Incorreta. Grau I limita-se ao ureter sem dilatação.',
    expD: 'Incorreta. Grau III apresenta dilatação apenas leve/moderada com preservação parcial das papilas.',
  });

  q({
    id: 'ped-itu-057',
    subtopic: 'Uretrocistografia Miccional e Refluxo Vesicoureteral',
    inst: 'IAMSPE',
    year: 2024,
    statement: 'Lactente de 6 meses com hidronefrose bilateral grave e ITU de repetição realiza UCM que evidencia dilatação maciça e grotesca dos ureteres bilaterais, com acentuada tortuosidade (ureteres em aspecto de serpentina/sifão), pelves renais imensamente dilatadas e perda absoluta de todas as impressões papilares caliciais. Qual é o grau dessa anomalia?',
    A: 'Refluxo Vesicoureteral Grau V.',
    B: 'Refluxo Vesicoureteral Grau III.',
    C: 'Refluxo Vesicoureteral Grau I.',
    D: 'Refluxo Vesicoureteral Grau II.',
    ans: 'A',
    comment: 'O Grau V é a forma mais grave de Refluxo Vesicoureteral. Caracteriza-se por dilatação massiva e grotesca de todo o trato superior, ureter excessivamente tortuoso e alongado ("em sifão" ou serpentina) e cálices completamente balonados com destruição e perda total de qualquer impressão papilar. Associa-se frequentemente a displasia renal congênita e risco extremo de insuficiência renal crônica.',
    expA: 'Correta. Grau V: dilatação maciça grotesca, extrema tortuosidade em serpentina e perda total das impressões papilares.',
    expB: 'Incorreta. Grau III tem dilatação leve/moderada.',
    expC: 'Incorreta. Grau I não atinge cálices.',
    expD: 'Incorreta. Grau II não tem dilatação.',
  });

  q({
    id: 'ped-itu-058',
    subtopic: 'Uretrocistografia Miccional e Refluxo Vesicoureteral',
    inst: 'SMS-SP',
    year: 2024,
    statement: 'Em que momento clínico deve ser agendada e realizada a Uretrocistografia Miccional (UCM) após a cura de um episódio de pielonefrite aguda em um lactente?',
    A: 'Aguardar a cura clínica completa e esterilização da urina confirmada por urocultura negativa (idealmente 2 a 6 semanas após o término da infecção), sob cobertura antibiótica profilática no dia do procedimento.',
    B: 'No primeiro dia de internação hospitalar no momento do pico febril de 40 °C.',
    C: 'Apenas após a criança completar 18 anos de idade.',
    D: 'Durante a infusão da primeira dose de ceftriaxona na sala de choque.',
    ans: 'A',
    comment: 'A UCM NUNCA deve ser realizada na vigência de infecção urinária ativa ou urina infectada, pois a cateterização vesical sob pressão pode introduzir bactérias no trato superior e deflagrar urossepse fulminante. Além disso, as toxinas bacterianas e a inflamação vesical geram relaxamento temporário da junção ureterovesical, produzindo refluxos falso-positivos. Deve-se aguardar a resolução clínica e urocultura estéril (geralmente 2 a 6 semanas após o tratamento), realizando quimioprofilaxia de cobertura no procedimento.',
    expA: 'Correta. Aguardar esterilização da urina (2-6 semanas após o episódio) e realizar sob profilaxia de procedimento.',
    expB: 'Incorreta. Fazer na vigência de febre e infecção ativa dissemina bactérias e causa choque séptico.',
    expC: 'Incorreta. Postergar para 18 anos impede o tratamento e prevenção de cicatrizes na infância.',
    expD: 'Incorreta. Na sala de choque a prioridade é a estabilização hemodinâmica.',
  });

  q({
    id: 'ped-itu-059',
    subtopic: 'Uretrocistografia Miccional e Refluxo Vesicoureteral',
    inst: 'PUC-PR',
    year: 2024,
    statement: 'Por que a fase miccional da Uretrocistografia (aquisição radiográfica contínua durante o ato da micção plena) é de execução indispensável e obrigatória em meninos com suspeita de anomalia congênita urinária?',
    A: 'Porque é exclusivamente durante a micção que a uretra posterior masculina se distende, permitindo o diagnóstico diferencial com Válvula de Uretra Posterior (VUP), caracterizada por uretra prostática dilatada e parada abrupta do fluxo.',
    B: 'Para verificar se o menino apresenta refluxo de contraste para o apêndice ileocecal.',
    C: 'Apenas para avaliar a contratilidade dos músculos trapézio e peitoral maior.',
    D: 'Porque a uretra anterior do menino não tolera contraste durante a fase de enchimento.',
    ans: 'A',
    comment: 'A fase miccional na UCM em meninos é mandatória para avaliar a anatomia da uretra masculina. É somente quando o paciente urina ativamente que a uretra posterior atinge sua distensão funcional máxima. Na presença de Válvula de Uretra Posterior (VUP), observa-se o clássico sinal radiológico: dilatação e balonamento acentuados da uretra prostática posterior com afilamento abrupto ou parada de fluxo na uretra membranosa e bulbar.',
    expA: 'Correta. A fase miccional permite avaliar a distensão da uretra posterior e diagnosticar VUP no menino.',
    expB: 'Incorreta. O contraste urinário não atinge o apêndice cecal.',
    expC: 'Incorreta. Músculos do tronco não têm relação com a anatomia uretral miccional.',
    expD: 'Incorreta. A fase de enchimento é bem tolerada; a fase miccional complementa o diagnóstico dinâmico.',
  });
}
