import { q } from './helper_itu.js';

export function loadSec8() {
  q({
    id: 'ped-itu-060',
    subtopic: 'Cintilografia Renal com DMSA',
    inst: 'USP-SP',
    year: 2024,
    statement: 'Qual é o exame de medicina nuclear considerado padrão-ouro indiscutível para a avaliação da morfologia do córtex renal funcionante e detecção precisa de cicatrizes renais pós-pielonefrite na infância?',
    A: 'Cintilografia Renal Estática com Ácido Dimercaptossuccínico marcado com Tecnécio-99m (DMSA-99mTc).',
    B: 'Cintilografia Dinâmica com DTPA marcado com Gálio-67.',
    C: 'PET-CT com fluordesoxiglicose (18F-FDG) de corpo inteiro.',
    D: 'Cintilografia óssea com pirofosfato de tecnécio.',
    ans: 'A',
    comment: 'A Cintilografia Renal Estática com 99mTc-DMSA é o método mais sensível e específico (padrão-ouro) para quantificar a massa de parênquima renal funcionante e identificar cicatrizes corticais renais (nefropatia de refluxo). O DMSA é avidamente captado pelas células dos túbulos contorcidos proximais e retido no córtex renal, gerando uma imagem de alta definição da integridade cortical.',
    expA: 'Correta. A cintilografia renal com 99mTc-DMSA é o padrão-ouro para avaliação do córtex renal e cicatrizes.',
    expB: 'Incorreta. DTPA é radiofármaco dinâmico para taxa de filtração e drenagem, não para imagem cortical estática.',
    expC: 'Incorreta. PET-FDG não é o método indicado para avaliação de cicatrizes na rotina nefropediátrica.',
    expD: 'Incorreta. Cintilografia óssea avalia remodelação do esqueleto ósseo.',
  });

  q({
    id: 'ped-itu-061',
    subtopic: 'Cintilografia Renal com DMSA',
    inst: 'UNICAMP',
    year: 2024,
    statement: 'Lactente de 11 meses realiza cintilografia renal com DMSA no 5º dia de internação hospitalar por pielonefrite aguda febril. O laudo descreve: "Área focal de hipocaptação do radiofármaco no polo superior do rim esquerdo, sem alteração no contorno renal externo". Qual é o significado fisiopatológico desse achado na fase aguda da infecção?',
    A: 'Área de isquemia microvascular e edema inflamatório intersticial agudo associada à infiltração leucocitária parenquimatosa (pielonefrite aguda ativa em evolução).',
    B: 'Diagnóstico definitivo e irreversível de agenesia congênita do polo superior.',
    C: 'Presença de fístula arteriovenosa congênita de alto débito.',
    D: 'Necrose cortical tubular maciça que exige nefrectomia de urgência.',
    ans: 'A',
    comment: 'Quando realizado na fase aguda da infecção (primeiros 7 a 14 dias), o DMSA revela áreas de hipocaptação (frio) decorrentes da isquemia tecidual, vasoconstrição microvascular reflexa, edema intersticial e disfunção tubular temporária gerados pela invasão bacteriana (pielonefrite aguda). Esse achado comprova o acometimento do parênquima renal, mas ainda não pode ser denominado cicatriz permanente.',
    expA: 'Correta. Hipocaptação na fase aguda traduz edema e isquemia inflamatória focal da pielonefrite.',
    expB: 'Incorreta. Não se trata de agenesia congênita, mas de processo inflamatório agudo adquirido.',
    expC: 'Incorreta. Fístula arteriovenosa apresenta achados vasculares característicos ao Doppler.',
    expD: 'Incorreta. Não há necrose cortical generalizada nem indicação cirúrgica.',
  });

  q({
    id: 'ped-itu-062',
    subtopic: 'Cintilografia Renal com DMSA',
    inst: 'ENARE',
    year: 2024,
    statement: 'Para confirmar com segurança se um episódio grave de pielonefrite aguda na infância evoluiu com formação de Cicatriz Renal Permanente (crônica) ou se houve regeneração completa do parênquima, qual é o intervalo de tempo mínimo recomendado após a infecção aguda para a realização da cintilografia renal com DMSA de controle?',
    A: 'Pelo menos 4 a 6 meses após o término do tratamento do episódio agudo.',
    B: 'Apenas 48 horas após a última dose do antibiótico oral.',
    C: 'Exatamente 7 dias após o desaparecimento da febre.',
    D: 'Apenas após a puberdade aos 16 anos de idade.',
    ans: 'A',
    comment: 'O processo de resolução do edema inflamatório, remodelação tecidual e cicatrização renal após uma pielonefrite aguda leva vários meses. Estudos cintilográficos demonstram que cerca de metade das áreas de hipocaptação observadas na fase aguda desaparecem com restituição ad integrum. Portanto, para documentar cicatriz permanente (retração cortical definitiva com perda de função tubular local), a cintilografia com DMSA deve ser realizada após no mínimo 4 a 6 meses do episódio.',
    expA: 'Correta. O intervalo de 4 a 6 meses é o tempo mínimo preconizado para diagnosticar cicatriz renal permanente.',
    expB: 'Incorreta. Em 48 horas o edema inflamatório ainda persiste, gerando confusão diagnóstica.',
    expC: 'Incorreta. 7 dias é fase subaguda precoce com disfunção tubular reversível ativa.',
    expD: 'Incorreta. Postergar anos impede medidas protetoras precoces e vigilância de hipertensão.',
  });

  q({
    id: 'ped-itu-063',
    subtopic: 'Cintilografia Renal com DMSA',
    inst: 'FMRP-USP',
    year: 2024,
    statement: 'Na análise quantitativa da captação relativa do radiofármaco na cintilografia estática com DMSA, como é expressa a função renal diferencial normal de cada rim em uma criança?',
    A: 'Cada rim deve contribuir com 45% a 55% da função renal total (assimetria fisiológica aceitável de até 10%).',
    B: 'O rim direito deve responder por 90% da função e o esquerdo por apenas 10%.',
    C: 'A captação normal exige 100% de captação em um rim e 0% no rim contralateral.',
    D: 'A captação do DMSA não permite qualquer quantificação percentual comparativa.',
    ans: 'A',
    comment: 'A cintilografia com DMSA calcula com precisão a contribuição percentual de cada rim para a massa renal total funcionante (função diferencial). Em condições normais, cada rim responde por aproximadamente metade da função global, sendo considerados normais valores entre 45% e 55% para cada rim. Uma função diferencial inferior a 40-45% em um rim denota perda significativa de massa parenquimatosa funcionante (hipoplasia, displasia ou dano cicatricial grave por pielonefrite).',
    expA: 'Correta. A função normal de cada rim situa-se entre 45% e 55% da captação global.',
    expB: 'Incorreta. Assimetria de 90/10 indica atrofia ou exclusão grave do rim hipocaptante.',
    expC: 'Incorreta. Captação unilateral total indica rim único funcionante.',
    expD: 'Incorreta. O cálculo quantitativo percentual é um dos pontos fortes do exame de DMSA.',
  });

  q({
    id: 'ped-itu-064',
    subtopic: 'Cintilografia Renal com DMSA',
    inst: 'SCMSP',
    year: 2024,
    statement: 'Qual é a diferença conceitual e de indicação clínica primária entre a Cintilografia Renal Estática com DMSA e a Cintilografia Renal Dinâmica com DTPA (ou MAG3)?',
    A: 'O DMSA fixa-se nos túbulos proximais e avalia a integridade do parênquima/córtex renal e cicatrizes; o DTPA/MAG3 é filtrado/excretado continuamente na urina e avalia a dinâmica de drenagem, curvas de esvaziamento e presença de estenose obstrutiva (uropatia obstrutiva).',
    B: 'O DMSA serve exclusivamente para avaliar litíase urinária de ácido úrico, enquanto o DTPA diagnostica cistite.',
    C: 'O DTPA avalia refluxo vesicoureteral retrógrado e o DMSA mede a pressão arterial na artéria renal.',
    D: 'Não há qualquer diferença, sendo radiofármacos idênticos com o mesmo alvo molecular.',
    ans: 'A',
    comment: 'O DMSA (ácido dimercaptossuccínico) é um exame estático: o traçador fixa-se no córtex e permanece retido nas células tubulares, sendo ideal para detectar defeitos parenquimatosos e cicatrizes renais. O DTPA (ou MAG3) é um exame dinâmico: o radiofármaco é filtrado pelos glomérulos e eliminado rapidamente na urina, gerando curvas renográficas de captação e excreção, sendo o método de eleição com estímulo de furosemida para diferenciar hidronefrose não obstrutiva de obstrução anatômica real (como estenose de JUP).',
    expA: 'Correta. DMSA avalia parênquima/cicatrizes (estático) e DTPA/MAG3 avalia excreção/obstrução (dinâmico).',
    expB: 'Incorreta. DMSA não avalia cálculos de ácido úrico.',
    expC: 'Incorreta. Refluxo anatômico é avaliado por UCM e pressão de artéria renal não é aferida por cintilografia.',
    expD: 'Incorreta. São radiofármacos completamente distintos com cinéticas e indicações diferentes.',
  });

  q({
    id: 'ped-itu-065',
    subtopic: 'Cintilografia Renal com DMSA',
    inst: 'UERJ',
    year: 2023,
    statement: 'Uma menina de 12 anos em acompanhamento nefrológico apresenta cintilografia com DMSA evidenciando cicatrizes corticais bilaterais extensas e função renal diferencial de 30% à esquerda e 70% à direita, com taxa de filtração glomerular estimada em 65 mL/min/1,73m². Quais são as complicações clínicas a longo prazo para as quais essa paciente apresenta risco expressivo?',
    A: 'Hipertensão arterial sistêmica secundária (renovascular/parenquimatosa), proteinúria secundária a hiperfiltração dos néfrons remanescentes, pré-eclâmpsia futura na gestação e progressão para doença renal crônica.',
    B: 'Diabetes mellitus tipo 1 descompensado e hipotireoidismo autoimune de Hashimoto.',
    C: 'Hemorragia digestiva alta por varizes de esôfago isoladas.',
    D: 'Fibrose cística com esteatorreia crônica e bronquiectasias difusas.',
    ans: 'A',
    comment: 'A nefropatia de refluxo com cicatrizes renais permanentes extensas provoca perda de néfrons. Os néfrons sobreviventes sofrem hipertrofia e hiperfiltração adaptativa com esclerose focal e proteinúria progressiva. A isquemia parenquimatosa focal ativa o sistema renina-angiotensina-aldosterona, causando hipertensão arterial secundária em até 10-20% das crianças afetadas, além de complicações obstétricas graves na vida reprodutiva e risco de falência renal crônica.',
    expA: 'Correta. Hipertensão, proteinúria, pré-eclâmpsia e doença renal crônica são sequelas clássicas de cicatrizes bilaterais.',
    expB: 'Incorreta. Cicatrizes renais não causam destruição autoimune de ilhotas pancreáticas ou da tireoide.',
    expC: 'Incorreta. Varizes esofágicas decorrem de hipertensão portal hepática.',
    expD: 'Incorreta. Fibrose cística é mutação no gene CFTR.',
  });

  q({
    id: 'ped-itu-066',
    subtopic: 'Cintilografia Renal com DMSA',
    inst: 'IAMSPE',
    year: 2024,
    statement: 'Na abordagem investigativa de imagem de crianças após ITU febril, qual é o fundamento da estratégia diagnóstica denominada "Abordagem Top-Down" (de cima para baixo)?',
    A: 'Realizar a cintilografia com DMSA na fase aguda; se o DMSA for estritamente normal (confirmando que não houve envolvimento do parênquima renal), dispensa-se a Uretrocistografia Miccional invasiva, realizando UCM apenas nos pacientes com DMSA alterado (com risco real de refluxo de alto grau e cicatrizes).',
    B: 'Realizar biópsia renal antes de qualquer exame de urina em todos os lactentes.',
    C: 'Iniciar obrigatoriamente por urografia excretora com contraste intravenoso.',
    D: 'Indicar cistectomia total precoce caso o DMSA revele rins normais.',
    ans: 'A',
    comment: 'A abordagem "Top-Down" propõe que o órgão nobre que realmente precisa ser protegido é o parênquima renal. Realiza-se o DMSA na fase aguda: se o DMSA estiver normal, o rim não foi afetado e o risco de refluxo de alto grau clinicamente relevante é mínimo, poupando a criança do desconforto, radiação e riscos da Uretrocistografia Miccional. A UCM fica restrita àqueles com DMSA alterado.',
    expA: 'Correta. A abordagem Top-Down usa o DMSA para selecionar quais pacientes realmente necessitam de UCM.',
    expB: 'Incorreta. Biópsia renal não é exame de triagem de ITU.',
    expC: 'Incorreta. Urografia não é recomendada na rotina pediátrica atual.',
    expD: 'Incorreta. Cistectomia é cirurgia oncológica de ressecção vesical.',
  });

  q({
    id: 'ped-itu-067',
    subtopic: 'Cintilografia Renal com DMSA',
    inst: 'SMS-SP',
    year: 2024,
    statement: 'Por que o laudo de uma cintilografia com DMSA realizada no 3º dia de pielonefrite aguda febril que descreve hipocaptação focal NÃO deve utilizar o termo "cicatriz renal definitiva"?',
    A: 'Porque a hipocaptação na fase aguda reflete inflamação e edema tecidual transitório que pode regredir totalmente com a cura da infecção, sendo necessária uma cintilografia tardia após 6 meses para comprovar se houve ou não sequela permanente.',
    B: 'Porque o DMSA na fase aguda é 100% ineficaz e nunca detecta alterações renais.',
    C: 'Porque os rins de crianças menores de 2 anos não absorvem o tecnécio-99m.',
    D: 'Porque a cicatriz renal é um termo reservado exclusivamente para lesões traumáticas penetrantes por arma branca.',
    ans: 'A',
    comment: 'Na fase aguda da infecção bacteriana, o edema, a infiltração por neutrófilos e a isquemia reversível provocam disfunção transitória das células tubulares, impedindo a captação do DMSA naquele segmento. Em cerca de 40 a 60% dos casos, após o tratamento antimicrobiano adequado, o parênquima se recupera integralmente sem qualquer retração tecidual residual. Por isso, na fase aguda fala-se em "defeito de captação compatível com pielonefrite aguda", reservando "cicatriz" para defeitos persistentes após 6 meses.',
    expA: 'Correta. O defeito agudo pode ser puramente inflamatório e reversível, exigindo controle após 6 meses.',
    expB: 'Incorreta. O DMSA agudo é altamente sensível para documentar a presença de pielonefrite aguda.',
    expC: 'Incorreta. O córtex de lactentes capta o DMSA de forma eficaz.',
    expD: 'Incorreta. Cicatriz renal é a sequela clássica da pielonefrite bacteriana na nefropatia de refluxo.',
  });
}
