import { q } from './helper_itu.js';

export function loadSec9() {
  q({
    id: 'ped-itu-068',
    subtopic: 'Manejo do Refluxo Vesicoureteral',
    inst: 'USP-SP',
    year: 2024,
    statement: 'Lactente feminina de 10 meses assintomática apresenta diagnóstico de Refluxo Vesicoureteral unilateral Grau II na UCM. A ultrassonografia e a cintilografia com DMSA mostram rins normais e sem cicatrizes. Qual é a história natural do RVU de baixo grau (graus I e II) e qual é a conduta preconizada?',
    A: 'Apresenta altíssima taxa de resolução espontânea com o crescimento somático da criança (> 80-90% de cura sem cirurgia); preconiza-se conduta conservadora expectante com vigilância clínica rigorosa e orientação familiar.',
    B: 'Evolui invariavelmente para atrofia renal irreversível em 6 meses se não for operada imediatamente.',
    C: 'Indicação obrigatória de nefrectomia parcial laparoscópica de urgência.',
    D: 'Internação contínua por 1 ano para cateterismo intermitente a cada 2 horas.',
    ans: 'A',
    comment: 'O mecanismo do RVU primário reside na brevidade congênita do túnel ureteral submucoso intravesical. Conforme a criança cresce e a bexiga se expande, o trajeto do ureter na parede vesical se alonga naturalmente, fortalecendo o mecanismo valvular antirrefluxo. No RVU de baixo grau (graus I e II), mais de 80 a 90% dos casos curam espontaneamente nos primeiros anos de vida. A conduta é conservadora, com orientações aos pais para diagnosticar rapidamente eventuais febres e vigilância clínica.',
    expA: 'Correta. Alta taxa de resolução espontânea (> 80-90%) e conduta conservadora com vigilância clínica.',
    expB: 'Incorreta. RVU de baixo grau não causa atrofia acelerada e raramente requer intervenção cirúrgica.',
    expC: 'Incorreta. Cirurgia radical mutiladora é completamente descabida.',
    expD: 'Incorreta. Cateterismo intermitente de rotina para RVU grau II assintomático é incorreto e deletério.',
  });

  q({
    id: 'ped-itu-069',
    subtopic: 'Manejo do Refluxo Vesicoureteral',
    inst: 'UNICAMP',
    year: 2024,
    statement: 'Qual é o papel primário da quimioprofilaxia antimicrobiana contínua em lactentes com diagnóstico de Refluxo Vesicoureteral de alto grau (graus IV e V)?',
    A: 'Manter a urina estéril para impedir que a bacteriúria atinja o parênquima renal sob alta pressão retrógrada, prevenindo novos episódios de pielonefrite aguda e a formação de novas cicatrizes renais.',
    B: 'Promover a dilatação farmacológica da junção ureterovesical facilitando a descida de cálculos.',
    C: 'Acelerar o fechamento cirúrgico da bexiga em crianças com extrofia cloacal.',
    D: 'Estimular a secreção de eritropoietina medular em até 500%.',
    ans: 'A',
    comment: 'O refluxo de urina estéril (sem bactérias) em um sistema de baixa pressão raramente lesa o parênquima renal. O dano grave e as cicatrizes ocorrem quando urina infectada reflui até os cálices e túbulos renais sob a alta pressão da contração vesical ("nefropatia de refluxo"). A quimioprofilaxia diária com dose baixa de antibiótico mantém a urina estéril, evitando que a bexiga funcione como vetor de pielonefrite até a resolução espontânea ou correção cirúrgica.',
    expA: 'Correta. Manter a urina estéril e prevenir pielonefrites e cicatrizes renais permanentes.',
    expB: 'Incorreta. A profilaxia não atua na dilatação da junção nem visa expulsar cálculos.',
    expC: 'Incorreta. A profilaxia não trata defeitos de fechamento de parede como extrofia.',
    expD: 'Incorreta. Antimicrobianos não possuem efeito estimulador direto sobre a eritropoietina.',
  });

  q({
    id: 'ped-itu-070',
    subtopic: 'Manejo do Refluxo Vesicoureteral',
    inst: 'ENARE',
    year: 2024,
    statement: 'Qual é a intervenção cirúrgica clássica considerada padrão-ouro definitivo para a correção do Refluxo Vesicoureteral anatômico de alto grau em crianças, com taxas de sucesso curativo superiores a 95% a 98%?',
    A: 'Ureterocistoneostomia (Reimplante Ureteral aberto ou laparoscópico/robótico, como as técnicas de Cohen ou Politano-Leadbetter).',
    B: 'Transplante renal heterotópico em fossa ilíaca contralateral.',
    C: 'Bandeamento dos ramos principais das artérias renais.',
    D: 'Ressecção do músculo detrusor com colocação de esfíncter artificial.',
    ans: 'A',
    comment: 'A cirurgia de Reimplante Ureteral (ou ureterocistoneostomia), realizada por via aberta (técnica intravesical de Cohen ou extravesical de Lich-Gregoir) ou por via laparoscópica/robótica, consiste na criação cirúrgica de um novo túnel submucoso longo para o ureter dentro da parede vesical (relação comprimento/diâmetro de 5:1). Apresenta taxa de cura definitiva superior a 95-98%, sendo o padrão-ouro cirúrgico.',
    expA: 'Correta. O reimplante ureteral (ureterocistoneostomia) é o padrão-ouro cirúrgico com > 95% de sucesso.',
    expB: 'Incorreta. O transplante renal destina-se a doença renal terminal, não ao tratamento inicial de RVU.',
    expC: 'Incorreta. Bandeamento de artérias renais não existe para tratar anomalias das vias urinárias.',
    expD: 'Incorreta. Esfíncter artificial não trata a competência da junção ureterovesical.',
  });

  q({
    id: 'ped-itu-071',
    subtopic: 'Manejo do Refluxo Vesicoureteral',
    inst: 'FMRP-USP',
    year: 2024,
    statement: 'Menina de 3 anos com RVU unilateral Grau III persistente e duas infecções urinárias febris é candidata ao tratamento endoscópico por cistoscopia com injeção subureteral de copolímero de Dextranômero e Ácido Hialurônico (Deflux / técnica STING). Qual é o mecanismo de ação e as principais vantagens desse procedimento minimamente invasivo?',
    A: 'A injeção do agente volumétrico sob a mucosa da porção terminal do ureter cria um suporte mecânico posterior firme (coxim submucoso) que coapta a luz ureteral e impede o refluxo retrógrado de urina, com baixíssima morbidade e sem necessidade de incisões abdominais.',
    B: 'O Deflux dissolve a parede da bexiga permitindo drenagem direta da urina para o retroperitônio.',
    C: 'A substância injetada esteriliza a urina para o resto da vida por liberação contínua de penicilina.',
    D: 'O procedimento paralisa totalmente o esfíncter uretral externo tornando a micção involuntária.',
    ans: 'A',
    comment: 'A técnica endoscópica de injeção subureteral (STING ou HIT) é um procedimento ambulatorial minimamente invasivo realizado por cistoscopia sob anestesia geral de curta duração. O cirurgião injeta um gel inerte e biocompatível (Dextranômero/Ácido Hialurônico - Deflux) imediatamente abaixo do óstio ureteral submucoso, elevando o assoalho ureteral e restaurando o mecanismo valvular. Apresenta taxa de sucesso de 75 a 85% e baixíssimo índice de complicações.',
    expA: 'Correta. Cria suporte submucoso (coxim) que coapta o meato e impede refluxo por via endoscópica.',
    expB: 'Incorreta. O agente não dissolve a parede da bexiga nem drena urina para o retroperitônio.',
    expC: 'Incorreta. O Deflux é um agente volumétrico inerte, sem liberação de antimicrobianos.',
    expD: 'Incorreta. O procedimento preserva integralmente a continência urinária e o esfíncter uretral.',
  });

  q({
    id: 'ped-itu-072',
    subtopic: 'Manejo do Refluxo Vesicoureteral',
    inst: 'SCMSP',
    year: 2024,
    statement: 'Qual das seguintes situações clínicas em uma criança com Refluxo Vesicoureteral em uso de quimioprofilaxia antibiótica regular representa indicação formal inequívoca para intervenção cirúrgica (reimplante ou injeção endoscópica)?',
    A: 'Ocorrência de novo episódio de Pielonefrite Aguda febril na vigência de profilaxia antimicrobiana correta ("infecção de escape" / breakthrough infection) ou surgimento documentado de novas cicatrizes corticais ao DMSA.',
    B: 'Presença isolada de um sedimento urinário com 5 leucócitos por campo em criança afebril e assintomática.',
    C: 'Ganho ponderal acelerado da criança no percentil 90.',
    D: 'Fechamento espontâneo do refluxo verificado na UCM de controle.',
    ans: 'A',
    comment: 'A ocorrência de pielonefrite febril na vigência de quimioprofilaxia correta ("infecção de escape" ou breakthrough UTI) demonstra que a proteção medicamentosa falhou e o parênquima renal está sob risco iminente de dano permanente adicional. Essa situação, assim como o aparecimento ou progressão de cicatrizes renais confirmadas ao DMSA, constitui indicação formal absoluta de correção cirúrgica antirrefluxo.',
    expA: 'Correta. Infecção de escape sob profilaxia correta e surgimento de novas cicatrizes indicam cirurgia.',
    expB: 'Incorreta. Leucocitúria assintomática isolada não autoriza cirurgia urológica.',
    expC: 'Incorreta. Bom desenvolvimento pôndero-estatural é sinal de evolução favorável.',
    expD: 'Incorreta. O fechamento espontâneo do RVU significa cura, dispensando cirurgia.',
  });

  q({
    id: 'ped-itu-073',
    subtopic: 'Manejo do Refluxo Vesicoureteral',
    inst: 'UERJ',
    year: 2023,
    statement: 'Menina de 5 anos com RVU bilateral Grau III e ITUs de repetição apresenta histórico de urinar apenas 2 vezes ao dia, apresentar perdas urinárias na calcinha com manobras de contenção (cruzar as pernas) e defecar a cada 4 a 5 dias fezes ressecadas em cíbalos dolorosos (escala de Bristol 1). Por que o tratamento agressivo dessa Disfunção do Trato Urinário Inferior e da Constipação Intestinal é prioritário antes de qualquer decisão cirúrgica antirrefluxo?',
    A: 'Porque a hiperatividade detrusora e o aumento das pressões intravesicais causadas pelo reto repleto perpetuam o refluxo vesicoureteral; o tratamento clínico da disfunção miccional e intestinal frequentemente cura ou melhora o refluxo e previne o insucesso da cirurgia.',
    B: 'Porque a constipação intestinal impede a anestesia geral devido à produção excessiva de gás hélio no cólon.',
    C: 'Porque o tratamento cirúrgico do RVU cura a constipação crônica em 100% das vezes.',
    D: 'Porque laxativos orais dissolvem o ureter defeituoso tornando a cirurgia desnecessária.',
    ans: 'A',
    comment: 'Existe uma íntima interação embriológica e funcional entre a bexiga e o reto (Síndrome de Eliminação Disfuncional / DTUI). O reto distendido por fezes empacotadas comprime a base da bexiga e o trígono, desencadeando contrações involuntárias do detrusor sob alta pressão, o que agrava o refluxo e facilita a ascensão de bactérias fecais. Se o cirurgião operar o RVU sem tratar a bexiga e o intestino, as altas pressões vesicais levarão à falha precoce da cirurgia antirrefluxo e a novas infecções.',
    expA: 'Correta. O tratamento da disfunção miccional e da constipação reduz as pressões vesicais e pode curar o RVU sem cirurgia.',
    expB: 'Incorreta. Justificativa absurda sobre gás hélio.',
    expC: 'Incorreta. O reimplante ureteral não trata a incoordenação esfincteriana ou o intestino.',
    expD: 'Incorreta. Laxativos regulam o trânsito intestinal e não destroem tecidos urológicos.',
  });

  q({
    id: 'ped-itu-074',
    subtopic: 'Manejo do Refluxo Vesicoureteral',
    inst: 'IAMSPE',
    year: 2024,
    statement: 'Em meninos com Refluxo Vesicoureteral grave (graus IV ou V) e episódios repetidos de pielonefrite aguda na vigência de prepúcio com anel fótico e orifício estreito, qual procedimento cirúrgico urológico simples reduz drasticamente (em mais de 80 a 90%) o risco de novas ITUs?',
    A: 'Postectomia (Circuncisão).',
    B: 'Orquidopexia bilateral de rotina.',
    C: 'Ressecção do colo vesical.',
    D: 'Secção bilateral dos nervos pudendos.',
    ans: 'A',
    comment: 'A superfície interna do prepúcio possui alta concentração de receptores para as fímbrias da Escherichia coli uropatogênica, funcionando como um grande reservatório de colonização bacteriana no menino. Estudos demonstram que a circuncisão (postectomia) reduz a taxa de colonização bacteriana periuretral e diminui em até 90% a incidência de infecções do trato urinário em meninos com uropatias predisponentes de alto risco (como RVU dilatante).',
    expA: 'Correta. A postectomia elimina o reservatório prepucial de uropatógenos, reduzindo em ~90% o risco de ITU no menino com RVU.',
    expB: 'Incorreta. Orquidopexia trata criptorquidia, sem relação com colonização bacteriana urinária.',
    expC: 'Incorreta. Ressecção do colo vesical causaria incontinência urinária grave.',
    expD: 'Incorreta. Denervação pudenda causaria incontinência fecal e urinária permanente.',
  });

  q({
    id: 'ped-itu-075',
    subtopic: 'Manejo do Refluxo Vesicoureteral',
    inst: 'SMS-SP',
    year: 2024,
    statement: 'Após a realização de um Reimplante Ureteral cirúrgico ou injeção endoscópica de Deflux para tratamento de RVU, qual exame de imagem não invasivo e em que momento ele deve ser obrigatoriamente realizado para descartar Obstrução Iatrogênica da junção ureterovesical?',
    A: 'Ultrassonografia de Rins e Vias Urinárias realizada entre 4 e 6 semanas de pós-operatório (para avaliar hidronefrose obstrutiva pós-operatória).',
    B: 'Tomografia de crânio com contraste aos 6 meses.',
    C: 'Uretrocistografia miccional na sala de recuperação pós-anestésica.',
    D: 'Radiografia simples de ossos longos aos 10 dias.',
    ans: 'A',
    comment: 'A principal complicação precoce do reimplante ureteral ou da injeção de agentes de preenchimento é a estenose/obstrução da junção ureterovesical decorrente de edema excessivo, hematoma ou criação de um túnel submucoso demasiadamente apertado. Recomenda-se a realização de uma Ultrassonografia renal após 4 a 6 semanas para assegurar que não há ureterohidronefrose obstrutiva secundária à intervenção cirúrgica.',
    expA: 'Correta. USG de controle pós-operatório (4-6 semanas) descarta estenose/obstrução iatrogênica da junção.',
    expB: 'Incorreta. TC de crânio não tem correlação com complicações locais urológicas.',
    expC: 'Incorreta. A UCM imediata na RPA é invasiva e contraindicada na ferida cirúrgica fresca.',
    expD: 'Incorreta. Raio X de ossos longos não avalia vias urinárias.',
  });
}
