import { q } from './helper_cardio_rev.js';

export function loadPart1() {
  q({
    id: 'ped-cardio-rev-01',
    subtopic: 'Comunicação Interventricular (CIV)',
    inst: 'USP-SP',
    year: 2024,
    statement: 'Lactente de 3 meses de vida é trazido para consulta por sudorese profusa durante as mamadas e baixo ganho de peso. Ao exame físico: taquipneico (FR: 64 irpm), acianótico, pulsos periféricos palpáveis simétricos. Ausculta cardíaca revela sopro holossistólico 4+/6+ rude em borda esternal esquerda baixa associado a frêmito palpável e sopro mesodiastólico suave em ápice. O ecocardiograma transtorácico confirma comunicação interventricular (CIV) perimembranosa com diâmetro de 8 mm e dilatação significativa de átrio e ventrículo esquerdos. Em relação à fisiopatologia e ao manejo clínico inicial dessa cardiopatia congênita com hiperfluxo pulmonar, assinale a conduta farmacológica mais apropriada para alívio dos sintomas de insuficiência cardíaca:',
    A: 'Iniciar diurético de alça (furosemida) associado a vasodilatador redutor de pós-carga (inibidor da ECA como captopril) e suporte nutricional hipercalórico, enquanto se programa a correção cirúrgica eletiva.',
    B: 'Iniciar betabloqueador em dose máxima e indometacina intravenosa para fechar a CIV farmacologicamente.',
    C: 'Suspender todo suporte oral e indicar cateterismo intervencionista para septostomia atrial com balão de urgência.',
    D: 'Prescrever apenas suplementação de ferro oral, pois o sopro mesodiastólico no ápice confirma estenose mitral congênita associada que contraindica diuréticos.',
    ans: 'A',
    comment: 'A CIV perimembranosa ampla produz um grande shunt esquerda-direita (VE -> VD), levando a hiperfluxo pulmonar maciço e aumento do retorno venoso pulmonar para o átrio esquerdo e ventrículo esquerdo (sobrecarga volumétrica de câmaras esquerdas). O sopro mesodiastólico em ápice (mitral) decorre do hiperfluxo relativo através da valva mitral aberta. O tratamento clínico inicial para controle da congestão pulmonar e insuficiência cardíaca consiste na combinação de diurético (furosemida) com vasodilatador sistêmico redutor de pós-carga (captopril / IECA), que reduz a resistência vascular sistêmica e diminui a magnitude do shunt E-D, associado a aporte nutricional calórico concentrado antes da correção cirúrgica.',
    expA: 'Correta. Furosemida associada a IECA (captopril) alivia a congestão pulmonar e reduz o shunt esquerda-direita antes do reparo cirúrgico definitivo.',
    expB: 'Incorreta. Anti-inflamatórios como indometacina fecham o canal arterial (PCA), mas não têm qualquer efeito sobre o fechamento de uma CIV.',
    expC: 'Incorreta. Septostomia de Rashkind é indicada na TGA com hipóxia refratária, não na CIV.',
    expD: 'Incorreta. O sopro mesodiastólico em ápice decorre de hiperfluxo relativo pela valva mitral pelo excesso de retorno venoso pulmonar, e não estenose mitral primária.',
  });

  q({
    id: 'ped-cresc-rev-02', // wait: let's ensure id is 'ped-cardio-rev-02'
    id: 'ped-cardio-rev-02',
    subtopic: 'Tetralogia de Fallot',
    inst: 'UNICAMP',
    year: 2024,
    statement: 'Lactente de 8 meses, sabidamente portador de Tetralogia de Fallot, dá entrada no pronto-socorro infantil apresentando episódio de choro vigoroso prolongado seguido de agitação psicomotora, cianose labial e periungueal intensa, palidez, respiração rápida e profunda (hiperpneia paroxística) e diminuição súbita da intensidade do sopro sistólico ejetivo pulmonar que habitualmente apresentava. A oximetria de pulso revela saturação de 62% em ar ambiente. Diante de uma clássica crise de hipóxia (crise hipercianótica ou "spelling"), qual é a sequência imediata de medidas recomendadas?',
    A: 'Manter a criança em posição genupeitoral (joelho-tórax), administrar oxigênio inalatório, morfina subcutânea/intravenosa e infusão cautelosa de volume e betabloqueador (esmolol/propranolol).',
    B: 'Administrar imediatamente digitálico intravenoso em bolus e colocar o paciente em posição de Trendelenburg com cabeça pendente.',
    C: 'Indicar intubação orotraqueal imediata com ventilação por pressão positiva em alta frequência sem qualquer sedação prévia.',
    D: 'Administrar furosemida intravenosa em alta dose e prostaglândina E1 para fechar o canal arterial.',
    ans: 'A',
    comment: 'A crise de hipóxia na Tetralogia de Fallot decorre do espasmo agudo do infundíbulo muscular subpulmonar associado a queda da Resistência Vascular Sistêmica (RVS), o que desvia quase todo o sangue desoxigenado do VD diretamente para a aorta através da CIV ampla (aumento brutal do shunt D-E). O sopro sistólico diminui porque menos sangue consegue atravessar a via de saída estenosada do VD. O manejo de emergência exige: 1) Posição genupeitoral (knee-chest): flexiona os membros inferiores sobre o abdome, dobrando as artérias femorais e aumentando agudamente a RVS, forçando o sangue do VD a entrar na artéria pulmonar; 2) Oxigênio e Morfina (0,1 a 0,2 mg/kg): acalma a criança, diminui a taquipneia e relaxa a musculatura infundibular subpulmonar; 3) Expansão volêmica cautelosa e Betabloqueador intravenoso (esmolol ou propranolol) para abortar o espasmo infundibular.',
    expA: 'Correta. Posição genupeitoral + O2 + morfina + hidratação e betabloqueador constituem o tratamento de primeira linha da crise hipercianótica de Fallot.',
    expB: 'Incorreta. Digitálicos são inotrópicos positivos que aumentam a contratilidade miocárdica e pioram o espasmo obstrutivo infundibular.',
    expC: 'Incorreta. A intubação sem sedação aprofunda a agitação e o estresse adrenérgico, agravando a crise de hipóxia.',
    expD: 'Incorreta. Furosemida causa hipovolemia, reduz a pré-carga do VD e agrava dramaticamente o shunt direita-esquerda.',
  });

  q({
    id: 'ped-cardio-rev-03',
    subtopic: 'Coarctação da Aorta',
    inst: 'FMUSP',
    year: 2024,
    statement: 'Menino de 10 anos é submetido a exame físico pré-participação esportiva na escola. O examinador identifica sopro telessistólico suave audível na região interescapular esquerda posterior e nota que a pressão arterial aferida no membro superior direito é de 142x88 mmHg (> percentil 99 para idade e sexo). À palpação dos pulsos, os pulsos radiais são amplos e cheios, enquanto os pulsos femorais e pediosos são nitidamente débeis e retardados (assimetria de pulsos com atraso braquiofemoral). A radiografia de tórax evidencia erosões nas bordas inferiores das 4ª a 8ª costelas posteriores ("Sinal de Roesler"). Qual é a principal hipótese diagnóstica e qual anomalia congênita valvar cardíaca associada ocorre em mais de 50% desses pacientes?',
    A: 'Coarctação de Aorta; Valva Aórtica Bicúspide.',
    B: 'Tetralogia de Fallot; Valva Pulmonar Quadricúspide.',
    C: 'Comunicação Interatrial; Prolapso de Valva Tricúspide.',
    D: 'Tronco Arterioso Comum; Estenose Mitral.',
    ans: 'A',
    comment: 'O quadro clínico é clássico de Coarctação da Aorta (estenose congênita do lúmen aórtico, habitualmente na região justaductal, próxima à inserção do ligamento arterioso e após a emergência da artéria subclávia esquerda): hipertensão arterial em membros superiores associada a pulsos femorais filiformes/ausentes e atraso de pulso braquiofemoral. O sopro interescapular posterior reflete o fluxo turbulento no ponto estenosado. O Sinal de Roesler (entalhes ou corrosões nas bordas inferiores das costelas posteriores) resulta do hiperfluxo e pulsação contínua de artérias intercostais colaterais dilatadas. A associação congênita mais comum (presente em 50% a 70% dos casos) é a Valva Aórtica Bicúspide.',
    expA: 'Correta. Coarctação de Aorta associada a Valva Aórtica Bicúspide é a combinação clássica.',
    expB: 'Incorreta. Fallot cursa com hipofluxo pulmonar e cianose, sem hipertensão de membros superiores nem sinal de Roesler.',
    expC: 'Incorreta. A CIA não gera hipertensão de membros superiores nem assimetria de pulsos femorais.',
    expD: 'Incorreta. O tronco arterioso é cardiopatia cianogênica com tronco vascular único ejetor.',
  });

  q({
    id: 'ped-cardio-rev-04',
    subtopic: 'Persistência do Canal Arterial (PCA)',
    inst: 'UFRJ',
    year: 2024,
    statement: 'Recém-nascido pré-termo de 28 semanas de idade gestacional, peso de nascimento 1.050 g, com 5 dias de vida, em ventilação mecânica por síndrome do desconforto respiratório, passa a apresentar episódios repetidos de apneia, necessidade de aumento dos parâmetros ventilatórios e da FiO2, pulsos periféricos amplos e saltitantes ("em martelo d\'água"), precórdio hiperdinâmico e sopro contínuo em maquinaria (sopro de Gibson) audível em borda esternal esquerda alta infraclavicular. O ecocardiograma confirma canal arterial pérvio de 3,5 mm com grande shunt esquerda-direita e sobrecarga de câmaras esquerdas. Qual é o tratamento farmacológico inicial indicado para promover o fechamento do canal arterial no prematuro sintomático?',
    A: 'Infusão contínua de Prostaglandina E1 (alprostadil) em dose dobrada.',
    B: 'Inibidores da ciclo-oxigenase (como Ibuprofeno intravenoso ou oral, ou Indometacina intravenosa).',
    C: 'Nitroprussiato de sódio associado a epinefrina contínua.',
    D: 'Propanolol em altas doses associado a amiodarona.',
    ans: 'B',
    comment: 'A patência do canal arterial na vida intrauterina é mantida ativamente pelas prostaglandinas vasodilatadoras circulantes (principalmente PGE2) produzidas pela placenta e pelo próprio endotélio ductal, somadas à baixa tensão de oxigênio fetal. No prematuro, a sensibilidade às prostaglandinas é maior e o fechamento espontâneo frequentemente falha. Quando clinicamente significativo (com repercussão hemodinâmica, pulsos amplos em martelo d\'água, sopro contínuo em maquinaria e piora ventilatória), o tratamento farmacológico de escolha baseia-se na inibição da síntese de prostaglandinas com inibidores da ciclo-oxigenase (Ibuprofeno ou Indometacina; o ibuprofeno é frequentemente preferido pelo menor perfil de toxicidade renal e vasoconstrição mesentérica).',
    expA: 'Incorreta. A Prostaglandina E1 mantém o canal aberto; na PCA com hiperfluxo o objetivo é fechar o canal.',
    expB: 'Correta. Ibuprofeno ou Indometacina inibem a ciclo-oxigenase, reduzem a síntese de PGE2 e promovem a constrição e fechamento do canal arterial.',
    expC: 'Incorreta. Não são fármacos indicados para fechamento ductal.',
    expD: 'Incorreta. Betabloqueador e amiodarona tratam arritmias, não promovem fechamento de PCA.',
  });

  q({
    id: 'ped-cardio-rev-05',
    subtopic: 'Transposição das Grandes Artérias (TGA)',
    inst: 'UNIFESP',
    year: 2024,
    statement: 'Recém-nascido a termo com 12 horas de vida, filho de mãe diabética, apresenta cianose central generalizada intensa que não melhora após administração de oxigênio a 100% (teste de hiperóxia negativo com PaO2 mantendo-se < 50 mmHg). A criança encontra-se confortável, eupneica, sem desconforto respiratório evidente ("cianose feliz"), sem sopros cardíacos audíveis. A radiografia de tórax revela coração discretamente aumentado com aspecto clássico de "ovo deitado sobre uma corda" (pedículo vascular estreito) e discreto hiperfluxo pulmonar. O ecocardiograma confirma que a Aorta emerge anatomicamente do Ventrículo Direito e a Artéria Pulmonar emerge do Ventrículo Esquerdo. Qual é a conduta imediata para garantir a sobrevida do paciente antes da correção cirúrgica anatômica?',
    A: 'Iniciar imediatamente infusão contínua de Prostaglandina E1 (Alprostadil) para manter a permeabilidade do canal arterial e, se a hipoxemia persistir crítica por forame oval restritivo, realizar Atriosseptostomia com Balão (Procedimento de Rashkind).',
    B: 'Administrar indometacina em alta dose para fechar o canal arterial imediatamente.',
    C: 'Realizar cirurgia de Fontan no primeiro dia de vida sem exames adicionais.',
    D: 'Iniciar furosemida e aguardar fechamento espontâneo da aorta em 30 dias.',
    ans: 'A',
    comment: 'Na Transposição das Grandes Artérias (TGA), as circulações sistêmica e pulmonar funcionam em circuitos paralelos independentes e fechados em si mesmos: o sangue venoso desoxigenado entra no AD -> VD -> Aorta -> corpo (sem oxigenar); o sangue arterial oxigenado entra no AE -> VE -> Pulmão -> AE (reoxigena sem ir ao corpo). Essa condição é absolutamente incompatível com a vida a menos que haja comunicações bidirecionais de mistura sanguínea (shunts), especialmente o canal arterial e o forame oval/CIA. A conduta de emergência obrigatória é: 1) Infusão contínua de Prostaglandina E1 (alprostadil) para reabrir/manter pérvio o canal arterial; 2) Se houver forame oval restritivo com hipóxia refratária grave, realiza-se na UTI a atriosseptostomia com balão de Rashkind por cateterismo, criando uma grande CIA de mistura até a cirurgia corretiva anatômica de Jatene (Switch Arterial), que deve ser realizada preferencialmente nas primeiras 2 a 3 semanas de vida.',
    expA: 'Correta. Prostaglandina E1 mantém o canal arterial aberto e a septostomia de Rashkind amplia a mistura atrial, salvando a vida do neonato.',
    expB: 'Incorreta. Fechar o canal arterial na TGA sem CIA ampla é letal em poucos minutos por asfixia circulatória.',
    expC: 'Incorreta. A cirurgia de Fontan é o estágio final para fisiologia univentricular, não indicada na TGA clássica.',
    expD: 'Incorreta. A aorta não se fecha espontaneamente; a TGA exige cirurgia de transposição de grandes vasos (Jatene).',
  });

  q({
    id: 'ped-cardio-rev-06',
    subtopic: 'Doença de Kawasaki',
    inst: 'UERJ',
    year: 2024,
    statement: 'Menino de 2 anos e 4 meses apresenta febre alta persistente (39,5 °C) há 6 dias consecutivos, refratária a antitérmicos e antibióticos comuns. Ao exame clínico: conjuntivite bulbar bilateral não exsudativa e não pruriginosa (sem secreção purulenta), hiperemia labial com fissuras sangrantes e língua com aspecto de morango ("língua em framboesa"), exantema polimorfo maculopapular eritematoso no tronco e região perineal, edema endurado e eritema em dorso de mãos e pés e linfoadenopatia cervical unilateral com gânglio doloroso de 2,0 cm de diâmetro. Não há foco infeccioso bacteriano. Qual é o diagnóstico e o tratamento de escolha comprovadamente eficaz para reduzir a incidência de aneurismas de artérias coronárias de 25% para menos de 4%?',
    A: 'Escarlatina; tratamento com Penicilina Benzatina intramuscular.',
    B: 'Doença de Kawasaki; tratamento com Imunoglobulina Humana Intravenosa (IVIG) em dose única de 2 g/kg associada a Ácido Acetilsalicílico (AAS).',
    C: 'Mononucleose infecciosa; tratamento sintomático exclusivo com aciclovir oral.',
    D: 'Febre reumática aguda; pulsoterapia com metilprednisolona isolada.',
    ans: 'B',
    comment: 'O paciente preenche com perfeição os critérios clássicos para Doença de Kawasaki: febre há ≥ 5 dias associada a pelo menos 4 dos 5 critérios clínicos principais: 1) Conjuntivite bulbar bilateral não purulenta; 2) Alterações de lábios e cavidade oral (língua em framboesa, fissuras e queilite); 3) Alterações de extremidades (edema/eritema palmar e plantar na fase aguda; descamação periungueal na convalescença); 4) Exantema polimorfo não vesicular; 5) Linfadenopatia cervical aguda não supurativa (> 1,5 cm, geralmente unilateral). A complicação mais temida é a vasculite necrotizante de artérias coronárias com formação de aneurismas coronarianos. O tratamento padrão-ouro, que deve ser administrado idealmente antes do 10º dia de febre, é a Imunoglobulina Humana Intravenosa (IVIG) na dose única de 2 g/kg infundida em 10-12 horas, associada ao Ácido Acetilsalicílico (AAS).',
    expA: 'Incorreta. A escarlatina não cursa com conjuntivite, edema de mãos e pés ou aneurismas coronarianos.',
    expB: 'Correta. Doença de Kawasaki tratada com IVIG 2 g/kg + AAS previne o surgimento de aneurismas coronarianos.',
    expC: 'Incorreta. A mononucleose não cursa com língua em framboesa nem fissuras labiais características de Kawasaki.',
    expD: 'Incorreta. A febre reumática não cursa com conjuntivite nem vasculite de artérias coronárias.',
  });

  q({
    id: 'ped-cardio-rev-07',
    subtopic: 'Febre Reumática',
    inst: 'SCMSP',
    year: 2024,
    statement: 'Menina de 9 anos é trazida ao ambulatório por dor articular migratória de grandes articulações: iniciou em joelho direito há 5 dias com calor, rubor e impotência funcional; com a melhora do joelho, passou a acometer o tornozelo esquerdo e hoje o punho direito (poliartrite migratória clássica). A mãe refere que a menina teve faringoamigdalite purulenta com febre alta há 3 semanas, tratada apenas com paracetamol. Ao exame cardiovascular: sopro holossistólico 3+/6+ em foco mitral com irradiação para a axila esquerda e sopro mesodiastólico suave em ápice (sopro de Carey Coombs). Os exames mostram VHS de 88 mm/h, PCR de 65 mg/L e ASLO (antiestreptolisina O) de 920 UI/mL (muito elevada). De acordo com os Critérios de Jones revisados pela American Heart Association para populações de moderado a alto risco, como se fecha o diagnóstico e qual é a droga de escolha para erradicação do estreptococo e profilaxia secundária?',
    A: 'Diagnóstico confirmado de Febre Reumática (presença de 2 critérios maiores: poliartrite e cardite + evidência de infecção estreptocócica prévia por ASLO elevada); tratamento com Penicilina G Benzatina intramuscular.',
    B: 'Artrite Idiopática Juvenil sistêmica; tratamento com metotrexato oral exclusivo.',
    C: 'Lúpus Eritematoso Sistêmico juvenil; pulsoterapia com ciclofosfamida.',
    D: 'Artrite séptica gonocócica; ceftriaxona intravenosa.',
    ans: 'A',
    comment: 'Pela revisão dos Critérios de Jones (AHA 2015), o diagnóstico de primeiro surto de Febre Reumática exige comprovação de infecção prévia pelo Streptococcus pyogenes (Streptococcus beta-hemolítico do grupo A) através de títulos elevados de ASLO ou anti-DNAse B, ou cultura de orofaringe positiva, associada a: 2 critérios maiores OU 1 critério maior e 2 critérios menores. Critérios maiores: 1) Cardite (clínica ou subclínica pelo ecocardiograma; sopro de regurgitação mitral e Carey Coombs); 2) Artrite (poliartrite migratória de grandes articulações); 3) Coreia de Sydenham; 4) Nódulos subcutâneos de Meynet; 5) Eritema marginado de Leiner. A paciente tem 2 critérios maiores (Artrite + Cardite) e ASLO elevada, fechando o diagnóstico. O primeiro passo é erradicar o estreptococo com Penicilina Benzatina IM dose única (que também inicia o regime de profilaxia secundária a cada 21 dias).',
    expA: 'Correta. Diagnóstico de Febre Reumática com 2 critérios maiores (artrite + cardite) e ASLO elevada, tratada com Penicilina G Benzatina.',
    expB: 'Incorreta. A artrite na AIJ sistêmica é aditiva e crônica (> 6 semanas), sem relação estreptocócica.',
    expC: 'Incorreta. LES cursa com FAN positivo, nefrite e fotossensibilidade, não poliartrite migratória aguda pós-faringite.',
    expD: 'Incorreta. A artrite séptica é monoartrite estática purulenta aguda com derrame articular volumoso e febre alta séptica.',
  });

  q({
    id: 'ped-cardio-rev-08',
    subtopic: 'Taquicardia Supraventricular (TSV)',
    inst: 'FMUSP',
    year: 2024,
    statement: 'Lactente de 2 meses é levado ao pronto-atendimento com história de irritabilidade súbita, palidez cutânea e recusa das mamadas nas últimas 4 horas. Ao exame clínico: afebril, tempo de enchimento capilar de 2 segundos, pulsos periféricos finos, mas palpáveis e simétricos, pressão arterial normal para a idade (estabilidade hemodinâmica). A frequência cardíaca na monitorização é fixa e invariável em 250 bpm. O eletrocardiograma (ECG) de 12 derivações demonstra taquicardia com complexos QRS estreitos (< 0,08s), intervalo R-R rigorosamente regular e ausência de ondas P visíveis precedendo o QRS. Diante do diagnóstico de Taquicardia Supraventricular (TSV) paroxística hemodinamicamente estável, qual é a conduta imediata recomendada pelas diretrizes do PALS (Pediatric Advanced Life Support)?',
    A: 'Realizar manobras vagais imediatamente (como aplicação de bolsa de gelo na face cobrindo testa e nariz por 10 a 15 segundos); se ineficaz, administrar Adenosina intravenosa em bolus rápido através de veia calibrosa periférica com flush imediato de soro fisiológico.',
    B: 'Administrar Verapamil intravenoso em infusão contínua lenta de 2 horas.',
    C: 'Realizar cardioversão elétrica sincronizada imediata com carga máxima de 10 J/kg.',
    D: 'Prescrever atropina intravenosa para estimular o nó sinusal.',
    ans: 'A',
    comment: 'A Taquicardia Supraventricular (TSV) é a taquiarritmia sintomática mais frequente na infância (FC típica no lactente > 220 bpm e na criança maior > 180 bpm, sem variação ciclo a ciclo e com QRS estreito). Na criança ESTÁVEL hemodinamicamente, a primeira linha de tratamento são as manobras vagais: no lactente, o método mais eficaz e seguro é a aplicação de bolsa com gelo picado/água gelada sobre o terço médio da face (cobrindo testa, nariz e olhos sem ocluir as vias aéreas) por 10 a 15 segundos ("reflexo do mergulhador"). Se as manobras vagais falharem ou não puderem ser realizadas rapidamente, o fármaco de escolha é a ADENOSINA intravenosa (0,1 mg/kg; máx 6 mg na 1ª dose) administrada em bolus ultra-rápido (técnica de duas seringas com torneirinha de três vias / push and flush) seguido de flush imediato de 5 a 10 mL de SF 0,9%.',
    expA: 'Correta. Manobras vagais (bolsa de gelo na face) seguidas de Adenosina em bolus rápido é a conduta recomendada pelo PALS no paciente estável.',
    expB: 'Incorreta. O Verapamil (bloqueador de canal de cálcio) é FORMALMENTE CONTRAINDICADO em menores de 1 ano pelo risco grave de colapso cardiovascular, choque cardiogênico irreversível e morte.',
    expC: 'Incorreta. Cardioversão elétrica sincronizada (0,5 a 1 J/kg) é reservada para pacientes INSTÁVEIS hemodinamicamente (com choque, alteração de consciência ou má perfusão).',
    expD: 'Incorreta. A atropina é um cronotrópico positivo parassimpaticolítico que aceleraria ainda mais a taquicardia.',
  });

  q({
    id: 'ped-cardio-rev-09',
    subtopic: 'Teste do Coraçãozinho (Oximetria de Pulso)',
    inst: 'USP-RP',
    year: 2024,
    statement: 'Recém-nascido a termo, com 30 horas de vida, clinicamente assintomático e com exame físico normal no alojamento conjunto, realiza a triagem neonatal para cardiopatias congênitas críticas (Teste do Coraçãozinho / Oximetria de Pulso). O resultado da aferição evidencia: Saturação de O2 no Membro Superior Direito (MSD) de 93% e no Membro Inferior Direito (MID) de 92%. De acordo com o protocolo padronizado pelo Ministério da Saúde e pela Sociedade Brasileira de Pediatria, qual é a conduta médica correta a ser adotada?',
    A: 'Considerar o teste normal e conceder alta hospitalar imediata com orientações gerais de puericultura.',
    B: 'O teste é considerado duvidoso/inconclusivo; a conduta é repetir a oximetria de pulso (MSD e MID) após 1 hora. Se o resultado permanecer alterado (SatO2 < 95% ou diferença ≥ 4%), o teste torna-se positivo, devendo-se solicitar Ecocardiograma antes da alta hospitalar.',
    C: 'Iniciar imediatamente intubação orotraqueal e infusão de adrenalina em acesso venoso central.',
    D: 'Indicar cirurgia cardíaca aberta de urgência na primeira hora.',
    ans: 'B',
    comment: 'O Teste do Coraçãozinho (triagem de cardiopatias congênitas dependentes de canal) deve ser realizado entre 24 e 48 horas de vida em todo RN a termo ou prematuro limítrofe assintomático antes da alta. Mede-se a SpO2 no MSD (pré-ductal) e em um dos membros inferiores (pós-ductal): 1) NORMAL / NEGATIVO: SpO2 ≥ 95% em ambos os sítios E diferença entre eles ≤ 3%; 2) ALTERADO / DUVIDOSO: SpO2 < 95% em qualquer um dos membros OU diferença ≥ 4% entre MSD e MI. Diante de um resultado alterado, NÃO se dá alta nem se diagnostica cardiopatia de imediato: REPETE-SE a aferição após 1 HORA. Se persistir alterado na segunda medida, o teste é POSITIVO e o RN deve ser mantido internado para realização de Ecocardiograma confirmatório em até 24 horas antes da alta.',
    expA: 'Incorreta. SatO2 de 93% está abaixo do ponto de corte de 95%, não podendo ser considerado normal.',
    expB: 'Correta. Repetir o teste em 1 hora; se persistir com SpO2 < 95% ou diferença ≥ 4%, o teste é positivo e impõe ecocardiograma antes da alta.',
    expC: 'Incorreta. A criança está assintomática e estável, sem indicação de IOT de emergência.',
    expD: 'Incorreta. Cirurgia depende de confirmação diagnóstica prévia por ecocardiograma.',
  });

  q({
    id: 'ped-cardio-rev-10',
    subtopic: 'Tronco Arterioso Comum',
    inst: 'UNICAMP',
    year: 2024,
    statement: 'Recém-nascido com 15 dias de vida apresenta taquipneia progressiva, cansaço nas mamadas, leve cianose periférica e precórdio hiperdinâmico. À ausculta: segunda bulha única e hiperfonética, sopro ejetivo sistólico áspero na borda esternal esquerda média e sopro diastólico precoce de regurgitação em foco aórtico. O ecocardiograma revela tronco vascular único emergindo da base do coração que dá origem simultaneamente à aorta ascendente, às artérias pulmonares e às coronárias, cavalgando sobre uma ampla comunicação interventricular (CIV). Qual é a cardiopatia congênita descrita e qual síndrome genética clássica por microdeleção cromossômica está fortemente associada a ela?',
    A: 'Tronco Arterioso Comum (Truncus Arteriosus); Síndrome de microdeleção 22q11.2 (Síndrome de DiGeorge / velocardiofacial).',
    B: 'Coarctação de Aorta simples; Trissomia do cromossomo 21.',
    C: 'Anomalia de Ebstein; Síndrome de Williams-Beuren.',
    D: 'Drenagem Anômala Total de Veias Pulmonares; Síndrome de Marfan.',
    ans: 'A',
    comment: 'O Tronco Arterioso Comum (Truncus Arteriosus) resulta da falha embrionária de septação conotruncal do bulbo cardíaco pelas cristas neurais, resultando em uma única raiz arterial ejetora que supre a circulação coronariana, sistêmica e pulmonar, cavalgando sobre uma ampla CIV. A valva troncal é habitualmente displásica (podendo ter de 2 a 6 cúspides) e regurgitante, explicando a segunda bulha única e o sopro diastólico de insuficiência. Cerca de 30% a 40% dos casos de Tronco Arterioso estão intimamente associados à microdeleção 22q11.2 (Síndrome de DiGeorge / velocardiofacial), caracterizada pela tríade: cardiopatia conotruncal + hipoplasia tímica (imunodeficiência de células T) + hipoplasia de paratireoides com hipocalcemia neonatal e convulsões.',
    expA: 'Correta. Tronco Arterioso Comum associado à microdeleção 22q11.2 (Síndrome de DiGeorge).',
    expB: 'Incorreta. A trissomia 21 associa-se tipicamente ao defeito do septo atrioventricular (DSAV) e CIV.',
    expC: 'Incorreta. A síndrome de Williams-Beuren (deleção 7q11.23) associa-se à estenose aórtica supravalvar.',
    expD: 'Incorreta. A síndrome de Marfan cursa com dilatação de raiz aórtica por mutação da fibrilina-1.',
  });

  q({
    id: 'ped-cardio-rev-11',
    subtopic: 'Drenagem Anômala Total de Veias Pulmonares (DATVP)',
    inst: 'USP-SP',
    year: 2024,
    statement: 'Lactente de 2 meses com cianose leve e taquipneia crônica realiza radiografia de tórax que revela cardiomegalia expressiva com imagem clássica em "Boneco de Neve" (ou imagem em "8" ou "cabeça de boneco"), decorrente da dilatação da veia cava superior e veia vertical anômala na porção superior e aumento das cavidades direitas na porção inferior. O ecocardiograma confirma que as quatro veias pulmonares não drenam no átrio esquerdo, mas sim confluem em um coletor retrocardíaco que drena na veia inominada e veia cava superior (tipo supracardíaco). Qual é essa cardiopatia congênita e qual estrutura intracardíaca é OBRIGATÓRIA para a sobrevivência da criança?',
    A: 'Drenagem Anômala Total de Veias Pulmonares (DATVP); Presença obrigatória de uma Comunicação Interatrial (CIA) ou Forame Oval Patente permitindo o shunt direita-esquerda para encher as câmaras esquerdas.',
    B: 'Atresia tricúspide; fechamento prematuro do forame oval.',
    C: 'Tetralogia de Fallot; persistência da veia cava superior esquerda exclusiva.',
    D: 'Transposição de Grandes Artérias; estenose aórtica isolada.',
    ans: 'A',
    comment: 'Na Drenagem Anômala Total de Veias Pulmonares (DATVP), todo o sangue oxigenado proveniente dos pulmões desemboca no circuito venoso sistêmico (coração direito) através de veias anômalas (supracardíaca, cardíaca no seio coronário ou infracardíaca na veia porta). Como NENHUMA veia pulmonar chega ao átrio esquerdo, todo o débito cardíaco sistêmico depende OBRIGATORIAMENTE da existência de uma Comunicação Interatrial (CIA) ou Forame Oval pérvio amplo, permitindo que o sangue misturado do AD passe para o AE e VE. Sem a CIA, a criança vai a óbito imediato ao nascer. Na forma supracardíaca, a veia vertical esquerda dilatada somada à veia inominada e VCS forma a sombra mediastinal superior ("cabeça do boneco de neve"), enquanto as câmaras direitas aumentadas formam o corpo.',
    expA: 'Correta. DATVP supracardíaca ("boneco de neve"), em que a sobrevida depende da passagem obrigatória de sangue oxigenado através da CIA para o átrio esquerdo.',
    expB: 'Incorreta. Na atresia tricúspide o fechamento do forame oval seria incompatível com a vida.',
    expC: 'Incorreta. O sinal do boneco de neve é patognomônico da DATVP supracardíaca, e não de Fallot.',
    expD: 'Incorreta. Não corresponde à anatomia da DATVP.',
  });

  q({
    id: 'ped-cardio-rev-12',
    subtopic: 'Síndrome do Coração Esquerdo Hipoplásico (SHCE)',
    inst: 'FMUSP',
    year: 2024,
    statement: 'Recém-nascido a termo com 48 horas de vida, aparentemente saudável ao nascimento, desenvolve subitamente choque circulatório cardiogênico fulminante com palidez acinzentada, hipotermia, anúria, pulsos periféricos impalpáveis em todos os quatro membros, tempo de enchimento capilar de 6 segundos e acidose metabólica lática profunda (pH 7,05, lactato 14 mmol/L), coincidindo com o momento do fechamento espontâneo fisiológico do canal arterial. O ecocardiograma confirma atresia da valva aórtica e mitral com ventrículo esquerdo hipoplásico e aorta ascendente hipoplásica de 2 mm ("aorta em fio de barbante"). Qual é a medida medicamentosa imediata de ressuscitação capaz de reverter o choque e salvar a vida desse neonato canal-dependente de circulação sistêmica?',
    A: 'Infusão contínua imediata de Prostaglandina E1 (Alprostadil) por via venosa para reabrir o canal arterial e restabelecer o débito cardíaco sistêmico retrógrado.',
    B: 'Administração de bicarbonato de sódio em bolus e indometacina intravenosa.',
    C: 'Cardioversão elétrica não sincronizada em 200 Joules.',
    D: 'Fechamento percutâneo imediato do canal arterial com mola de Gianturco.',
    ans: 'A',
    comment: 'A Síndrome da Hipoplasia do Coração Esquerdo (SHCE) é uma das cardiopatias congênitas mais letais no período neonatal: as estruturas esquerdas (valva mitral, VE, valva aórtica e aorta ascendente) são hipoplásicas e incapazes de gerar débito cardíaco sistêmico. Todo o débito cardíaco da criança (tanto para o pulmão quanto para o corpo e coronárias) depende do VENTRÍCULO DIREITO, que ejeta na artéria pulmonar e envia sangue para a aorta descendente e coronárias EXCLUSIVAMENTE ATRAVÉS DO CANAL ARTERIAL (cardiopatia canal-dependente de circulação sistêmica). Quando o canal se fecha naturalmente entre 24 e 72 horas de vida, cessa abruptamente a perfusão sistêmica, desencadeando choque cardiogênico profundo e morte em horas. A infusão emergencial de Prostaglandina E1 (Alprostadil) reabre o canal arterial e restabelece a perfusão sistêmica, revertendo o choque.',
    expA: 'Correta. Prostaglandina E1 intravenosa reabre o canal arterial e salva a vida do neonato na cardiopatia canal-dependente de circulação sistêmica.',
    expB: 'Incorreta. Indometacina fecha o canal arterial e aceleraria o óbito imediato do paciente.',
    expC: 'Incorreta. O choque é mecânico por parada da perfusão sistêmica pelo fechamento do canal, não fibrilação ventricular primária.',
    expD: 'Incorreta. Fechar o canal arterial é letal na hipoplasia de coração esquerdo.',
  });

  q({
    id: 'ped-cardio-rev-13',
    subtopic: 'Endocardite Infecciosa e Profilaxia',
    inst: 'UNICAMP',
    year: 2024,
    statement: 'Menino de 7 anos foi submetido à correção cirúrgica de Tetralogia de Fallot há 3 meses com implante de prótese valvar pulmonar biológica e remendo protético de Dacron na CIV. Ele irá realizar um procedimento odontológico invasivo que envolverá manipulação de tecido gengival e perfuração de mucosa oral. De acordo com as diretrizes atuais da American Heart Association e da Sociedade Brasileira de Cardiologia (SBC), qual é a recomendação para a profilaxia antimicrobiana de endocardite infecciosa nesse paciente?',
    A: 'A profilaxia de endocardite é desnecessária em qualquer cardiopatia congênita corrigida.',
    B: 'A profilaxia antimicrobiana é formalmente indicada: administrar Amoxicilina por via oral na dose de 50 mg/kg em dose única 30 a 60 minutos antes do procedimento odontológico (ou Clindamicina/Azitromicina se alérgico a penicilina).',
    C: 'Prescrever penicilina benzatina intramuscular diária por 6 meses.',
    D: 'Administrar vancomicina e gentamicina intravenosas por 14 dias antes da consulta odontológica.',
    ans: 'B',
    comment: 'Pelas diretrizes modernas (AHA e SBC), a profilaxia antimicrobiana para Endocardite Infecciosa foi restringida apenas aos pacientes de ALTO RISCO submetidos a procedimentos odontológicos com manipulação gengival, região periapical ou perfuração da mucosa. Os pacientes de alto risco incluem: 1) Presença de prótese valvar cardíaca ou material protético usado em plastia valvar; 2) História prévia de endocardite infecciosa; 3) Cardiopatia congênita cianogênica não corrigida (incluindo shunts paliativos); 4) Cardiopatia congênita completamente reparada com material protético DURANTE OS PRIMEIROS 6 MESES após o procedimento cirúrgico ou percutâneo; 5) Cardiopatia corrigida que apresente defeito residual adjacente ao remendo protético. O esquema de escolha é Amoxicilina oral na dose única de 50 mg/kg (máx. 2 g) 30 a 60 minutos antes do procedimento.',
    expA: 'Incorreta. Pacientes com prótese valvar biológica e nos primeiros 6 meses de remendo protético têm indicação formal de alto risco.',
    expB: 'Correta. Amoxicilina 50 mg/kg VO dose única 30-60 minutos antes da manipulação odontológica é o padrão.',
    expC: 'Incorreta. Penicilina benzatina diária não é regime profilático de endocardite.',
    expD: 'Incorreta. Não há indicação de regime parenteral hospitalar com vancomicina para procedimentos ambulatoriais de rotina.',
  });

  q({
    id: 'ped-cardio-rev-14',
    subtopic: 'Comunicação Interatrial (CIA)',
    inst: 'UERJ',
    year: 2024,
    statement: 'Menina de 6 anos assintomática é encaminhada para avaliação após o pediatra auscultar um sopro cardíaco. Ao exame físico: acianótica, corada, pulsos simétricos normais. Ausculta cardíaca revela desdobramento amplo e FIXO da segunda bulha cardíaca (B2) em foco pulmonar, que não varia com os ciclos respiratórios de inspiração e expiração, associado a um sopro sistólico ejetivo suave 2+/6+ em foco pulmonar. O ECG evidencia desvio do eixo para a direita e padrão de bloqueio incompleto de ramo direito (rSr\' em V1). Qual é a cardiopatia congênita e qual é o tipo anatômico mais frequente?',
    A: 'Comunicação Interatrial (CIA); tipo Ostium Secundum (localizada na região da fossa oval).',
    B: 'Coarctação de Aorta pré-ductal.',
    C: 'Tetralogia de Fallot extrema.',
    D: 'Doença de Kawasaki sem aneurisma.',
    ans: 'A',
    comment: 'O achado semiológico de DESDOBRAMENTO AMPLO E FIXO DA SEGUNDA BULHA (B2) é o sinal clássico patognomônico da Comunicação Interatrial (CIA). Na CIA, o shunt esquerda-direita (AE -> AD) causa sobrecarga volumétrica crônica do ventrículo direito. Esse excesso de volume no VD retarda o fechamento do componente pulmonar de B2 (P2); como o shunt é constante ao longo de todo o ciclo respiratório, o intervalo entre A2 e P2 permanece fixo e invariável tanto na inspiração quanto na expiração. O sopro sistólico não é gerado pelo fluxo através do defeito atrial (que é de baixa pressão), mas sim pelo hiperfluxo relativo através da valva pulmonar normal. O tipo anatômico mais frequente (representando cerca de 70% a 80% das CIAs) é o defeito do tipo Ostium Secundum, situado na fossa oval.',
    expA: 'Correta. CIA do tipo Ostium Secundum manifesta-se tipicamente pelo desdobramento amplo e fixo de B2 e bloqueio incompleto de ramo direito.',
    expB: 'Incorreta. A coarctação aórtica cursa com assimetria de pulsos e sopro interescapular, sem desdobramento fixo de B2.',
    expC: 'Incorreta. Fallot cursa com hipóxia e cianose acentuadas.',
    expD: 'Incorreta. Kawasaki é vasculite sistêmica febril adquirida, não cardiopatia congênita de hiperfluxo.',
  });

  q({
    id: 'ped-cardio-rev-15',
    subtopic: 'Síndrome de Eisenmenger',
    inst: 'SCMSP',
    year: 2024,
    statement: 'Adolescente de 16 anos, portador de grande Comunicação Interventricular (CIV) não tratada na infância, procura assistência médica referindo que o sopro rude e a taquipneia que tinha em criança "desapareceram" aos 10 anos, mas agora vem evoluindo com intolerância progressiva aos esforços, cansaço, cianose labial que piora na atividade física, baqueteamento digital (dedos em vidro de relógio) e eritrocitose secundária com hemoglobina de 21 g/dL e hematócrito de 64%. Ao exame: B2 hiperfonética estalante no foco pulmonar e ausência quase total do sopro holossistólico anterior. O ecocardiograma revela inversão do shunt interventricular, que agora flui da direita para a esquerda (VD -> VE). Qual é o diagnóstico e qual é a conduta quanto à correção cirúrgica intracardíaca?',
    A: 'Síndrome de Eisenmenger (doença vascular pulmonar obstrutiva irreversível com inversão de shunt); a correção cirúrgica intracardíaca da CIV é FORMALMENTE CONTRAINDICADA.',
    B: 'Cura espontânea da cardiopatia; indicar alta ambulatorial sem restrições.',
    C: 'Tetralogia de Fallot adquirida; indicar cirurgia de Blalock-Taussig.',
    D: 'Persistência de canal arterial; fechar cirurgicamente a CIV em 24 horas.',
    ans: 'A',
    comment: 'A síndrome de Eisenmenger representa o estágio terminal da história natural de defeitos congênitos com grande shunt esquerda-direita (como CIV ampla, PCA volumoso ou DSAV) não operados a tempo: o hiperfluxo e a hiperpressão pulmonar crônica causam remodelamento endotelial patológico, hipertrofia da camada média, proliferação intimal concêntrica e necrose fibrinoide das arteríolas pulmonares (vasculopatia pulmonar obstrutiva irreversível). Quando a Resistência Vascular Pulmonar (RVP) supera a Resistência Vascular Sistêmica (RVS), o shunt se inverte, passando a ser da DIREITA PARA A ESQUERDA (D-E), surgindo cianose, hipoxemia crônica e baqueteamento digital. Nesse estágio, o fechamento cirúrgico da CIV é FORMALMENTE CONTRAINDICADO e fatal, pois o ventrículo direito entraria em falência aguda catastrófica sem a via de escape (a CIV funciona como válvula de escape pop-off para o VD hipertenso). O tratamento é estritamente clínico com vasodilatadores pulmonares (sildenafila, bosentana) ou transplante cardiopulmonar.',
    expA: 'Correta. Síndrome de Eisenmenger com inversão de shunt; a cirurgia corretiva da CIV é contraindicada pelo risco de falência fulminante do VD.',
    expB: 'Incorreta. O paciente desenvolveu hipertensão arterial pulmonar irreversível catastrófica, e não cura espontânea.',
    expC: 'Incorreta. Não existe Fallot adquirido.',
    expD: 'Incorreta. Fechar a CIV no Eisenmenger causa choque cardiogênico direito imediato e morte na mesa cirúrgica.',
  });
}
