import { q } from './helper_crescimento.js';

export function loadSec10() {
  q({
    id: 'ped-cresc-077',
    subtopic: 'Doenças Sistêmicas e Crônicas',
    inst: 'USP-SP',
    year: 2024,
    statement: 'Lactente de 16 meses é levado ao pediatra com perda ponderal progressiva e estagnação do crescimento nos últimos 6 meses. A mãe relata que a criança mamou no peito exclusivo até os 6 meses, momento em que foram introduzidas papas e biscoitos de trigo. Desde os 10 meses, passou a apresentar fezes pastosas, volumosas, brilhantes e fétidas, distensão abdominal progressiva, emagrecimento com perda da musculatura glútea ("nádegas caídas em saco vazio") e irritabilidade. O peso caiu do percentil 50 para < p3 e o comprimento agora está no percentil 3. Qual é a principal hipótese diagnóstica e a conduta inicial?',
    A: 'Doença celíaca clássica; solicitar anticorpo antitransglutaminase tecidual IgA (anti-tTG IgA) e dosagem de IgA total sérica.',
    B: 'Deficiência primária de GH; iniciar GH recombinante de urgência.',
    C: 'Acondroplasia tardia; solicitar radiografia de bacia.',
    D: 'Tolerância normal ao desmame; orientar aumento da ingesta de pão e massas.',
    ans: 'A',
    comment: 'O quadro clínico é o protótipo da forma clássica da Doença Celíaca na primeira infância: surge habitualmente meses após a introdução de alimentos contendo glúten (trigo, centeio, cevada), manifestando-se por diarreia crônica malabsortiva (fezes esteatorreicas volumosas), distensão abdominal, atrofia marcante da musculatura glútea e dos membros, anorexia, irritabilidade e a clássica sequência de desnutrição crônica: o PESO despenca primeiro e, subsequentemente, o COMPRIMENTO/ESTATURA desacelera e estagna. O rastreio inicial padrão-ouro é o anticorpo anti-transglutaminase tecidual recombinante da classe IgA (anti-tTG IgA) acompanhado da dosagem de IgA total sérica.',
    expA: 'Correta. Doença celíaca clássica pós-introdução de glúten com atrofia glútea e má absorção; triagem com anti-tTG IgA e IgA total.',
    expB: 'Incorreta. Na deficiência de GH o peso é preservado e não há diarreia crônica ou desnutrição grave.',
    expC: 'Incorreta. Acondroplasia é displasia óssea congênita sem relação com diarreia ou glúten.',
    expD: 'Incorreta. Continuar aumentando o glúten agravaria a síndrome de má absorção grave e o risco de crise celíaca.',
  });

  q({
    id: 'ped-cresc-078',
    subtopic: 'Doenças Sistêmicas e Crônicas',
    inst: 'UNICAMP',
    year: 2024,
    statement: 'Menino de 9 anos é encaminhado para investigação de baixa estatura (Escore-Z de -2,4 DP) com desaceleração da velocidade de crescimento (3,5 cm/ano). Ele NÃO apresenta diarreia, dor abdominal, vômitos ou qualquer queixa gastrointestinal. O exame físico é inocente, exceto pela palidez cutânea moderada. O hemograma revela anemia ferropriva refratária a sulfato ferroso oral. Por que o rastreio sorológico para Doença Celíaca é MANDATÓRIO na propedêutica de baixa estatura mesmo sem sintomas digestivos?',
    A: 'Porque a forma atípica/monossintomática da doença celíaca pode ter como ÚNICA manifestação clínica na infância e adolescência a baixa estatura isolada e/ou anemia ferropriva refratária.',
    B: 'Porque a doença celíaca é causada por um tumor hipofisário que destrói os somatotrofos.',
    C: 'Porque o glúten age como agonista direto da somatostatina no fêmur.',
    D: 'O rastreio para celíaca é contraindicado se não houver diarreia crônica associada.',
    ans: 'A',
    comment: 'Nas crianças maiores e adolescentes, a Doença Celíaca frequentemente se manifesta sob a forma ATÍPICA (ou não clássica/monossintomática), em que os sintomas digestivos floridos estão completamente ausentes. Nesses pacientes, a BAIXA ESTATURA ISOLADA e/ou a ANEMIA FERROPRIVA refratária ao tratamento oral podem ser a única manifestação da enteropatia autoimune mediada pelo glúten. Por essa razão, todas as diretrizes internacionais (ESPGHAN, SBP) preconizam a triagem sorológica com anti-tTG IgA como obrigatória no algoritmo de investigação da baixa estatura.',
    expA: 'Correta. A baixa estatura isolada ou anemia refratária pode ser a única manifestação da doença celíaca na infância.',
    expB: 'Incorreta. Doença celíaca é uma enteropatia autoimune intestinal, sem relação com tumor hipofisário.',
    expC: 'Incorreta. Fisiopatologia inventada sem embasamento.',
    expD: 'Incorreta. A ausência de diarreia não exclui a doença celíaca (forma atípica silenciosa).',
  });

  q({
    id: 'ped-cresc-079',
    subtopic: 'Doenças Sistêmicas e Crônicas',
    inst: 'FMUSP',
    year: 2024,
    statement: 'Ao solicitar a triagem sorológica para doença celíaca em uma criança com baixa estatura, o pediatra solicita anti-tTG IgA e dosagem sérica de IgA total. A dosagem de IgA total resulta indetectável (< 5 mg/dL). Por que a dosagem de IgA total é indispensável nessa avaliação e qual é a conduta diagnóstica subsequente?',
    A: 'A dosagem de IgA é irrelevante; o resultado indetectável confirma que a criança não tem doença celíaca.',
    B: 'A deficiência seletiva de IgA é 10 a 15 vezes mais prevalente em portadores de doença celíaca do que na população geral e causa falsos-negativos nos testes baseados em IgA; a conduta é solicitar testes baseados em anticorpos da classe IgG (como anti-tTG IgG ou anticorpo contra peptídeo de gliadina desamidada - anti-DGP IgG).',
    C: 'A deficiência de IgA exige transplante de medula óssea imediato.',
    D: 'Deve-se iniciar imunoglobulina intravenosa em altas doses antes de repetir o teste.',
    ans: 'B',
    comment: 'A deficiência seletiva de IgA é a imunodeficiência primária mais comum (1 em 600 na população geral), mas em celíacos sua prevalência sobe para 1 em cada 40 indivíduos. Se uma criança tiver deficiência de IgA, ela não consegue produzir anticorpos da classe IgA em quantidade detectável; logo, o anti-tTG IgA será FALSO-NEGATIVO. Por isso, a diretriz internacional determina que toda triagem sorológica de celíaca DEVE dosar a IgA total sérica concomitante. Se houver deficiência de IgA, deve-se obrigatoriamente utilizar anticorpos baseados na classe IgG (anti-DGP IgG ou anti-tTG IgG).',
    expA: 'Incorreta. Se a IgA total é indetectável, o teste de anti-tTG IgA será falsamente negativo.',
    expB: 'Correta. A deficiência de IgA causa falso-negativo no anti-tTG IgA, impondo o uso de sorologia da classe IgG (anti-DGP IgG ou anti-tTG IgG).',
    expC: 'Incorreta. Deficiência seletiva de IgA não exige transplante de medula.',
    expD: 'Incorreta. Imunoglobulina IV introduz anticorpos exógenos de doadores e confunde a sorologia diagnóstica.',
  });

  q({
    id: 'ped-cresc-080',
    subtopic: 'Doenças Sistêmicas e Crônicas',
    inst: 'UFRJ',
    year: 2024,
    statement: 'Menino de 11 anos apresenta atraso puberal (G1P1) e desaceleração do crescimento estatural há 2 anos, tendo caído do percentil 50 para o percentil 10. Apresenta episódios ocasionais de febre baixa vespertina, dor abdominal periumbilical vaga após as refeições e artrite em tornozelo direito. A velocidade de crescimento é de 2,5 cm/ano. O exame perianal minucioso revela a presença de uma fissura anal profunda indolor e um plicoma cutâneo sentinela exuberante. Qual é o diagnóstico provável e qual exame de triagem não invasivo nas fezes corrobora essa hipótese?',
    A: 'Doença de Crohn pediátrica; dosagem de Calprotectina fecal.',
    B: 'Apendicite aguda flegmonosa; enema opaco de urgência.',
    C: 'Retardo constitucional simples; dosagem de prolactina.',
    D: 'Febre reumática pura; cultura de orofaringe.',
    ans: 'A',
    comment: 'A Doença de Crohn pediátrica é uma causa clássica e traiçoeira de falha de crescimento e atraso puberal na infância e adolescência: em até 10% a 20% das crianças, a baixa estatura e o atraso puberal PRECEDEM o surgimento de diarreia evidente ou dores abdominais graves por meses ou anos. A presença de manifestações perianais (plicomas exuberantes, fissuras indolores ou fístulas), artrite periférica e inflamação sistêmica crônica reforçam a suspeita. As citocinas inflamatórias (IL-6 e TNF-alfa) causam resistência hepática direta ao GH, bloqueando a síntese de IGF-1. A Calprotectina fecal é o biomarcador não invasivo de escolha para demonstrar inflamação transmural da mucosa intestinal.',
    expA: 'Correta. Doença de Crohn pediátrica apresentando-se com desaceleração estatural, lesão perianal e artrite; calprotectina fecal é o marcador de triagem.',
    expB: 'Incorreta. Apendicite aguda é quadro cirúrgico agudo de horas/dias, não causa desaceleração de 2 anos.',
    expC: 'Incorreta. No RCCP a velocidade é normal e não há fissura perianal, artrite ou febre.',
    expD: 'Incorreta. Febre reumática aguda não causa fissuras perianais nem parada de crescimento crônica.',
  });

  q({
    id: 'ped-cresc-081',
    subtopic: 'Doenças Sistêmicas e Crônicas',
    inst: 'UNIFESP',
    year: 2024,
    statement: 'Qual é a regra fisiopatológica fundamental que diferencia o padrão antropométrico das doenças sistêmicas/desnutritivas (como doença celíaca, cardiopatia congênita, DII e DRC) em relação às endocrinopatias primárias (como deficiência de GH, hipotireoidismo e Cushing)?',
    A: 'Nas doenças sistêmicas a estatura cai anos antes do peso; nas endocrinopatias o peso despenca primeiro.',
    B: 'Nas doenças sistêmicas e desnutritivas, o PESO cai antes e de forma mais acentuada do que a ESTATURA; nas endocrinopatias, a ESTATURA para de crescer enquanto o PESO continua aumentando ou se mantém (baixa estatura com sobrepeso/obesidade).',
    C: 'Não existe qualquer diferença no comportamento do peso e da altura entre essas etiologias.',
    D: 'Tanto as doenças sistêmicas quanto as endocrinopatias cursam com emaciação terminal imediata.',
    ans: 'B',
    comment: 'Esta é uma das regras mais cobradas e aplicadas na prática médica pediátrica: 1) Doenças sistêmicas, crônicas e desnutrição: há um déficit de energia e substratos plásticos e/ou aumento do gasto calórico catabólico. Como consequência, o PESO despenca primeiro (a criança emagrece); se a injúria for crônica e persistente, a criança passa a economizar energia e a ESTATURA desacelera secundariamente; 2) Doenças endócrinas primárias (DGH, hipotireoidismo, Cushing): não há carência de calorias, mas sim falta de sinalização anabólica esquelética; a ESTATURA para de crescer, mas as calorias continuam sendo estocadas como tecido adiposo, resultando em baixa estatura associada a ganho de peso (IMC elevado).',
    expA: 'Incorreta. A afirmação inverte completamente a dinâmica fisiopatológica.',
    expB: 'Correta. Doenças sistêmicas: o peso cai antes da estatura; Endocrinopatias: a estatura para enquanto o peso sobe ou se mantém.',
    expC: 'Incorreta. A dissociação entre peso e estatura é a chave do raciocínio diagnóstico.',
    expD: 'Incorreta. Endocrinopatias clássicas cursam com preservação ou aumento ponderal.',
  });

  q({
    id: 'ped-cresc-082',
    subtopic: 'Doenças Sistêmicas e Crônicas',
    inst: 'UERJ',
    year: 2024,
    statement: 'Criança de 6 anos com Doença Renal Crônica (DRC) estágio 4 secundária a uropatia obstrutiva congênita apresenta baixa estatura grave (Escore-Z de -3,2 DP). Quais são os principais fatores fisiopatológicos que explicam a grave falha de crescimento na criança com DRC?',
    A: 'Excesso de vitamina D e hipercalcemia suprimindo a formação óssea.',
    B: 'Acidose metabólica crônica, osteodistrofia renal com hiperparatireoidismo secundário, desnutrição proteico-calórica e estado de resistência periférica ao hormônio do crescimento (GH) induzido pela uremia crônica.',
    C: 'Hipersecreção de testosterona pelos rins.',
    D: 'Mutação do gene FGFR3 induzida pela uremia.',
    ans: 'B',
    comment: 'A falha de crescimento na DRC pediátrica é multifatorial e complexa: 1) A acidose metabólica crônica inibe a secreção de GH, induz degradação proteica muscular e desmineralização óssea; 2) A uremia crônica e as toxinas urêmicas provocam um estado de RESISTÊNCIA PERIFÉRICA ao GH e ao IGF-1 (downregulation dos receptores e acúmulo de IGFBPs inibitórias que não são depuradas pelo rim); 3) Distúrbio mineral e ósseo da DRC (DMO-DRC / osteodistrofia renal por retenção de fósforo, deficiência de 1,25-di-hidroxivitamina D e hiperparatireoidismo secundário); 4) Anemia crônica, hiporexia e desnutrição. O tratamento inclui correção da acidose com bicarbonato, quelantes de fósforo, calcitriol e rhGH.',
    expA: 'Incorreta. Na DRC há deficiência de 1-alfa-hidroxilação renal (falta de calcitriol) e hipocalcemia/hiperfosfatemia.',
    expB: 'Correta. Acidose, osteodistrofia, uremia com resistência ao GH e desnutrição explicam o déficit estatural na DRC.',
    expC: 'Incorreta. O rim não secreta testosterona.',
    expD: 'Incorreta. FGFR3 é uma mutação congênita da acondroplasia, não causada por uremia.',
  });

  q({
    id: 'ped-cresc-083',
    subtopic: 'Doenças Sistêmicas e Crônicas',
    inst: 'SCMSP',
    year: 2024,
    statement: 'Qual é o papel aprovado do hormônio do crescimento recombinante (rhGH) no manejo da baixa estatura de crianças portadoras de Doença Renal Crônica (DRC)?',
    A: 'O rhGH é contraindicado formalmente na DRC pelo risco de nefrosclerose imediata.',
    B: 'O rhGH tem indicação formal e aprovada para crianças com DRC com baixa estatura e velocidade diminuída após a correção dos distúrbios hidroeletrolíticos e nutricionais, mesmo na fase pré-dialítica, superando o estado de resistência urêmica ao GH.',
    C: 'O rhGH só pode ser administrado após o transplante renal bem-sucedido.',
    D: 'O rhGH atua curando a insuficiência renal e normalizando a creatinina sérica.',
    ans: 'B',
    comment: 'O tratamento com rhGH na DRC pediátrica é uma indicação consagrada e aprovada mundialmente. Como a uremia causa um estado de resistência periférica ao GH (os receptores estão dessensibilizados e as IGFBPs estão elevadas), o uso de doses farmacológicas suprafisiológicas de rhGH supera esse bloqueio urêmico, ativando as placas de crescimento e promovendo expressivo ganho estatural antes do transplante renal. A indicação exige que a acidose, o fósforo, o cálcio e o estado nutricional já tenham sido previamente otimizados.',
    expA: 'Incorreta. O rhGH é amplamente indicado e seguro na DRC pediátrica.',
    expB: 'Correta. O rhGH supera a resistência urêmica e promove aceleração do crescimento em crianças com DRC com déficit estatural.',
    expC: 'Incorreta. O rhGH é utilizado exatamente antes do transplante para recuperar a estatura.',
    expD: 'Incorreta. O rhGH estimula o crescimento esquelético, não regenera néfrons esclerosados.',
  });

  q({
    id: 'ped-cresc-084',
    subtopic: 'Doenças Sistêmicas e Crônicas',
    inst: 'UFPE',
    year: 2024,
    statement: 'Menino de 5 anos com cardiopatia congênita acianogênica com hiperfluxo pulmonar (grande Comunicação Interventricular - CIV ampla não corrigida) apresenta Escore-Z de Estatura/Idade de -2,5 DP e Peso/Idade de -3,1 DP. Qual é o mecanismo primário do déficit pôndero-estatural nessa criança cardiopata?',
    A: 'Hipermetabolismo acentuado por aumento do trabalho cardíaco e respiratório associado a baixa ingesta calórica por cansaço nas mamadas/refeições.',
    B: 'Ausência total de secreção de GH por necrose hipofisária isquêmica.',
    C: 'Intoxicação por cálcio iônico.',
    D: 'Fechamento congênito prematuro de todas as epífises.',
    ans: 'A',
    comment: 'Cardiopatias congênitas com hiperfluxo pulmonar e insuficiência cardíaca congestiva (como CIV ampla, PCA volumoso, defeitos do septo atrioventricular) são causas clássicas de desnutrição e baixa estatura na infância inicial: 1) Aumento drástico do gasto calórico diário (hipermetabolismo) pelo trabalho mecânico miocárdico e esforço respiratório crônico (taquipneia contínua); 2) Ingesta calórica insuficiente por fadiga rápida, sudorese e dispneia durante a alimentação; 3) Má absorção relativa por congestão venosa das alças intestinais. A correção cirúrgica da cardiopatia remove esse hipermetabolismo e promove catch-up ponderal e estatural.',
    expA: 'Correta. Hipermetabolismo pelo trabalho cardiorrespiratório somado à baixa ingesta por fadiga alimentar causa desnutrição e baixa estatura secundária.',
    expB: 'Incorreta. Não há necrose hipofisária (síndrome de Sheehan é obstétrica em adultas).',
    expC: 'Incorreta. Não há intoxicação por cálcio.',
    expD: 'Incorreta. As epífises permanecem abertas e recuperam o crescimento após a cirurgia cardíaca.',
  });
}
