import { q } from './helper_crescimento.js';

export function loadSec12() {
  q({
    id: 'ped-cresc-093',
    subtopic: 'Alta Estatura e Síndromes de Hipercrescimento',
    inst: 'USP-SP',
    year: 2024,
    statement: 'Adolescente de 15 anos é encaminhado ao ambulatório de cardiologia após avaliação de alta estatura. Ele mede 194 cm e sua envergadura braquial é de 208 cm (relação envergadura/estatura = 1,07). Apresenta dedos das mãos excessivamente longos e afilados (aracnodactilia), sinal do punho (Walker-Murdoch) e sinal do polegar (Steinberg) fortemente positivos, tórax com pectus excavatum acentuado e palato ogival. O oftalmologista relata subluxação súpera-temporal bilateral do cristalino (ectopia lentis). Qual é o diagnóstico e qual complicação cardiovascular ameaçadora da vida deve ser precocemente rastreada e prevenida nessa síndrome?',
    A: 'Síndrome de Turner; coarctação da aorta.',
    B: 'Síndrome de Marfan; dilatação progressiva da raiz da aorta com risco iminente de dissecção e rotura aórtica aguda.',
    C: 'Acondroplasia; estenose do forame magno.',
    D: 'Síndrome de Down; comunicação interventricular.',
    ans: 'B',
    comment: 'A síndrome de Marfan é uma desordem autossômica dominante do tecido conjuntivo causada por mutações no gene FBN1 (Fibrilina-1 no cromossomo 15q21.1), que codifica uma glicoproteína essencial das microfibrilas da matriz extracelular. A tríade clássica envolve: 1) Esqueleto: alta estatura com dolicostenomelia (envergadura/estatura > 1,05), aracnodactilia (sinais de Steinberg e Walker-Murdoch positivos), pectus excavatum/carinatum; 2) Olhos: subluxação do cristalino (ectopia lentis, tipicamente superior/temporal); 3) Sistema Cardiovascular (principal determinante da sobrevida): necrose cística da média aórtica com dilatação progressiva da raiz aórtica (aneurisma de seio de Valsalva), insuficiência aórtica e dissecção/rotura aórtica aguda.',
    expA: 'Incorreta. Síndrome de Turner ocorre em meninas e cursa com baixa estatura (não alta estatura de 194 cm).',
    expB: 'Correta. Síndrome de Marfan (mutação no gene FBN1): aracnodactilia, envergadura > estatura, ectopia lentis e risco de dissecção/rotura de raiz aórtica.',
    expC: 'Incorreta. Acondroplasia cursa com baixa estatura extrema e membros curtos.',
    expD: 'Incorreta. Down cursa com trissomia 21 e baixa estatura, sem ectopia lentis ou dolicostenomelia.',
  });

  q({
    id: 'ped-cresc-094',
    subtopic: 'Alta Estatura e Síndromes de Hipercrescimento',
    inst: 'UNICAMP',
    year: 2024,
    statement: 'Qual é o fundamento genético e molecular da Síndrome de Marfan?',
    A: 'Mutação inativadora no gene FGFR3 no cromossomo 4.',
    B: 'Mutação com perda de função ou dominante negativa no gene FBN1 (Fibrilina-1), localizado no cromossomo 15q21.1, gerando enfraquecimento das microfibrilas elásticas e hiperativação da sinalização do TGF-beta tecidual.',
    C: 'Trissomia livre do cromossomo 18 (Síndrome de Edwards).',
    D: 'Monossomia do cromossomo X (45,X).',
    ans: 'B',
    comment: 'A base molecular da síndrome de Marfan reside em mutações no gene FBN1 (15q21.1), que codifica a fibrilina-1. Além da desestruturação mecânica das microfibrilas elásticas da parede aórtica e ligamentos, a deficiência de fibrilina-1 impede o sequestro adequado do fator de crescimento transformador beta (TGF-beta) na matriz extracelular, causando hiperativação crônica e desregulada da cascata pró-inflamatória e proteolítica do TGF-beta. Isso explica a eficácia de bloqueadores dos receptores de angiotensina II (como a Losartana), que antagonizam a via do TGF-beta.',
    expA: 'Incorreta. FGFR3 mutado é a causa da acondroplasia.',
    expB: 'Correta. A mutação no gene FBN1 com desregulação do TGF-beta é a etiologia molecular da Síndrome de Marfan.',
    expC: 'Incorreta. Edwards é trissomia 18 e cursa com anomalias congênitas múltiplas e alta letalidade neonatal.',
    expD: 'Incorreta. 45,X é o cariótipo de Turner.',
  });

  q({
    id: 'ped-cresc-095',
    subtopic: 'Alta Estatura e Síndromes de Hipercrescimento',
    inst: 'FMUSP',
    year: 2024,
    statement: 'No paciente pediátrico ou adolescente com Síndrome de Marfan, qual fármaco cardiovascular é consagrado em diretrizes para retardar a taxa de dilatação da raiz aórtica e reduzir o estresse mecânico de cisalhamento sobre a parede aórtica?',
    A: 'Digitálicos intravenosos em infusão contínua.',
    B: 'Betabloqueadores (como atenolol ou propranolol) e/ou Bloqueadores dos Receptores de Angiotensina II (como a losartana, que atenua a sinalização anômala de TGF-beta).',
    C: 'Anti-inflamatórios não esteroidais em dose máxima.',
    D: 'Hormônio do crescimento recombinante em dose suprafisiológica.',
    ans: 'B',
    comment: 'A farmacoterapia na síndrome de Marfan é voltada para proteger a aorta: 1) Betabloqueadores (atenolol/propranolol/metoprolol) reduzem a frequência cardíaca e a força de ejeção ventricular esquerda (dP/dt), diminuindo a onda de choque sistólica contra a raiz aórtica fragilizada; 2) Bloqueadores dos Receptores de Angiotensina (BRAs, como a Losartana) atuam não apenas como anti-hipertensivos, mas especificamente bloqueiam a cascata proliferativa tecidual de TGF-beta, desacelerando a dilatação do anel aórtico. A cirurgia profilática de troca de raiz aórtica é indicada quando o diâmetro atinge limites críticos (ex: 50 mm no adulto, ou ajustado pela superfície corporal em crianças).',
    expA: 'Incorreta. Digitálicos são inotrópicos positivos que aumentam o estresse sobre a aorta.',
    expB: 'Correta. Betabloqueadores e BRAs (losartana) são a base farmacológica para retardar o aneurisma aórtico no Marfan.',
    expC: 'Incorreta. AINES não impedem a progressão da dilatação aórtica.',
    expD: 'Incorreta. O rhGH é contraindicado, pois aumentaria ainda mais a alta estatura e o estresse mecânico esquelético.',
  });

  q({
    id: 'ped-cresc-096',
    subtopic: 'Alta Estatura e Síndromes de Hipercrescimento',
    inst: 'UFRJ',
    year: 2024,
    statement: 'Adolescente do sexo masculino de 16 anos é levado ao endocrinologista por alta estatura desproporcionada (Escore-Z de +2,3 DP) com pernas excessivamente longas em relação ao tronco. Ao exame físico: ginecomastia bilateral indolor e testículos bilateralmente pequenos, medindo apenas 3 mL de volume cada (consistência firme/endurecida), associado a escassa pilosidade facial e corporal. O histórico escolar revela histórico de dificuldades no aprendizado da leitura e linguagem. O perfil laboratorial evidencia: FSH de 42 mUI/mL (muito elevado), LH de 26 mUI/mL (muito elevado) e Testosterona total de 110 ng/dL (baixa). Qual é a principal hipótese diagnóstica e o cariótipo esperado?',
    A: 'Síndrome de Turner (45,X).',
    B: 'Síndrome de Klinefelter (47,XXY).',
    C: 'Puberdade precoce central verdadeira.',
    D: 'Adenoma hipofisário secretor de prolactina.',
    ans: 'B',
    comment: 'A síndrome de Klinefelter é a aneuploidia cromossômica sexual mais comum no sexo masculino (1 em cada 600 nascidos vivos masculinos), decorrente da presença de um cromossomo X supranumerário (cariótipo 47,XXY clássico em 80-90%). Apresenta-se tipicamente na adolescência por: 1) Alta estatura desproporcionada: membros inferiores longos (a presença de três cópias do gene SHOX, duas na região PAR1 do X e uma no Y, promove crescimento ósseo linear excessivo); 2) Hipogonadismo hipergonadotrófico: hialinização e fibrose progressiva dos túbulos seminíferos com falência das células de Leydig, gerando testículos pequenos e duros (< 4 mL), testosterona baixa e FSH/LH marcadamente elevados; 3) Ginecomastia puberal pelo aumento da relação estrógeno/andrógeno; 4) Azoospermia e infertilidade; 5) Atraso de fala e dificuldades de linguagem na infância.',
    expA: 'Incorreta. Turner ocorre em meninas e cursa com baixa estatura (45,X).',
    expB: 'Correta. Síndrome de Klinefelter (47,XXY): alta estatura com pernas longas, testículos pequenos e firmes, ginecomastia, FSH/LH elevados e testosterona baixa.',
    expC: 'Incorreta. Na puberdade precoce os testículos são aumentados e a testosterona é alta, com idade óssea avançada e baixa estatura final precoce.',
    expD: 'Incorreta. Prolactinoma isolado não explica o cromossomo X extra nem a hialinização testicular primária.',
  });

  q({
    id: 'ped-cresc-097',
    subtopic: 'Alta Estatura e Síndromes de Hipercrescimento',
    inst: 'UNIFESP',
    year: 2024,
    statement: 'Por que os pacientes com Síndrome de Klinefelter (47,XXY) apresentam alta estatura desproporcionada com pernas notavelmente longas?',
    A: 'Devido à dosagem tripla do gene SHOX (duas cópias nos cromossomos X e uma cópia no cromossomo Y, já que o gene SHOX escapa da inativação do X), somada ao atraso na fusão epifisária pela deficiência de testosterona e estrógeno.',
    B: 'Devido à hipersecreção maciça de GH por um adenoma hipofisário congênito obrigatório.',
    C: 'Porque o cromossomo Y duplicado produz osteocalcina em excesso.',
    D: 'Por destruição autoimune de todas as epífises ósseas.',
    ans: 'A',
    comment: 'A alta estatura desproporcionada do Klinefelter tem duas explicações fisiopatológicas primorosas: 1) O gene SHOX (responsável pelo crescimento esquelético) localiza-se na região pseudoautossômica PAR1 e escapa da inativação habitual do cromossomo X de Lyon. Um homem normal tem 2 cópias (X e Y). O homem Klinefelter 47,XXY tem TRÊS cópias ativas do gene SHOX, promovendo superexpressão genética e maior crescimento dos ossos longos dos membros; 2) O hipogonadismo com menor produção de estradiol (o hormônio responsável pelo fechamento epifisário) retarda a fusão das cartilagens de crescimento, prolongando o crescimento linear das pernas.',
    expA: 'Correta. Efeito de dosagem gênica (três cópias do gene SHOX) associado ao atraso na fusão epifisária por hipogonadismo explica as pernas longas no Klinefelter.',
    expB: 'Incorreta. Não decorre de adenoma hipofisário secretor de GH.',
    expC: 'Incorreta. O cariótipo tem um único cromossomo Y (XXY), não Y duplicado.',
    expD: 'Incorreta. As epífises são normais, apenas permanecem abertas por mais tempo.',
  });

  q({
    id: 'ped-cresc-098',
    subtopic: 'Alta Estatura e Síndromes de Hipercrescimento',
    inst: 'FMUSP',
    year: 2024,
    statement: 'Garoto de 12 anos apresenta velocidade de crescimento impressionante de 14 cm/ano antes de entrar em puberdade plena. Mede 198 cm (Escore-Z de Estatura > +4 DP). Apresenta macrocefalia com mandíbula proeminente (prognatismo), pés e mãos gigantes com aumento das partes moles (sapatos apertando rapidamente), cefaleia e sudorese profusa. Os exames mostram IGF-1 extremamente elevado (> +4 DP) e o teste oral de tolerância à glicose (TOTG) com 75 g de dextrosol evidencia falha de supressão do GH sérico (todos os valores de GH > 8 ng/mL). A ressonância magnética revela macroadenoma hipofisário expansivo de 2,2 cm. Qual é o diagnóstico?',
    A: 'Alta estatura constitucional simples.',
    B: 'Gigantismo hipofisário por adenoma somatotrófico secretor de GH.',
    C: 'Síndrome de Turner variante alta.',
    D: 'Acondroplasia descompensada.',
    ans: 'B',
    comment: 'O Gigantismo hipofisário é uma doença rara decorrente da hipersecreção crônica e autônoma de Hormônio do Crescimento (GH) por um adenoma hipofisário somatotrófico que surge ANTES do fechamento das cartilagens epifisárias de crescimento na infância ou adolescência. Caracteriza-se por crescimento linear vertical aceleradíssimo e descontrolado, levando a estaturas gigantescas, associado a crescimento acral de partes moles (pés, mãos, mandíbula). O diagnóstico laboratorial é confirmado pela elevação marcante de IGF-1 e pela ausência de supressão do GH sérico para < 0,4 a 1,0 ng/mL durante o teste de sobrecarga oral com glicose (TOTG). A RM confirma o macroadenoma.',
    expA: 'Incorreta. A velocidade de 14 cm/ano pré-puberal e o adenoma hipofisário excluem variante constitucional normal.',
    expB: 'Correta. Gigantismo hipofisário por adenoma somatotrófico com hipersecreção de GH e falha de supressão no TOTG.',
    expC: 'Incorreta. Turner causa baixa estatura.',
    expD: 'Incorreta. Acondroplasia causa baixa estatura rizomélica extrema.',
  });

  q({
    id: 'ped-cresc-099',
    subtopic: 'Alta Estatura e Síndromes de Hipercrescimento',
    inst: 'UERJ',
    year: 2024,
    statement: 'Qual é o teste funcional padrão-ouro para confirmar a hipersecreção autônoma de GH no diagnóstico de Gigantismo ou Acromegalia?',
    A: 'Teste de estímulo com clonidina oral.',
    B: 'Teste de supressão do GH com sobrecarga oral de glicose (TOTG com 75 g de glicose anidra).',
    C: 'Dosagem de cortisol salivar noturno.',
    D: 'Gasometria arterial com cálculo do ânion gap.',
    ans: 'B',
    comment: 'Em indivíduos saudáveis, a hiperglicemia aguda induzida pela ingesta de glicose inibe imediatamente a secreção hipofisária de GH (o GH sérico cai para níveis indetectáveis ou inferiores a 0,4-1,0 ng/mL aos 30, 60, 90 e 120 minutos do TOTG). Em pacientes com adenomas somatotróficos secretores de GH (Gigantismo/Acromegalia), a secreção tumoral é totalmente autônoma e insensível ao feedback negativo da glicemia, ocorrendo FALHA DE SUPRESSÃO (o GH permanece persistentemente elevado durante todo o TOTG).',
    expA: 'Incorreta. O teste com clonidina é de ESTÍMULO, usado para pesquisar DEFICIÊNCIA de GH, e não hipersecreção.',
    expB: 'Correta. O teste de supressão com TOTG é o padrão-ouro confirmatório para excesso autônomo de GH.',
    expC: 'Incorreta. Cortisol salivar avalia síndrome de Cushing.',
    expD: 'Incorreta. Gasometria avalia equilíbrio ácido-base.',
  });

  q({
    id: 'ped-cresc-100',
    subtopic: 'Alta Estatura e Síndromes de Hipercrescimento',
    inst: 'SCMSP',
    year: 2024,
    statement: 'Menino de 8 anos tem estatura no percentil 97. O pai mede 196 cm e a mãe mede 182 cm. A estatura-alvo parental calculada é de 195,5 cm (percentil 97). Sua velocidade de crescimento é de 6,2 cm/ano (estritamente normal para a idade escolar). O exame físico é harmônico e completamente normal, sem qualquer dismorfismo, com envergadura proporcional à estatura e idade óssea compatível com a idade cronológica (IO = IC). Qual é a interpretação clínica correta?',
    A: 'Síndrome de Sotos com indicação de craniotomia descompressiva.',
    B: 'Alta Estatura Familiar (variante normal do crescimento); a criança está crescendo dentro do seu canal genético saudável determinado por pais altos, sem necessidade de exames invasivos.',
    C: 'Gigantismo hipofisário que exige ressecção transesfenoidal imediata.',
    D: 'Síndrome de Marfan clássica.',
    ans: 'B',
    comment: 'Assim como existe a Baixa Estatura Familiar, existe a Alta Estatura Familiar (variante normal do crescimento): a criança apresenta estatura acima do percentil 97 (ou Escore-Z > +2 DP), porém com velocidade de crescimento fisiologicamente normal (5 a 7 cm/ano), proporções corporais perfeitamente normais (relação SS/SI e envergadura adequadas), idade óssea compatível com a cronológica (IO = IC) e congruência total com a estatura de pais saudáveis e geneticamente altos (pai 196 cm e mãe 182 cm). Não há doença, neoplasia ou síndrome genética, sendo indicada apenas a tranquilização da família e o acompanhamento pediátrico de puericultura.',
    expA: 'Incorreta. A síndrome de Sotos cursa com macrocefalia marcante, fronte proeminente, atraso neuropsicomotor e mutação no gene NSD1.',
    expB: 'Correta. Alta Estatura Familiar: variante normal com velocidade normal, proporcionalidade esquelética, IO = IC e alvo familiar congruente.',
    expC: 'Incorreta. A velocidade normal de 6,2 cm/ano e ausência de sinais acrais afastam gigantismo.',
    expD: 'Incorreta. Não há aracnodactilia, envergadura aumentada ou ectopia de cristalino.',
  });
}
