import { q } from './helper_crescimento.js';

export function loadSec1() {
  q({
    id: 'ped-cresc-001',
    subtopic: 'Velocidade de Crescimento',
    inst: 'USP-SP',
    year: 2024,
    statement: 'Lactente masculino de 12 meses de vida é trazido para consulta de puericultura de rotina. Ao nascimento, a termo, media 50 cm. Hoje, sua estatura aferida em estadiômetro horizontal infantil adequado é de 75 cm. O ganho estatural no primeiro ano foi de 25 cm. A mãe questiona se o crescimento está dentro da normalidade para a faixa etária. Com base no padrão fisiológico de velocidade de crescimento no primeiro ano de vida, assinale a orientação correta:',
    A: 'O crescimento foi insuficiente, pois lactentes a termo devem crescer no mínimo 30 cm no primeiro ano de vida.',
    B: 'O crescimento está estritamente normal, pois o ganho estatural fisiológico esperado no primeiro ano de vida é de aproximadamente 25 cm (cerca de 15 cm no 1º semestre e 10 cm no 2º semestre).',
    C: 'O crescimento foi excessivo e sugere síndrome de supercrescimento, já que o ganho estatural médio esperado para o primeiro ano é de 15 cm.',
    D: 'O crescimento não pode ser avaliado sem radiografia de punho esquerdo para idade óssea de urgência.',
    ans: 'B',
    comment: 'No primeiro ano de vida, o ser humano experimenta a sua maior velocidade de crescimento pós-natal. Em média, um lactente a termo nasce com cerca de 50 cm e cresce 25 cm no primeiro ano de vida (atingindo cerca de 75 cm aos 12 meses): aproximadamente 15 cm no 1º semestre (cerca de 3 cm/mês no 1º trimestre e 2 cm/mês no 2º trimestre) e 10 cm no 2º semestre (cerca de 1,5 a 1,8 cm/mês).',
    expA: 'Incorreta. O ganho médio esperado é de 25 cm/ano, e não 30 cm.',
    expB: 'Correta. O crescimento de 25 cm no primeiro ano reflete o ritmo de crescimento fisiológico humano mais acelerado da vida pós-natal.',
    expC: 'Incorreta. 15 cm é o ganho médio esperado apenas para o 1º semestre de vida, ou para o 2º ano de vida (12 a 15 cm/ano).',
    expD: 'Incorreta. Não há qualquer indicação de idade óssea em um lactente com crescimento perfeitamente normal e saudável.',
  });

  q({
    id: 'ped-cresc-002',
    subtopic: 'Velocidade de Crescimento',
    inst: 'UNICAMP',
    year: 2024,
    statement: 'Menina de 6 anos é acompanhada na unidade básica de saúde. Em consulta há 12 meses, media 112 cm. Na consulta atual, mede 118 cm. A criança não apresenta queixas clínicas, tem alimentação variada e bom rendimento escolar. Qual é a interpretação correta da velocidade de crescimento dessa paciente no período escolar?',
    A: 'Velocidade de crescimento diminuída (< 4 cm/ano), devendo-se solicitar rastreio para deficiência de hormônio de crescimento.',
    B: 'Velocidade de crescimento acelerada (> 10 cm/ano), sendo obrigatória a investigação de puberdade precoce central.',
    C: 'Velocidade de crescimento normal, pois na faixa pré-escolar e escolar (de 4 anos até o início da puberdade) a velocidade esperada é de 5 a 7 cm/ano.',
    D: 'A velocidade de crescimento só pode ser avaliada se calculada a cada trimestre com densitometria óssea.',
    ans: 'C',
    comment: 'No período pré-escolar e escolar (dos 4 anos até o início da puberdade), o crescimento entra em uma fase de desaceleração estável, com velocidade média entre 5 e 7 cm por ano (mínimo aceitável em torno de 5 cm/ano). No caso apresentado, a criança cresceu 6 cm em 1 ano (118 - 112 = 6 cm/ano), padrão perfeitamente fisiológico.',
    expA: 'Incorreta. A criança cresceu 6 cm/ano, o que é plenamente normal (5 a 7 cm/ano).',
    expB: 'Incorreta. 6 cm/ano não configura velocidade acelerada; estirões > 8 a 10 cm/ano ocorrem na puberdade.',
    expC: 'Correta. A velocidade de 6 cm/ano está dentro da faixa fisiológica de 5 a 7 cm/ano esperada para crianças em idade escolar antes do estirão puberal.',
    expD: 'Incorreta. Velocidade de crescimento é avaliada por medições seriadas de estatura ao longo de um intervalo de 6 a 12 meses em estadiômetro vertical, sem necessidade de densitometria.',
  });

  q({
    id: 'ped-cresc-003',
    subtopic: 'Velocidade de Crescimento',
    inst: 'UFRJ',
    year: 2024,
    statement: 'Menina de 11 anos e 6 meses é levada ao pediatra pela mãe. Ao exame físico, encontra-se no estágio puberal M3P3 de Tanner e refere que nos últimos 12 meses cresceu 9,2 cm. Não teve menarca ainda. A mãe está preocupada com o crescimento acelerado. Qual é o diagnóstico e a conduta adequada?',
    A: 'Trata-se de gigantismo hipofisário decorrente de adenoma secretor de GH; solicitar RM de sela túrcica imediatamente.',
    B: 'Trata-se do pico do estirão puberal feminino (PHV - Peak Height Velocity), que ocorre caracteristicamente nos estágios M2-M3 de Tanner, com velocidade entre 8 e 10 cm/ano; conduta expectante e orientação sobre a proximidade da menarca.',
    C: 'Trata-se de puberdade precoce periférica com esgotamento epifisário grave; iniciar análogo de GnRH em caráter de urgência.',
    D: 'Trata-se de hipotireoidismo descompensado com síndrome de Van Wyk-Grumbach; iniciar levotiroxina.',
    ans: 'B',
    comment: 'Nas meninas, o estirão puberal é precoce em relação aos meninos, ocorrendo no início/meio da puberdade, predominantemente entre os estágios M2 e M3 de Tanner. O pico de velocidade de crescimento (PHV) feminino atinge cerca de 8 a 9 cm/ano (podendo chegar a 10 cm/ano) e precede a menarca por cerca de 1 a 1,5 anos. Após a menarca (que ocorre geralmente em M4), a velocidade desacelera drasticamente e o crescimento residual é em média de 4 a 6 cm até o fechamento epifisário definitivo.',
    expA: 'Incorreta. O estirão de 9,2 cm/ano em M3 é perfeitamente fisiológico e não adenoma hipofisário.',
    expB: 'Correta. Em M2/M3 a menina atinge seu pico de velocidade de crescimento (cerca de 8 a 9 cm/ano), e a menarca ocorrerá em média cerca de 1 ano após esse pico.',
    expC: 'Incorreta. Aos 11,5 anos em M3, a puberdade tem cronologia absolutamente normal (início fisiológico feminino entre 8 e 13 anos).',
    expD: 'Incorreta. A síndrome de Van Wyk-Grumbach cursa com puberdade precoce associada a parada ou atraso marcante de crescimento estatural (velocidade de crescimento muito baixa), e não estirão normal.',
  });

  q({
    id: 'ped-cresc-004',
    subtopic: 'Velocidade de Crescimento',
    inst: 'UNIFESP',
    year: 2024,
    statement: 'Garoto de 13 anos e 8 meses encontra-se no estágio G4P4 de Tanner (volume testicular de 15 mL bilateralmente). Nos últimos 12 meses, cresceu 10,8 cm. Seus amigos já haviam crescido antes e a mãe pergunta por que o estirão dele ocorreu mais tarde do que o da irmã mais velha. Assinale a afirmativa fisiologicamente correta sobre o estirão puberal masculino:',
    A: 'Nos meninos, o estirão puberal ocorre precocemente em G1-G2 com velocidade de 5 cm/ano.',
    B: 'Nos meninos, o estirão puberal é tardio, atingindo seu pico de velocidade de crescimento (cerca de 10 a 12 cm/ano) nos estágios G3-G4 de Tanner, cerca de 1,5 a 2 anos mais tarde do que nas meninas.',
    C: 'O estirão masculino é dependente exclusivamente de progesterona e ocorre simultaneamente à pubarca precoce.',
    D: 'O estirão puberal masculino produz menor ganho estatural absoluto do que o estirão feminino.',
    ans: 'B',
    comment: 'Ao contrário do sexo feminino (onde o pico de estirão ocorre precocemente em M2/M3), no sexo masculino o estirão de crescimento é um evento puberal tardio, ocorrendo nos estágios G3 e G4 de Tanner (volume testicular entre 12 e 15 mL), cerca de 1,5 a 2 anos mais tarde do que nas meninas. O pico de velocidade masculina é mais potente (10 a 12 cm/ano, vs 8 a 9 cm/ano nas meninas), o que explica, somado aos 2 anos a mais de crescimento pré-puberal, a diferença média de 13 cm de estatura final entre homens e mulheres.',
    expA: 'Incorreta. Em G1/G2 o menino ainda não iniciou o estirão puberal.',
    expB: 'Correta. O pico de velocidade masculino ocorre em estágios avançados (G3-G4), com velocidade de 10 a 12 cm/ano, conferindo maior estatura final.',
    expC: 'Incorreta. O estirão depende do sinergismo entre esteroides sexuais (testosterona convertida em estradiol nas epífises pela aromatase) e o eixo GH/IGF-1.',
    expD: 'Incorreta. O estirão masculino proporciona maior ganho estatural absoluto (cerca de 28 a 30 cm) do que o feminino (cerca de 23 a 25 cm).',
  });

  q({
    id: 'ped-cresc-005',
    subtopic: 'Velocidade de Crescimento',
    inst: 'UERJ',
    year: 2024,
    statement: 'Em pediatria, qual é considerado o parâmetro isolado mais sensível e precoce para detectar desvios patológicos do crescimento estatural?',
    A: 'A dosagem sérica isolada de hormônio do crescimento (GH) basal em jejum.',
    B: 'A velocidade de crescimento calculada em um intervalo mínimo de 6 a 12 meses.',
    C: 'A idade cronológica comparada à idade dentária.',
    D: 'A medida isolada do perímetro cefálico no escolar.',
    ans: 'B',
    comment: 'A velocidade de crescimento calculada ao longo de um período mínimo de 6 meses (idealmente 12 meses) é o indicador mais precoce e sensível de falha ou desvio do crescimento. Uma criança pode ainda estar dentro dos limites estatísticos normais da curva (ex: entre percentis 15 e 50), mas se sua velocidade de crescimento for inferior ao percentil 25 para a idade e sexo (< 5 cm/ano no escolar), ela já apresenta um processo patológico ativo antes mesmo de cruzar os canais de crescimento para baixo.',
    expA: 'Incorreta. O GH basal tem secreção pulsátil e níveis basais indetectáveis na maioria das crianças normais ao longo do dia, não tendo valor isolado.',
    expB: 'Correta. A velocidade de crescimento reflete a dinâmica do crescimento no tempo e detecta desacelerações muito antes da queda visível de percentis absolutos.',
    expC: 'Incorreta. A idade dentária sofre grande variação genética e não substitui a velocidade de crescimento.',
    expD: 'Incorreta. O perímetro cefálico tem maior valor no lactente até os 2 anos de idade para acompanhar o crescimento cerebral, perdendo sensibilidade para estatura no escolar.',
  });

  q({
    id: 'ped-cresc-006',
    subtopic: 'Velocidade de Crescimento',
    inst: 'USP-RP',
    year: 2024,
    statement: 'Menino de 9 anos é trazido ao ambulatório porque a mãe nota que ele está crescendo menos que os colegas. O prontuário mostra que há 12 meses media 128 cm e hoje mede 131,5 cm (ganho de 3,5 cm/ano). Não iniciou puberdade (G1P1). Considerando a velocidade de crescimento esperada no período pré-puberal, qual é a conduta inicial recomendada?',
    A: 'Tranquilizar a família, pois qualquer crescimento acima de 2 cm/ano é considerado normal no escolar.',
    B: 'Indicar que a velocidade está abaixo do limite fisiológico (< 5 cm/ano no escolar pré-puberal) e iniciar investigação clínica e laboratorial para causas de desaceleração do crescimento.',
    C: 'Iniciar imediatamente reposição de GH recombinante sem necessidade de exames.',
    D: 'Prescrever oxandrolona oral para estimular o apetite e acelerar a velocidade.',
    ans: 'B',
    comment: 'No período pré-puberal (escolar dos 4 anos até a puberdade), o limite inferior normal da velocidade de crescimento é de 5 cm/ano (p25). Um ganho de 3,5 cm/ano representa desaceleração patológica do crescimento (falha de crescimento), exigindo investigação etiológica minuciosa (hemograma, função tireoidiana, função renal, parasitológico, rastreio de doença celíaca, idade óssea e IGF-1).',
    expA: 'Incorreta. Crescimento de 3,5 cm/ano no escolar é patológico (< 5 cm/ano).',
    expB: 'Correta. Velocidade < 5 cm/ano no período pré-puberal exige investigação detalhada para identificar a etiologia da falha de crescimento.',
    expC: 'Incorreta. GH só tem indicação após diagnóstico etiológico e critérios formais preenchidos.',
    expD: 'Incorreta. Andrógenos anabolizantes promovem avanço rápido da idade óssea e fechamento prematuro das epífises, comprometendo a estatura final.',
  });

  q({
    id: 'ped-cresc-007',
    subtopic: 'Velocidade de Crescimento',
    inst: 'SCMSP',
    year: 2024,
    statement: 'Qual é o ganho estatural médio esperado para uma criança saudável durante o segundo ano de vida (entre 12 e 24 meses)?',
    A: 'Cerca de 25 cm/ano.',
    B: 'Cerca de 12 a 15 cm/ano.',
    C: 'Cerca de 4 a 5 cm/ano.',
    D: 'Cerca de 1 a 2 cm/ano.',
    ans: 'B',
    comment: 'A velocidade de crescimento decai de forma contínua desde o nascimento: 1º ano: ~25 cm/ano; 2º ano: ~12 a 15 cm/ano; 3º ano: ~7 a 8 cm/ano; 4 anos até início da puberdade: ~5 a 7 cm/ano; Estirão puberal: ~8 a 12 cm/ano. Assim, no 2º ano o ganho médio é de 12 a 15 cm.',
    expA: 'Incorreta. 25 cm/ano é o ganho do primeiro ano de vida.',
    expB: 'Correta. No segundo ano de vida a criança cresce em média de 12 a 15 cm.',
    expC: 'Incorreta. 4 a 5 cm/ano é o limite inferior do período escolar pré-puberal.',
    expD: 'Incorreta. Ganho de 1 a 2 cm/ano representa parada quase total do crescimento.',
  });

  q({
    id: 'ped-cresc-008',
    subtopic: 'Velocidade de Crescimento',
    inst: 'UFMG',
    year: 2024,
    statement: 'Menina de 13 anos, cuja menarca ocorreu há 18 meses, comparece para consulta. A mãe quer saber se ela ainda crescerá mais 15 cm como a prima que acabou de entrar na puberdade. Ao exame: M5P4, epífises em fase final de fusão. Qual é a resposta cientificamente respaldada sobre o crescimento pós-menarca?',
    A: 'A menarca marca o início do pico do estirão, momento em que a menina cresce mais 15 a 20 cm.',
    B: 'Após a menarca, a velocidade de crescimento cai expressivamente e o ganho estatural residual médio é de apenas 4 a 6 cm até a fusão epifisária completa.',
    C: 'O crescimento pós-menarca cessa imediatamente em 24 horas devido ao fechamento súbito de todas as cartilagens.',
    D: 'A menarca não tem qualquer correlação temporal com a desaceleração do crescimento estatural.',
    ans: 'B',
    comment: 'A menarca é um marco puberal tardio no sexo feminino, ocorrendo habitualmente cerca de 1 a 1,5 anos após o pico do estirão de crescimento (PHV), no estágio M4 de Tanner. Sob a ação dos níveis elevados de estrógeno, ocorre a rápida senescência e ossificação das cartilagens de conjugação epifisárias. O ganho estatural pós-menarca é limitado, girando em média entre 4 e 6 cm (raramente ultrapassando 7 a 8 cm).',
    expA: 'Incorreta. O pico do estirão ocorre antes da menarca, em M2-M3.',
    expB: 'Correta. O crescimento residual médio pós-menarca é de 4 a 6 cm devido à ação do estradiol promovendo o fechamento epifisário.',
    expC: 'Incorreta. O fechamento não é imediato em 24 horas; ocorre ao longo de cerca de 1 a 2 anos após a primeira menstruação.',
    expD: 'Incorreta. A menarca correlaciona-se intimamente com a desaceleração final e parada do crescimento estatural.',
  });
}
