import { q } from './helper_crescimento.js';

export function loadSec11() {
  q({
    id: 'ped-cresc-085',
    subtopic: 'Raquitismo Carencial e Hipofosfatêmico',
    inst: 'USP-SP',
    year: 2024,
    statement: 'Lactente de 14 meses é levado à consulta por atraso na marcha e deformidade nas pernas. História: amamentação exclusiva ao seio materno até hoje, sem fórmulas infantis, sem uso de suplementos vitamínicos profiláticos e com restrição domiciliar estrita (sem banho de sol). Ao exame físico: fontanela anterior ampla e aberta (3x3 cm), proeminência nodular palpável nas junções costocondrais bilateralmente ("rosário raquítico"), alargamento evidente dos punhos e tornozelos e arqueamento pronunciado das pernas em varo (genu varo). Qual é o diagnóstico fisiopatológico e o exame radiológico inicial de escolha?',
    A: 'Acondroplasia clássica; radiografia de crânio.',
    B: 'Raquitismo carencial por deficiência de vitamina D; radiografia de punhos e joelhos em AP.',
    C: 'Escorbuto infantil por carência de vitamina C; tomografia de tórax.',
    D: 'Osteogênese imperfeita tipo II; ressonância magnética dos membros.',
    ans: 'B',
    comment: 'O quadro clínico reúne as manifestações patognomônicas do raquitismo carencial ativo da primeira infância: 1) Fatores de risco clássicos (aleitamento materno exclusivo sem suplementação diária de 400-600 UI de vitamina D e privação de radiação solar UV-B); 2) Sinais esqueléticos decorrentes de falha de mineralização da matriz osteoide na placa epifisária: alargamento metafisário de punhos e tornozelos, rosário raquítico (proeminência das junções costocondrais), fontanela anterior ampla com atraso de fechamento e deformidade em arqueamento dos membros inferiores com a sustentação de peso (genu varo). A radiografia de punho e joelho em AP é o exame de imagem inicial padrão para demonstrar o alargamento e desfiamento metafisário.',
    expA: 'Incorreta. Acondroplasia é congênita, cursa com membros curtos rizomélicos e não decorre de carência vitamínica.',
    expB: 'Correta. Raquitismo carencial por deficiência de vitamina D em lactente em aleitamento exclusivo sem suplementação; avaliação radiológica com punhos e joelhos.',
    expC: 'Incorreta. Escorbuto (deficiência de vitamina C) cursa com manifestações hemorrágicas gengivais e dor óssea intensa por hematomas subperiósteos (pseudoparalisia de Parrot).',
    expD: 'Incorreta. Osteogênese imperfeita tipo II é forma perinatal letal com múltiplas fraturas intraútero.',
  });

  q({
    id: 'ped-cresc-086',
    subtopic: 'Raquitismo Carencial e Hipofosfatêmico',
    inst: 'UNICAMP',
    year: 2024,
    statement: 'Quais são as alterações radiológicas clássicas visualizadas nas metáfises dos ossos longos (como rádio e ulna distais no punho) na fase ativa do raquitismo?',
    A: 'Esclerose cortical intensa e hiperdensidade homogênea de toda a diáfise.',
    B: 'Alargamento da placa de crescimento, perda da linha de mineralização provisória, concavidade em forma de "taça" (cupping) e aspecto desfiado ou espiculado em "pincel" (fraying) da borda metafisária.',
    C: 'Ausência total de cartilagem de crescimento com fechamento epifisário aos 12 meses.',
    D: 'Fraturas patológicas em galho verde exclusivas da diáfise média.',
    ans: 'B',
    comment: 'No raquitismo ativo, os condrócitos hipertróficos continuam proliferando na fise, mas a matriz osteoide não consegue ser mineralizada com hidroxiapatita de cálcio e fósforo. Isso gera um acúmulo patológico de osteoide desorganizado e amolecido, que sob estresse mecânico se alarga lateralmente. Na radiografia, isso se traduz pela tétrade clássica: 1) Aumento da distância entre a epífise e a diáfise (alargamento radiológico da fise); 2) Perda da nitidez da linha de mineralização; 3) Escavação metafisária em "taça" (cupping); 4) Bordas metafisárias desfiadas e irregulares com aspecto em "pincel" (fraying).',
    expA: 'Incorreta. O raquitismo cursa com osteopenia e desmineralização, e não esclerose densa (típica da osteopetrose).',
    expB: 'Correta. A concavidade em taça (cupping) e as bordas desfiadas em pincel (fraying) com alargamento metafisário são os sinais radiológicos patognomônicos do raquitismo.',
    expC: 'Incorreta. As cartilagens estão alargadas e abertas, nunca fechadas prematuramente.',
    expD: 'Incorreta. Embora possam ocorrer pseudofraturas (zonas de Looser), as alterações metafisárias em taça e pincel são a marca do raquitismo.',
  });

  q({
    id: 'ped-cresc-087',
    subtopic: 'Raquitismo Carencial e Hipofosfatêmico',
    inst: 'FMUSP',
    year: 2024,
    statement: 'Qual é o perfil laboratorial sérico clássico encontrado em um lactente com Raquitismo Carencial por deficiência de vitamina D em fase de descompensação estabelecida?',
    A: '25(OH)Vitamina D muito baixa (< 12 a 20 ng/mL), Cálcio sérico normal ou baixo, Fósforo sérico baixo, Fosfatase Alcalina (FA) MUITO elevada e PTH (paratormônio) marcadamente elevado.',
    B: '25(OH)Vitamina D normal, Cálcio elevado, Fósforo elevado, Fosfatase Alcalina suprimida e PTH indetectável.',
    C: '25(OH)Vitamina D elevada (> 100 ng/mL), com hipocalciúria grave.',
    D: 'Elevação exclusiva de ácido úrico sem qualquer alteração mineral.',
    ans: 'A',
    comment: 'A cascata laboratorial do raquitismo carencial tem lógica fisiopatológica perfeita: 1) A carência de vitamina D derruba os níveis de 25-hidroxivitamina D [25(OH)D < 20 ng/mL, frequentemente < 12 ng/mL]; 2) Sem calcitriol suficiente, a absorção intestinal de cálcio despenca, tendendo à hipocalcemia; 3) A hipocalcemia estimula imediatamente as paratireoides a secretarem maciçamente PTH (hiperparatireoidismo secundário); 4) O PTH elevado atua nos rins induzindo fosfatúria maciça (promovendo hipofosfatemia marcante) e retira cálcio do osso, normalizando ou mantendo o cálcio sérico no limite inferior; 5) A tentativa osteoblástica desesperada de mineralizar a matriz não calcificada eleva exponencialmente a Fosfatase Alcalina (FA), que é o melhor marcador sérico de atividade da doença.',
    expA: 'Correta. 25(OH)D baixa + hipofosfatemia + fosfatase alcalina muito elevada + PTH elevado (com cálcio normal/baixo) compõem o perfil típico do raquitismo carencial.',
    expB: 'Incorreta. Esse perfil sugeriria intoxicação por vitamina D com hipercalcemia e supressão de PTH.',
    expC: 'Incorreta. Na deficiência carencial a 25(OH)D está severamente diminuída.',
    expD: 'Incorreta. O raquitismo é um distúrbio do metabolismo de cálcio e fósforo, não de ácido úrico.',
  });

  q({
    id: 'ped-cresc-088',
    subtopic: 'Raquitismo Carencial e Hipofosfatêmico',
    inst: 'UFRJ',
    year: 2024,
    statement: 'Menino de 2 anos e meio apresenta arqueamento progressivo e severo das pernas em varo com rotação interna da tíbia, baixa estatura desproporcionada por encurtamento de membros inferiores e alargamento de punhos. O histórico alimentar é excelente, com ingesta adequada de laticínios e suplementação vitamínica regular. O perfil laboratorial revela: Cálcio sérico de 9,6 mg/dL (normal), Fósforo sérico de 1,8 mg/dL (MUITO BAIXO), Fosfatase Alcalina de 1.450 U/L (muito elevada), PTH normal e 25(OH)Vitamina D de 38 ng/mL (normal). O teste de urina revela perda renal isolada maciça de fosfato com baixa reabsorção tubular de fosfato (TRP < 85%). Qual é o diagnóstico e o defeito genético subjacente?',
    A: 'Raquitismo carencial de vitamina D por erro alimentar.',
    B: 'Raquitismo Hipofosfatêmico Ligado ao X (XLH), decorrente de mutação no gene PHEX com hipersecreção do hormônio fosfatúrico FGF23.',
    C: 'Hipotireoidismo primário por tireoidite autoimune.',
    D: 'Acondroplasia com mutação no FGFR3.',
    ans: 'B',
    comment: 'O Raquitismo Hipofosfatêmico Ligado ao X (XLH) é a forma hereditária mais frequente de raquitismo (herança dominante ligada ao X). É causado por mutações inativadoras no gene PHEX (no cromossomo X), o que resulta em perda da regulação e consequente hipersecreção crônica do hormônio FGF23 (Fator de Crescimento de Fibroblasto 23) pelos osteócitos. O excesso de FGF23 atua nos túbulos renais: 1) Inibe os cotransportadores de sódio-fósforo (NaPi-IIa e NaPi-IIc), causando perda maciça de fósforo na urina e hipofosfatemia severa intratável; 2) Inibe a enzima 1-alfa-hidroxilase renal, impedindo a conversão de 25(OH)D em calcitriol ativo. Como consequência, o cálcio é normal, a 25(OH)D é normal, mas o fósforo é extremamente baixo com FA muito alta.',
    expA: 'Incorreta. A 25(OH)D é normal (38 ng/mL) e o paciente recebe suplementação adequada, afastando a causa carencial.',
    expB: 'Correta. Raquitismo Hipofosfatêmico Ligado ao X (mutação no gene PHEX com excesso de FGF23 promovendo fosfatúria renal com cálcio normal e fósforo muito baixo).',
    expC: 'Incorreta. Não cursa com hipofosfatemia isolada nem fosfatúria maciça.',
    expD: 'Incorreta. Acondroplasia não altera fósforo, cálcio ou fosfatase alcalina séricos.',
  });

  q({
    id: 'ped-cresc-089',
    subtopic: 'Raquitismo Carencial e Hipofosfatêmico',
    inst: 'UNIFESP',
    year: 2024,
    statement: 'Qual é a terapia farmacológica moderna com anticorpo monoclonal humano aprovada para o tratamento específico do Raquitismo Hipofosfatêmico Ligado ao X (XLH), que neutraliza diretamente o FGF23 circulante?',
    A: 'Infliximabe (anti-TNF alfa).',
    B: 'Burosumabe (anticorpo monoclonal IgG1 humano anti-FGF23).',
    C: 'Rituximabe (anti-CD20).',
    D: 'Trastuzumabe (anti-HER2).',
    ans: 'B',
    comment: 'O Burosumabe é um anticorpo monoclonal humano totalmente recombinante da classe IgG1 direcionado contra o FGF23 circulante. Ele se liga ao FGF23 e neutraliza sua atividade biológica, restaurando a reabsorção tubular renal de fosfato e a síntese renal de 1,25-di-hidroxivitamina D (calcitriol). Essa terapia modificadora da doença normaliza os níveis séricos de fósforo, melhora a mineralização da placa de crescimento, corrige deformidades ósseas e promove recuperação da velocidade de crescimento estatural em crianças com XLH.',
    expA: 'Incorreta. Infliximabe trata doenças inflamatórias intestinais e artrite reumatoide.',
    expB: 'Correta. Burosumabe é o anticorpo monoclonal específico anti-FGF23 aprovado para Raquitismo Hipofosfatêmico Ligado ao X.',
    expC: 'Incorreta. Rituximabe depele linfócitos B em linfomas e doenças autoimunes.',
    expD: 'Incorreta. Trastuzumabe trata câncer de mama HER2-positivo.',
  });

  q({
    id: 'ped-cresc-090',
    subtopic: 'Raquitismo Carencial e Hipofosfatêmico',
    inst: 'UERJ',
    year: 2024,
    statement: 'Qual é a recomendação oficial da Sociedade Brasileira de Pediatria (SBP) e do Ministério da Saúde para a suplementação profilática universal de vitamina D em lactentes em aleitamento materno exclusivo a termo?',
    A: 'Não é necessária qualquer suplementação se a mãe se alimentar bem.',
    B: 'Administrar 400 UI/dia de vitamina D por via oral a partir da primeira semana de vida até os 12 meses; e 600 UI/dia no segundo ano de vida (dos 12 aos 24 meses).',
    C: 'Administrar uma megadose única de 600.000 UI intramuscular ao nascimento e nenhuma outra dose.',
    D: 'Administrar 10.000 UI/dia por via venosa contínua.',
    ans: 'B',
    comment: 'Pelo consenso da Sociedade Brasileira de Pediatria (SBP, 2016/2021) e da Academia Americana de Pediatria (AAP), o leite materno humano, embora seja o alimento mais perfeito para a espécie humana, possui concentrações relativamente baixas de vitamina D (cerca de 20 a 60 UI/litro). Devido às restrições contemporâneas de exposição solar desprotegida pelo risco de neoplasias cutâneas futuras, recomenda-se a suplementação profilática universal: 400 UI/dia de vitamina D (colecalciferol) iniciando na primeira semana de vida até completar 12 meses; a partir dos 12 meses até os 24 meses de vida, a dose recomendada é de 600 UI/dia.',
    expA: 'Incorreta. O leite humano não supre as necessidades de vitamina D sem exposição solar intensa, havendo alto risco de raquitismo sem suplementação.',
    expB: 'Correta. 400 UI/dia no primeiro ano e 600 UI/dia no segundo ano de vida é a diretriz oficial da SBP.',
    expC: 'Incorreta. Megadoses neonatais rotineiras aumentam o risco de hipercalcemia e nefrocalcinose.',
    expD: 'Incorreta. Dose tóxica diária inaceitável.',
  });

  q({
    id: 'ped-cresc-091',
    subtopic: 'Raquitismo Carencial e Hipofosfatêmico',
    inst: 'SCMSP',
    year: 2024,
    statement: 'Como se denomina o amolecimento patológico dos ossos da calota craniana (parietais e occipital), que à palpação digital cede com facilidade e retorna elásticamente com sensação comparada à compressão de uma "bola de pingue-pongue", sinal precoce de raquitismo em lactentes jovens?',
    A: 'Plagiocefalia posicional.',
    B: 'Craniossinostose coronal.',
    C: 'Craniotabes raquítico.',
    D: 'Hiperostose cortical infantil.',
    ans: 'C',
    comment: 'O Craniotabes é um dos sinais clínicos mais precoces de raquitismo ativo no lactente pequeno (geralmente nos primeiros meses de vida). Caracteriza-se pelo amolecimento das tábuas ósseas do crânio nas regiões parietal e occipital posterior (ao longo da sutura lambdoide). À palpação suave com as pontas dos dedos, o osso adelgaçado deprime-se sob a pressão digital e rebate elasticamente, produzindo uma sensação tátil idêntica à de pressionar uma bola de celuloide/pingue-pongue.',
    expA: 'Incorreta. Plagiocefalia posicional é assimetria craniana por apoio postural vicioso sem amolecimento elástico.',
    expB: 'Incorreta. Craniossinostose é fusão prematura das suturas com fechamento ósseo precoce rígido.',
    expC: 'Correta. Craniotabes é o termo semiótico clássico para o amolecimento raquítico da calota craniana.',
    expD: 'Incorreta. Hiperostose infantil (doença de Caffey) cursa com espessamento ósseo mandibular e diafisário doloroso.',
  });

  q({
    id: 'ped-cresc-092',
    subtopic: 'Raquitismo Carencial e Hipofosfatêmico',
    inst: 'UFMG',
    year: 2024,
    statement: 'Qual é o tratamento inicial preconizado para um lactente de 15 meses diagnosticado com Raquitismo Carencial ativo grave por deficiência de vitamina D?',
    A: 'Cirurgia ortopédica de osteotomia corretiva imediata das duas tíbias.',
    B: 'Administração de Vitamina D (Colecalciferol) em dose de ataque (2.000 UI/dia por via oral por 8 a 12 semanas ou dose cumulativa equivalente), associada obrigatoriamente a aporte adequado de Cálcio elementar oral (cerca de 500 mg/dia) para prevenir a síndrome da "fome óssea" (hipocalcemia aguda pós-tratamento).',
    C: 'Aporte exclusivo de vitamina C intravenosa e suspensão de laticínios.',
    D: 'Uso de bisfosfonatos intravenosos diários sem vitamina D.',
    ans: 'B',
    comment: 'O tratamento do raquitismo carencial ativo visa restabelecer rapidamente os estoques corporais de colecalciferol: administra-se vitamina D3 (2.000 UI/dia por via oral durante cerca de 2 a 3 meses, ou doses escalonadas conformes peso/idade) até a normalização radiológica e da fosfatase alcalina, passando em seguida para a dose de manutenção (400 a 600 UI/dia). É MANDATÓRIO associar cálcio elementar oral (30 a 50 mg/kg/dia ou ~500 mg/dia), pois a rápida remineralização óssea ("hungry bone syndrome" / fome óssea) drena maciçamente o cálcio circulante para o esqueleto; sem aporte de cálcio, o paciente pode evoluir com hipocalcemia aguda grave, tetania e convulsões.',
    expA: 'Incorreta. Deformidades raquíticas leves a moderadas remodelam espontaneamente após a mineralização; cirurgia é contraindicada na fase ativa.',
    expB: 'Correta. Colecalciferol terapêutico associado a cálcio elementar para prevenir hipocalcemia por fome óssea é o padrão de tratamento.',
    expC: 'Incorreta. Vitamina C não trata raquitismo de cálcio e vitamina D.',
    expD: 'Incorreta. Bisfosfonatos inibem a reabsorção óssea e não corrigem a mineralização epifisária.',
  });
}
