import { q } from './helper_crescimento.js';

export function loadSec2() {
  q({
    id: 'ped-cresc-009',
    subtopic: 'Curvas da OMS e Avaliação Antropométrica',
    inst: 'USP-SP',
    year: 2024,
    statement: 'Menino de 5 anos é levado à UBS para avaliação do desenvolvimento. Sua estatura atual aferida com técnica correta encontra-se no Escore-Z de Estatura para Idade (E/I) de -2,4 DP nos gráficos de referência da OMS 2006/2007. Segundo os critérios diagnósticos padronizados pelo Ministério da Saúde e pela Sociedade Brasileira de Pediatria (SBP), como se classifica a estatura dessa criança?',
    A: 'Estatura adequada para a idade.',
    B: 'Baixa estatura para a idade.',
    C: 'Muito baixa estatura para a idade.',
    D: 'Nanismo letal acondroplásico.',
    ans: 'B',
    comment: 'Pelas curvas da OMS adotadas pela SBP e Ministério da Saúde: Estatura/Idade ≥ Escore-Z -2: Estatura adequada para a idade; Escore-Z < -2 e ≥ -3: Baixa estatura para a idade (equivalente a percentil < 3 e ≥ 0,1); Escore-Z < -3: Muito baixa estatura para a idade (percentil < 0,1). No caso, com Escore-Z de -2,4 DP, classifica-se como Baixa estatura para a idade.',
    expA: 'Incorreta. Estatura adequada exige Escore-Z ≥ -2 DP.',
    expB: 'Correta. Escore-Z entre -2 e -3 DP define Baixa estatura para a idade.',
    expC: 'Incorreta. Muito baixa estatura exige Escore-Z < -3 DP.',
    expD: 'Incorreta. O diagnóstico de acondroplasia requer características clínicas de displasia óssea desproporcionada e confirmação genética ou radiológica, não sendo uma classificação antropométrica da OMS.',
  });

  q({
    id: 'ped-cresc-010',
    subtopic: 'Curvas da OMS e Avaliação Antropométrica',
    inst: 'UNICAMP',
    year: 2024,
    statement: 'Menina de 3 anos e 6 meses tem sua caderneta de saúde analisada. Aos 12 meses, sua estatura encontrava-se no percentil 50 (Escore-Z 0). Aos 2 anos, caiu para o percentil 25. Aos 3 anos e meio, encontra-se no percentil 10. Embora ainda esteja acima do percentil 3, a mãe relata que ela parou de trocar o tamanho das calças. Qual é o conceito aplicado a essa evolução antropométrica?',
    A: 'Crescimento perfeitamente fisiológico, pois qualquer estatura acima do percentil 3 dispensa preocupação clínica.',
    B: 'Desaceleração do crescimento com cruzamento descendente de canais de percentil (falha de crescimento), justificando investigação diagnóstica mesmo com estatura absoluta momentaneamente > -2 DP.',
    C: 'Erro de medição inevitável, sem relevância clínica.',
    D: 'Variante normal do tipo baixa estatura familiar sem necessidade de exames.',
    ans: 'B',
    comment: 'Após os 2 anos de idade, a criança já encontrou seu canal genético de crescimento e deve manter uma trajetória paralela às linhas das curvas de percentil/escore-Z. A perda ou cruzamento descendente de canais de percentil (queda de 2 ou mais canais principais de percentil ou perda superior a 0,5 a 1 DP no Escore-Z) define falha de crescimento e indica desaceleração patológica da velocidade de crescimento, devendo ser investigada independentemente de a criança ainda estar acima do percentil 3.',
    expA: 'Incorreta. A perda de canais é sinal de alarme precoce que antecede a baixa estatura em valor absoluto.',
    expB: 'Correta. O cruzamento descendente de percentis após os 2 anos de idade indica desaceleração estatural patológica ativa e impõe investigação clínica.',
    expC: 'Incorreta. A persistência da queda ao longo de sucessivas consultas não pode ser atribuída a simples erro de aferição.',
    expD: 'Incorreta. Na baixa estatura familiar, a criança cresce paralelamente à curva, dentro de seu canal, sem queda progressiva de percentis.',
  });

  q({
    id: 'ped-cresc-011',
    subtopic: 'Curvas da OMS e Avaliação Antropométrica',
    inst: 'UFRJ',
    year: 2024,
    statement: 'Lactente masculino de 8 meses nasceu a termo, com peso de 3.200 g e comprimento de 50 cm (ambos no percentil 50). Desde os 4 meses, sua curva de comprimento vem desacelerando e hoje está no percentil 15, compatível com a estatura-alvo parental calculada (p15-p25). A criança é ativa, mama bem ao seio e não tem sintomas sistêmicos. Qual é o fenômeno fisiológico mais provável?',
    A: 'Deficiência congênita grave de GH com indicação de ressonância magnética imediata.',
    B: 'Canalização do crescimento (regulação do canal genético ou "catch-down" fisiológico), comum entre os 6 e 18 a 24 meses de vida.',
    C: 'Síndrome de má absorção intestinal por doença celíaca precoce.',
    D: 'Erro inato do metabolismo mitocondrial com acidose láctica.',
    ans: 'B',
    comment: 'Ao nascimento e nos primeiros meses de vida, as dimensões antropométricas da criança refletem primariamente as condições do ambiente intrauterino e a nutrição materno-placentária. Entre os 6 e os 18-24 meses de vida, ocorre o fenômeno fisiológico de "canalização do crescimento" (regulação ao canal genético): crianças com potencial genético menor podem desacelerar (catch-down) até atingir seu canal familiar, enquanto crianças com pais altos nascidas menores aceleram (catch-up). Uma vez atingido o canal genético, o crescimento passa a ocorrer paralelo às curvas.',
    expA: 'Incorreta. O quadro é perfeitamente típico da canalização fisiológica para o alvo genético.',
    expB: 'Correta. O alinhamento com a estatura-alvo familiar entre 6 e 24 meses representa o fenômeno de canalização genética.',
    expC: 'Incorreta. A criança está assintomática, em aleitamento materno e sem diarreia, distensão ou perda ponderal desproporcional.',
    expD: 'Incorreta. Não há acidose, hipoglicemia, atraso neuromotor ou qualquer manifestação metabólica.',
  });

  q({
    id: 'ped-cresc-012',
    subtopic: 'Curvas da OMS e Avaliação Antropométrica',
    inst: 'UNIFESP',
    year: 2024,
    statement: 'Segundo a distribuição gaussiana padrão utilizada nas curvas de crescimento da Organização Mundial da Saúde (OMS), a qual percentil aproxima-se o Escore-Z de -2 desvios-padrão (DP)?',
    A: 'Percentil 50.',
    B: 'Percentil 10.',
    C: 'Percentil 2,3 (aproximadamente percentil 3).',
    D: 'Percentil 0,1.',
    ans: 'C',
    comment: 'Em uma curva de distribuição normal (gaussiana): Escore-Z 0 corresponde à mediana (Percentil 50); Escore-Z -1 DP corresponde aproximadamente ao Percentil 16; Escore-Z -2 DP corresponde exatamente ao Percentil 2,3 (arredondado clinicamente para Percentil 3); Escore-Z -3 DP corresponde ao Percentil 0,13 (aproximadamente Percentil 0,1). Por isso, define-se baixa estatura por E/I < percentil 3 ou Escore-Z < -2 DP.',
    expA: 'Incorreta. Percentil 50 equivale a Escore-Z 0.',
    expB: 'Incorreta. Percentil 10 equivale a Escore-Z de aproximadamente -1,28 DP.',
    expC: 'Correta. O Escore-Z de -2 DP corresponde estatisticamente ao percentil 2,28% (~ percentil 3).',
    expD: 'Incorreta. Percentil 0,1 equivale a Escore-Z de -3 DP.',
  });

  q({
    id: 'ped-cresc-013',
    subtopic: 'Curvas da OMS e Avaliação Antropométrica',
    inst: 'FMUSP',
    year: 2024,
    statement: 'Criança de 2 anos e 3 meses apresenta Escore-Z de Estatura para Idade de -3,4 DP nos gráficos da OMS. Não há dismorfismos evidentes, mas os pais referem que a criança sempre foi a menor de qualquer grupo e o crescimento é estagnado. Como se classifica essa condição antropométrica e qual o significado prognóstico?',
    A: 'Classifica-se como variante normal de baixa estatura familiar, sem necessidade de investigação etiológica.',
    B: 'Classifica-se como "Muito baixa estatura para a idade" (Escore-Z < -3 DP); afasta praticamente variantes normais e impõe ampla investigação etiológica (sindrômica, endócrina ou sistêmica).',
    C: 'Classifica-se como estatura adequada limítrofe, recomendando-se reavaliação em 3 anos.',
    D: 'Classifica-se como gigantismo infantil mascarado por desidratação crônica.',
    ans: 'B',
    comment: 'Escore-Z de Estatura/Idade < -3 DP é um critério de grande gravidade clínica e epidemiológica (encontra-se abaixo do percentil 0,1, ou seja, menos de 1 em cada 1.000 crianças saudáveis tem essa estatura). Essa magnitude de déficit estatural afasta com quase 100% de certeza as variantes normais (baixa estatura familiar ou retardo constitucional) e quase invariavelmente decorre de patologia orgânica primária (doença genética, displasia óssea, síndrome cromossômica, endocrinopatia grave ou doença crônica consumptiva).',
    expA: 'Incorreta. Variantes normais raramente causam déficits abaixo de -2,5 ou -3 DP.',
    expB: 'Correta. Escore-Z < -3 DP define Muito Baixa Estatura e exige investigação formal completa de causas patológicas.',
    expC: 'Incorreta. Escore-Z de -3,4 DP é um déficit gravíssimo, nunca considerado limítrofe normal.',
    expD: 'Incorreta. Hipótese sem qualquer sentido biológico ou clínico.',
  });

  q({
    id: 'ped-cresc-014',
    subtopic: 'Curvas da OMS e Avaliação Antropométrica',
    inst: 'UERJ',
    year: 2024,
    statement: 'Ao plotar o crescimento de uma criança de 4 anos com suspeita de baixa estatura, o pediatra avalia os índices antropométricos de Waterlow: Peso para Estatura (P/E) e Estatura para Idade (E/I). A criança apresenta E/I < 90% do padrão (baixa estatura/nanismo) com P/E normal (> 90%). Qual é a interpretação clínico-nutricional desse perfil?',
    A: 'Desnutrição aguda grave (emaciação recente / wasting).',
    B: 'Desnutrição crônica pregressa / compensada (stunting / nanismo nutricional).',
    C: 'Obesidade mórbida de causa neuroendócrina.',
    D: 'Edema nutricional por kwashiorkor agudo.',
    ans: 'B',
    comment: 'Na classificação de Waterlow: Desnutrição aguda (emaciação / wasting): P/E diminuído (< 90%) com E/I normal (≥ 90%); Desnutrição crônica pregressa compensada (nanismo nutricional / stunting): E/I diminuída (< 90%) com P/E normal (≥ 90%) — a criança já adaptou seu peso à sua baixa estatura resultante de desnutrição crônica antiga; Desnutrição crônica agudizada: ambos diminuídos (E/I < 90% e P/E < 90%).',
    expA: 'Incorreta. A desnutrição aguda cursa com P/E baixo e E/I preservada.',
    expB: 'Correta. E/I comprometida com P/E normal reflete cronicidade com adaptação ponderal (nanismo nutricional).',
    expC: 'Incorreta. P/E está normal, não havendo obesidade.',
    expD: 'Incorreta. Kwashiorkor é forma grave aguda com edema bilateral e hepatomegalia.',
  });

  q({
    id: 'ped-cresc-015',
    subtopic: 'Curvas da OMS e Avaliação Antropométrica',
    inst: 'SCMSP',
    year: 2024,
    statement: 'Na avaliação da técnica antropométrica em pediatria, a partir de qual idade a criança deve ser medida obrigatoriamente na posição em pé (estatura / estadiômetro vertical), e não deitada (comprimento / estadiômetro horizontal)?',
    A: 'A partir dos 6 meses de vida.',
    B: 'A partir dos 2 anos de idade (24 meses).',
    C: 'Apenas após os 5 anos de idade.',
    D: 'Apenas após a puberdade.',
    ans: 'B',
    comment: 'Pelas normas da OMS e da SBP: Menores de 2 anos (0 a 23 meses): afere-se o COMPRIMENTO deitado (decúbito dorsal) em estadiômetro horizontal infantil (antropômetro infantil de mesa com cabeceira fixa e cursor móvel nos pés). Crianças de 2 anos ou mais (≥ 24 meses): afere-se a ESTATURA em pé (posição ereta) em estadiômetro vertical de parede com encosto em 4 ou 5 pontos (calcanhares, panturrilhas, nádegas, dorso e occipício com a cabeça no plano de Frankfurt). Medir em pé diminui cerca de 0,7 cm em relação ao deitado por compressão fisiológica da gravidade sobre os discos intervertebrais.',
    expA: 'Incorreta. Aos 6 meses mede-se rigorosamente deitado.',
    expB: 'Correta. O ponto de corte clássico e normativo da OMS é aos 2 anos de idade (24 meses).',
    expC: 'Incorreta. Aos 5 anos a criança já deve ser medida em pé há 3 anos.',
    expD: 'Incorreta. Não tem correlação com a puberdade.',
  });

  q({
    id: 'ped-cresc-016',
    subtopic: 'Curvas da OMS e Avaliação Antropométrica',
    inst: 'UFPE',
    year: 2024,
    statement: 'Uma criança de 3 anos tem Escore-Z de IMC para Idade (IMC/I) de +2,3 DP associado a Escore-Z de Estatura para Idade de -2,6 DP (baixa estatura com sobrepeso/obesidade). Esse padrão antropométrico clássico (estatura caindo enquanto o IMC/peso sobe) é fortemente sugestivo de:',
    A: 'Desnutrição proteico-calórica secundária a parasitose intestinal.',
    B: 'Doença celíaca clássica em fase ativa.',
    C: 'Etiologia endócrina da baixa estatura (como deficiência de GH, hipotireoidismo ou síndrome de Cushing).',
    D: 'Baixa estatura constitucional simples sem necessidade de rastreio.',
    ans: 'C',
    comment: 'A regra de ouro da propedêutica do crescimento é: Doenças desnutritivas/sistêmicas (celíaca, DII, cardiopatias, DRC, desnutrição): o PESO cai antes da altura (criança emagrece e depois para de crescer). Já nas endocrinopatias (deficiência de GH, hipotireoidismo grave e hipercortisolismo/Cushing): a ALTURA para de crescer, mas o PESO continua subindo ou se mantém (baixa estatura com ganho ponderal relativo ou obesidade).',
    expA: 'Incorreta. Na desnutrição o peso é o primeiro parâmetro a declinar acentuadamente.',
    expB: 'Incorreta. Na doença celíaca a má absorção causa perda ponderal e emaciação prévia ao atraso estatural.',
    expC: 'Correta. O padrão de baixa estatura associada a sobrepeso/obesidade é o protótipo clínico das causas endócrinas de baixa estatura.',
    expD: 'Incorreta. Variantes constitucionais cursam com velocidade normal e proporção harmônica de peso e estatura.',
  });

  q({
    id: 'ped-cresc-017',
    subtopic: 'Curvas da OMS e Avaliação Antropométrica',
    inst: 'UFRGS',
    year: 2024,
    statement: 'Menino de 7 anos apresenta velocidade de crescimento de 5,8 cm/ano, sem queixas clínicas. Sua curva de estatura encontra-se exatamente sobre a linha do percentil 10 desde os 2 anos de idade, paralela ao canal mediano. O pai mede 165 cm e a mãe 152 cm. Qual é a conduta médica correta para este paciente?',
    A: 'Solicitar teste de estímulo de GH com clonidina de urgência.',
    B: 'Iniciar reposição de hormônio tireoidiano em dose suprafisiológica.',
    C: 'Reconhecer que a criança tem velocidade de crescimento normal, canalizada e compatível com o percentil genético familiar, devendo manter acompanhamento clínico sem exames invasivos desnecessários.',
    D: 'Encaminhar para cirurgia de alongamento ósseo femoral.',
    ans: 'C',
    comment: 'A criança tem velocidade de crescimento normal (5,8 cm/ano está dentro da faixa esperada de 5 a 7 cm/ano para escolares pré-puberais) e mantém seu canal estável no percentil 10, que é absolutamente congruente com a baixa estatura de seus pais (pai 165 cm e mãe 152 cm geram um alvo genético baixo, em torno de 165 cm). Trata-se de uma variante normal (Baixa Estatura Familiar), que não exige exames invasivos.',
    expA: 'Incorreta. Velocidade normal e canal estável afastam deficiência de GH.',
    expB: 'Incorreta. Não há hipotireoidismo e reposição desnecessária causa hipertireoidismo iatrogênico.',
    expC: 'Correta. Velocidade normal (5,8 cm/ano) e estabilidade de canal compatível com o canal parental configuram variante normal que requer apenas seguimento clínico.',
    expD: 'Incorreta. Indicação absurda para uma criança fisiologicamente saudável.',
  });
}
