import { q } from './helper_crescimento.js';

export function loadSec3() {
  q({
    id: 'ped-cresc-018',
    subtopic: 'Estatura-Alvo Parental',
    inst: 'USP-SP',
    year: 2024,
    statement: 'Menino de 6 anos é avaliado por baixa estatura. O pai mede 175 cm e a mãe mede 162 cm. Utilizando o método clássico de Tanner para o cálculo da estatura-alvo (canal genético parental), qual é o valor da estatura-alvo calculada e qual a faixa esperada de variação normal?',
    A: 'Alvo de 168,5 cm; variação esperada de 165 a 172 cm.',
    B: 'Alvo de 175 cm; variação esperada de 166,5 a 183,5 cm (+/- 8,5 cm).',
    C: 'Alvo de 162 cm; variação esperada de 157 a 167 cm.',
    D: 'Alvo de 182 cm; variação esperada de 178 a 186 cm.',
    ans: 'B',
    comment: 'Pela fórmula de Tanner: Para MENINOS: [Estatura do Pai + (Estatura da Mãe + 13)] / 2 = [175 + (162 + 13)] / 2 = [175 + 175] / 2 = 350 / 2 = 175 cm. A faixa de canal genético esperada admite uma variação de +/- 5 cm (ou +/- 8,5 cm, correspondente ao intervalo de confiança de aproximadamente 2 DP). Assim, para margem de +/- 8,5 cm, a faixa vai de 166,5 cm a 183,5 cm.',
    expA: 'Incorreta. O cálculo de 168,5 cm seria a média aritmética simples sem a correção de +13 cm para o sexo masculino.',
    expB: 'Correta. Para meninos soma-se 13 cm à altura materna: (175 + 162 + 13) / 2 = 175 cm (+/- 8,5 cm).',
    expC: 'Incorreta. Este valor desconsidera a altura paterna e o bônus masculino de 13 cm.',
    expD: 'Incorreta. Superestima o cálculo parental.',
  });

  q({
    id: 'ped-cresc-019',
    subtopic: 'Estatura-Alvo Parental',
    inst: 'UNICAMP',
    year: 2024,
    statement: 'Menina de 7 anos é trazida para consulta. Seu pai mede 180 cm e sua mãe mede 165 cm. Qual é a estatura-alvo parental prevista para essa menina pelo método de Tanner?',
    A: '172,5 cm (+/- 8,5 cm).',
    B: '166 cm (+/- 8,5 cm).',
    C: '159,5 cm (+/- 8,5 cm).',
    D: '179 cm (+/- 8,5 cm).',
    ans: 'B',
    comment: 'Para MENINAS, a fórmula de Tanner subtrai 13 cm da altura paterna (ou subtrai 13 cm da soma das alturas): Alvo Menina = [(Estatura do Pai - 13) + Estatura da Mãe] / 2 = [(180 - 13) + 165] / 2 = [167 + 165] / 2 = 332 / 2 = 166 cm. Margem esperada: 166 +/- 8,5 cm (de 157,5 cm a 174,5 cm).',
    expA: 'Incorreta. 172,5 cm é a média aritmética simples entre os pais [(180 + 165) / 2], sem o ajuste biológico de sexo.',
    expB: 'Correta. Alvo Menina = [(180 - 13) + 165] / 2 = 166 cm (+/- 8,5 cm).',
    expC: 'Incorreta. Subtrai duas vezes o fator de correção.',
    expD: 'Incorreta. Corresponderia ao cálculo para meninos [(180 + 165 + 13) / 2 = 179 cm].',
  });

  q({
    id: 'ped-cresc-020',
    subtopic: 'Estatura-Alvo Parental',
    inst: 'FMUSP',
    year: 2024,
    statement: 'Por que o cálculo da estatura-alvo parental utiliza o valor constante de 13 cm na fórmula matemática entre os sexos masculino e feminino?',
    A: 'Porque 13 cm é a diferença média de comprimento observada ao nascimento entre recém-nascidos do sexo masculino e feminino.',
    B: 'Porque 13 cm representa a diferença média histórica de estatura final adulta entre homens e mulheres na população mundial, decorrente do tempo adicional de crescimento pré-puberal e da maior intensidade do estirão masculino.',
    C: 'Porque 13 cm é o ganho estatural fixo decorrente da ação da progesterona na puberdade feminina.',
    D: 'Porque 13 cm é a margem de erro permitida pelo estadiômetro de Harpenden.',
    ans: 'B',
    comment: 'A constante biológica de 13 cm (adicionada à mãe no cálculo do menino ou subtraída do pai no cálculo da menina) reflete a diferença média observada nas curvas populacionais mundiais entre a estatura adulta de homens e mulheres. Essa diferença decorre de dois fatores principais: 1) os meninos entram em puberdade cerca de 1,5 a 2 anos mais tarde do que as meninas, crescendo cerca de 8 a 10 cm a mais no período pré-puberal; 2) o estirão puberal masculino é mais vigoroso, gerando cerca de 3 a 5 cm a mais de ganho estatural do que o feminino.',
    expA: 'Incorreta. Ao nascimento a diferença entre meninos e meninas é de menos de 1 cm em média (meninos ~50 cm, meninas ~49,5 cm).',
    expB: 'Correta. 13 cm é a diferença média populacional adulta entre homens e mulheres decorrente do atraso fisiológico de 2 anos na puberdade e do maior pico de velocidade masculino.',
    expC: 'Incorreta. A progesterona não tem esse efeito de ganho linear de 13 cm.',
    expD: 'Incorreta. O estadiômetro de Harpenden tem precisão milimétrica (< 0,1 cm), não erro de 13 cm.',
  });

  q({
    id: 'ped-cresc-021',
    subtopic: 'Estatura-Alvo Parental',
    inst: 'UFRJ',
    year: 2024,
    statement: 'Menino de 8 anos apresenta estatura no percentil 3 da curva da OMS. O pai mede 190 cm e a mãe mede 175 cm. Sua velocidade de crescimento nos últimos 12 meses foi de 3,8 cm/ano. O cálculo de sua estatura-alvo é de 189 cm (percentil 90 da curva adulta). Como deve ser interpretado esse caso clínico?',
    A: 'Criança normal, pois o percentil 3 ainda está dentro da faixa de normalidade estatística da população geral.',
    B: 'Criança com desaceleração patológica do crescimento e nítida discordância genética, crescendo muito abaixo do seu canal genético parental esperado; investigação obrigatória.',
    C: 'Baixa estatura familiar típica com excelente prognóstico estatural.',
    D: 'Hipercrescimento proporcional que se resolverá espontaneamente.',
    ans: 'B',
    comment: 'Este é o exemplo clássico de "falsa normalidade estatística": embora a estatura esteja no percentil 3, o canal genético da criança situa-se no percentil 90 (alvo de 189 cm). O desvio da criança em relação ao seu alvo genético ultrapassa 2 desvios-padrão para baixo, associado a velocidade de crescimento francamente patológica (3,8 cm/ano no escolar, quando o normal é ≥ 5 cm/ano). Trata-se de falha de crescimento com discordância genética gravíssima, exigindo investigação completa.',
    expA: 'Incorreta. Estar no p3 com pais no p90 e velocidade de 3,8 cm/ano é manifestamente patológico.',
    expB: 'Correta. A discordância com o canal familiar (> 2 DP abaixo do alvo) e velocidade de 3,8 cm/ano (< 5 cm/ano) impõem investigação diagnóstica imediata.',
    expC: 'Incorreta. Na baixa estatura familiar os pais são baixos; aqui os pais são muito altos.',
    expD: 'Incorreta. A criança apresenta déficit estatural em relação ao alvo e baixa velocidade, não hipercrescimento.',
  });

  q({
    id: 'ped-cresc-022',
    subtopic: 'Estatura-Alvo Parental',
    inst: 'UERJ',
    year: 2024,
    statement: 'Menina de 5 anos mede 102 cm (percentil 10). Pai mede 164 cm e mãe mede 151 cm. Calculando o alvo genético: [(164 - 13) + 151] / 2 = 151 cm (percentil 10). A velocidade de crescimento é de 6 cm/ano e a idade óssea é igual à idade cronológica. Qual é o diagnóstico e a conduta recomendada?',
    A: 'Baixa Estatura Familiar (BEF); tranquilizar os pais, manter acompanhamento de rotina da velocidade de crescimento.',
    B: 'Deficiência grave de GH; indicar reposição de somatropina recombinante.',
    C: 'Síndrome de Turner; solicitar cariótipo de urgência e laparotomia exploradora.',
    D: 'Hipotireoidismo congênito tardio; iniciar levotiroxina imediatamente.',
    ans: 'A',
    comment: 'A paciente apresenta: 1) Estatura compatível com o canal parental (percentil 10 da criança coincide com o percentil 10 da estatura-alvo); 2) Velocidade de crescimento estritamente normal (6 cm/ano); 3) Idade óssea igual à idade cronológica (IO = IC); 4) Pais geneticamente baixos. Este conjunto fecha com precisão o diagnóstico de Baixa Estatura Familiar (variante normal do crescimento), não havendo qualquer necessidade de propedêutica invasiva ou medicação.',
    expA: 'Correta. A convergência entre o canal da criança e o alvo parental associada a velocidade normal e IO = IC define Baixa Estatura Familiar.',
    expB: 'Incorreta. A velocidade de 6 cm/ano e canal familiar estável afastam deficiência de GH.',
    expC: 'Incorreta. Não há desaceleração, estigmas de Turner ou discordância genética.',
    expD: 'Incorreta. Não há bócio, mixedema, constipação ou atraso de idade óssea.',
  });

  q({
    id: 'ped-cresc-023',
    subtopic: 'Estatura-Alvo Parental',
    inst: 'UNIFESP',
    year: 2024,
    statement: 'Em qual das seguintes situações o cálculo da estatura-alvo parental pelo método clássico de Tanner perde sua precisão e confiabilidade clínica?',
    A: 'Quando ambos os pais têm estaturas semelhantes entre os percentis 25 e 50.',
    B: 'Quando há grande discrepância estatural entre os pais (ex: pai no percentil 97 e mãe no percentil 3) ou quando um dos genitores teve crescimento comprometido por patologia crônica na infância.',
    C: 'Quando a criança nasce de parto cesárea eletiva.',
    D: 'Quando a criança é do sexo feminino.',
    ans: 'B',
    comment: 'A fórmula de Tanner baseia-se na premissa de herança poligênica de pais saudáveis com estaturas relativamente homogêneas. O método perde confiabilidade quando: 1) Há grande disparidade estatural entre os pais (ex: pai muito alto e mãe muito baixa, o que gera uma "média" artificial que pode não representar a segregação alélica); 2) Um dos genitores teve sua estatura adulta reduzida por doença crônica na infância (desnutrição, doença celíaca, cardiopatia congênita, radioterapia) ou por displasia óssea.',
    expA: 'Incorreta. Pais com alturas homogêneas aumentam a precisão do cálculo.',
    expB: 'Correta. Disparidade marcante entre os pais ou história de doença crônica comprometedora na infância de um dos pais invalida o potencial genético real.',
    expC: 'Incorreta. A via de parto não interfere no potencial genético parental.',
    expD: 'Incorreta. A fórmula é perfeitamente calibrada para ambos os sexos através da constante de 13 cm.',
  });

  q({
    id: 'ped-cresc-024',
    subtopic: 'Estatura-Alvo Parental',
    inst: 'SCMSP',
    year: 2024,
    statement: 'Menino de 10 anos tem pai de 172 cm e mãe de 159 cm. Qual é o valor exato da estatura-alvo e os limites inferior e superior do canal genético considerando a faixa habitual de +/- 5 cm?',
    A: 'Alvo: 172 cm; Limites: 167 a 177 cm.',
    B: 'Alvo: 165,5 cm; Limites: 160,5 a 170,5 cm.',
    C: 'Alvo: 178,5 cm; Limites: 173,5 a 183,5 cm.',
    D: 'Alvo: 160 cm; Limites: 155 a 165 cm.',
    ans: 'A',
    comment: 'Cálculo para menino: Alvo = [Estatura Pai + Estatura Mãe + 13] / 2 = [172 + 159 + 13] / 2 = 344 / 2 = 172 cm. Considerando a margem de variação fisiológica de +/- 5 cm: Limite inferior = 172 - 5 = 167 cm; Limite superior = 172 + 5 = 177 cm.',
    expA: 'Correta. Alvo de 172 cm com canal genético entre 167 e 177 cm.',
    expB: 'Incorreta. Este valor é a média simples sem somar 13 cm.',
    expC: 'Incorreta. Superestima a altura dos pais.',
    expD: 'Incorreta. Subestima o cálculo em mais de 12 cm.',
  });

  q({
    id: 'ped-cresc-025',
    subtopic: 'Estatura-Alvo Parental',
    inst: 'UFMG',
    year: 2024,
    statement: 'Ao plotar a estatura-alvo parental calculada em um gráfico de crescimento da OMS para acompanhamento longitudinal, em qual idade do gráfico a faixa do canal genético deve ser assinalada para representar o prognóstico de altura adulta?',
    A: 'Aos 2 anos de idade.',
    B: 'Aos 5 anos de idade.',
    C: 'Aos 19 ou 20 anos de idade (final da curva de crescimento estatural).',
    D: 'No ponto exato da idade cronológica atual da criança.',
    ans: 'C',
    comment: 'A estatura-alvo parental representa a predição da estatura final ADULTA esperada para a criança. Portanto, nos gráficos de crescimento da OMS/CDC que vão até os 19-20 anos, o ponto da estatura-alvo com sua respectiva faixa (+/- 5 a 8,5 cm) deve ser plotado no extremo direito da curva, aos 19-20 anos. A partir desse ponto, o examinador projeta visualmente se o canal atual de percentil em que a criança cresce caminha em direção a essa meta adulta.',
    expA: 'Incorreta. Aos 2 anos a criança ainda está em plena fase de infância inicial.',
    expB: 'Incorreta. Aos 5 anos a criança ainda não atingiu a puberdade nem o estirão final.',
    expC: 'Correta. A estatura-alvo prevê a altura adulta final e deve ser plotada aos 19-20 anos de idade.',
    expD: 'Incorreta. Plotar a altura adulta na idade atual faria parecer que a criança tem gigantismo grotesco.',
  });
}
