import { q } from './helper_crescimento.js';

export function loadSec4() {
  q({
    id: 'ped-cresc-026',
    subtopic: 'Idade Óssea e Atlas de Greulich & Pyle',
    inst: 'USP-SP',
    year: 2024,
    statement: 'Para a avaliação da maturação esquelética e determinação da idade óssea pelo método clássico de Greulich & Pyle, qual é a incidência radiológica internacionalmente padronizada e qual segmento anatômico deve ser radiografado?',
    A: 'Radiografia de bacia e joelhos bilateral em incidência anteroposterior (AP).',
    B: 'Radiografia de crânio e coluna cervical em perfil estrito.',
    C: 'Radiografia simples de mão e punho esquerdos em incidência póstero-anterior (PA).',
    D: 'Ressonância magnética tridimensional do fêmur direito.',
    ans: 'C',
    comment: 'O método de referência mundial para avaliação da idade óssea é o Atlas de Greulich & Pyle (1959), realizado através de uma radiografia simples da mão e punho esquerdos na incidência póstero-anterior (PA). A escolha do lado esquerdo foi padronizada para evitar discrepâncias causadas por microtraumas e hipertrofia osteogênica pelo uso preferencial da mão direita (mão dominante na maioria da população), além de oferecer múltiplos centros epifisários e carpais com mínima exposição à radiação ionizante.',
    expA: 'Incorreta. Radiografias de bacia e joelho só têm utilidade em casos específicos de lactentes muito jovens ou displasias esqueléticas.',
    expB: 'Incorreta. Crânio e coluna não são utilizados para estimativa de idade óssea habitual.',
    expC: 'Correta. A radiografia de mão e punho esquerdos em PA é o padrão-ouro universal para determinação da idade óssea.',
    expD: 'Incorreta. Método de altíssimo custo, desnecessário e não padronizado para idade óssea.',
  });

  q({
    id: 'ped-cresc-027',
    subtopic: 'Idade Óssea e Atlas de Greulich & Pyle',
    inst: 'UNICAMP',
    year: 2024,
    statement: 'Menino de 11 anos tem estatura no percentil 3. Sua velocidade de crescimento nos últimos 12 meses foi de 5,2 cm/ano. Ao exame físico: G1P1, sem dismorfismos. A radiografia de punho esquerdo revela idade óssea compatível com 8 anos e 6 meses (atraso de 2,5 anos em relação à idade cronológica). A idade estatural da criança também é de aproximadamente 8 anos e meio. Qual é a principal implicação prognóstica desse atraso da idade óssea?',
    A: 'Prognóstico desfavorável, indicando que a criança parou de crescer e terá estatura adulta extremamente baixa.',
    B: 'Prognóstico favorável quanto à estatura final, pois a idade óssea atrasada indica que as cartilagens epifisárias permanecem abertas por mais tempo, permitindo um período prolongado de crescimento e estirão tardio.',
    C: 'Indicação imediata de fusão cirúrgica de epífises para impedir gigantismo.',
    D: 'O atraso da idade óssea não guarda qualquer relação com a estatura adulta.',
    ans: 'B',
    comment: 'A idade óssea (IO) reflete a idade biológica do esqueleto e o tempo restante de crescimento antes da fusão epifisária definitiva. Quando a IO está atrasada em relação à idade cronológica (IO < IC) e acompanha a idade estatural (IO ≈ IE) com velocidade de crescimento normal, como no Retardo Constitucional do Crescimento e da Puberdade (RCCP), o prognóstico estatural é excelente: a criança entrará em puberdade mais tarde, suas cartilagens fecharão mais tarde e ela terá mais anos para crescer, alcançando uma estatura adulta normal dentro do seu canal genético.',
    expA: 'Incorreta. O atraso epifisário preserva o potencial de crescimento futuro, não indicando parada.',
    expB: 'Correta. Epífises abertas por mais tempo significam maior tempo de crescimento linear e excelente prognóstico estatural final.',
    expC: 'Incorreta. Epifisiodese cirúrgica é utilizada para frear hipercrescimento, e não em baixa estatura.',
    expD: 'Incorreta. A idade óssea é o parâmetro primordial para a predição da estatura adulta (tabelas de Bayley-Pinneau).',
  });

  q({
    id: 'ped-cresc-028',
    subtopic: 'Idade Óssea e Atlas de Greulich & Pyle',
    inst: 'UFRJ',
    year: 2024,
    statement: 'Menina de 7 anos e 2 meses apresenta telarca bilateral há 6 meses, associada a pubarca e aceleração da velocidade de crescimento para 10 cm/ano. A radiografia de punho esquerdo mostra idade óssea de 10 anos e 6 meses (avanço de mais de 3 anos). Qual é a principal consequência clínica e fisiopatológica desse avanço acentuado da idade óssea?',
    A: 'A criança se tornará um adulto gigante, com altura muito superior ao canal parental.',
    B: 'Fechamento prematuro das cartilagens de crescimento induzido pelos estrógenos, resultando em término precoce do crescimento e baixa estatura final na vida adulta.',
    C: 'Desenvolvimento imediato de osteoporose pós-menopáusica na infância.',
    D: 'Ausência total de impacto sobre o crescimento esquelético.',
    ans: 'B',
    comment: 'Os esteroides sexuais (especialmente o estradiol, que nos ossos é o principal mediador da fusão epifisária em ambos os sexos) estimulam fortemente o estirão no curto prazo, mas aceleram a senescência e ossificação das cartilagens de conjugação epifisárias. Na puberdade precoce, a idade óssea avança desproporcionalmente (IO >> IC). Isso causa uma falsa impressão inicial de que a criança é alta para a idade cronológica, mas as epífises se fundem precocemente, cessando o crescimento cedo e acarretando baixa estatura final grave.',
    expA: 'Incorreta. O avanço epifisário precoce encurta a janela temporal de crescimento, impedindo a alta estatura adulta.',
    expB: 'Correta. O estrogênio fecha precocemente as epífises, levando à perda irreparável de potencial estatural e baixa estatura na idade adulta.',
    expC: 'Incorreta. Não ocorre osteoporose; pelo contrário, há mineralização e fechamento ósseo acelerado.',
    expD: 'Incorreta. O impacto sobre a estatura adulta é a principal complicação da puberdade precoce não tratada.',
  });

  q({
    id: 'ped-cresc-029',
    subtopic: 'Idade Óssea e Atlas de Greulich & Pyle',
    inst: 'UNIFESP',
    year: 2024,
    statement: 'Qual das seguintes alterações clínicas cursa tipicamente com idade óssea atrasada (IO < IC) de forma muito marcante (frequentemente com atraso superior a 3 ou 4 anos)?',
    A: 'Puberdade precoce central verdadeira.',
    B: 'Hiperplasia adrenal congênita não tratada.',
    C: 'Hipotireoidismo primário congênito ou adquirido grave (Tireoidite de Hashimoto descompensada).',
    D: 'Obesidade exógena simples na infância.',
    ans: 'C',
    comment: 'Os hormônios tireoidianos (T3 e T4) são estritamente necessários para a maturação, recrutamento e ossificação condrocitária nas epífises. No hipotireoidismo primário grave não tratado, a maturação óssea é quase paralisada, resultando em um dos atrasos de idade óssea mais acentuados da pediatria (IO muito menor que a IC, com disgenesia epifisária típica). Ao contrário, puberdade precoce, hiperplasia adrenal e obesidade exógena simples cursam com idade óssea avançada.',
    expA: 'Incorreta. Puberdade precoce avança a idade óssea (IO > IC).',
    expB: 'Incorreta. Andrógenos adrenais em excesso avançam a idade óssea.',
    expC: 'Correta. O hipotireoidismo é uma das causas clássicas de atraso profundo da idade óssea (IO << IC).',
    expD: 'Incorreta. Crianças com obesidade exógena costumam apresentar leve avanço da idade óssea (IO discretamente > IC) pela aromatização periférica.',
  });

  q({
    id: 'ped-cresc-030',
    subtopic: 'Idade Óssea e Atlas de Greulich & Pyle',
    inst: 'FMUSP',
    year: 2024,
    statement: 'Na radiografia de mão e punho esquerdos de um menino de 13 anos, a identificação da presença do osso sesamoide do polegar (no tendão do músculo adutor do polegar na articulação metacarpofalângica) tem qual significado no acompanhamento da puberdade?',
    A: 'Indica que as epífises já se fecharam completamente e não há mais crescimento residual.',
    B: 'Marca radiológica que sinaliza que o paciente atingiu ou está muito próximo do seu pico de velocidade de crescimento puberal (estirão).',
    C: 'Sinal patognomônico de raquitismo resistente à vitamina D.',
    D: 'Indica que a idade óssea é inferior a 8 anos.',
    ans: 'B',
    comment: 'O aparecimento do centro de ossificação do osso sesamoide do polegar na articulação metacarpofalângica do 1º quirodáctilo ocorre habitualmente por volta dos 11 anos nas meninas e 13 anos nos meninos (idade óssea). Esse marco radiológico tem grande utilidade clínica, pois se correlaciona intimamente com a proximidade imediata ou vigência do pico de velocidade de crescimento do estirão puberal.',
    expA: 'Incorreta. O sesamoide surge no início/pico do estirão; o fechamento completo ocorre anos depois.',
    expB: 'Correta. A ossificação do sesamoide do polegar é um excelente marcador biológico de aproximação ou início do pico do estirão puberal.',
    expC: 'Incorreta. O sesamoide é uma estrutura anatômica fisiológica normal, não sinal de raquitismo.',
    expD: 'Incorreta. O sesamoide surge tipicamente com idade óssea de 11 anos em meninas e 13 anos em meninos.',
  });

  q({
    id: 'ped-cresc-031',
    subtopic: 'Idade Óssea e Atlas de Greulich & Pyle',
    inst: 'UERJ',
    year: 2024,
    statement: 'Em um laudo radiológico de idade óssea pelo método de Greulich & Pyle, qual intervalo de discrepância entre a Idade Óssea (IO) e a Idade Cronológica (IC) ainda é aceito como variação biológica fisiológica normal?',
    A: 'Até +/- 1 ano (ou 12 meses).',
    B: 'Até +/- 4 anos.',
    C: 'Qualquer diferença, mesmo de 1 mês, é obrigatoriamente patológica.',
    D: 'A idade óssea deve ser sempre 2 anos superior à cronológica em todas as crianças.',
    ans: 'A',
    comment: 'A maturação esquelética populacional tem distribuição normal. Considera-se compatível com a normalidade fisiológica (IO = IC) uma variação de até +/- 1 ano (12 meses) de diferença entre a idade óssea e a idade cronológica (em crianças acima de 2-3 anos; em menores de 1 ano, variações acima de 6 meses já merecem atenção). Diferenças superiores a 1,5 a 2 anos definem formalmente atraso ou avanço patológico da idade óssea.',
    expA: 'Correta. Uma variação de até +/- 1 ano entre a idade óssea e a cronológica é considerada fisiológica e esperada.',
    expB: 'Incorreta. 4 anos é uma discrepância gravíssima.',
    expC: 'Incorreta. Pequenas variações de alguns meses são inerentes à biologia humana e ao método do atlas.',
    expD: 'Incorreta. Não existe exigência de avanço sistemático.',
  });

  q({
    id: 'ped-cresc-032',
    subtopic: 'Idade Óssea e Atlas de Greulich & Pyle',
    inst: 'SCMSP',
    year: 2024,
    statement: 'Menino de 9 anos é avaliado por baixa estatura. Sua idade cronológica é 9 anos, sua idade estatural é 7 anos e sua idade óssea é de 9 anos e 2 meses (IO = IC). A velocidade de crescimento é de 5,5 cm/ano. O pai mede 163 cm e a mãe 150 cm. O diagnóstico mais provável e a justificativa pela idade óssea são:',
    A: 'Retardo Constitucional do Crescimento, pois a idade óssea está atrasada.',
    B: 'Baixa Estatura Familiar, pois a idade óssea é compatível com a idade cronológica (IO = IC), com velocidade de crescimento normal e pais baixos.',
    C: 'Deficiência de hormônio do crescimento (DGH), pois a idade óssea está avançada.',
    D: 'Disgenesia gonadal com cariótipo 45,X.',
    ans: 'B',
    comment: 'A diferenciação clássica entre as duas grandes variantes normais do crescimento reside na Idade Óssea: 1) Baixa Estatura Familiar (BEF): IO = IC (idade óssea igual à cronológica), velocidade de crescimento normal, pais baixos; 2) Retardo Constitucional do Crescimento e da Puberdade (RCCP): IO < IC (idade óssea atrasada, acompanhando a idade estatural IE), estirão e puberdade atrasados, mas pais com altura normal e história de menarca/estirão tardios. No caso, com IO = 9 anos e 2 meses para IC de 9 anos (IO = IC) e pais baixos, o diagnóstico é de Baixa Estatura Familiar.',
    expA: 'Incorreta. No RCCP a idade óssea é caracteristicamente atrasada (IO < IC), o que não ocorre aqui.',
    expB: 'Correta. IO = IC com velocidade normal e canal compatível com o canal parental fecha o diagnóstico de Baixa Estatura Familiar.',
    expC: 'Incorreta. Na DGH a idade óssea é atrasada e a velocidade de crescimento é muito baixa (< 4 cm/ano).',
    expD: 'Incorreta. Trata-se de um menino fenotipicamente masculino normal, sem relação com síndrome de Turner.',
  });

  q({
    id: 'ped-cresc-033',
    subtopic: 'Idade Óssea e Atlas de Greulich & Pyle',
    inst: 'UFPE',
    year: 2024,
    statement: 'Qual é o método clássico mais utilizado na prática clínica endocrinopediátrica para predizer a estatura final adulta a partir da idade óssea de Greulich & Pyle?',
    A: 'Tabelas e coeficientes de Bayley & Pinneau.',
    B: 'Escala de Glasgow modificada para pediatria.',
    C: 'Critérios de Jones para febre reumática.',
    D: 'Escore de Apgar expandido.',
    ans: 'A',
    comment: 'O método preditivo de estatura adulta mais consolidado na prática clínica pediátrica é o de Bayley & Pinneau (1952), que utiliza tabelas matemáticas com base na estatura atual e na porcentagem da estatura adulta já atingida conforme a idade óssea avaliada pelo atlas de Greulich & Pyle. Outros métodos incluem o de Tanner-Whitehouse (TW3) e o de Roche-Wainer-Thissen (RWT).',
    expA: 'Correta. As tabelas de Bayley-Pinneau utilizam a idade óssea para projetar a porcentagem de crescimento remanescente e a estatura final adulta.',
    expB: 'Incorreta. Glasgow avalia nível de consciência neurológico.',
    expC: 'Incorreta. Critérios de Jones diagnosticam febre reumática.',
    expD: 'Incorreta. Escore de Apgar avalia adaptação neonatal imediata nos primeiros minutos de vida.',
  });
}
