import { q } from './helper_crescimento.js';

export function loadSec5() {
  q({
    id: 'ped-cresc-034',
    subtopic: 'Variantes Normais do Crescimento',
    inst: 'USP-SP',
    year: 2024,
    statement: 'Garoto de 14 anos é levado ao consultório porque é o menor da turma do 9º ano e ainda não apresenta sinais de puberdade (estágio G1P1, testículos com 2 mL bilateralmente). Sua estatura encontra-se logo abaixo do percentil 3. A velocidade de crescimento nos últimos 12 meses foi de 5,1 cm/ano. O pai relata que era muito pequeno na escola e deu o estirão aos 17 anos no serviço militar; a mãe teve menarca aos 15 anos e ambos têm estaturas normais hoje (pai 176 cm e mãe 163 cm, alvo de 176 cm). A radiografia de punho esquerdo revela idade óssea de 11 anos e 6 meses (atrasada em relação à cronológica de 14 anos, mas perfeitamente compatível com a idade estatural). Qual é o diagnóstico mais provável?',
    A: 'Síndrome de Klinefelter (47,XXY).',
    B: 'Retardo Constitucional do Crescimento e da Puberdade (RCCP).',
    C: 'Baixa Estatura Familiar (BEF).',
    D: 'Craniofaringioma com pan-hipopituitarismo agudo.',
    ans: 'B',
    comment: 'O quadro reúne todos os critérios patognomônicos do Retardo Constitucional do Crescimento e da Puberdade (RCCP): 1) Menino na adolescência inicial com atraso puberal fisiológico; 2) Velocidade de crescimento mantida na faixa normal para o período pré-puberal (5,1 cm/ano); 3) Idade óssea atrasada (IO de 11,5 anos para IC de 14 anos) acompanhando a idade estatural (IO ≈ IE); 4) Pais com altura normal na vida adulta; 5) História familiar clássica de maturação tardia (pai com estirão tardio e mãe com menarca tardia); 6) Prognóstico de estatura final adulta plenamente normal.',
    expA: 'Incorreta. A síndrome de Klinefelter cursa com alta estatura desproporcionada com membros longos e ginecomastia.',
    expB: 'Correta. RCCP é a variante normal mais frequente no sexo masculino, caracterizada por atraso da IO, história familiar de estirão tardio e estatura adulta final normal.',
    expC: 'Incorreta. Na Baixa Estatura Familiar, a idade óssea é igual à cronológica (IO = IC) e os pais são baixos.',
    expD: 'Incorreta. Craniofaringioma cursa com parada do crescimento (velocidade < 3 cm/ano), cefaleia, alterações de campo visual e diabetes insipidus.',
  });

  q({
    id: 'ped-cresc-035',
    subtopic: 'Variantes Normais do Crescimento',
    inst: 'UNICAMP',
    year: 2024,
    statement: 'Qual é o prognóstico de estatura final adulta de uma criança com diagnóstico confirmado de Retardo Constitucional do Crescimento e da Puberdade (RCCP)?',
    A: 'Estatura final severamente comprometida, com nanismo na vida adulta.',
    B: 'Estatura final normal, convergindo para o canal genético parental após um estirão puberal tardio.',
    C: 'Gigantismo desproporcionado com necessidade de bloqueio puberal precoce.',
    D: 'Parada definitiva do crescimento aos 15 anos sem fechamento epifisário.',
    ans: 'B',
    comment: 'No RCCP, o "relógio biológico" da criança funciona em ritmo mais lento. Como a idade óssea está atrasada, as cartilagens epifisárias permanecem abertas por mais tempo. A criança cresce por um período de tempo mais prolongado e o estirão puberal, embora atrase em relação aos pares de mesma idade cronológica, ocorre com pleno vigor, permitindo que o paciente atinja uma estatura final adulta normal, perfeitamente compatível com o canal parental.',
    expA: 'Incorreta. O RCCP não causa baixa estatura na vida adulta.',
    expB: 'Correta. A estatura adulta final no RCCP é normal e congruente com a estatura-alvo familiar.',
    expC: 'Incorreta. A criança não se torna gigante; ela atinge a altura normal prevista para sua família.',
    expD: 'Incorreta. A criança continua crescendo além dos 16-18 anos até o fechamento epifisário tardio.',
  });

  q({
    id: 'ped-cresc-036',
    subtopic: 'Variantes Normais do Crescimento',
    inst: 'UFRJ',
    year: 2024,
    statement: 'Menino de 14 anos e 8 meses apresenta diagnóstico firmado de Retardo Constitucional do Crescimento e da Puberdade. Encontra-se em G1P1, com idade óssea de 12 anos. O paciente vem sofrendo intenso isolamento social e recusa-se a ir à escola devido a bullying constante por ser tratado como uma criança de 10 anos. Diante do sofrimento psíquico evidente, qual intervenção terapêutica transitória pode ser indicada?',
    A: 'Hormônio do crescimento recombinante em altíssima dose por 5 anos.',
    B: 'Tratamento de estímulo ("priming") com baixas doses de testosterona de depósito intramuscular por curto período (3 a 6 meses).',
    C: 'Orquidectomia bilateral para elevar os níveis de LH e FSH.',
    D: 'Inibidor de aromatase associado a análogo de GnRH em dose contínua.',
    ans: 'B',
    comment: 'No RCCP, a conduta padrão é expectante com apoio psicológico. Contudo, em meninos com idade cronológica ≥ 14 anos com atraso puberal persistente e sofrimento psicossocial grave documentado, pode-se realizar o "priming" androgênico transitório: uso de baixas doses de testosterona de depósito (ex: cipionato ou enantato de testosterona, 50 a 100 mg IM a cada 4 semanas por 3 a 6 meses). Essa conduta induz caracteres sexuais secundários iniciais, acelera a velocidade de crescimento e deflagra o eixo hipotálamo-hipófise-gonadal sem causar avanço desproporcional da idade óssea nem comprometer a estatura final.',
    expA: 'Incorreta. GH não é indicado para RCCP, pois a secreção de GH é normal para a idade biológica.',
    expB: 'Correta. O priming com baixas doses de testosterona por 3 a 6 meses é uma conduta bem estabelecida e segura para alívio psicossocial no RCCP.',
    expC: 'Incorreta. Conduta absurda e mutiladora.',
    expD: 'Incorreta. O bloqueio com análogo de GnRH atrasaria ainda mais a puberdade.',
  });

  q({
    id: 'ped-cresc-037',
    subtopic: 'Variantes Normais do Crescimento',
    inst: 'UNIFESP',
    year: 2024,
    statement: 'Menina de 8 anos tem estatura no percentil 3, sem queixas. O pai mede 162 cm (percentil 3) e a mãe mede 150 cm (percentil 3). A estatura-alvo da paciente é de 150 cm (+/- 5 cm). Sua velocidade de crescimento no último ano foi de 5,6 cm/ano. O exame físico é totalmente normal. A radiografia de punho esquerdo evidencia idade óssea de 8 anos (IO = IC). Qual é a principal característica que diferencia este quadro de Baixa Estatura Familiar (BEF) em relação ao Retardo Constitucional (RCCP)?',
    A: 'Na BEF a idade óssea é atrasada em relação à cronológica, enquanto no RCCP ela é igual.',
    B: 'Na BEF a idade óssea é igual à idade cronológica (IO = IC) e a estatura adulta prevista é baixa (compatível com os pais), enquanto no RCCP a idade óssea é atrasada (IO < IC) e a estatura adulta prevista é normal.',
    C: 'Na BEF a velocidade de crescimento é nula, enquanto no RCCP é de 15 cm/ano.',
    D: 'A BEF ocorre exclusivamente em indivíduos do sexo masculino.',
    ans: 'B',
    comment: 'A comparação clássica entre as duas variantes normais é fundamental: 1) Baixa Estatura Familiar: IO = IC, pais baixos, canal genético baixo, puberdade no tempo normal, estatura final baixa (porém congruente com os pais); 2) Retardo Constitucional (RCCP): IO < IC (atrasada, acompanhando a idade estatural), pais com altura normal, história de maturação familiar tardia, puberdade tardia, estatura final normal. Em ambos a velocidade de crescimento é normal.',
    expA: 'Incorreta. A afirmação inverte os achados de idade óssea.',
    expB: 'Correta. BEF cursa com IO = IC e previsão de altura adulta baixa; RCCP cursa com IO < IC e previsão de altura adulta normal.',
    expC: 'Incorreta. Em ambas as variantes normais a velocidade de crescimento é estritamente normal (5 a 7 cm/ano no escolar).',
    expD: 'Incorreta. A BEF acomete igualmente ambos os sexos.',
  });

  q({
    id: 'ped-cresc-038',
    subtopic: 'Variantes Normais do Crescimento',
    inst: 'FMUSP',
    year: 2024,
    statement: 'Qual é a velocidade de crescimento esperada em uma criança portadora de variante normal do crescimento, seja ela Baixa Estatura Familiar (BEF) ou Retardo Constitucional do Crescimento (RCCP)?',
    A: 'Velocidade de crescimento diminuída (< 4 cm/ano), caracterizando falha crônica.',
    B: 'Velocidade de crescimento estritamente normal para a idade cronológica ou idade biológica (≥ 5 cm/ano no período escolar pré-puberal).',
    C: 'Velocidade de crescimento muito acelerada (> 12 cm/ano) desde o período de lactente.',
    D: 'Velocidade flutuante e caótica com semanas de crescimento de 2 cm e semanas de perda de estatura.',
    ans: 'B',
    comment: 'Por definição, uma "variante normal do crescimento" (BEF ou RCCP) NÃO cursa com velocidade de crescimento patológica. Uma velocidade de crescimento inferior a 5 cm/ano no escolar pré-puberal afasta variante normal e impõe investigação para causas patológicas de baixa estatura (endocrinopatias, doenças sistêmicas, desnutrição ou síndromes genéticas).',
    expA: 'Incorreta. Velocidade < 4 cm/ano é patológica e exclui variantes normais.',
    expB: 'Correta. A manutenção de velocidade de crescimento fisiologicamente normal (5 a 7 cm/ano) é o pilar que define as variantes normais.',
    expC: 'Incorreta. Velocidades > 12 cm/ano fora do estirão puberal sugerem patologia de hipercrescimento.',
    expD: 'Incorreta. O crescimento linear humano é estável e progressivo.',
  });

  q({
    id: 'ped-cresc-039',
    subtopic: 'Variantes Normais do Crescimento',
    inst: 'UERJ',
    year: 2024,
    statement: 'Em um adolescente de 14 anos com Retardo Constitucional do Crescimento e da Puberdade (RCCP), qual é o principal diagnóstico diferencial patológico que deve ser considerado quando o atraso puberal persiste além dos 15-16 anos de idade?',
    A: 'Deficiência congênita ou adquirida de hormônio do crescimento (DGH) e Hipogonadismo Hipogonadotrófico congênito (como na Síndrome de Kallmann).',
    B: 'Doença de Kawasaki atípica.',
    C: 'Estenose aórtica congênita crítica.',
    D: 'Tetralogia de Fallot compensada.',
    ans: 'A',
    comment: 'O grande desafio clínico na adolescência é diferenciar o RCCP (atraso transitório funcional do eixo hipotálamo-hipófise-gonadal) do Hipogonadismo Hipogonadotrófico permanente (congênito, como na síndrome de Kallmann com anosmia, ou secundário a tumores do SNC como craniofaringioma) e da deficiência de GH. Se o paciente não iniciar puberdade espontânea até os 15-16 anos, impõe-se investigação detalhada (RM de crânio, dosagens de LH, FSH, testosterona, IGF-1 e testes de estímulo).',
    expA: 'Correta. O hipogonadismo hipogonadotrófico e a deficiência de GH são os principais diagnósticos diferenciais do atraso puberal persistente.',
    expB: 'Incorreta. Kawasaki é vasculite febril aguda da primeira infância.',
    expC: 'Incorreta. Estenose aórtica é cardiopatia anatômica congênita.',
    expD: 'Incorreta. Fallot é cardiopatia cianogênica.',
  });

  q({
    id: 'ped-cresc-040',
    subtopic: 'Variantes Normais do Crescimento',
    inst: 'SCMSP',
    year: 2024,
    statement: 'Menina de 6 anos tem estatura no percentil 3, sem qualquer dismorfismo. Seus pais são primos de primeiro grau; o pai mede 158 cm e a mãe 147 cm. A criança nasceu a termo com peso e comprimento adequados e sempre cresceu paralelamente ao percentil 3, com ganho de 5,5 cm no último ano. A idade óssea é de 6 anos. A mãe solicita prescrição de hormônio do crescimento (rhGH) para que a filha fique mais alta que a média da família. Qual é a conduta ética e tecnicamente correta?',
    A: 'Prescrever rhGH imediatamente, pois qualquer criança no percentil 3 tem indicação aprovada em bula.',
    B: 'Esclarecer que a criança apresenta Baixa Estatura Familiar (variante normal do crescimento), não havendo deficiência hormonal nem indicação médica ou aprovação legal para uso de rhGH; manter seguimento pediátrico de rotina.',
    C: 'Indicar tireoidectomia profilática para induzir estirão compensatório.',
    D: 'Encaminhar para cirurgia de alongamento ortopédico dos quatro membros.',
    ans: 'B',
    comment: 'A Baixa Estatura Familiar não é uma doença, mas sim a expressão biológica saudável de um conjunto poligênico herdado de pais geneticamente baixos. A criança tem velocidade normal, idade óssea normal e exame físico normal. O uso de hormônio de crescimento não é indicado nem aprovado para baixa estatura familiar com velocidade normal, trazendo riscos de efeitos adversos metabólicos e custo financeiro sem benefício ético comprovado.',
    expA: 'Incorreta. Baixa estatura familiar não é indicação formal de rhGH.',
    expB: 'Correta. Orientar a família sobre a variante normal e a ausência de indicação para rhGH é a conduta médica ética e correta.',
    expC: 'Incorreta. A tireoidectomia causaria hipotireoidismo grave e parada do crescimento.',
    expD: 'Incorreta. Cirurgias invasivas de alongamento não têm indicação em variantes normais.',
  });

  q({
    id: 'ped-cresc-041',
    subtopic: 'Variantes Normais do Crescimento',
    inst: 'UFMG',
    year: 2024,
    statement: 'Qual é o padrão evolutivo típico da curva de crescimento de uma criança com Retardo Constitucional do Crescimento e da Puberdade (RCCP) nos primeiros 3 anos de vida?',
    A: 'Cresce no percentil 97 até os 2 anos e depois para completamente de crescer.',
    B: 'Pode apresentar uma desaceleração fisiológica transitória entre os 12 e 36 meses, fixando-se em um canal inferior (frequentemente p3 a p10), onde passa a crescer com velocidade normal paralela à curva durante toda a fase escolar, até apresentar o atraso do estirão puberal.',
    C: 'Apresenta perda ponderal grave com queda para Escore-Z de peso < -5 DP.',
    D: 'Nasce invariavelmente com nanismo e microcefalia ao parto.',
    ans: 'B',
    comment: 'O padrão bifásico clássico do RCCP inclui: 1) Um período inicial nos primeiros 1 a 3 anos em que o crescimento desacelera suavemente até encontrar seu canal biológico próprio (geralmente próximo ao p3 ou logo abaixo dele); 2) Estabilização na fase escolar, onde a criança cresce com velocidade rigorosamente normal paralela às curvas; 3) Atraso do estirão na adolescência, quando os colegas aceleram e o paciente parece "ficar para trás", seguido de estirão tardio e normalização na vida adulta.',
    expA: 'Incorreta. O RCCP não cursa com percentil 97 inicial e parada súbita.',
    expB: 'Correta. A desaceleração inicial precoce seguida de paralelismo na infância e estirão tardio é a história natural típica do RCCP.',
    expC: 'Incorreta. No RCCP o peso é proporcional à estatura, sem desnutrição grave.',
    expD: 'Incorreta. O comprimento ao nascer é habitualmente normal.',
  });

  q({
    id: 'ped-cresc-042',
    subtopic: 'Variantes Normais do Crescimento',
    inst: 'UFPE',
    year: 2024,
    statement: 'Uma criança pode apresentar a sobreposição de ambas as variantes normais do crescimento (Baixa Estatura Familiar associada a Retardo Constitucional do Crescimento)?',
    A: 'Não, são condições geneticamente incompatíveis e mutuamente excludentes.',
    B: 'Sim, a criança pode herdar o potencial genético baixo de seus pais (BEF) e simultaneamente o padrão familiar de maturação tardia (RCCP); nesses casos, a estatura situa-se abaixo do percentil 3 e a idade óssea é atrasada, atingindo na vida adulta a estatura baixa prevista para sua família.',
    C: 'Sim, e essa associação invariavelmente se transforma em síndrome de Down na adolescência.',
    D: 'Apenas se a criança for portadora de diabetes mellitus tipo 1.',
    ans: 'B',
    comment: 'A sobreposição de BEF e RCCP é relativamente comum na prática clínica pediátrica: a criança herda pais geneticamente baixos (canal de BEF) e também herda a cronologia de puberdade tardia (RCCP). Nesses pacientes, a estatura na infância fica abaixo do percentil 3, a idade óssea é atrasada e o estirão é tardio, alcançando no final da maturação a estatura adulta baixa esperada para o canal de seus pais.',
    expA: 'Incorreta. As duas variantes podem coexistir perfeitamente no mesmo indivíduo.',
    expB: 'Correta. A coexistência de BEF e RCCP é bem conhecida e combina idade óssea atrasada com meta final baixa compatível com os pais.',
    expC: 'Incorreta. A síndrome de Down é uma aneuploidia congênita (trissomia 21) presente desde a concepção.',
    expD: 'Incorreta. Não há qualquer correlação com diabetes mellitus.',
  });
}
