import { q } from './helper_crescimento.js';

export function loadSec6() {
  q({
    id: 'ped-cresc-043',
    subtopic: 'Baixa Estatura Desproporcionada e Displasias Ósseas',
    inst: 'USP-SP',
    year: 2024,
    statement: 'Na avaliação propedêutica de uma criança com suspeita de displasia esquelética, qual medida antropométrica divide o corpo em Segmento Superior (SS) e Segmento Inferior (SI)?',
    A: 'A distância da ponta do nariz até o umbigo.',
    B: 'A medida do Segmento Inferior (do topo da sínfise púbica até o chão, em pé) subtraída da Estatura total para obtenção do Segmento Superior.',
    C: 'A medida da circunferência da cintura dividida pela prega triciptal.',
    D: 'A distância entre o acrômio direito e o maléolo lateral esquerdo.',
    ans: 'B',
    comment: 'A avaliação das proporções corporais exige a divisão corporal em Segmento Inferior (SI) e Segmento Superior (SS). O Segmento Inferior é medido com o paciente descalço em pé, medindo-se a distância vertical do bordo superior da sínfise púbica até o chão. O Segmento Superior (SS) é obtido subtraindo-se o Segmento Inferior da Estatura total: SS = Estatura - SI. A relação SS/SI permite diagnosticar se a baixa estatura é proporcional (variantes normais, causas endócrinas e sistêmicas) ou desproporcionada (displasias esqueléticas).',
    expA: 'Incorreta. O nariz e o umbigo não são marcos anatômicos para proporções esqueléticas.',
    expB: 'Correta. O SI mede da sínfise púbica ao chão; o SS é obtido subtraindo o SI da estatura total (SS = Estatura - SI).',
    expC: 'Incorreta. Essa medida avalia adiposidade e risco cardiovascular, não proporções ósseas.',
    expD: 'Incorreta. Medida sem padronização anatômica.',
  });

  q({
    id: 'ped-cresc-044',
    subtopic: 'Baixa Estatura Desproporcionada e Displasias Ósseas',
    inst: 'UNICAMP',
    year: 2024,
    statement: 'Qual é o comportamento fisiológico normal da relação Segmento Superior / Segmento Inferior (SS/SI) desde o nascimento até a idade adulta em crianças saudáveis?',
    A: 'É de 0,5 ao nascimento e sobe para 2,5 no adulto.',
    B: 'É de cerca de 1,7 ao nascimento (tronco longo e membros curtos), decresce para cerca de 1,3 aos 3 anos, atinge 1,0 entre os 7 e 10 anos (quando membros e tronco se equivalem) e estabiliza em torno de 0,9 a 1,0 no adulto.',
    C: 'Mantém-se constante e fixa em 1,0 durante todas as etapas da vida intrauterina e pós-natal.',
    D: 'A relação SS/SI não sofre qualquer alteração decorrente do crescimento.',
    ans: 'B',
    comment: 'Ao nascer, o bebê apresenta cabeça e tronco proporcionalmente maiores do que os membros inferiores, com relação SS/SI em torno de 1,7. Ao longo da infância, os membros inferiores crescem a uma taxa proporcionalmente maior do que o tronco, de modo que a relação SS/SI decai continuamente: aos 3 anos é de cerca de 1,3; entre os 7 e 10 anos atinge o equilíbrio de 1,0 (SS = SI); no adulto normal situa-se entre 0,9 e 1,0. Se em uma criança de 8 anos a relação for de 1,6 (muito aumentada), significa membros inferiores curtos (displasia óssea com membros curtos).',
    expA: 'Incorreta. A relação decresce com o crescimento relativo das pernas, não aumenta.',
    expB: 'Correta. A evolução fisiológica da relação SS/SI vai de 1,7 no recém-nascido a 1,0 entre 7-10 anos e ~0,95 no adulto.',
    expC: 'Incorreta. A relação sofre intensa dinâmica com a idade.',
    expD: 'Incorreta. É um dos pilares antropométricos da endocrinologia pediátrica.',
  });

  q({
    id: 'ped-cresc-045',
    subtopic: 'Baixa Estatura Desproporcionada e Displasias Ósseas',
    inst: 'FMUSP',
    year: 2024,
    statement: 'Lactente de 4 meses é trazido para consulta. Ao exame, apresenta encurtamento marcante dos quatro membros, com maior comprometimento dos segmentos proximais (braços e coxas / padrão rizomélico), macrocefalia relativa com fronte olímpica proeminente, hipoplasia do terço médio da face com base nasal deprimida, mãos curtas e largas com separação entre o terceiro e quarto dedos ("mão em tridente") e cifose tóraco-lombar. Os pais têm estatura normal e o pai tem 48 anos. Qual é a principal hipótese diagnóstica e a base genética dessa condição?',
    A: 'Osteogênese imperfeita tipo I (mutação do colágeno tipo 1).',
    B: 'Acondroplasia (mutação no gene FGFR3 com ganho de função).',
    C: 'Mucopolissacaridose tipo I (síndrome de Hurler).',
    D: 'Síndrome de Turner (45,X).',
    ans: 'B',
    comment: 'A acondroplasia é a displasia óssea não letal mais frequente no ser humano. Tem herança autossômica dominante, sendo que cerca de 80% dos casos decorrem de mutações novas (de novo), fortemente associadas à idade paterna avançada (> 35-40 anos). A mutação pontual quase universal no gene FGFR3 (frequentemente Gly380Arg) causa ativação constitutiva (ganho de função) do receptor FGFR3, que atua como inibidor tônico da proliferação condrocitária nas placas de crescimento epifisárias. O fenótipo clássico inclui membros curtos rizomélicos, macrocefalia com bossa frontal, hipoplasia mediofacial e mão em tridente.',
    expA: 'Incorreta. Osteogênese imperfeita cursa com ossos frágeis, fraturas frequentes e escleras azuladas.',
    expB: 'Correta. Acondroplasia: encurtamento rizomélico, macrocefalia, mão em tridente e mutação com ganho de função no gene FGFR3 associada à idade paterna avançada.',
    expC: 'Incorreta. Mucopolissacaridose cursa com fácies grosseira, opacidade de córnea e hepatoesplenomegalia.',
    expD: 'Incorreta. A síndrome de Turner causa baixa estatura proporcional em meninas, sem membros rizomélicos ou mão em tridente.',
  });

  q({
    id: 'ped-cresc-046',
    subtopic: 'Baixa Estatura Desproporcionada e Displasias Ósseas',
    inst: 'UFRJ',
    year: 2024,
    statement: 'No lactente portador de acondroplasia, qual é a complicação anatômica grave decorrente do estreitamento da base do crânio que exige rastreio rigoroso por neuroimagem (TC/RM) nos primeiros meses de vida devido ao risco de morte súbita?',
    A: 'Agenesia completa do corpo caloso.',
    B: 'Estenose crítica do forame magno com compressão da transição bulbomedular e risco de apneia central do sono.',
    C: 'Fechamento prematuro da sutura sagital isolada (escafocefalia simples).',
    D: 'Aneurisma congênito da artéria basilar.',
    ans: 'B',
    comment: 'Na acondroplasia, a ossificação endocondral da base do crânio é gravemente comprometida, resultando em um forame magno anormalmente pequeno e estenosado. Isso gera compressão crônica da transição craniocervical / medula oblonga superior, causando apneia central, hiper-reflexia, hipotonia grave e risco aumentado de morte súbita do lactente (morte no berço). O rastreio com polissonografia e neuroimagem (TC/RM da transição craniocervical) é formalmente indicado pela Academia Americana de Pediatria e pela SBP.',
    expA: 'Incorreta. Não é a complicação ameaçadora clássica da base do crânio.',
    expB: 'Correta. A estenose de forame magno com compressão bulbomedular é a complicação mais letal do primeiro ano de vida na acondroplasia.',
    expC: 'Incorreta. A macrocefalia decorre de hidrocefalia comunicante ou megalencefalia, e não cranioestenose isolada.',
    expD: 'Incorreta. Aneurismas basilares não fazem parte da história natural da doença.',
  });

  q({
    id: 'ped-cresc-047',
    subtopic: 'Baixa Estatura Desproporcionada e Displasias Ósseas',
    inst: 'UNIFESP',
    year: 2024,
    statement: 'Como se denominam os três padrões anatômicos de encurtamento dos membros nas displasias esqueléticas de acordo com o segmento ósseo primordialmente acometido?',
    A: 'Axial, Apendicular e Visceral.',
    B: 'Rizomélico (raiz do membro: fêmur/úmero), Mesomélico (meio do membro: rádio/ulna e tíbia/fíbula) e Acromélico (extremidades: mãos e pés).',
    C: 'Proximal, Cortical e Medular.',
    D: 'Osteoclástico, Osteoblástico e Condrocítico.',
    ans: 'B',
    comment: 'A semiologia das displasias esqueléticas classifica o encurtamento dos membros em três tipos anatômicos: 1) Rizomélico: compromete o segmento proximal / raiz do membro (braço/úmero e coxa/fêmur), clássico da Acondroplasia; 2) Mesomélico: compromete o segmento intermediário (antebraço/rádio-ulna e perna/tíbia-fíbula), clássico da Discondrosteose de Léri-Weill; 3) Acromélico: compromete as extremidades distais (mãos e pés), visto na Acromesomelia.',
    expA: 'Incorreta. Termos não correspondem à classificação de encurtamento de membros.',
    expB: 'Correta. Rizomélico (raiz), Mesomélico (intermediário) e Acromélico (mãos/pés) são os termos semiológicos corretos.',
    expC: 'Incorreta. São divisões histológicas/anatômicas do tecido ósseo.',
    expD: 'Incorreta. São termos relacionados às linhagens celulares ósseas.',
  });

  q({
    id: 'ped-cresc-048',
    subtopic: 'Baixa Estatura Desproporcionada e Displasias Ósseas',
    inst: 'UERJ',
    year: 2024,
    statement: 'Menina de 10 anos é encaminhada por baixa estatura desproporcionada. Ao exame: antebraços curtos com desvio ulnar das mãos e proeminência dorsal dolorosa da cabeça da ulna em ambos os punhos (Deformidade de Madelung). A mãe apresenta alterações físicas semelhantes e baixa estatura. O exame genético-molecular demonstra mutação em heterozigose no gene SHOX. Qual é o diagnóstico?',
    A: 'Discondrosteose de Léri-Weill.',
    B: 'Acondroplasia clássica.',
    C: 'Síndrome de Marfan.',
    D: 'Raquitismo hipofosfatêmico ligado ao X.',
    ans: 'A',
    comment: 'A Discondrosteose de Léri-Weill é uma displasia esquelética autossômica dominante causada por mutações com perda de função ou deleções do gene SHOX (Short Stature Homeobox, localizado na região pseudoautossômica PAR1 dos cromossomos sexuais X e Y). Caracteriza-se por encurtamento mesomélico dos membros (antebraços e pernas curtos) e pela Deformidade de Madelung bilateral (subluxação dorsal e arqueamento da ulna distal decorrente de parada prematura da placa fisária radial medial). Pacientes com deficiência de SHOX têm indicação formal de tratamento com rhGH aprovada pela FDA e ANVISA.',
    expA: 'Correta. A tríade de encurtamento mesomélico, Deformidade de Madelung e mutação no gene SHOX define a Discondrosteose de Léri-Weill.',
    expB: 'Incorreta. Acondroplasia decorre de mutação no FGFR3 e cursa com membros rizomélicos.',
    expC: 'Incorreta. A síndrome de Marfan cursa com alta estatura e membros muito longos (dolicostenomelia).',
    expD: 'Incorreta. O raquitismo hipofosfatêmico causa deformidades em varo/valgo e rosário raquítico, não a deformidade de Madelung por gene SHOX.',
  });

  q({
    id: 'ped-cresc-049',
    subtopic: 'Baixa Estatura Desproporcionada e Displasias Ósseas',
    inst: 'SCMSP',
    year: 2024,
    statement: 'Em um paciente com acondroplasia, qual é a conduta farmacológica mais recente que atua diretamente na via fisiopatológica do FGFR3, recentemente aprovada para promover melhora do crescimento ósseo?',
    A: 'Altas doses de vitamina D parenteral.',
    B: 'Vosoritida (análogo do peptídeo natriurético tipo C - CNP), que inibe a cascata proliferativa negativa ativada pelo FGFR3 mutado.',
    C: 'Metformina em dose plena associada a insulina glargina.',
    D: 'Bisfosfonatos intravenosos diários.',
    ans: 'B',
    comment: 'A Vosoritida é uma inovação terapêutica recente aprovada pelas principais agências regulatórias (FDA, EMA e ANVISA). Trata-se de um análogo recombinante do peptídeo natriurético tipo C (CNP). O CNP liga-se ao seu receptor específico (NPR-B) e antagoniza a via de sinalização intracelular downstream ativada constitutivamente pelo FGFR3 (via MAPK/ERK), liberando a placa de crescimento epifisária para proliferar e promovendo ganho estatural linear em crianças com acondroplasia com epífises abertas.',
    expA: 'Incorreta. A vitamina D não tem papel terapêutico na acondroplasia e doses excessivas causam intoxicação e nefrocalcinose.',
    expB: 'Correta. A Vosoritida é o primeiro fármaco modificador da doença na acondroplasia, atuando como agonista do receptor de CNP que bloqueia a hiperativação do FGFR3.',
    expC: 'Incorreta. Fármacos hipoglicemiantes sem indicação em displasias ósseas.',
    expD: 'Incorreta. Bisfosfonatos são usados na osteogênese imperfeita para reduzir fraturas, não na acondroplasia.',
  });

  q({
    id: 'ped-cresc-050',
    subtopic: 'Baixa Estatura Desproporcionada e Displasias Ósseas',
    inst: 'UFPE',
    year: 2024,
    statement: 'Qual é o achado radiológico característico observado na radiografia simples da coluna lombar de uma criança com acondroplasia, que a diferencia de outras etiologias de baixa estatura?',
    A: 'Aumento progressivo da distância interpeduncular lombar no sentido craniocaudal.',
    B: 'Estreitamento progressivo da distância interpeduncular lombar no sentido craniocaudal (de L1 a L5), associado a ossos ilíacos quadrados e estreitamento da incisura isquiática.',
    C: 'Vértebras em borboleta em múltiplos níveis cervicais.',
    D: 'Escoliose congênita grave por hemivértebra isolada.',
    ans: 'B',
    comment: 'Na coluna normal, a distância entre os pedículos vertebrais (distância interpeduncular) alarga-se progressivamente no sentido craniocaudal (de L1 até L5) para acomodar a cauda equina. Na acondroplasia, ocorre a inversão patológica desse padrão: há um estreitamento progressivo da distância interpeduncular de L1 para L5. Na bacia, os ossos ilíacos são pequenos e arredondados/quadrados ("orelhas de elefante") com incisura isquiática estreita e teto acetabular horizontal.',
    expA: 'Incorreta. O aumento progressivo é o padrão anatômico fisiológico normal.',
    expB: 'Correta. O estreitamento caudal da distância interpeduncular lombar é o sinal radiológico clássico da acondroplasia na coluna.',
    expC: 'Incorreta. Vértebra em borboleta é típica da síndrome de Alagille.',
    expD: 'Incorreta. Hemivértebra é anomalia isolada de segmentação vertebral.',
  });
}
