import { q } from './helper_crescimento.js';

export function loadSec7() {
  q({
    id: 'ped-cresc-051',
    subtopic: 'Causas Cromossômicas e Sindrômicas',
    inst: 'USP-SP',
    year: 2024,
    statement: 'Menina de 8 anos é trazida pela mãe com queixa de baixa estatura. Ao exame: estatura no percentil < 3 (Escore-Z de -2,7 DP), velocidade de crescimento de 3,6 cm/ano nos últimos 12 meses. O exame físico não revela estigmas evidentes além de implantação discretamente baixa de cabelos na nuca e palato ligeiramente ogival. Não há sopros cardíacos. Diante de uma menina com desaceleração inexplicada do crescimento, qual é a conduta diagnóstica obrigatória preconizada pela Sociedade Brasileira de Pediatria (SBP)?',
    A: 'Solicitar TC de crânio com contraste para pesquisar craniofaringioma.',
    B: 'Solicitar cariótipo de sangue periférico com contagem estendida de metáfases (mínimo 30) para pesquisa formal de Síndrome de Turner e seus mosaicismos.',
    C: 'Aguardar até os 15 anos para verificar se haverá menarca espontânea antes de qualquer exame.',
    D: 'Prescrever sulfato ferroso e encaminhar para psicoterapia infantil.',
    ans: 'B',
    comment: 'A regra de ouro da endocrinologia pediátrica é mandatória: TODA MENINA COM BAIXA ESTATURA INEXPLICADA OU DESACELERAÇÃO DO CRESCIMENTO DEVE REALIZAR CARIÓTIPO, mesmo na ausência completa de estigmas fenotípicos clássicos de Turner. Até 30% a 50% das meninas com Síndrome de Turner (especialmente as formas em mosaico como 45,X/46,XX ou anomalias estruturais do X) apresentam a baixa estatura como ÚNICA manifestação clínica na infância. A contagem de pelo menos 30 a 50 metáfases é essencial para excluir mosaicismos de baixo grau.',
    expA: 'Incorreta. O cariótipo é o exame primordial e obrigatório para qualquer menina com baixa estatura.',
    expB: 'Correta. O cariótipo com contagem de metáfases é mandatório em qualquer menina com baixa estatura inexplicada para rastrear Turner.',
    expC: 'Incorreta. Aguardar até os 15 anos atrasa irreversivelmente a janela de oportunidade de tratamento com rhGH.',
    expD: 'Incorreta. Não há qualquer evidência de anemia ferropriva primária justificando a conduta.',
  });

  q({
    id: 'ped-cresc-052',
    subtopic: 'Causas Cromossômicas e Sindrômicas',
    inst: 'UNICAMP',
    year: 2024,
    statement: 'Qual é o mecanismo genético responsável pela baixa estatura desproporcional ou proporcional observada na quase totalidade das pacientes com Síndrome de Turner (45,X)?',
    A: 'Duplicação do gene FGFR3 no cromossomo 4.',
    B: 'Haploinsuficiência do gene SHOX (Short Stature Homeobox), localizado na região pseudoautossômica PAR1 do braço curto do cromossomo X.',
    C: 'Mutações no receptor de vasopressina V2 no túbulo coletor.',
    D: 'Deleção do cromossomo 22q11.2.',
    ans: 'B',
    comment: 'O gene SHOX (Short Stature Homeobox) está localizado na região pseudoautossômica PAR1 dos cromossomos sexuais X e Y (escapa da inativação do X). Para um crescimento esquelético normal, são necessárias duas cópias ativas do gene SHOX (uma em cada cromossomo sexual: XX ou XY). Na síndrome de Turner clássica (45,X), a perda de um cromossomo sexual acarreta a perda de uma das cópias do gene SHOX (haploinsuficiência), sendo esta a causa primária da baixa estatura.',
    expA: 'Incorreta. FGFR3 mutado é a causa da acondroplasia.',
    expB: 'Correta. A haploinsuficiência do gene SHOX na região PAR1 do cromossomo X é a base molecular da baixa estatura na síndrome de Turner.',
    expC: 'Incorreta. O receptor V2 está associado ao diabetes insipidus nefrogênico.',
    expD: 'Incorreta. A deleção 22q11.2 causa a síndrome de DiGeorge / velocardiofacial.',
  });

  q({
    id: 'ped-cresc-053',
    subtopic: 'Causas Cromossômicas e Sindrômicas',
    inst: 'FMUSP',
    year: 2024,
    statement: 'Menina de 10 anos tem diagnóstico citogenético de Síndrome de Turner (45,X). Em relação ao manejo do crescimento e desenvolvimento puberal nessa paciente, qual é a conduta terapêutica padronizada?',
    A: 'Uso de hormônio do crescimento recombinante (rhGH) em doses suprafisiológicas a partir do momento da desaceleração estatural, seguido de indução puberal com baixas doses de estrógeno aos 11-12 anos e posterior adição de progesterona após sangramento ou 2 anos de estrogenioterapia.',
    B: 'Contraindicação absoluta ao uso de rhGH devido ao risco de fechamento prematuro das cartilagens.',
    C: 'Uso exclusivo de testosterona oral em altas doses para masculinizar a genitália.',
    D: 'Ooforoplastia laparoscópica de urgência para retirada de cistos foliculares.',
    ans: 'A',
    comment: 'O protocolo padrão para Turner inclui: 1) Início de rhGH em doses suprafisiológicas (0,045 a 0,050 mg/kg/dia) precocemente (a partir dos 2-4 anos ou assim que houver desaceleração estatural) para otimizar o ganho de altura antes da puberdade; 2) Indução puberal fisiológica com baixas doses de estradiol transdérmico por volta dos 11-12 anos (mimetizando a cronologia normal de puberdade sem fechar precocemente as epífises), com escalonamento gradual da dose; 3) Adição de progestágeno cíclico após cerca de 2 anos de estrógeno ou após sangramento de escape, para proteção endometrial.',
    expA: 'Correta. Protocolo padrão: rhGH em doses elevadas para crescimento linear + indução puberal estrogênica gradual com posterior progestágeno.',
    expB: 'Incorreta. O rhGH é a terapia de escolha comprovada e aprovada para Turner.',
    expC: 'Incorreta. A indução é estrogênica, respeitando o fenótipo feminino.',
    expD: 'Incorreta. Na síndrome de Turner as gônadas são fitas fibrosas disgenéticas (streak gonads), sem cistos foliculares funcionantes.',
  });

  q({
    id: 'ped-cresc-054',
    subtopic: 'Causas Cromossômicas e Sindrômicas',
    inst: 'UFRJ',
    year: 2024,
    statement: 'Menino de 6 anos apresenta baixa estatura, pescoço curto e alado (pterygium colli), hipertelorismo ocular, ptose palpebral bilateral, tórax com pectus carinatum superior e excavatum inferior, criptorquidia unilateral e sopro sistólico ejetivo rude em foco pulmonar 3+/6+. O ecocardiograma confirma estenose valvar pulmonar com espessamento displásico. O cariótipo de sangue periférico é 46,XY. Qual é o diagnóstico?',
    A: 'Síndrome de Turner masculina.',
    B: 'Síndrome de Noonan.',
    C: 'Síndrome de Down.',
    D: 'Acondroplasia grave.',
    ans: 'B',
    comment: 'A síndrome de Noonan é uma rasopatia com herança autossômica dominante (frequentemente mutações nos genes PTPN11, SOS1, RAF1 ou KRAS da via RAS-MAPK), que acomete igualmente indivíduos de ambos os sexos e cursa com CARIÓTIPO NORMAL (46,XY ou 46,XX). Compartilha estigmas físicos semelhantes aos de Turner (pescoço alado, baixa estatura, hipertelorismo, orelhas baixas), mas tem como cardiopatia mais clássica a Estenose Valvar Pulmonar (coração direito) e/ou miocardiopatia hipertrófica, além de criptorquidia frequente nos meninos.',
    expA: 'Incorreta. O termo "Turner masculina" é obsoleto e incorreto; a patologia é a Síndrome de Noonan (cariótipo 46,XY normal).',
    expB: 'Correta. Síndrome de Noonan: fenótipo Turner-like, estenose pulmonar, pectus excavatum/carinatum, criptorquidia e cariótipo 46,XY normal.',
    expC: 'Incorreta. Down cursa com trissomia 21 e defeito de septo atrioventricular total (DSAV).',
    expD: 'Incorreta. Não há encurtamento rizomélico de membros nem mutação de FGFR3.',
  });

  q({
    id: 'ped-cresc-055',
    subtopic: 'Causas Cromossômicas e Sindrômicas',
    inst: 'UNIFESP',
    year: 2024,
    statement: 'Qual é a cardiopatia congênita mais frequente na Síndrome de Turner (45,X), e qual é a mais clássica da Síndrome de Noonan, respectivamente?',
    A: 'Estenose pulmonar na Turner; Comunicação interatrial na Noonan.',
    B: 'Coarctação de Aorta e Valva Aórtica Bicúspide na Turner; Estenose Valvar Pulmonar e Miocardiopatia Hipertrófica na Noonan.',
    C: 'Tetralogia de Fallot na Turner; Transposição das Grandes Artérias na Noonan.',
    D: 'Truncus arteriosus em ambas.',
    ans: 'B',
    comment: 'A diferenciação cardiovascular é clássica de prova: Síndrome de Turner afeta primariamente o CORAÇÃO ESQUERDO: valva aórtica bicúspide (em até 30-50%) e coarctação de aorta (em 10-15%), com risco aumentado de dissecção aórtica. Já a Síndrome de Noonan acomete primariamente o CORAÇÃO DIREITO e o miocárdio: estenose valvar pulmonar com displasia valvar (50-60%) e miocardiopatia hipertrófica (20-30%).',
    expA: 'Incorreta. A estenose pulmonar é da Noonan, não de Turner.',
    expB: 'Correta. Turner: valva aórtica bicúspide / coarctação de aorta (lado esquerdo); Noonan: estenose pulmonar / cardiomiopatia hipertrófica.',
    expC: 'Incorreta. Fallot e TGA não são as lesões marcadoras dessas duas síndromes.',
    expD: 'Incorreta. Truncus arteriosus é típico da microdeleção 22q11.2.',
  });

  q({
    id: 'ped-cresc-056',
    subtopic: 'Causas Cromossômicas e Sindrômicas',
    inst: 'UERJ',
    year: 2024,
    statement: 'Lactente masculino nasceu com hipotonia grave generalizada ("bebê frouxo"), reflexos de sucção e deglutição quase ausentes, necessitando de alimentação por sonda enteral por 2 meses, associada a criptorquidia bilateral e micropênis. A partir dos 2 anos e meio de idade, a hipotonia melhorou, mas a criança desenvolveu apetite voraz e incontrolável (hiperfagia compulsiva), escondendo comida, com ganho ponderal acelerado e desaceleração do crescimento estatural (baixa estatura com obesidade mórbida). Apresenta mãos e pés pequenos. Qual é o diagnóstico e o teste genético indicado?',
    A: 'Síndrome de Down; cariótipo por banda G.',
    B: 'Síndrome de Prader-Willi; teste de metilação do DNA da região 15q11-q13 (MS-MLPA ou PCR específico).',
    C: 'Acondroplasia; dosagem de cálcio e fósforo.',
    D: 'Hipotireoidismo congênito isolado por bócio simples.',
    ans: 'B',
    comment: 'A síndrome de Prader-Willi tem um quadro bifásico patognomônico: 1) Fase 1 (neonatal/lactente): hipotonia profunda com letargia, choro fraco, hiporreflexia e falha de sucção com dificuldade para ganhar peso (failure to thrive), associada a hipogonadismo (micropênis e criptorquidia); 2) Fase 2 (a partir dos 2-3 anos): hiperfagia compulsiva insaciável com obsessão por comida, levando a obesidade precoce e grave, baixa estatura por disfunção do eixo GH, atraso cognitivo, fronte estreita, olhos amendoados e mãos e pés pequenos. Decorre de perda de expressão de genes de origem paterna na região 15q11-q13 (deleção paterna em 70% ou dissomia uniparental materna em 25-30%). O teste padrão-ouro de triagem inicial é o estudo de metilação da região 15q11-q13.',
    expA: 'Incorreta. Down não tem esse padrão bifásico de hiperfagia insaciável.',
    expB: 'Correta. Síndrome de Prader-Willi: hipotonia neonatal precoce seguida de hiperfagia, obesidade e baixa estatura; diagnóstico por metilação em 15q11-q13.',
    expC: 'Incorreta. Acondroplasia não cursa com hiperfagia nem hipotonia neonatal grave com sonda.',
    expD: 'Incorreta. Hipotireoidismo congênito é detectado no teste do pezinho e não causa essa hiperfagia compulsiva.',
  });

  q({
    id: 'ped-cresc-057',
    subtopic: 'Causas Cromossômicas e Sindrômicas',
    inst: 'FMUSP',
    year: 2024,
    statement: 'Qual é o papel comprovado do hormônio do crescimento recombinante (rhGH) no manejo terapêutico de crianças com Síndrome de Prader-Willi?',
    A: 'Nenhum, o uso de rhGH é formalmente contraindicado em todas as fases da síndrome.',
    B: 'O rhGH melhora a estatura final, promove aumento da massa magra, redução da massa gorda corporal e melhora da força muscular e do tônus, sendo aprovado formalmente para essa síndrome.',
    C: 'O rhGH serve exclusivamente para curar a hiperfagia e cessar o apetite da criança.',
    D: 'O rhGH é utilizado apenas se houver hipoglicemia cetótica associada a diabetes tipo 2.',
    ans: 'B',
    comment: 'A Síndrome de Prader-Willi é uma das indicações formais e aprovadas de tratamento com rhGH. Devido a uma disfunção hipotalâmica intrínseca, essas crianças têm deficiência relativa de GH e uma composição corporal patológica (excesso de gordura e acentuada sarcopenia com fraqueza muscular). O tratamento com rhGH aumenta a estatura final, reduz a massa adiposa, aumenta a massa muscular e melhora significativamente o desenvolvimento motor e o gasto calórico basal. (Nota: deve-se sempre realizar polissonografia antes do início para descartar apneia obstrutiva do sono grave).',
    expA: 'Incorreta. O rhGH é uma das terapias mais benéficas e consagradas na síndrome de Prader-Willi.',
    expB: 'Correta. O rhGH melhora a composição corporal (aumenta massa magra, diminui gordura) e a estatura na síndrome de Prader-Willi.',
    expC: 'Incorreta. O rhGH não cura a hiperfagia hipotalâmica compulsiva.',
    expD: 'Incorreta. A indicação independe de hipoglicemia.',
  });

  q({
    id: 'ped-cresc-058',
    subtopic: 'Causas Cromossômicas e Sindrômicas',
    inst: 'SCMSP',
    year: 2024,
    statement: 'Criança de 4 anos é avaliada por baixa estatura severa (Escore-Z de -3,8 DP). Nasceu a termo pesando 1.800 g e medindo 42 cm (PIG grave com restrição de crescimento intrauterino). Não apresentou catch-up growth. Ao exame físico: fácies triangular com queixo afilado e fronte ampla, cantos da boca voltados para baixo ("boca de carpa"), assimetria corporal evidente (membro inferior e hemitórax direitos menores que os esquerdos) e clinodactilia do 5º quirodáctilo. Qual é o diagnóstico mais provável?',
    A: 'Síndrome de Silver-Russell.',
    B: 'Acondroplasia.',
    C: 'Síndrome de Klinefelter.',
    D: 'Síndrome de Marfan.',
    ans: 'A',
    comment: 'A síndrome de Silver-Russell é caracterizada por: 1) RCIU grave com nascimento PIG acentuado e falha completa de crescimento compensatório (sem catch-up); 2) Baixa estatura grave pós-natal proporcional; 3) Assimetria corporal (hemi-hipotrofia ou hemi-hipertrofia de membros ou tronco); 4) Fácies triangular com fronte ampla e queixo pontiagudo; 5) Clinodactilia do 5º dedo. A base molecular mais frequente envolve a hipometilação do centro de imprinting 1 em 11p15 (em cerca de 50%) ou dissomia uniparental materna do cromossomo 7 (mUPD7 em cerca de 10%). Tem indicação formal de rhGH.',
    expA: 'Correta. Síndrome de Silver-Russell: PIG grave sem catch-up + fácies triangular + assimetria corporal.',
    expB: 'Incorreta. Acondroplasia tem membros curtos rizomélicos, sem assimetria corporal ou fácies triangular.',
    expC: 'Incorreta. Klinefelter causa alta estatura na puberdade com ginecomastia.',
    expD: 'Incorreta. Marfan cursa com alta estatura e membros muito longos.',
  });

  q({
    id: 'ped-cresc-059',
    subtopic: 'Causas Cromossômicas e Sindrômicas',
    inst: 'UFPE',
    year: 2024,
    statement: 'Menina de 12 anos com diagnóstico de Síndrome de Turner realiza ecocardiograma de rotina e ressonância magnética cardíaca. Os exames mostram aorta bivalvular com dilatação da raiz aórtica. Qual é a principal complicação cardiovascular potencialmente letal que deve ser prevenida com rigoroso controle da pressão arterial nessa paciente?',
    A: 'Dissecção e rotura da aorta torácica.',
    B: 'Mixoma de átrio esquerdo.',
    C: 'Estenose mitral congênita em paraquedas.',
    D: 'Tromboembolismo pulmonar maciço de repetição.',
    ans: 'A',
    comment: 'A dissecção e rotura aórtica é uma das principais causas de mortalidade prematura em pacientes com síndrome de Turner. A fragilidade intrínseca da parede vascular (necrose cística da camada média), somada à alta prevalência de valva aórtica bicúspide, coarctação de aorta e hipertensão arterial sistêmica, eleva exponencialmente o estresse de cisalhamento sobre a aorta ascendente. O monitoramento do diâmetro da raiz aórtica indexado à superfície corporal (ASI - Aortic Size Index) e o controle rigoroso da pressão arterial com betabloqueadores/IECA são cruciais.',
    expA: 'Correta. A dilatação e dissecção aguda de aorta representam a complicação mais letal na história natural de Turner.',
    expB: 'Incorreta. Mixomas são tumores benignos sem associação com Turner (associados ao complexo de Carney).',
    expC: 'Incorreta. A lesão mais comum é valva aórtica bicúspide, e não mitral em paraquedas.',
    expD: 'Incorreta. O risco primordial é a dissecção aórtica.',
  });
}
