import { q } from './helper_crescimento.js';

export function loadSec8() {
  q({
    id: 'ped-cresc-060',
    subtopic: 'Recém-Nascido PIG e Catch-up Growth',
    inst: 'USP-SP',
    year: 2024,
    statement: 'Qual é o critério antropométrico padronizado internacionalmente e adotado pela SBP para definir um recém-nascido como Pequeno para a Idade Gestacional (PIG)?',
    A: 'Peso e/ou comprimento ao nascer inferior ao percentil 10 (ou Escore-Z < -2 DP) para a idade gestacional e sexo nas curvas de crescimento intrauterino adequadas (como Fenton ou Intergrowth-21st).',
    B: 'Peso ao nascer fixo < 2.500 g independentemente de ter nascido com 28 ou 41 semanas de gestação.',
    C: 'Comprimento ao nascer estritamente entre os percentis 25 e 75.',
    D: 'Apgar de 1º minuto menor que 5.',
    ans: 'A',
    comment: 'Pela definição consensual da Sociedade Brasileira de Pediatria, da OMS e das sociedades de endocrinologia pediátrica, o recém-nascido é considerado Pequeno para a Idade Gestacional (PIG ou SGA - Small for Gestational Age) quando seu peso e/ou comprimento de nascimento encontram-se abaixo do percentil 10 (critério epidemiológico) ou abaixo do Escore-Z de -2 DP (critério estatístico rigoroso) para a respectiva idade gestacional e sexo nas curvas de referência fetal/neonatal.',
    expA: 'Correta. Peso e/ou comprimento < p10 ou < -2 DP para a idade gestacional define o concepto PIG.',
    expB: 'Incorreta. Peso < 2.500 g define "Baixo Peso ao Nascer" (conceito estático que inclui prematuros com peso adequado para a idade gestacional).',
    expC: 'Incorreta. Percentil 25 a 75 define Adequado para a Idade Gestacional (AIG).',
    expD: 'Incorreta. O Apgar avalia vitalidade e asfixia neonatal imediata, não adequação antropométrica fetal.',
  });

  q({
    id: 'ped-cresc-061',
    subtopic: 'Recém-Nascido PIG e Catch-up Growth',
    inst: 'UNICAMP',
    year: 2024,
    statement: 'Em relação à história natural do crescimento de crianças nascidas Pequenas para a Idade Gestacional (PIG), qual proporção delas realiza o crescimento de recuperação compensatório espontâneo (catch-up growth) até os 2 anos de vida?',
    A: 'Apenas 5% a 10%.',
    B: 'Aproximadamente 85% a 90%.',
    C: '100% de todas as crianças, sem exceções.',
    D: 'Nenhuma criança PIG é capaz de recuperar o crescimento sem reposição hormonal obrigatória imediata no berçário.',
    ans: 'B',
    comment: 'Cerca de 85% a 90% dos recém-nascidos PIG apresentam crescimento de recuperação acelerado espontâneo (catch-up growth), que ocorre predominantemente nos primeiros 6 a 12 meses de vida e se consolida até os 2 anos de idade (em prematuros muito extremos esse prazo pode se estender até os 4 anos). No entanto, cerca de 10% a 15% das crianças nascidas PIG não realizam o catch-up espontâneo e permanecem com baixa estatura (Escore-Z < -2 DP).',
    expA: 'Incorreta. A esmagadora maioria realiza catch-up espontâneo (cerca de 85% a 90%).',
    expB: 'Correta. 85% a 90% dos nascidos PIG recuperam o crescimento espontaneamente até os 2 anos de vida.',
    expC: 'Incorreta. Cerca de 10% a 15% não fazem catch-up e persistem com baixa estatura crônica.',
    expD: 'Incorreta. O catch-up é fisiológico e não se usa hormônio no berçário.',
  });

  q({
    id: 'ped-cresc-062',
    subtopic: 'Recém-Nascido PIG e Catch-up Growth',
    inst: 'FMUSP',
    year: 2024,
    statement: 'Menino de 3 anos e 6 meses foi nascido a termo, com peso de 2.100 g e comprimento de 43 cm (PIG grave simétrico por insuficiência placentária crônica materna). Desde então, vem sendo acompanhado regularmente. Sua curva de crescimento mostra estatura atual no Escore-Z de -2,8 DP, com velocidade de crescimento normal para a idade, porém sem apresentar crescimento compensatório (falha de catch-up growth aos 3 anos e meio). Exames gerais (hemograma, TSH, T4 livre, eletrólitos, função renal e anticorpos celíacos) são normais. Qual é a conduta médica indicada e respaldada pelos consensos internacionais?',
    A: 'Aguardar passivamente até os 18 anos sem qualquer intervenção.',
    B: 'Indicar tratamento com hormônio do crescimento recombinante (rhGH), pois a criança nascida PIG que não recuperou o crescimento até os 2 a 4 anos preenche critério formal aprovado de terapia com rhGH.',
    C: 'Iniciar dieta hipercalórica com 200% das necessidades energéticas para forçar o ganho rápido de peso.',
    D: 'Prescrever hormônio tireoidiano em dose triplicada.',
    ans: 'B',
    comment: 'A falha de crescimento de recuperação (catch-up growth) em crianças nascidas PIG é uma indicação formal e consolidada de tratamento com rhGH, aprovada pela FDA (2001), EMA (2003) e ANVISA. Os critérios de indicação são: 1) História neonatal de PIG comprovada; 2) Idade ≥ 2 anos (nos EUA) ou ≥ 4 anos (na Europa); 3) Estatura atual persistente no Escore-Z < -2,5 ou -2,0 DP; 4) Exclusão de outras causas orgânicas. O tratamento com rhGH promove ganho estatural substancial, permitindo que a maioria atinja a estatura dentro do canal genético parental.',
    expA: 'Incorreta. Deixar sem tratamento condena a criança a uma baixa estatura adulta definitiva desnecessária.',
    expB: 'Correta. Criança nascida PIG sem catch-up aos 2-4 anos tem indicação formal e aprovada de tratamento com rhGH.',
    expC: 'Incorreta. Sobrecarregar a dieta de um PIG sem catch-up causa ganho excessivo de massa gorda, acentuando o risco precoce de síndrome metabólica.',
    expD: 'Incorreta. Se o perfil tireoidiano é normal, levotiroxina causa tireotoxicose iatrogênica.',
  });

  q({
    id: 'ped-cresc-063',
    subtopic: 'Recém-Nascido PIG e Catch-up Growth',
    inst: 'UFRJ',
    year: 2024,
    statement: 'A teoria da "Programação Fetal" (Hipótese de Barker) correlaciona o nascimento de crianças Pequenas para a Idade Gestacional (PIG) com alterações fisiopatológicas a longo prazo. Qual é o principal risco metabólico associado ao indivíduo nascido PIG na vida adulta, especialmente se submetido a ganho ponderal rápido e precoce na infância?',
    A: 'Risco aumentado de obesidade central, resistência à insulina, diabetes mellitus tipo 2, dislipidemia mista e doença cardiovascular isquêmica prematura (Síndrome Metabólica).',
    B: 'Hipotensão arterial crônica e magreza constitucional incurável.',
    C: 'Desenvolvimento exclusivo de raquitismo hipofosfatêmico.',
    D: 'Proteção absoluta contra qualquer evento aterosclerótico coronariano.',
    ans: 'A',
    comment: 'A hipótese de Barker postula que, diante de um ambiente intrauterino adverso com desnutrição fetal, o feto desenvolve o "fenótipo poupador" (thrifty phenotype), alterando permanentemente a expressão de genes metabólicos para maximizar o armazenamento de energia e resistir à fome. Quando essa criança nasce e é exposta a um ambiente pós-natal com abundância calórica, ocorre um ganho rápido de peso que sobrecarrega tecidos periféricos metabolicamente programados para a escassez, culminando em resistência insulínica severa, obesidade visceral, hipertensão, dislipidemia aterogênica e DM2 na vida adulta.',
    expA: 'Correta. A hipótese de Barker estabelece a ligação entre nascimento PIG e predisposição a síndrome metabólica e DCV.',
    expB: 'Incorreta. O risco é de hipertensão e obesidade, e não hipotensão e magreza.',
    expC: 'Incorreta. Raquitismo decorre de distúrbios da mineralização óssea (vitamina D/fósforo), sem relação com a hipótese de Barker.',
    expD: 'Incorreta. O risco aterosclerótico é significativamente elevado, não reduzido.',
  });

  q({
    id: 'ped-cresc-064',
    subtopic: 'Recém-Nascido PIG e Catch-up Growth',
    inst: 'UNIFESP',
    year: 2024,
    statement: 'Qual é a diferença conceitual fundamental entre "Recém-Nascido Pequeno para a Idade Gestacional (PIG)" e "Restrição de Crescimento Intrauterino (RCIU)"?',
    A: 'Não há diferença, são termos estritamente sinônimos que expressam o mesmo conceito.',
    B: 'PIG é um conceito antropométrico estático de nascimento (peso/comprimento < p10 ao nascer), ao passo que RCIU é um processo dinâmico patológico fetal intrauterino demonstrado por queda seriada de percentis fetais na ultrassonografia obstétrica.',
    C: 'PIG só acomete fetos do sexo feminino, enquanto RCIU acomete exclusivamente fetos masculinos.',
    D: 'PIG refere-se exclusivamente a recém-nascidos pós-termo (> 42 semanas).',
    ans: 'B',
    comment: 'PIG é uma classificação estritamente antropométrica no momento do nascimento: a criança nasceu com peso e/ou comprimento abaixo do percentil 10 (ou < -2 DP) para a idade gestacional. Uma criança pode ser constitucionalmente pequena (pais geneticamente pequenos) e ser PIG sem ter tido qualquer doença na gestação. Por outro lado, RCIU (Restrição de Crescimento Intrauterino) é um diagnóstico fetal dinâmico e patológico: o feto tinha potencial genético para percentil 70 e, por insuficiência placentária, desceu para o percentil 20 (teve restrição de crescimento fetal, mas nasceu no percentil 20, ou seja, AIG e não PIG).',
    expA: 'Incorreta. Os termos não são sinônimos.',
    expB: 'Correta. PIG é classificação antropométrica estática ao nascer; RCIU é um processo dinâmico patológico fetal pré-natal.',
    expC: 'Incorreta. Ambos acometem qualquer sexo biológico.',
    expD: 'Incorreta. PIG pode ocorrer em qualquer idade gestacional (pré-termo, termo ou pós-termo).',
  });

  q({
    id: 'ped-cresc-065',
    subtopic: 'Recém-Nascido PIG e Catch-up Growth',
    inst: 'UERJ',
    year: 2024,
    statement: 'Menina de 7 anos nascida PIG grave sem catch-up growth desenvolveu pubarca precoce aos 6 anos de idade, com odor axilar adulto e aceleração do ganho de peso. Os exames evidenciam elevação isolada de DHEA-S (sulfato de desidroepiandrosterona) com 17-OH-progesterona normal e idade óssea compatível com a cronológica. Qual é a associação clínica comum em meninas nascidas PIG?',
    A: 'Adrenarca precoce exagerada, que frequentemente se associa a risco posterior aumentado de Síndrome dos Ovários Policísticos (SOP) na adolescência.',
    B: 'Carcinoma de córtex adrenal metastático fulminante.',
    C: 'Deficiência congênita de 21-hidroxilase na forma perdedora de sal.',
    D: 'Craniofaringioma calcificado intraselar.',
    ans: 'A',
    comment: 'Meninas nascidas PIG apresentam risco aumentado de apresentar adrenarca precoce exagerada (elevação prematura de andrógenos adrenais como DHEA-S sem ativação do eixo hipófise-ovariano). Essa condição é mediada por hiperinsulinemia compensatória secundária à resistência insulínica, que estimula as enzimas esteroidogênicas adrenais (citocromo P450c17). Na adolescência, essas meninas têm incidência significativamente maior de anovulação crônica, hiperandrogenismo e Síndrome dos Ovários Policísticos (SOP).',
    expA: 'Correta. Adrenarca precoce e posterior SOP na adolescência são complicações metabólicas clássicas da programação fetal em meninas PIG.',
    expB: 'Incorreta. A virilização seria rápida, com níveis monstruosos de DHEA-S e sinais de massa abdominal palpável.',
    expC: 'Incorreta. A 17-OHP normal afasta a forma clássica de hiperplasia adrenal congênita.',
    expD: 'Incorreta. Craniofaringioma não causa elevação de DHEA-S nem pubarca precoce isolada.',
  });

  q({
    id: 'ped-cresc-066',
    subtopic: 'Recém-Nascido PIG e Catch-up Growth',
    inst: 'SCMSP',
    year: 2024,
    statement: 'Em prematuros nascidos com idade gestacional < 32 semanas e classificados como PIG graves, até qual idade cronológica a literatura pediátrica e os consensos de crescimento recomendam aguardar a possibilidade de crescimento de recuperação espontâneo antes de firmar a falha definitiva de catch-up growth?',
    A: 'Até os 6 meses de vida.',
    B: 'Até os 12 meses de vida.',
    C: 'Até os 4 anos de idade.',
    D: 'Até os 18 anos de idade.',
    ans: 'C',
    comment: 'Embora na maioria dos nascidos a termo o catch-up growth esteja praticamente concluído aos 2 anos de vida, em recém-nascidos muito prematuros (< 32 semanas) ou prematuros extremos (< 28 semanas) com morbidades neonatais complexas (displasia broncopulmonar, enterocolite necrosante, sepse neonatal tardia), a recuperação pode ser mais lenta e arrastada, podendo ocorrer até os 4 anos de idade. Por isso, a diretriz europeia (EMA) preconiza os 4 anos como idade de corte formal para indicação de rhGH.',
    expA: 'Incorreta. 6 meses é tempo insuficiente para prematuros extremos.',
    expB: 'Incorreta. Muitos prematuros realizam catch-up substancial no segundo e terceiro anos.',
    expC: 'Correta. Em prematuros extremos, aguarda-se até os 4 anos de idade para confirmação de falha de catch-up.',
    expD: 'Incorreta. Aos 18 anos as cartilagens já estão fechadas.',
  });

  q({
    id: 'ped-cresc-067',
    subtopic: 'Recém-Nascido PIG e Catch-up Growth',
    inst: 'UFMG',
    year: 2024,
    statement: 'Qual é o impacto do tratamento com hormônio de crescimento recombinante (rhGH) sobre a sensibilidade à insulina e o perfil glicêmico em crianças nascidas PIG sem catch-up, e qual monitoramento laboratorial é mandatório durante a terapia?',
    A: 'O rhGH é um potente sensibilizador de insulina, causando hipoglicemias intratáveis e exigindo aporte contínuo de glicose.',
    B: 'O rhGH tem efeito contrainsulínico fisiológico e pode acentuar a resistência à insulina prévia da criança PIG; é mandatório monitorar periodicamente glicemia de jejum, hemoglobina glicada e IGF-1 sérico.',
    C: 'O rhGH não tem qualquer ação metabólica sobre o metabolismo de carboidratos.',
    D: 'O tratamento induz diabetes insipidus nefrogênico com poliúria grave.',
    ans: 'B',
    comment: 'O GH é um hormônio contrainsulínico clássico: estimula a lipólise e inibe a captação periférica de glicose mediada por insulina no músculo esquelético e tecido adiposo. Como crianças nascidas PIG já possuem risco intrínseco de resistência insulínica basal (pela programação fetal de Barker), o uso de rhGH pode aumentar temporariamente os níveis de insulina e agravar a resistência insulínica. O rastreio periódico de glicemia de jejum, HbA1c e dosagem de IGF-1 (para evitar sobredose suprafisiológica com IGF-1 > +2 DP) é mandatório durante todo o acompanhamento.',
    expA: 'Incorreta. O GH tem ação hiperglicemiante contrainsulínica, e não hipoglicemiante.',
    expB: 'Correta. O efeito contrainsulínico do rhGH exige monitoramento glicêmico e de IGF-1 durante a terapia em nascidos PIG.',
    expC: 'Incorreta. O GH tem profundo impacto metabólico lipolítico e glicídico.',
    expD: 'Incorreta. O GH não interfere nos canais de aquaporina nem causa diabetes insipidus.',
  });
}
