import { q } from './helper_crescimento.js';

export function loadSec9() {
  q({
    id: 'ped-cresc-068',
    subtopic: 'Causas Endócrinas de Baixa Estatura',
    inst: 'USP-SP',
    year: 2024,
    statement: 'Recém-nascido masculino a termo apresenta episódios repetidos de hipoglicemia grave sintomática com convulsões nas primeiras 48 horas de vida, além de icterícia colestática prolongada sem atresia de vias biliares. Ao exame físico detalhado, observa-se comprimento normal ao nascer, micropênis verdadeiro (comprimento peniano esticado de 1,5 cm) e testículos tópicos normais. Qual é a principal suspeita clínica e qual deficiência hormonal congênita explica conjuntamente o micropênis e as hipoglicemias graves?',
    A: 'Deficiência congênita de hormônio do crescimento (DGH) e/ou Pan-hipopituitarismo congênito.',
    B: 'Hipotireoidismo primário por ectopia tireoidiana isolada.',
    C: 'Doença celíaca clássica congênita.',
    D: 'Acondroplasia grave com compressão medular.',
    ans: 'A',
    comment: 'No período neonatal, a deficiência congênita de GH isolada ou associada ao hipopituitarismo múltiplo (deficiência combinada de GH, ACTH e gonadotrofinas LH/FSH) não costuma alterar o comprimento ao nascer (o crescimento fetal independe de GH, sendo mediado por insulina e IGF-2). Contudo, manifesta-se classicamente pela tríade: 1) Hipoglicemias graves e refratárias de jejum (por ausência do efeito contrainsulínico do GH e do cortisol); 2) Micropênis no sexo masculino (< 2,5 cm no RN a termo, dependente da ação das gonadotrofinas e do GH no 2º e 3º trimestres fetais); 3) Icterícia colestática neonatal prolongada idiopática.',
    expA: 'Correta. Hipoglicemia neonatal grave associada a micropênis e colestase é a apresentação clássica do hipopituitarismo congênito / deficiência de GH.',
    expB: 'Incorreta. Hipotireoidismo primário isolado não causa micropênis nem hipoglicemias refratárias com convulsões dessa gravidade.',
    expC: 'Incorreta. Doença celíaca exige introdução de glúten na dieta, não se manifestando em recém-nascido.',
    expD: 'Incorreta. Acondroplasia cursa com membros curtos rizomélicos e não cursa com hipoglicemias nem micropênis.',
  });

  q({
    id: 'ped-cresc-069',
    subtopic: 'Causas Endócrinas de Baixa Estatura',
    inst: 'UNICAMP',
    year: 2024,
    statement: 'Por que a dosagem sérica basal isolada de Hormônio do Crescimento (GH) em jejum NÃO tem valor diagnóstico para confirmar ou afastar a deficiência de GH (DGH) em crianças com baixa estatura?',
    A: 'Porque o GH se liga irreversivelmente à albumina e não pode ser dosado no sangue periférico.',
    B: 'Porque a secreção fisiológica do GH pela hipófise anterior é estritamente pulsátil, com picos associados ao sono de ondas lentas, permanecendo com níveis basais muito baixos ou indetectáveis na maior parte do dia em crianças normais.',
    C: 'Porque o GH só é secretado após os 18 anos de vida.',
    D: 'Porque o GH é destruído pelo ácido clorídrico no estômago antes de atingir o sangue.',
    ans: 'B',
    comment: 'O GH é secretado pelos somatotrofos da adeno-hipófise em pulsos episódicos (cerca de 6 a 8 picos ao dia, principalmente durante o sono de ondas lentas / sono profundo NREM estágios 3 e 4). Nos intervalos entre os picos (na maior parte do dia e em jejum matinal), os níveis séricos basais de GH em crianças saudáveis são habitualmente muito baixos ou totalmente indetectáveis (< 0,05 a 0,1 ng/mL). Assim, um GH basal indetectável pode ocorrer em qualquer criança normal, sendo obrigatórios testes de estímulo farmacológico para avaliar a capacidade secretória hipofisária.',
    expA: 'Incorreta. O GH circula ligado à GHBP (Growth Hormone Binding Protein), não à albumina, e é perfeitamente mensurável por imunoensaios.',
    expB: 'Correta. A secreção pulsátil e os níveis basais indetectáveis em crianças saudáveis inviabilizam o uso do GH basal isolado para diagnóstico.',
    expC: 'Incorreta. O GH é secretado e atua ativamente desde a infância precoce.',
    expD: 'Incorreta. O GH é um hormônio hipofisário secretado diretamente na circulação sistêmica, sem passar pelo trato gastrointestinal.',
  });

  q({
    id: 'ped-cresc-070',
    subtopic: 'Causas Endócrinas de Baixa Estatura',
    inst: 'FMUSP',
    year: 2024,
    statement: 'Menino de 7 anos apresenta baixa estatura grave (Escore-Z de -3,1 DP), velocidade de crescimento de 2,8 cm/ano, face de boneca (fronte olímpica, raiz nasal deprimida e bochechas proeminentes com adiposidade facial), voz aguda e micropênis. A idade óssea é de 4 anos. A dosagem de IGF-1 e IGFBP-3 encontra-se abaixo do percentil 3 (< -2 DP). Para o diagnóstico laboratorial definitivo de deficiência de GH (DGH), qual é o protocolo padrão preconizado pelos consensos da SBP e da Growth Hormone Research Society?',
    A: 'Realização de ressonância magnética nuclear de crânio isolada, sem exames laboratoriais.',
    B: 'Realização de dois testes de estímulo farmacológico independentes de secreção de GH (com clonidina, glucagon, insulina ou L-dopa), confirmando-se a deficiência se o pico máximo de GH for inferior a 5 ou 7 ng/mL em ambos.',
    C: 'Dosagem de GH na urina de 24 horas por 7 dias seguidos.',
    D: 'Biópsia a céu aberto da glândula hipófise.',
    ans: 'B',
    comment: 'O protocolo diagnóstico padrão-ouro para deficiência de GH (DGH) na infância exige: 1) Quadro clínico e auxológico compatível (baixa estatura com velocidade de crescimento subnormal); 2) IGF-1 e IGFBP-3 baixos (< -2 DP); 3) Realização de DOIS testes de estímulo farmacológico provocativos da secreção de GH (utilizando agentes como clonidina, glucagon, teste de tolerância à insulina/ITT ou L-dopa). O diagnóstico de DGH exige falha de pico secretório de GH (pico < 5 a 7-10 ng/mL, dependendo do imunoensaio e protocolo) em AMBOS os testes de estímulo, minimizando falsos-positivos.',
    expA: 'Incorreta. A RM é exame de imagem complementar obrigatório após a confirmação laboratorial, mas não substitui os testes de estímulo.',
    expB: 'Correta. A confirmação de DGH exige falha de resposta de pico em dois testes de estímulo farmacológico independentes.',
    expC: 'Incorreta. O GH urinário não é validado clinicamente para diagnóstico de DGH.',
    expD: 'Incorreta. Biópsia hipofisária é um procedimento de altíssimo risco e contraindicado para DGH.',
  });

  q({
    id: 'ped-cresc-071',
    subtopic: 'Causas Endócrinas de Baixa Estatura',
    inst: 'UFRJ',
    year: 2024,
    statement: 'Uma vez confirmado o diagnóstico laboratorial de deficiência de hormônio do crescimento (DGH) em uma criança, qual exame de imagem é MANDATÓRIO para a investigação anatômica etiológica e exclusão de tumores da linha média?',
    A: 'Tomografia computadorizada simples de tórax.',
    B: 'Ressonância Magnética (RM) de encéfalo com foco em sela túrcica e hipotálamo, com cortes finos e contraste paramagnético.',
    C: 'Cintilografia de corpo inteiro com iodo-131.',
    D: 'Ultrassonografia de abdome total com doppler de artérias renais.',
    ans: 'B',
    comment: 'A Ressonância Magnética (RM) de sela túrcica e hipotálamo com contraste é o exame anatômico indispensável e obrigatório em toda criança com confirmação laboratorial de deficiência de GH. Ela permite: 1) Diagnosticar causas congênitas estruturais da haste e glândula hipofisária (tríade da interrupção da haste hipofisária: ausência de haste, sela túrcica rasa/hipoplasia de adeno-hipófise e neuro-hipófise ectópica na eminência média); 2) Excluir formalmente neoplasias compressivas adquiridas da região selar e supraselar, principalmente o craniofaringioma e o germinoma.',
    expA: 'Incorreta. TC de tórax avalia pulmões e mediastino, não a hipófise.',
    expB: 'Correta. A RM de sela túrcica e hipotálamo com cortes finos é mandatória para identificar anomalias anatômicas congênitas ou neoplasias como o craniofaringioma.',
    expC: 'Incorreta. Cintilografia com I-131 é usada no câncer diferenciado de tireoide.',
    expD: 'Incorreta. USG de abdome não avalia o sistema nervoso central.',
  });

  q({
    id: 'ped-cresc-072',
    subtopic: 'Causas Endócrinas de Baixa Estatura',
    inst: 'UNIFESP',
    year: 2024,
    statement: 'Menino de 9 anos vinha crescendo normalmente até os 7 anos, quando sua velocidade de crescimento caiu drasticamente para 1,5 cm/ano. Nos últimos 6 meses, passou a apresentar cefaleia holocraniana matinal progressiva, vômitos em jato, poliúria intensa com polidipsia (ingesta de 5 litros de água/dia) e perda de campo visual periférico (hemianopsia bitemporal). A radiografia de crânio mostra calcificações na região supraselar. Qual é o diagnóstico mais provável?',
    A: 'Tireoidite de Hashimoto.',
    B: 'Craniofaringioma.',
    C: 'Retardo Constitucional do Crescimento e da Puberdade.',
    D: 'Doença de Addison primária.',
    ans: 'B',
    comment: 'O craniofaringioma é o tumor benigno de origem embrionária (derivado de remanescentes da bolsa de Rathke) mais comum da região selar/supraselar na infância. Seu quadro clássico inclui: 1) Desaceleração grave ou parada do crescimento (por deficiência adquirida de GH/pan-hipopituitarismo); 2) Sinais de hipertensão intracraniana (cefaleia matinal e vômitos); 3) Diabetes insipidus central precoce (poliúria e polidipsia por compressão hipotalâmica); 4) Defeitos visuais por compressão do quiasma óptico (hemianopsia bitemporal); 5) Calcificações supraselares clássicas vistas na TC/RM.',
    expA: 'Incorreta. Hashimoto não causa hemianopsia bitemporal nem diabetes insipidus com calcificações selares.',
    expB: 'Correta. A tríade de parada de crescimento + diabetes insipidus + hemianopsia bitemporal com calcificações selares é patognomônica de craniofaringioma.',
    expC: 'Incorreta. No RCCP a velocidade é normal e não há cefaleia ou distúrbios visuais.',
    expD: 'Incorreta. Addison cursa com hiperpigmentação e hipotensão, sem massa supraselar.',
  });

  q({
    id: 'ped-cresc-073',
    subtopic: 'Causas Endócrinas de Baixa Estatura',
    inst: 'UERJ',
    year: 2024,
    statement: 'Menina de 8 anos apresenta parada do crescimento estatural nos últimos 2 anos (velocidade de 2,2 cm/ano) acompanhada de ganho progressivo de peso, constipação intestinal crônica, letargia, intolerância ao frio, pele seca e amarelada, mixedema palpebral e aumento indolor e difuso da tireoide (bócio). A idade óssea é de 4 anos e meio (gravemente atrasada). Os exames mostram TSH de 145 mUI/L, T4 livre de 0,2 ng/dL e anticorpo anti-TPO fortemente positivo. Qual é o diagnóstico e o efeito esperado do tratamento com levotiroxina sobre a velocidade de crescimento?',
    A: 'Tireoidite de Hashimoto (hipotireoidismo primário adquirido); a reposição com levotiroxina promoverá um vigoroso crescimento de recuperação (catch-up growth) acelerado, com normalização da velocidade de crescimento.',
    B: 'Hipertireoidismo primário por Doença de Graves; o tratamento com metimazol causará nanismo definitivo.',
    C: 'Doença celíaca clássica; o início da levotiroxina é contraindicado.',
    D: 'Deficiência isolada de GH; a levotiroxina não terá efeito algum.',
    ans: 'A',
    comment: 'A tireoidite de Hashimoto é a principal causa de hipotireoidismo adquirido na infância. O hormônio tireoidiano é indispensável para a proliferação condrocitária e ossificação epifisária; sua deficiência crônica leva à parada do crescimento linear associada a ganho de peso, atraso profundo da idade óssea e bócio. A introdução de reposição com levotiroxina sódica em dose adequada corrige o hipometabolismo e deflagra um espetacular "catch-up growth" (crescimento compensatório acelerado), recuperando o canal genético se a intervenção for precoce.',
    expA: 'Correta. Hipotireoidismo primário por tireoidite de Hashimoto; o tratamento com levotiroxina desencadeia vigoroso catch-up growth.',
    expB: 'Incorreta. O quadro é de hipotireoidismo (TSH muito elevado e T4L baixo), e não Graves.',
    expC: 'Incorreta. O diagnóstico é de hipotireoidismo autoimune, exigindo reposição imediata de levotiroxina.',
    expD: 'Incorreta. O hipotireoidismo primário tratado restabelece o crescimento sem necessidade de GH.',
  });

  q({
    id: 'ped-cresc-074',
    subtopic: 'Causas Endócrinas de Baixa Estatura',
    inst: 'SCMSP',
    year: 2024,
    statement: 'Menina de 9 anos com hipotireoidismo primário grave e de longa data não tratado apresenta parada de crescimento estatural associada paradoxalmente a telarca e sangramento vaginal cíclico precoce, sem pubarca (ausência de pelos pubianos). A ressonância de crânio mostra aumento volumétrico homogêneo da hipófise simulando macroadenoma. Como se denomina essa condição e qual é o seu mecanismo fisiopatológico?',
    A: 'Síndrome de Turner em mosaico com hiperplasia adrenal.',
    B: 'Síndrome de Van Wyk-Grumbach, decorrente de hiperestimulação do receptor de FSH nos ovários pelas concentrações extremamente elevadas de TSH sérico (homologia estrutural de subunidades) associada à hiperplasia reativa de tireotrofos por excesso de TRH.',
    C: 'Craniofaringioma com metástase ovariana.',
    D: 'Tumor secretor de LH de células da teca ovariana.',
    ans: 'B',
    comment: 'A síndrome de Van Wyk-Grumbach é uma entidade clássica da endocrinologia pediátrica que ocorre em crianças com hipotireoidismo primário grave e crônico não tratado: 1) A falta crônica de T4/T3 eleva maciçamente o TRH hipotalâmico, o que induz hiperplasia difusa dos tireotrofos na hipófise anterior, mimetizando um adenoma hipofisário na RM; 2) O TSH extremamente elevado, pela homologia molecular de sua subunidade alfa com o FSH e pela reatividade cruzada nos receptores de FSH ovarianos, estimula o desenvolvimento folicular ovariano e produção de estrógenos, causando telarca, sangramento uterino disfuncional e cistos ovarianos, porém SEM pubarca (já que a adrenal não foi ativada); 3) Toda essa manifestação de puberdade precoce paradoxal com parada de crescimento regride completamente apenas com a reposição de levotiroxina.',
    expA: 'Incorreta. Não é Turner nem hiperplasia adrenal.',
    expB: 'Correta. Síndrome de Van Wyk-Grumbach: hipotireoidismo grave de longa data + puberdade precoce periférica paradoxal com sangramento vaginal + hiperplasia hipofisária reversível com levotiroxina.',
    expC: 'Incorreta. Não se trata de neoplasia maligna metastática.',
    expD: 'Incorreta. A patologia primária é a falência tireoidiana com TSH maciçamente elevado.',
  });

  q({
    id: 'ped-cresc-075',
    subtopic: 'Causas Endócrinas de Baixa Estatura',
    inst: 'FMUSP',
    year: 2024,
    statement: 'Menino de 10 anos portador de asma grave vem utilizando prednisona oral contínua há 18 meses por prescrição inadvertida sem desmame. Ao exame físico: velocidade de crescimento de 1,2 cm/ano (estagnação estatural), ganho ponderal de 9 kg no período, fácies arredondada e pletórica ("em lua cheia"), gibosidade dorsal ("giba de búfalo"), obesidade centrípeta com membros finos, estrias violáceas largas (> 1 cm) em abdome e coxas e PA de 138x92 mmHg (> p99). Qual é o diagnóstico e o mecanismo da parada de crescimento?',
    A: 'Síndrome de Cushing exógena; os glicocorticoides em excesso inibem a secreção hipofisária de GH, antagonizam a ação periférica do IGF-1 e exercem efeito antianabólico direto inibitório sobre a placa de crescimento epifisária.',
    B: 'Feocromocitoma bilateral; as catecolaminas fecham imediatamente as cartilagens epifisárias.',
    C: 'Deficiência congênita de 21-hidroxilase.',
    D: 'Baixa estatura familiar associada a efeito rebote da asma.',
    ans: 'A',
    comment: 'A síndrome de Cushing exógena (iatrogênica) é a causa mais comum de hipercortisolismo na infância, secundária ao uso crônico e indiscriminado de corticosteroides orais, tópicos de alta potência ou injetáveis. O excesso de glicocorticoides é um dos mais potentes inibidores biológicos do crescimento estatural humano: 1) Inibe a secreção pulsátil de GH na hipófise; 2) Bloqueia a transcrição e sinalização periférica de IGF-1 nos condrócitos; 3) Induz apoptose e inibe a proliferação condrocitária diretamente nas placas de crescimento epifisárias, além de causar catabolismo proteico com osteopenia, obesidade troncular e estrias violáceas largas.',
    expA: 'Correta. Síndrome de Cushing exógena por uso prolongado de corticoide com ação inibitória direta sobre as placas de crescimento e o eixo GH/IGF-1.',
    expB: 'Incorreta. Feocromocitoma secreta catecolaminas causando sudorese, palpitações e perda de peso, e não obesidade com estrias violáceas.',
    expC: 'Incorreta. A hiperplasia adrenal cursa com virilização precoce, perda de sal e avanço de idade óssea com estirão precoce inicial.',
    expD: 'Incorreta. A criança desenvolveu síndrome de Cushing iatrogênica clássica.',
  });

  q({
    id: 'ped-cresc-076',
    subtopic: 'Causas Endócrinas de Baixa Estatura',
    inst: 'UFMG',
    year: 2024,
    statement: 'Quais são os exames laboratoriais de triagem inicial recomendados para confirmar o hipercortisolismo endógeno em uma criança com baixa estatura associada a ganho de peso e estrias violáceas suspeita de Síndrome de Cushing?',
    A: 'Cortisol sérico matinal basal isolado em jejum.',
    B: 'Cortisol livre urinário de 24 horas (duas coletas), dosagem de cortisol salivar noturno (às 23h) e/ou teste de supressão noturna com dose baixa de dexametasona (1 mg overnight ou teste clássico de Liddle 1).',
    C: 'Dosagem de renina plasmática e aldosterona em repouso.',
    D: 'Biópsia renal percutânea ecoguiada.',
    ans: 'B',
    comment: 'O cortisol sérico matinal isolado NÃO serve para triagem de Cushing, pois tanto indivíduos normais quanto pacientes com Cushing têm cortisol elevado às 8h da manhã. O diagnóstico exige demonstrar a PERDA DO RITMO CIRCADIANO ou hipersecreção persistente através de testes consagrados: 1) Cortisol salivar noturno (coletado às 23h-24h, que em normais é indetectável, mas no Cushing permanece elevado); 2) Cortisol livre urinário de 24 horas (CLU); 3) Teste de supressão com dose baixa de dexametasona (overnight 1 mg ou com dose ajustada por peso em crianças: falha de supressão para < 1,8 mcg/dL confirma hipercortisolismo).',
    expA: 'Incorreta. O cortisol matinal é alto fisiologicamente pelo pico circadiano matinal normal.',
    expB: 'Correta. A tríade de triagem para Cushing inclui CLU de 24h, cortisol salivar noturno às 23h e teste de supressão com dexametasona.',
    expC: 'Incorreta. Avalia hiperaldosteronismo primário, não Cushing.',
    expD: 'Incorreta. Procedimento invasivo sem qualquer papel no diagnóstico de hipercortisolismo.',
  });
}
